import type { CustomerSuccessLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";
import { SUCCESS_PLAN_STATUSES } from "./config";

export function buildCustomerSuccessLabels(t: Translator): CustomerSuccessLabels {
  const p = "customerApp.portalStructure.customerSuccess";
  const rec = (key: string) => ({
    title: t(`${p}.recommendations.${key}.title`),
    reason: t(`${p}.recommendations.${key}.reason`),
    action: t(`${p}.recommendations.${key}.action`),
  });

  const planStates = Object.fromEntries(
    SUCCESS_PLAN_STATUSES.map((status) => [status, t(`${p}.planStates.${status}`)])
  ) as CustomerSuccessLabels["planStates"];

  return {
    eyebrow: t(`${p}.eyebrow`),
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    breadcrumbSupport: t(`${p}.breadcrumbSupport`),
    breadcrumbCustomerSuccess: t(`${p}.breadcrumbCustomerSuccess`),
    backToSupport: t(`${p}.backToSupport`),
    accessDenied: t(`${p}.accessDenied`),
    organizationMissing: t(`${p}.organizationMissing`),
    subscriptionRequired: t(`${p}.subscriptionRequired`),
    permissionMissing: t(`${p}.permissionMissing`),
    entitlementMissing: t(`${p}.entitlementMissing`),
    errorTitle: t(`${p}.errorTitle`),
    errorBody: t(`${p}.errorBody`),
    retry: t(`${p}.retry`),
    sections: {
      overview: t(`${p}.sections.overview`),
      nextAction: t(`${p}.sections.nextAction`),
      successPlans: t(`${p}.sections.successPlans`),
      followUpsMilestones: t(`${p}.sections.followUpsMilestones`),
      outcomes: t(`${p}.sections.outcomes`),
      risksAdoption: t(`${p}.sections.risksAdoption`),
      activeRisks: t(`${p}.sections.activeRisks`),
      adoptionSignals: t(`${p}.sections.adoptionSignals`),
      recentActivity: t(`${p}.sections.recentActivity`),
      understanding: t(`${p}.sections.understanding`),
    },
    overview: {
      organizationOverview: t(`${p}.overview.organizationOverview`),
      healthScore: t(`${p}.overview.healthScore`),
      adoptionScore: t(`${p}.overview.adoptionScore`),
      utilizationScore: t(`${p}.overview.utilizationScore`),
      engagementScore: t(`${p}.overview.engagementScore`),
      healthStatus: t(`${p}.overview.healthStatus`),
      advisory: t(`${p}.overview.advisory`),
      lastUpdated: t(`${p}.overview.lastUpdated`),
    },
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      priority: t(`${p}.filters.priority`),
      successStatus: t(`${p}.filters.successStatus`),
      owner: t(`${p}.filters.owner`),
      dueDate: t(`${p}.filters.dueDate`),
      sortBy: t(`${p}.filters.sortBy`),
      all: t(`${p}.filters.all`),
      sortDueDate: t(`${p}.filters.sortDueDate`),
      sortPriority: t(`${p}.filters.sortPriority`),
      sortTitle: t(`${p}.filters.sortTitle`),
      sortProgress: t(`${p}.filters.sortProgress`),
      sortUpdated: t(`${p}.filters.sortUpdated`),
    },
    followUpTabs: {
      all: t(`${p}.followUpTabs.all`),
      followUps: t(`${p}.followUpTabs.followUps`),
      milestones: t(`${p}.followUpTabs.milestones`),
      overdue: t(`${p}.followUpTabs.overdue`),
      completed: t(`${p}.followUpTabs.completed`),
    },
    planStates,
    statuses: {
      getting_started: t(`${p}.statuses.gettingStarted`),
      developing: t(`${p}.statuses.developing`),
      established: t(`${p}.statuses.established`),
      advanced: t(`${p}.statuses.advanced`),
      high_performing: t(`${p}.statuses.highPerforming`),
    },
    scores: {
      learningCompletion: t(`${p}.scores.learningCompletion`),
      featureAdoption: t(`${p}.scores.featureAdoption`),
      userEngagement: t(`${p}.scores.userEngagement`),
      operationalMaturity: t(`${p}.scores.operationalMaturity`),
      securityCompletion: t(`${p}.scores.securityCompletion`),
      integrationUsage: t(`${p}.scores.integrationUsage`),
      teamCount: t(`${p}.scores.teamCount`),
      businessPacks: t(`${p}.scores.businessPacks`),
      integrationsConnected: t(`${p}.scores.integrationsConnected`),
      twoFaAdoption: t(`${p}.scores.twoFaAdoption`),
    },
    adoptionSignals: {
      learningCompletion: t(`${p}.scores.learningCompletion`),
      featureAdoption: t(`${p}.scores.featureAdoption`),
      userEngagement: t(`${p}.scores.userEngagement`),
      teamCount: t(`${p}.scores.teamCount`),
      businessPacks: t(`${p}.scores.businessPacks`),
      integrationsConnected: t(`${p}.scores.integrationsConnected`),
      twoFaAdoption: t(`${p}.scores.twoFaAdoption`),
    },
    categories: {
      learning: t(`${p}.categories.learning`),
      security: t(`${p}.categories.security`),
      adoption: t(`${p}.categories.adoption`),
      integration: t(`${p}.categories.integration`),
      operations: t(`${p}.categories.operations`),
    },
    priorities: {
      opportunity: t(`${p}.priorities.opportunity`),
      recommended: t(`${p}.priorities.recommended`),
      important: t(`${p}.priorities.important`),
      high_impact: t(`${p}.priorities.highImpact`),
    },
    recommendations: {
      activate2faAllUsers: rec("activate2faAllUsers"),
      completeOnboardingTraining: rec("completeOnboardingTraining"),
      exploreUnusedBusinessPacks: rec("exploreUnusedBusinessPacks"),
      connectIntegrations: rec("connectIntegrations"),
      reviewOperationalDashboards: rec("reviewOperationalDashboards"),
      encourageCertification: rec("encourageCertification"),
    },
    understanding: {
      q1: t(`${p}.understanding.q1`),
      a1: t(`${p}.understanding.a1`),
      q2: t(`${p}.understanding.q2`),
      a2: t(`${p}.understanding.a2`),
      q3: t(`${p}.understanding.q3`),
      a3: t(`${p}.understanding.a3`),
      q4: t(`${p}.understanding.q4`),
      a4: t(`${p}.understanding.a4`),
    },
    empty: {
      plans: t(`${p}.empty.plans`),
      followUps: t(`${p}.empty.followUps`),
      outcomes: t(`${p}.empty.outcomes`),
      risks: t(`${p}.empty.risks`),
      activity: t(`${p}.empty.activity`),
    },
    healthStates: {
      healthy: t(`${p}.healthStates.healthy`),
      good: t(`${p}.healthStates.good`),
      moderate: t(`${p}.healthStates.moderate`),
      poor: t(`${p}.healthStates.poor`),
      critical_health: t(`${p}.healthStates.criticalHealth`),
      unknown: t(`${p}.healthStates.unknown`),
    },
    card: {
      owner: t(`${p}.card.owner`),
      progress: t(`${p}.card.progress`),
      targetDate: t(`${p}.card.targetDate`),
      target: t(`${p}.card.target`),
      current: t(`${p}.card.current`),
    },
  };
}
