import type { Translator } from "@/lib/i18n/translate";
import {
  APPROVAL_ROLES,
  CONDITION_KEYS,
  DESIGNER_TRIGGER_TYPES,
  EXECUTION_OUTCOMES,
  FLOW_NODES,
  PLAYBOOK_CATEGORIES,
  PLAYBOOK_PRIORITIES,
  PLAYBOOK_STATUSES,
  STEP_ACTION_TYPES,
  STEP_KINDS,
} from "./constants";
import type { PlatformPlaybookCenterLabels } from "./types";

function mapKeys<T extends string>(t: Translator, prefix: string, keys: readonly T[]): Record<T, string> {
  return Object.fromEntries(keys.map((k) => [k, t(`${prefix}.${k}`)])) as Record<T, string>;
}

export function buildPlatformPlaybookCenterLabels(t: Translator): PlatformPlaybookCenterLabels {
  const p = "platform.playbookCenter";

  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    back: t(`${p}.back`),
    principle: t(`${p}.principle`),
    emptyState: t(`${p}.emptyState`),
    emptyOnboardingTitle: t(`${p}.emptyOnboardingTitle`),
    emptyOnboardingBody: t(`${p}.emptyOnboardingBody`),
    sections: {
      overview: t(`${p}.sections.overview`),
      playbooks: t(`${p}.sections.playbooks`),
      templates: t(`${p}.sections.templates`),
      executions: t(`${p}.sections.executions`),
      audit: t(`${p}.sections.audit`),
      filters: t(`${p}.sections.filters`),
      steps: t(`${p}.sections.steps`),
      conditions: t(`${p}.sections.conditions`),
      createPlaybook: t(`${p}.sections.createPlaybook`),
      detail: t(`${p}.sections.detail`),
      triggers: t(`${p}.sections.triggers`),
      approvalRequirements: t(`${p}.sections.approvalRequirements`),
      assignedOwners: t(`${p}.sections.assignedOwners`),
      executionHistory: t(`${p}.sections.executionHistory`),
      designer: t(`${p}.sections.designer`),
      visualFlow: t(`${p}.sections.visualFlow`),
      fieldSettings: t(`${p}.sections.fieldSettings`),
    },
    overview: {
      activePlaybooks: t(`${p}.overview.activePlaybooks`),
      scheduledAutomations: t(`${p}.overview.scheduledAutomations`),
      runningAutomations: t(`${p}.overview.runningAutomations`),
      failedExecutions: t(`${p}.overview.failedExecutions`),
      pendingApprovals: t(`${p}.overview.pendingApprovals`),
      recentlyCompleted: t(`${p}.overview.recentlyCompleted`),
    },
    table: {
      name: t(`${p}.table.name`),
      category: t(`${p}.table.category`),
      description: t(`${p}.table.description`),
      owner: t(`${p}.table.owner`),
      department: t(`${p}.table.department`),
      priority: t(`${p}.table.priority`),
      triggerType: t(`${p}.table.triggerType`),
      status: t(`${p}.table.status`),
      lastExecuted: t(`${p}.table.lastExecuted`),
      playbookName: t(`${p}.table.playbookName`),
      triggerEvent: t(`${p}.table.triggerEvent`),
      executionDate: t(`${p}.table.executionDate`),
      outcome: t(`${p}.table.outcome`),
      duration: t(`${p}.table.duration`),
      actions: t(`${p}.table.actions`),
      requiresApproval: t(`${p}.table.requiresApproval`),
      startedBy: t(`${p}.table.startedBy`),
      startTime: t(`${p}.table.startTime`),
      currentStatus: t(`${p}.table.currentStatus`),
      completedSteps: t(`${p}.table.completedSteps`),
      failedSteps: t(`${p}.table.failedSteps`),
      completionTime: t(`${p}.table.completionTime`),
    },
    categories: mapKeys(t, `${p}.categories`, PLAYBOOK_CATEGORIES),
    triggerTypes: mapKeys(t, `${p}.designer.triggerTypes`, DESIGNER_TRIGGER_TYPES),
    statuses: mapKeys(t, `${p}.statuses`, PLAYBOOK_STATUSES),
    priorities: mapKeys(t, `${p}.designer.priorities`, PLAYBOOK_PRIORITIES),
    stepActions: mapKeys(t, `${p}.stepActions`, STEP_ACTION_TYPES),
    stepKinds: mapKeys(t, `${p}.designer.stepKinds`, STEP_KINDS),
    conditions: mapKeys(t, `${p}.designer.conditions`, CONDITION_KEYS),
    approvalRoles: mapKeys(t, `${p}.designer.approvalRoles`, APPROVAL_ROLES),
    outcomes: mapKeys(t, `${p}.outcomes`, EXECUTION_OUTCOMES),
    executionStatuses: {
      running: t(`${p}.designer.executionStatuses.running`),
      paused: t(`${p}.designer.executionStatuses.paused`),
      completed: t(`${p}.designer.executionStatuses.completed`),
      failed: t(`${p}.designer.executionStatuses.failed`),
      test: t(`${p}.designer.executionStatuses.test`),
    },
    flowNodes: mapKeys(t, `${p}.designer.flowNodes`, FLOW_NODES),
    filters: {
      category: t(`${p}.filters.category`),
      status: t(`${p}.filters.status`),
      triggerType: t(`${p}.filters.triggerType`),
      owner: t(`${p}.filters.owner`),
      department: t(`${p}.filters.department`),
      outcome: t(`${p}.filters.outcome`),
      allCategories: t(`${p}.filters.allCategories`),
      allStatuses: t(`${p}.filters.allStatuses`),
      allTriggerTypes: t(`${p}.filters.allTriggerTypes`),
      allOutcomes: t(`${p}.filters.allOutcomes`),
      apply: t(`${p}.filters.apply`),
    },
    actions: {
      activate: t(`${p}.actions.activate`),
      pause: t(`${p}.actions.pause`),
      archive: t(`${p}.actions.archive`),
      execute: t(`${p}.actions.execute`),
      retry: t(`${p}.actions.retry`),
      escalate: t(`${p}.actions.escalate`),
      disable: t(`${p}.actions.disable`),
      grantApproval: t(`${p}.actions.grantApproval`),
      rejectApproval: t(`${p}.actions.rejectApproval`),
      useTemplate: t(`${p}.actions.useTemplate`),
      applying: t(`${p}.actions.applying`),
      edit: t(`${p}.actions.edit`),
      duplicate: t(`${p}.actions.duplicate`),
      viewDetails: t(`${p}.actions.viewDetails`),
      save: t(`${p}.actions.save`),
      cancel: t(`${p}.actions.cancel`),
      createPlaybook: t(`${p}.actions.createPlaybook`),
      openDesigner: t(`${p}.actions.openDesigner`),
      saveDesigner: t(`${p}.actions.saveDesigner`),
      runTest: t(`${p}.actions.runTest`),
      skipStep: t(`${p}.actions.skipStep`),
      publishTemplate: t(`${p}.actions.publishTemplate`),
    },
    create: {
      name: t(`${p}.create.name`),
      owner: t(`${p}.create.owner`),
      description: t(`${p}.create.description`),
      submit: t(`${p}.create.submit`),
      placeholderName: t(`${p}.create.placeholderName`),
      placeholderOwner: t(`${p}.create.placeholderOwner`),
      placeholderDescription: t(`${p}.create.placeholderDescription`),
    },
    designer: {
      title: t(`${p}.designer.title`),
      subtitle: t(`${p}.designer.subtitle`),
      ifLabel: t(`${p}.designer.ifLabel`),
      thenLabel: t(`${p}.designer.thenLabel`),
      completionRules: t(`${p}.designer.completionRules`),
      addCondition: t(`${p}.designer.addCondition`),
      addApproval: t(`${p}.designer.addApproval`),
    },
    notifications: {
      onStart: t(`${p}.designer.notifications.onStart`),
      onApproval: t(`${p}.designer.notifications.onApproval`),
      onComplete: t(`${p}.designer.notifications.onComplete`),
      onFailure: t(`${p}.designer.notifications.onFailure`),
    },
    errorHandling: {
      retry: t(`${p}.designer.errorHandling.retry`),
      skip: t(`${p}.designer.errorHandling.skip`),
      escalate: t(`${p}.designer.errorHandling.escalate`),
      pause: t(`${p}.designer.errorHandling.pause`),
    },
    testMode: {
      title: t(`${p}.designer.testMode.title`),
      description: t(`${p}.designer.testMode.description`),
      valid: t(`${p}.designer.testMode.valid`),
      invalid: t(`${p}.designer.testMode.invalid`),
    },
    superAdmin: {
      title: t(`${p}.designer.superAdmin.title`),
      publishTemplate: t(`${p}.designer.superAdmin.publishTemplate`),
      disableWorkflow: t(`${p}.designer.superAdmin.disableWorkflow`),
      reviewFailures: t(`${p}.designer.superAdmin.reviewFailures`),
      analyzeAdoption: t(`${p}.designer.superAdmin.analyzeAdoption`),
      totalPlaybooks: t(`${p}.designer.superAdmin.totalPlaybooks`),
      templatesPublished: t(`${p}.designer.superAdmin.templatesPublished`),
    },
  };
}
