import type { Translator } from "@/lib/i18n/translate";

export function buildMarketplaceOperationsLabels(t: Translator) {
  const p = "customerApp.marketplaceOperations";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    businessPacks: t(`${p}.businessPacks`),
    installed: t(`${p}.installed`),
    recommended: t(`${p}.recommended`),
    connectors: t(`${p}.connectors`),
    licenses: t(`${p}.licenses`),
    domains: t(`${p}.domains`),
    purchases: t(`${p}.purchases`),
    reports: t(`${p}.reports`),
    companion: t(`${p}.companion`),
    catalogCount: t(`${p}.catalogCount`),
    installedCount: t(`${p}.installedCount`),
    trialCount: t(`${p}.trialCount`),
    updateCount: t(`${p}.updateCount`),
    installPack: t(`${p}.installPack`),
    startTrial: t(`${p}.startTrial`),
    applyUpdate: t(`${p}.applyUpdate`),
    featuredPacks: t(`${p}.featuredPacks`),
    industryPacks: t(`${p}.industryPacks`),
    availableUpgrades: t(`${p}.availableUpgrades`),
    packHealth: t(`${p}.packHealth`),
    domainIntelligence: t(`${p}.domainIntelligence`),
    licenseOrchestration: t(`${p}.licenseOrchestration`),
    companionAdvisor: t(`${p}.companionAdvisor`),
    executiveDashboard: t(`${p}.executiveDashboard`),
    platformGovernance: t(`${p}.platformGovernance`),
    searchPlaceholder: t(`${p}.searchPlaceholder`),
    searchMarketplace: t(`${p}.searchMarketplace`),
    noItems: t(`${p}.noItems`),
    emptyHint: t(`${p}.emptyHint`),
    auditLog: t(`${p}.auditLog`),
    statusInstalled: t(`${p}.statusInstalled`),
    statusAvailable: t(`${p}.statusAvailable`),
    statusUpdate: t(`${p}.statusUpdate`),
    statusLicense: t(`${p}.statusLicense`),
    statusDisabled: t(`${p}.statusDisabled`),
    healthHealthy: t(`${p}.healthHealthy`),
    healthAttention: t(`${p}.healthAttention`),
    healthAction: t(`${p}.healthAction`),
    perMonth: t(`${p}.perMonth`),
    dependenciesMissing: t(`${p}.dependenciesMissing`),
    openCatalog: t(`${p}.openCatalog`),
    openInstalled: t(`${p}.openInstalled`),
  };
}

export type MarketplaceOperationsLabels = ReturnType<typeof buildMarketplaceOperationsLabels>;
