import type { ResilienceLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildResilienceLabels(t: Translator): ResilienceLabels {
  const p = "customerApp.portalStructure.resilience";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      status: t(`${p}.filters.status`),
      owner: t(`${p}.filters.owner`),
      trend: t(`${p}.filters.trend`),
      priority: t(`${p}.filters.priority`),
      periodFrom: t(`${p}.filters.periodFrom`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      resilienceScore: t(`${p}.dashboard.resilienceScore`),
      adaptability: t(`${p}.dashboard.adaptability`),
      continuityPreparedness: t(`${p}.dashboard.continuityPreparedness`),
      operationalStability: t(`${p}.dashboard.operationalStability`),
      dependencyRisk: t(`${p}.dashboard.dependencyRisk`),
      recoveryReadiness: t(`${p}.dashboard.recoveryReadiness`),
      positiveIndicators: t(`${p}.dashboard.positiveIndicators`),
      openRecommendations: t(`${p}.dashboard.openRecommendations`),
      resilienceStatus: t(`${p}.dashboard.resilienceStatus`),
    },
    signals: {
      title: t(`${p}.signals.title`),
      continuityPlanning: t(`${p}.signals.continuityPlanning`),
      riskMitigation: t(`${p}.signals.riskMitigation`),
      backupOwnership: t(`${p}.signals.backupOwnership`),
      operationalDependencies: t(`${p}.signals.operationalDependencies`),
      learningImplementation: t(`${p}.signals.learningImplementation`),
      capacityBalance: t(`${p}.signals.capacityBalance`),
      policyCompliance: t(`${p}.signals.policyCompliance`),
      incidentPreparedness: t(`${p}.signals.incidentPreparedness`),
      vendorDiversification: t(`${p}.signals.vendorDiversification`),
      leadershipReadiness: t(`${p}.signals.leadershipReadiness`),
    },
    areas: {
      title: t(`${p}.areas.title`),
      owner: t(`${p}.areas.owner`),
      assessment: t(`${p}.areas.assessment`),
      status: t(`${p}.areas.status`),
      trend: t(`${p}.areas.trend`),
      vulnerabilities: t(`${p}.areas.vulnerabilities`),
      safeguards: t(`${p}.areas.safeguards`),
      recovery: t(`${p}.areas.recovery`),
      lastReviewed: t(`${p}.areas.lastReviewed`),
    },
    vulnerabilities: { title: t(`${p}.vulnerabilities.title`) },
    timeline: { title: t(`${p}.timeline.title`) },
    statuses: {
      highly_resilient: t(`${p}.statuses.highlyResilient`),
      resilient: t(`${p}.statuses.resilient`),
      stable: t(`${p}.statuses.stable`),
      vulnerable: t(`${p}.statuses.vulnerable`),
      requires_attention: t(`${p}.statuses.requiresAttention`),
    },
    trends: {
      improving: t(`${p}.trends.improving`),
      stable: t(`${p}.trends.stable`),
      declining: t(`${p}.trends.declining`),
    },
    priorities: {
      opportunity: t(`${p}.priorities.opportunity`),
      recommended: t(`${p}.priorities.recommended`),
      important: t(`${p}.priorities.important`),
      immediate_attention: t(`${p}.priorities.immediateAttention`),
    },
    categories: {
      operational_resilience: t(`${p}.categories.operationalResilience`),
      technology_resilience: t(`${p}.categories.technologyResilience`),
      workforce_resilience: t(`${p}.categories.workforceResilience`),
      vendor_resilience: t(`${p}.categories.vendorResilience`),
      leadership_resilience: t(`${p}.categories.leadershipResilience`),
      financial_resilience: t(`${p}.categories.financialResilience`),
      compliance_resilience: t(`${p}.categories.complianceResilience`),
      security_resilience: t(`${p}.categories.securityResilience`),
      strategic_resilience: t(`${p}.categories.strategicResilience`),
      custom_category: t(`${p}.categories.customCategory`),
    },
    recommendations: {
      reviewSinglePointsOfFailure: t(`${p}.recommendations.reviewSinglePointsOfFailure`),
      strengthenBackupOwnership: t(`${p}.recommendations.strengthenBackupOwnership`),
      updateContinuityPlans: t(`${p}.recommendations.updateContinuityPlans`),
      diversifyCriticalDependencies: t(`${p}.recommendations.diversifyCriticalDependencies`),
      scheduleResilienceReviews: t(`${p}.recommendations.scheduleResilienceReviews`),
      conductPreparednessExercises: t(`${p}.recommendations.conductPreparednessExercises`),
    },
    vulnerabilityKeys: {
      overRelianceKeyIndividuals: t(`${p}.vulnerabilityKeys.overRelianceKeyIndividuals`),
      assetsWithoutBackups: t(`${p}.vulnerabilityKeys.assetsWithoutBackups`),
      singlePointsOfFailure: t(`${p}.vulnerabilityKeys.singlePointsOfFailure`),
      agingContinuityPlans: t(`${p}.vulnerabilityKeys.agingContinuityPlans`),
      insufficientReviewFrequency: t(`${p}.vulnerabilityKeys.insufficientReviewFrequency`),
      vendorConcentrationRisk: t(`${p}.vulnerabilityKeys.vendorConcentrationRisk`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      predictDisruptions: t(`${p}.faq.predictDisruptions`),
      predictDisruptionsAnswer: t(`${p}.faq.predictDisruptionsAnswer`),
      improveOverTime: t(`${p}.faq.improveOverTime`),
      improveOverTimeAnswer: t(`${p}.faq.improveOverTimeAnswer`),
    },
  };
}
