import type { CustomerHealthLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildCustomerHealthLabels(t: Translator): CustomerHealthLabels {
  const p = "customerApp.portalStructure.customerHealth";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      priority: t(`${p}.filters.priority`),
      trend: t(`${p}.filters.trend`),
      periodFrom: t(`${p}.filters.periodFrom`),
      department: t(`${p}.filters.department`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      overallHealth: t(`${p}.dashboard.overallHealth`),
      engagement: t(`${p}.dashboard.engagement`),
      supportSatisfaction: t(`${p}.dashboard.supportSatisfaction`),
      adoption: t(`${p}.dashboard.adoption`),
      learningCompletion: t(`${p}.dashboard.learningCompletion`),
      relationshipTrend: t(`${p}.dashboard.relationshipTrend`),
      openRecommendations: t(`${p}.dashboard.openRecommendations`),
      healthStatus: t(`${p}.dashboard.healthStatus`),
    },
    indicators: {
      title: t(`${p}.indicators.title`),
      platformEngagement: t(`${p}.indicators.platformEngagement`),
      trainingParticipation: t(`${p}.indicators.trainingParticipation`),
      supportInteractions: t(`${p}.indicators.supportInteractions`),
      adoptionProgress: t(`${p}.indicators.adoptionProgress`),
      securityCompletion: t(`${p}.indicators.securityCompletion`),
      integrationActivity: t(`${p}.indicators.integrationActivity`),
      recommendationCompletion: t(`${p}.indicators.recommendationCompletion`),
    },
    engagement: {
      title: t(`${p}.engagement.title`),
      activeTeams: t(`${p}.engagement.activeTeams`),
      departmentsSupport: t(`${p}.engagement.departmentsSupport`),
      underutilized: t(`${p}.engagement.underutilized`),
      positiveMomentum: t(`${p}.engagement.positiveMomentum`),
      decliningActivity: t(`${p}.engagement.decliningActivity`),
    },
    support: {
      title: t(`${p}.support.title`),
      openRequests: t(`${p}.support.openRequests`),
      resolvedRequests: t(`${p}.support.resolvedRequests`),
      resolutionTrend: t(`${p}.support.resolutionTrend`),
      satisfaction: t(`${p}.support.satisfaction`),
      selfService: t(`${p}.support.selfService`),
      knowledgeEngagement: t(`${p}.support.knowledgeEngagement`),
    },
    timeline: { title: t(`${p}.timeline.title`) },
    team: {
      title: t(`${p}.team.title`),
      engagement: t(`${p}.team.engagement`),
      learning: t(`${p}.team.learning`),
    },
    statuses: {
      thriving: t(`${p}.statuses.thriving`),
      healthy: t(`${p}.statuses.healthy`),
      stable: t(`${p}.statuses.stable`),
      requires_attention: t(`${p}.statuses.requiresAttention`),
      critical_support_needed: t(`${p}.statuses.criticalSupportNeeded`),
    },
    trends: {
      improving: t(`${p}.trends.improving`),
      stable: t(`${p}.trends.stable`),
      declining: t(`${p}.trends.declining`),
      insufficient_data: t(`${p}.trends.insufficientData`),
    },
    priorities: {
      informational: t(`${p}.priorities.informational`),
      opportunity: t(`${p}.priorities.opportunity`),
      important: t(`${p}.priorities.important`),
      high_priority: t(`${p}.priorities.highPriority`),
    },
    recommendations: {
      scheduleOnboardingRefresh: t(`${p}.recommendations.scheduleOnboardingRefresh`),
      reviewOpenSupportRequests: t(`${p}.recommendations.reviewOpenSupportRequests`),
      exploreBusinessPacks: t(`${p}.recommendations.exploreBusinessPacks`),
      encourageAssignedLearning: t(`${p}.recommendations.encourageAssignedLearning`),
      activateSecurityProtections: t(`${p}.recommendations.activateSecurityProtections`),
      conductQuarterlyReview: t(`${p}.recommendations.conductQuarterlyReview`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      goodCustomer: t(`${p}.faq.goodCustomer`),
      goodCustomerAnswer: t(`${p}.faq.goodCustomerAnswer`),
      improveOutcomes: t(`${p}.faq.improveOutcomes`),
      improveOutcomesAnswer: t(`${p}.faq.improveOutcomesAnswer`),
    },
  };
}
