import type { CustomerHealthLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildCustomerHealthLabels(t: Translator): CustomerHealthLabels {
  const p = "customerApp.portalStructure.customerHealth";
  const rec = (key: string) => ({
    title: t(`${p}.recommendations.${key}.title`),
    reason: t(`${p}.recommendations.${key}.reason`),
    action: t(`${p}.recommendations.${key}.action`),
  });

  return {
    eyebrow: t(`${p}.eyebrow`),
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    breadcrumbSupport: t(`${p}.breadcrumbSupport`),
    breadcrumbCustomerHealth: t(`${p}.breadcrumbCustomerHealth`),
    backToSupport: t(`${p}.backToSupport`),
    purposeSummary: {
      healthy: t(`${p}.purposeSummary.healthy`),
      moderate: t(`${p}.purposeSummary.moderate`),
      poor: t(`${p}.purposeSummary.poor`),
      critical: t(`${p}.purposeSummary.critical`),
      unknown: t(`${p}.purposeSummary.unknown`),
    },
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyAction: t(`${p}.emptyAction`),
    errorTitle: t(`${p}.errorTitle`),
    errorBody: t(`${p}.errorBody`),
    retry: t(`${p}.retry`),
    sections: {
      overview: t(`${p}.sections.overview`),
      recommendedAction: t(`${p}.sections.recommendedAction`),
      drivers: t(`${p}.sections.drivers`),
      strengths: t(`${p}.sections.strengths`),
      needsAttention: t(`${p}.sections.needsAttention`),
      trend: t(`${p}.sections.trend`),
      risks: t(`${p}.sections.risks`),
      operationalSignals: t(`${p}.sections.operationalSignals`),
      history: t(`${p}.sections.history`),
      understanding: t(`${p}.sections.understanding`),
    },
    overview: {
      healthScore: t(`${p}.overview.healthScore`),
      healthState: t(`${p}.overview.healthState`),
      trend: t(`${p}.overview.trend`),
      scoreChange: t(`${p}.overview.scoreChange`),
      scoreChangeUnavailable: t(`${p}.overview.scoreChangeUnavailable`),
      riskLevel: t(`${p}.overview.riskLevel`),
      lastCalculated: t(`${p}.overview.lastCalculated`),
      explanation: t(`${p}.overview.explanation`),
      advisory: t(`${p}.overview.advisory`),
    },
    healthStates: {
      healthy: t(`${p}.healthStates.healthy`),
      good: t(`${p}.healthStates.good`),
      moderate: t(`${p}.healthStates.moderate`),
      poor: t(`${p}.healthStates.poor`),
      critical_health: t(`${p}.healthStates.criticalHealth`),
      unknown: t(`${p}.healthStates.unknown`),
    },
    trendStates: {
      improving: t(`${p}.trendStates.improving`),
      stable: t(`${p}.trendStates.stable`),
      declining: t(`${p}.trendStates.declining`),
      rapid_decline: t(`${p}.trendStates.rapidDecline`),
      insufficient_data: t(`${p}.trendStates.insufficientData`),
    },
    riskLevels: {
      low: t(`${p}.riskLevels.low`),
      moderate: t(`${p}.riskLevels.moderate`),
      elevated: t(`${p}.riskLevels.elevated`),
      high: t(`${p}.riskLevels.high`),
    },
    driverEffects: {
      positive: t(`${p}.driverEffects.positive`),
      neutral: t(`${p}.driverEffects.neutral`),
      moderate_negative: t(`${p}.driverEffects.moderateNegative`),
      strong_negative: t(`${p}.driverEffects.strongNegative`),
      critical_negative: t(`${p}.driverEffects.criticalNegative`),
      unavailable: t(`${p}.driverEffects.unavailable`),
    },
    drivers: {
      adoption: t(`${p}.drivers.adoption`),
      engagement: t(`${p}.drivers.engagement`),
      utilization: t(`${p}.drivers.utilization`),
      learning: t(`${p}.drivers.learning`),
      security: t(`${p}.drivers.security`),
      integrations: t(`${p}.drivers.integrations`),
    },
    strengths: {
      active_users: t(`${p}.strengths.activeUsers`),
      team_size: t(`${p}.strengths.teamSize`),
      business_packs: t(`${p}.strengths.businessPacks`),
      integrations: t(`${p}.strengths.integrations`),
      open_support: t(`${p}.strengths.openSupport`),
      pending_approvals: t(`${p}.strengths.pendingApprovals`),
      open_follow_ups: t(`${p}.strengths.openFollowUps`),
    },
    strengthValues: {
      active_users: t(`${p}.strengthValues.activeUsers`),
      team_size: t(`${p}.strengthValues.teamSize`),
      business_packs: t(`${p}.strengthValues.businessPacks`),
      integrations: t(`${p}.strengthValues.integrations`),
      open_support: t(`${p}.strengthValues.openSupport`),
      pending_approvals: t(`${p}.strengthValues.pendingApprovals`),
      open_follow_ups: t(`${p}.strengthValues.openFollowUps`),
      none: t(`${p}.strengthValues.none`),
    },
    needsAttention: {
      active_users: t(`${p}.needsAttention.activeUsers`),
      team_size: t(`${p}.needsAttention.teamSize`),
      business_packs: t(`${p}.needsAttention.businessPacks`),
      integrations: t(`${p}.needsAttention.integrations`),
      open_support: t(`${p}.needsAttention.openSupport`),
      pending_approvals: t(`${p}.needsAttention.pendingApprovals`),
      open_follow_ups: t(`${p}.needsAttention.openFollowUps`),
    },
    risks: {
      open_support_backlog: t(`${p}.risks.openSupportBacklog`),
      pending_approvals: t(`${p}.risks.pendingApprovals`),
      security_not_configured: t(`${p}.risks.securityNotConfigured`),
      low_engagement: t(`${p}.risks.lowEngagement`),
    },
    riskDescriptions: {
      openSupportBacklog: t(`${p}.riskDescriptions.openSupportBacklog`),
      pendingApprovals: t(`${p}.riskDescriptions.pendingApprovals`),
      securityNotConfigured: t(`${p}.riskDescriptions.securityNotConfigured`),
      lowEngagement: t(`${p}.riskDescriptions.lowEngagement`),
    },
    operationalSignals: {
      team_activity: t(`${p}.operationalSignals.teamActivity`),
      business_packs_installed: t(`${p}.operationalSignals.businessPacksInstalled`),
      capabilities_enabled: t(`${p}.operationalSignals.capabilitiesEnabled`),
      operations_activity: t(`${p}.operationalSignals.operationsActivity`),
    },
    signalDescriptions: {
      teamActivity: t(`${p}.signalDescriptions.teamActivity`),
      businessPacksInstalled: t(`${p}.signalDescriptions.businessPacksInstalled`),
      capabilitiesEnabled: t(`${p}.signalDescriptions.capabilitiesEnabled`),
      operationsActivity: t(`${p}.signalDescriptions.operationsActivity`),
    },
    signalStatuses: {
      positive: t(`${p}.signalStatuses.positive`),
      neutral: t(`${p}.signalStatuses.neutral`),
      warning: t(`${p}.signalStatuses.warning`),
      unavailable: t(`${p}.signalStatuses.unavailable`),
    },
    historyEventTypes: {
      scoreCalculated: t(`${p}.historyEventTypes.scoreCalculated`),
      reviewStarted: t(`${p}.historyEventTypes.reviewStarted`),
      genericEvent: t(`${p}.historyEventTypes.genericEvent`),
    },
    historyDescriptions: {
      scoreCalculated: t(`${p}.historyDescriptions.scoreCalculated`),
      reviewStarted: t(`${p}.historyDescriptions.reviewStarted`),
      genericEvent: t(`${p}.historyDescriptions.genericEvent`),
    },
    historyStatuses: {
      healthy: t(`${p}.historyStatuses.healthy`),
      moderate: t(`${p}.historyStatuses.moderate`),
      poor: t(`${p}.historyStatuses.poor`),
      critical_health: t(`${p}.historyStatuses.criticalHealth`),
      neutral: t(`${p}.historyStatuses.neutral`),
      unavailable: t(`${p}.historyStatuses.unavailable`),
      unknown: t(`${p}.historyStatuses.unknown`),
    },
    trend: {
      periodLabel: t(`${p}.trend.periodLabel`),
      empty: t(`${p}.trend.empty`),
      insufficientData: t(`${p}.trend.insufficientData`),
      periods: {
        "7": t(`${p}.trend.periods.d7`),
        "30": t(`${p}.trend.periods.d30`),
        "90": t(`${p}.trend.periods.d90`),
        "365": t(`${p}.trend.periods.d365`),
      },
    },
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      priority: t(`${p}.filters.priority`),
      trend: t(`${p}.filters.trend`),
      date: t(`${p}.filters.date`),
      sortBy: t(`${p}.filters.sortBy`),
      all: t(`${p}.filters.all`),
      categories: {
        support: t(`${p}.filters.categories.support`),
        governance: t(`${p}.filters.categories.governance`),
        security: t(`${p}.filters.categories.security`),
        engagement: t(`${p}.filters.categories.engagement`),
        adoption: t(`${p}.filters.categories.adoption`),
        utilization: t(`${p}.filters.categories.utilization`),
        operations: t(`${p}.filters.categories.operations`),
      },
      priorities: {
        high: t(`${p}.filters.priorities.high`),
        high_impact: t(`${p}.filters.priorities.highImpact`),
        medium: t(`${p}.filters.priorities.medium`),
        important: t(`${p}.filters.priorities.important`),
        low: t(`${p}.filters.priorities.low`),
      },
      sortOptions: {
        impact_desc: t(`${p}.filters.sortOptions.impactDesc`),
        severity_desc: t(`${p}.filters.sortOptions.severityDesc`),
        date_desc: t(`${p}.filters.sortOptions.dateDesc`),
        date_asc: t(`${p}.filters.sortOptions.dateAsc`),
      },
    },
    history: {
      score: t(`${p}.history.score`),
      eventType: t(`${p}.history.eventType`),
      empty: t(`${p}.history.empty`),
    },
    understanding: {
      q1: t(`${p}.understanding.q1`),
      a1: t(`${p}.understanding.a1`),
      q2: t(`${p}.understanding.q2`),
      a2: t(`${p}.understanding.a2`),
      q3: t(`${p}.understanding.q3`),
      a3: t(`${p}.understanding.a3`),
      q4: t(`${p}.understanding.q4`),
      a4: t(`${p}.understanding.a4`),
    },
    scoreAvailability: {
    available: t(`${p}.scoreAvailability.available`),
    awaiting_first_sync: t(`${p}.scoreAvailability.awaitingFirstSync`),
    calculating: t(`${p}.scoreAvailability.calculating`),
    insufficient_data: t(`${p}.scoreAvailability.insufficientData`),
    stale: t(`${p}.scoreAvailability.stale`),
    source_unavailable: t(`${p}.scoreAvailability.sourceUnavailable`),
    calculation_failed: t(`${p}.scoreAvailability.calculationFailed`),
    delayed: t(`${p}.scoreAvailability.delayed`),
  },
    scoreAvailabilityDescriptions: {
      available: t(`${p}.scoreAvailabilityDescriptions.available`),
      awaitingFirstSync: t(`${p}.scoreAvailabilityDescriptions.awaitingFirstSync`),
      calculating: t(`${p}.scoreAvailabilityDescriptions.calculating`),
      insufficientData: t(`${p}.scoreAvailabilityDescriptions.insufficientData`),
      stale: t(`${p}.scoreAvailabilityDescriptions.stale`),
      sourceUnavailable: t(`${p}.scoreAvailabilityDescriptions.sourceUnavailable`),
      calculationFailed: t(`${p}.scoreAvailabilityDescriptions.calculationFailed`),
      delayed: t(`${p}.scoreAvailabilityDescriptions.delayed`),
    },
    sourceFreshness: {
      current: t(`${p}.sourceFreshness.current`),
      delayed: t(`${p}.sourceFreshness.delayed`),
      stale: t(`${p}.sourceFreshness.stale`),
      unavailable: t(`${p}.sourceFreshness.unavailable`),
      awaiting_first_sync: t(`${p}.sourceFreshness.awaitingFirstSync`),
    },
    pilot: {
      title: t(`${p}.pilot.title`),
      readOnlyMode: t(`${p}.pilot.readOnlyMode`),
      readOnlyDescription: t(`${p}.pilot.readOnlyDescription`),
      lastSuccessfulSync: t(`${p}.pilot.lastSuccessfulSync`),
      dataFreshness: t(`${p}.pilot.dataFreshness`),
      connectedSources: t(`${p}.pilot.connectedSources`),
      awaitingFirstSync: t(`${p}.pilot.awaitingFirstSync`),
      shadowPrepared: t(`${p}.pilot.shadowPrepared`),
      shadowNoAction: t(`${p}.pilot.shadowNoAction`),
    },
    severityLabels: {
      critical: t(`${p}.severityLabels.critical`),
      high: t(`${p}.severityLabels.high`),
      medium: t(`${p}.severityLabels.medium`),
      low: t(`${p}.severityLabels.low`),
      info: t(`${p}.severityLabels.info`),
    },
    recommendations: {
      inviteTeam: rec("inviteTeam"),
      explorePacks: rec("explorePacks"),
      enableIntegrations: rec("enableIntegrations"),
      reviewSupport: rec("reviewSupport"),
      reviewApprovals: rec("reviewApprovals"),
      completeFollowUps: rec("completeFollowUps"),
      completeOnboarding: rec("completeOnboarding"),
      configureSecurity: rec("configureSecurity"),
      completeFirstUnonightSync: rec("completeFirstUnonightSync"),
    },
  };
}
