import type { Translator } from "@/lib/i18n/translate";

export function buildEmployeeManagementLabels(t: Translator) {
  const p = "customerApp.employeeManagement";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    privacyNote: t(`${p}.privacyNote`),
    overview: t(`${p}.overview`),
    employees: t(`${p}.employees`),
    roles: t(`${p}.roles`),
    departments: t(`${p}.departments`),
    invitations: t(`${p}.invitations`),
    accessControl: t(`${p}.accessControl`),
    activity: t(`${p}.activity`),
    offboarding: t(`${p}.offboarding`),
    myWorkspace: t(`${p}.myWorkspace`),
    inviteEmployee: t(`${p}.inviteEmployee`),
    searchPlaceholder: t(`${p}.searchPlaceholder`),
    totalSeats: t(`${p}.totalSeats`),
    usedSeats: t(`${p}.usedSeats`),
    availableSeats: t(`${p}.availableSeats`),
    pendingInvitations: t(`${p}.pendingInvitations`),
    activeEmployees: t(`${p}.activeEmployees`),
    name: t(`${p}.name`),
    email: t(`${p}.email`),
    role: t(`${p}.role`),
    department: t(`${p}.department`),
    status: t(`${p}.status`),
    jobTitle: t(`${p}.jobTitle`),
    manager: t(`${p}.manager`),
    suspend: t(`${p}.suspend`),
    reactivate: t(`${p}.reactivate`),
    offboard: t(`${p}.offboard`),
    sendInvite: t(`${p}.sendInvite`),
    cancel: t(`${p}.cancel`),
    noEmployees: t(`${p}.noEmployees`),
    noInvitations: t(`${p}.noInvitations`),
    accessDenied: t(`${p}.accessDenied`),
    appSuspended: t(`${p}.appSuspended`),
    manageModuleAccess: t(`${p}.manageModuleAccess`),
    purchaseSeats: t(`${p}.purchaseSeats`),
    assignedModules: t(`${p}.assignedModules`),
    myTasks: t(`${p}.myTasks`),
    myCalendar: t(`${p}.myCalendar`),
    myNotifications: t(`${p}.myNotifications`),
    offboardWarning: t(`${p}.offboardWarning`),
    confirmOffboard: t(`${p}.confirmOffboard`),
    back: t(`${p}.back`),
  };
}

export type EmployeeManagementLabels = ReturnType<typeof buildEmployeeManagementLabels>;
