import type { FutureStatePlanningLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildFutureStatePlanningLabels(t: Translator): FutureStatePlanningLabels {
  const p = "customerApp.portalStructure.futureStatePlanning";
  return {
    title:        t(`${p}.title`),
    subtitle:     t(`${p}.subtitle`),
    loading:      t(`${p}.loading`),
    principle:    t(`${p}.principle`),
    advisoryNote: t(`${p}.advisoryNote`),
    emptyTitle:   t(`${p}.emptyTitle`),
    emptyBody:    t(`${p}.emptyBody`),
    emptyCta:     t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search:            t(`${p}.filters.search`),
      category:          t(`${p}.filters.category`),
      department:        t(`${p}.filters.department`),
      strategicPriority: t(`${p}.filters.strategicPriority`),
      timeHorizon:       t(`${p}.filters.timeHorizon`),
      executiveOwner:    t(`${p}.filters.executiveOwner`),
      status:            t(`${p}.filters.status`),
      all:               t(`${p}.filters.all`),
    },
    dashboard: {
      readinessScore:    t(`${p}.dashboard.readinessScore`),
      alignmentScore:    t(`${p}.dashboard.alignmentScore`),
      progressScore:     t(`${p}.dashboard.progressScore`),
      completenessScore: t(`${p}.dashboard.completenessScore`),
      executiveSummary:  t(`${p}.dashboard.executiveSummary`),
      activePlans:       t(`${p}.dashboard.activePlans`),
      upcomingReviews:   t(`${p}.dashboard.upcomingReviews`),
      allPlans:          t(`${p}.dashboard.allPlans`),
      recommendations:   t(`${p}.dashboard.recommendations`),
      milestones:        t(`${p}.dashboard.milestones`),
      timeline:          t(`${p}.dashboard.timeline`),
      briefing:          t(`${p}.dashboard.briefing`),
      alignmentView:     t(`${p}.dashboard.alignmentView`),
      blueprint:         t(`${p}.dashboard.blueprint`),
      planningQuestions: t(`${p}.dashboard.planningQuestions`),
      viewPlan:          t(`${p}.dashboard.viewPlan`),
      createPlan:        t(`${p}.dashboard.createPlan`),
    },
    blueprint: {
      visionStatement:     t(`${p}.blueprint.visionStatement`),
      desiredOutcomes:     t(`${p}.blueprint.desiredOutcomes`),
      strategicPriorities: t(`${p}.blueprint.strategicPriorities`),
      executiveSponsors:   t(`${p}.blueprint.executiveSponsors`),
      departmentsInvolved: t(`${p}.blueprint.departmentsInvolved`),
      estimatedTimeline:   t(`${p}.blueprint.estimatedTimeline`),
      keyDependencies:     t(`${p}.blueprint.keyDependencies`),
      risks:               t(`${p}.blueprint.risks`),
      opportunities:       t(`${p}.blueprint.opportunities`),
      currentState:        t(`${p}.blueprint.currentState`),
      desiredFutureState:  t(`${p}.blueprint.desiredFutureState`),
      strategicObjectives: t(`${p}.blueprint.strategicObjectives`),
      initiatives:         t(`${p}.blueprint.initiatives`),
      successIndicators:   t(`${p}.blueprint.successIndicators`),
      reviewSchedule:      t(`${p}.blueprint.reviewSchedule`),
    },
    alignment: {
      department:       t(`${p}.alignment.department`),
      currentAlignment: t(`${p}.alignment.currentAlignment`),
      targetAlignment:  t(`${p}.alignment.targetAlignment`),
      progress:         t(`${p}.alignment.progress`),
      owner:            t(`${p}.alignment.owner`),
      reviewDate:       t(`${p}.alignment.reviewDate`),
    },
    milestone: {
      planned:          t(`${p}.milestone.planned`),
      completed:        t(`${p}.milestone.completed`),
      delayed:          t(`${p}.milestone.delayed`),
      upcoming:         t(`${p}.milestone.upcoming`),
      successIndicator: t(`${p}.milestone.successIndicator`),
      owner:            t(`${p}.milestone.owner`),
      targetDate:       t(`${p}.milestone.targetDate`),
    },
    briefing: {
      currentPosition:    t(`${p}.briefing.currentPosition`),
      futureVision:       t(`${p}.briefing.futureVision`),
      progressStatus:     t(`${p}.briefing.progressStatus`),
      keyOpportunities:   t(`${p}.briefing.keyOpportunities`),
      keyRisks:           t(`${p}.briefing.keyRisks`),
      recommendedActions: t(`${p}.briefing.recommendedActions`),
      nextReviewDate:     t(`${p}.briefing.nextReviewDate`),
    },
    detail: {
      back:          t(`${p}.detail.back`),
      blueprint:     t(`${p}.detail.blueprint`),
      alignment:     t(`${p}.detail.alignment`),
      milestones:    t(`${p}.detail.milestones`),
      reviewHistory: t(`${p}.detail.reviewHistory`),
      advisoryNote:  t(`${p}.detail.advisoryNote`),
    },
    create: {
      title:       t(`${p}.create.title`),
      description: t(`${p}.create.description`),
      category:    t(`${p}.create.category`),
      horizon:     t(`${p}.create.horizon`),
      vision:      t(`${p}.create.vision`),
      submit:      t(`${p}.create.submit`),
      success:     t(`${p}.create.success`),
    },
    categories: {
      organizationalGrowth:    t(`${p}.categories.organizationalGrowth`),
      leadershipEvolution:     t(`${p}.categories.leadershipEvolution`),
      workforceDevelopment:    t(`${p}.categories.workforceDevelopment`),
      customerExperience:      t(`${p}.categories.customerExperience`),
      marketExpansion:         t(`${p}.categories.marketExpansion`),
      operationalExcellence:   t(`${p}.categories.operationalExcellence`),
      technologyAdvancement:   t(`${p}.categories.technologyAdvancement`),
      governanceMaturity:      t(`${p}.categories.governanceMaturity`),
      businessInnovation:      t(`${p}.categories.businessInnovation`),
      enterpriseTransformation:t(`${p}.categories.enterpriseTransformation`),
    },
    statuses: {
      draft:       t(`${p}.statuses.draft`),
      active:      t(`${p}.statuses.active`),
      underReview: t(`${p}.statuses.underReview`),
      onTrack:     t(`${p}.statuses.onTrack`),
      atRisk:      t(`${p}.statuses.atRisk`),
      completed:   t(`${p}.statuses.completed`),
      archived:    t(`${p}.statuses.archived`),
    },
    horizons: {
      oneYear:   t(`${p}.horizons.oneYear`),
      threeYears:t(`${p}.horizons.threeYears`),
      fiveYears: t(`${p}.horizons.fiveYears`),
      tenYears:  t(`${p}.horizons.tenYears`),
      custom:    t(`${p}.horizons.custom`),
    },
    priorities: {
      low:      t(`${p}.priorities.low`),
      moderate: t(`${p}.priorities.moderate`),
      high:     t(`${p}.priorities.high`),
      strategic:t(`${p}.priorities.strategic`),
    },
    milestoneStatuses: {
      planned:   t(`${p}.milestoneStatuses.planned`),
      completed: t(`${p}.milestoneStatuses.completed`),
      delayed:   t(`${p}.milestoneStatuses.delayed`),
      upcoming:  t(`${p}.milestoneStatuses.upcoming`),
    },
    recommendations: {
      defineExecutiveOwnership:      t(`${p}.recommendations.defineExecutiveOwnership`),
      clarifyStrategicPriorities:    t(`${p}.recommendations.clarifyStrategicPriorities`),
      improveDepartmentAlignment:    t(`${p}.recommendations.improveDepartmentAlignment`),
      createMilestoneReviews:        t(`${p}.recommendations.createMilestoneReviews`),
      strengthenGovernance:          t(`${p}.recommendations.strengthenGovernance`),
      establishMeasurementFrameworks:t(`${p}.recommendations.establishMeasurementFrameworks`),
    },
    timelineEvents: {
      workspaceInitialized: t(`${p}.timelineEvents.workspaceInitialized`),
      visionCreated:        t(`${p}.timelineEvents.visionCreated`),
      planUpdated:          t(`${p}.timelineEvents.planUpdated`),
      strategicReview:      t(`${p}.timelineEvents.strategicReview`),
      milestoneCompleted:   t(`${p}.timelineEvents.milestoneCompleted`),
      initiativeLaunched:   t(`${p}.timelineEvents.initiativeLaunched`),
      alignmentReview:      t(`${p}.timelineEvents.alignmentReview`),
    },
    planningQuestions: [
      t(`${p}.planningQuestions.whatSuccessLooksLike`),
      t(`${p}.planningQuestions.whatMustChange`),
      t(`${p}.planningQuestions.capabilitiesRequired`),
      t(`${p}.planningQuestions.risksToManage`),
      t(`${p}.planningQuestions.initiativesToday`),
      t(`${p}.planningQuestions.measureProgress`),
    ],
    successIndicators: [
      t(`${p}.successIndicators.customerSatisfaction`),
      t(`${p}.successIndicators.revenueGoals`),
      t(`${p}.successIndicators.workforceDevelopment`),
      t(`${p}.successIndicators.operationalEfficiency`),
      t(`${p}.successIndicators.expansionTargets`),
      t(`${p}.successIndicators.strategicObjectives`),
    ],
    faq: {
      title:                t(`${p}.faq.title`),
      whatIs:               t(`${p}.faq.whatIs`),
      whatIsAnswer:         t(`${p}.faq.whatIsAnswer`),
      createsStrategy:      t(`${p}.faq.createsStrategy`),
      createsStrategyAnswer:t(`${p}.faq.createsStrategyAnswer`),
      whoShouldUse:         t(`${p}.faq.whoShouldUse`),
      whoShouldUseAnswer:   t(`${p}.faq.whoShouldUseAnswer`),
    },
  };
}

export function horizonLabel(
  labels: FutureStatePlanningLabels,
  horizon: string
): string {
  const map: Record<string, string> = {
    "1_year": labels.horizons.oneYear,
    "3_years": labels.horizons.threeYears,
    "5_years": labels.horizons.fiveYears,
    "10_years": labels.horizons.tenYears,
    custom: labels.horizons.custom,
  };
  return map[horizon] ?? horizon;
}

export function categoryLabel(
  labels: FutureStatePlanningLabels,
  category: string
): string {
  const map: Record<string, string> = {
    organizational_growth: labels.categories.organizationalGrowth,
    leadership_evolution: labels.categories.leadershipEvolution,
    workforce_development: labels.categories.workforceDevelopment,
    customer_experience: labels.categories.customerExperience,
    market_expansion: labels.categories.marketExpansion,
    operational_excellence: labels.categories.operationalExcellence,
    technology_advancement: labels.categories.technologyAdvancement,
    governance_maturity: labels.categories.governanceMaturity,
    business_innovation: labels.categories.businessInnovation,
    enterprise_transformation: labels.categories.enterpriseTransformation,
  };
  return map[category] ?? category;
}
