import type { createTranslator } from "@/lib/i18n/translate";
import type { PresenceLabels } from "@/components/presence/PresenceProvider";

type Translator = ReturnType<typeof createTranslator>;

export function buildPresenceLabels(t: Translator): PresenceLabels {
  return {
    indicatorTitle: t("presence.indicator.title"),
    indicatorAria: t("presence.indicator.aria"),
    indicatorTooltip: {
      title: t("presence.indicator.tooltipTitle"),
      status: t("presence.indicator.tooltipStatus"),
      learning: t("presence.indicator.tooltipLearning"),
      approvals: t("presence.indicator.tooltipApprovals"),
      healing: t("presence.indicator.tooltipHealing"),
      health: t("presence.indicator.tooltipHealth"),
      open: t("presence.indicator.tooltipOpen"),
    },
    centerTitle: t("presence.center.title"),
    close: t("presence.center.close"),
    loading: t("presence.center.loading"),
    currentState: t("presence.center.currentState"),
    currentActivity: t("presence.center.currentActivity"),
    status: t("presence.center.status"),
    estimatedCompletion: t("presence.center.estimatedCompletion"),
    riskLevel: t("presence.center.riskLevel"),
    seconds: t("presence.center.seconds"),
    today: t("presence.center.today"),
    snapshot: {
      environments: t("presence.center.snapshot.environments"),
      learning: t("presence.center.snapshot.learning"),
      healing: t("presence.center.snapshot.healing"),
      pending: t("presence.center.snapshot.pending"),
    },
    health: {
      title: t("presence.center.health.title"),
      deltaUp: t("presence.center.health.deltaUp"),
      deltaDown: t("presence.center.health.deltaDown"),
      deltaFlat: t("presence.center.health.deltaFlat"),
      contributors: t("presence.center.health.contributors"),
    },
    approval: {
      whyTitle: t("presence.center.approval.whyTitle"),
      whyBody: t("presence.center.approval.whyBody"),
      reasonsTitle: t("presence.center.approval.reasonsTitle"),
    },
    history: {
      viewDetails: t("presence.center.history.viewDetails"),
      hideDetails: t("presence.center.history.hideDetails"),
      trigger: t("presence.center.history.trigger"),
      actions: t("presence.center.history.actions"),
      outcome: t("presence.center.history.outcome"),
    },
    recommendations: {
      whatHappened: t("presence.center.recommendations.whatHappened"),
      whyMatters: t("presence.center.recommendations.whyMatters"),
      suggestedAction: t("presence.center.recommendations.suggestedAction"),
      ifIgnored: t("presence.center.recommendations.ifIgnored"),
    },
    impact: {
      low: t("presence.center.impact.low"),
      medium: t("presence.center.impact.medium"),
      high: t("presence.center.impact.high"),
      critical: t("presence.center.impact.critical"),
    },
    modes: {
      title: t("presence.center.modes.title"),
      normal: t("presence.center.modes.normal"),
      learning: t("presence.center.modes.learning"),
      healing: t("presence.center.modes.healing"),
      approval_required: t("presence.center.modes.approval_required"),
      attention_required: t("presence.center.modes.attention_required"),
    },
    viewMode: {
      title: t("presence.center.viewMode.title"),
      executive: t("presence.center.viewMode.executive"),
      operations: t("presence.center.viewMode.operations"),
      executiveHint: t("presence.center.viewMode.executiveHint"),
      operationsHint: t("presence.center.viewMode.operationsHint"),
    },
    metrics: {
      automationsRunning: t("presence.center.metrics.automationsRunning"),
      learningToday: t("presence.center.metrics.learningToday"),
      healingToday: t("presence.center.metrics.healingToday"),
      pendingApprovals: t("presence.center.metrics.pendingApprovals"),
      systemHealth: t("presence.center.metrics.systemHealth"),
    },
    sections: {
      activities: t("presence.center.sections.activities"),
      recommendations: t("presence.center.sections.recommendations"),
      history: t("presence.center.sections.history"),
      executiveSummary: t("presence.center.sections.executiveSummary"),
      settings: t("presence.center.sections.settings"),
      notifications: t("presence.center.sections.notifications"),
      actions: t("presence.center.sections.actions"),
    },
    actions: {
      openCenter: t("presence.center.actions.openCenter"),
      pending: t("presence.center.actions.pending"),
      executed: t("presence.center.actions.executed"),
      failed: t("presence.center.actions.failed"),
    },
    states: {
      standby: t("presence.states.standby"),
      analysing: t("presence.states.analysing"),
      working: t("presence.states.working"),
      learning: t("presence.states.learning"),
      self_healing: t("presence.states.selfHealing"),
      human_approval_required: t("presence.states.humanApproval"),
      critical_attention: t("presence.states.critical"),
    },
    stateMessages: {
      standby: t("presence.stateMessages.standby"),
      analysing: t("presence.stateMessages.analysing"),
      working: t("presence.stateMessages.working"),
      learning: t("presence.stateMessages.learning"),
      self_healing: t("presence.stateMessages.selfHealing"),
      human_approval_required: t("presence.stateMessages.humanApproval"),
      critical_attention: t("presence.stateMessages.critical"),
    },
    settings: {
      animationMode: t("presence.settings.animationMode"),
      presenceVisible: t("presence.settings.presenceVisible"),
      executiveSummaries: t("presence.settings.executiveSummaries"),
      selfHealingNotifications: t("presence.settings.selfHealingNotifications"),
      approvalNotifications: t("presence.settings.approvalNotifications"),
      learningNotifications: t("presence.settings.learningNotifications"),
      soundMode: t("presence.settings.soundMode"),
      intensities: {
        subtle: t("presence.settings.intensities.subtle"),
        normal: t("presence.settings.intensities.normal"),
        enhanced: t("presence.settings.intensities.enhanced"),
      },
      soundModes: {
        off: t("presence.settings.soundModes.off"),
        minimal: t("presence.settings.soundModes.minimal"),
        enabled: t("presence.settings.soundModes.enabled"),
      },
      save: t("presence.settings.save"),
      saved: t("presence.settings.saved"),
    },
    empty: {
      history: t("presence.empty.history"),
      recommendations: t("presence.empty.recommendations"),
    },
    briefing: {
      title: t("presence.center.briefing.title"),
      promise: t("presence.center.briefing.promise"),
      alwaysOn: t("presence.center.briefing.alwaysOn"),
      positive: t("presence.center.briefing.positive"),
      categories: t("presence.center.briefing.categories"),
      morning: t("presence.center.briefing.morning"),
      evening: t("presence.center.briefing.evening"),
      weekend: t("presence.center.briefing.weekend"),
      positiveCategory: t("presence.center.briefing.positiveCategory"),
      attention: t("presence.center.briefing.attention"),
      critical: t("presence.center.briefing.critical"),
      criticalNote: t("presence.center.briefing.criticalNote"),
      openPresence: t("presence.center.briefing.openPresence"),
      dismiss: t("presence.center.briefing.dismiss"),
    },
  };
}
