export const PRESENCE_POLL_INTERVAL_OPEN_MS = 45_000;
export const PRESENCE_POLL_INTERVAL_CLOSED_MS = 90_000;
export const COMPANION_HEARTBEAT_INTERVAL_MS = 90_000;
export const COMPANION_HEARTBEAT_INTERVAL_COLLAPSED_MS = 120_000;
