import type { PredictiveIntelligenceLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildPredictiveIntelligenceLabels(t: Translator): PredictiveIntelligenceLabels {
  const p = "customerApp.portalStructure.predictiveIntelligence";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    probabilityNote: t(`${p}.probabilityNote`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      confidenceLevel: t(`${p}.filters.confidenceLevel`),
      timeHorizon: t(`${p}.filters.timeHorizon`),
      organizationalArea: t(`${p}.filters.organizationalArea`),
      potentialImpact: t(`${p}.filters.potentialImpact`),
      reviewStatus: t(`${p}.filters.reviewStatus`),
      timePeriod: t(`${p}.filters.timePeriod`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      forecastSummary: t(`${p}.dashboard.forecastSummary`),
      executiveSummary: t(`${p}.dashboard.executiveSummary`),
      emergingOpportunities: t(`${p}.dashboard.emergingOpportunities`),
      emergingRisks: t(`${p}.dashboard.emergingRisks`),
      areasRequiringAttention: t(`${p}.dashboard.areasRequiringAttention`),
      confidenceLevels: t(`${p}.dashboard.confidenceLevels`),
      preventiveActions: t(`${p}.dashboard.preventiveActions`),
      predictions: t(`${p}.dashboard.predictions`),
      earlyWarnings: t(`${p}.dashboard.earlyWarnings`),
      recommendations: t(`${p}.dashboard.recommendations`),
      timeline: t(`${p}.dashboard.timeline`),
      viewPrediction: t(`${p}.dashboard.viewPrediction`),
    },
    card: {
      category: t(`${p}.card.category`),
      confidence: t(`${p}.card.confidence`),
      timeHorizon: t(`${p}.card.timeHorizon`),
      impact: t(`${p}.card.impact`),
      relatedAreas: t(`${p}.card.relatedAreas`),
      lastReviewed: t(`${p}.card.lastReviewed`),
      recommendedActions: t(`${p}.card.recommendedActions`),
    },
    detail: {
      back: t(`${p}.detail.back`),
      outcomeReview: t(`${p}.detail.outcomeReview`),
      reviewNotes: t(`${p}.detail.reviewNotes`),
      submitReview: t(`${p}.detail.submitReview`),
      reviewSuccess: t(`${p}.detail.reviewSuccess`),
      probabilityNote: t(`${p}.detail.probabilityNote`),
      priorReviews: t(`${p}.detail.priorReviews`),
    },
    generate: {
      success: t(`${p}.generate.success`),
      governanceNote: t(`${p}.generate.governanceNote`),
    },
    categories: {
      operational: t(`${p}.categories.operational`),
      capacity: t(`${p}.categories.capacity`),
      strategic: t(`${p}.categories.strategic`),
      customer_success: t(`${p}.categories.customerSuccess`),
      learning: t(`${p}.categories.learning`),
      governance: t(`${p}.categories.governance`),
      risk: t(`${p}.categories.risk`),
      business_pack: t(`${p}.categories.businessPack`),
    },
    confidenceLevels: {
      exploratory: t(`${p}.confidenceLevels.exploratory`),
      emerging_pattern: t(`${p}.confidenceLevels.emergingPattern`),
      moderate_confidence: t(`${p}.confidenceLevels.moderateConfidence`),
      high_confidence: t(`${p}.confidenceLevels.highConfidence`),
    },
    timeHorizons: {
      next_30_days: t(`${p}.timeHorizons.next30Days`),
      next_quarter: t(`${p}.timeHorizons.nextQuarter`),
      next_6_months: t(`${p}.timeHorizons.next6Months`),
      next_12_months: t(`${p}.timeHorizons.next12Months`),
    },
    impactLevels: {
      low: t(`${p}.impactLevels.low`),
      moderate: t(`${p}.impactLevels.moderate`),
      high: t(`${p}.impactLevels.high`),
      critical: t(`${p}.impactLevels.critical`),
    },
    reviewStatuses: {
      pending: t(`${p}.reviewStatuses.pending`),
      reviewed: t(`${p}.reviewStatuses.reviewed`),
      needs_follow_up: t(`${p}.reviewStatuses.needsFollowUp`),
    },
    outcomes: {
      confirmed: t(`${p}.outcomes.confirmed`),
      partially_confirmed: t(`${p}.outcomes.partiallyConfirmed`),
      not_observed: t(`${p}.outcomes.notObserved`),
      insufficient_evidence: t(`${p}.outcomes.insufficientEvidence`),
    },
    recommendations: {
      conductPreventiveCapacityReviews: t(`${p}.recommendations.conductPreventiveCapacityReviews`),
      strengthenFollowUpDiscipline: t(`${p}.recommendations.strengthenFollowUpDiscipline`),
      reviewEmergingGovernanceRisks: t(`${p}.recommendations.reviewEmergingGovernanceRisks`),
      scheduleExecutivePlanningSessions: t(`${p}.recommendations.scheduleExecutivePlanningSessions`),
      expandLearningInitiatives: t(`${p}.recommendations.expandLearningInitiatives`),
      monitorIdentifiedTrends: t(`${p}.recommendations.monitorIdentifiedTrends`),
    },
    timelineEvents: {
      predictions_generated: t(`${p}.timelineEvents.predictionsGenerated`),
      prediction_reviewed: t(`${p}.timelineEvents.predictionReviewed`),
      action_implemented: t(`${p}.timelineEvents.actionImplemented`),
      outcome_evaluated: t(`${p}.timelineEvents.outcomeEvaluated`),
      lesson_recorded: t(`${p}.timelineEvents.lessonRecorded`),
      accuracy_review_completed: t(`${p}.timelineEvents.accuracyReviewCompleted`),
      outcome_reviewed: t(`${p}.timelineEvents.outcomeReviewed`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      predictFuture: t(`${p}.faq.predictFuture`),
      predictFutureAnswer: t(`${p}.faq.predictFutureAnswer`),
      whyReview: t(`${p}.faq.whyReview`),
      whyReviewAnswer: t(`${p}.faq.whyReviewAnswer`),
    },
  };
}
