import type { IntelligenceCommandCenterLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildICCLabels(t: Translator): IntelligenceCommandCenterLabels {
  const p = "customerApp.portalStructure.intelligenceCommandCenter";
  return {
    title:        t(`${p}.title`),
    subtitle:     t(`${p}.subtitle`),
    loading:      t(`${p}.loading`),
    principle:    t(`${p}.principle`),
    advisoryNote: t(`${p}.advisoryNote`),
    emptyTitle:   t(`${p}.emptyTitle`),
    emptyBody:    t(`${p}.emptyBody`),
    emptyCta:     t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search:        t(`${p}.filters.search`),
      category:      t(`${p}.filters.category`),
      priority:      t(`${p}.filters.priority`),
      timeHorizon:   t(`${p}.filters.timeHorizon`),
      department:    t(`${p}.filters.department`),
      executiveOwner:t(`${p}.filters.executiveOwner`),
      reviewStatus:  t(`${p}.filters.reviewStatus`),
      all:           t(`${p}.filters.all`),
    },
    dashboard: {
      intelligenceScore:      t(`${p}.dashboard.intelligenceScore`),
      executiveHealthScore:   t(`${p}.dashboard.executiveHealthScore`),
      readinessScore:         t(`${p}.dashboard.readinessScore`),
      opportunityScore:       t(`${p}.dashboard.opportunityScore`),
      forecastScore:          t(`${p}.dashboard.forecastScore`),
      collaborationScore:     t(`${p}.dashboard.collaborationScore`),
      futurePreparednessScore:t(`${p}.dashboard.futurePreparednessScore`),
      executiveSummary:       t(`${p}.dashboard.executiveSummary`),
      keyObservations:        t(`${p}.dashboard.keyObservations`),
      executiveSnapshot:      t(`${p}.dashboard.executiveSnapshot`),
      topPriorities:          t(`${p}.dashboard.topPriorities`),
      opportunitiesRisks:     t(`${p}.dashboard.opportunitiesRisks`),
      futureOutlook:          t(`${p}.dashboard.futureOutlook`),
      crossFunctionalHealth:  t(`${p}.dashboard.crossFunctionalHealth`),
      executiveActions:       t(`${p}.dashboard.executiveActions`),
      intelligenceSources:    t(`${p}.dashboard.intelligenceSources`),
      briefingMode:           t(`${p}.dashboard.briefingMode`),
      priorities:             t(`${p}.dashboard.priorities`),
      timeline:               t(`${p}.dashboard.timeline`),
      viewModule:             t(`${p}.dashboard.viewModule`),
      refreshIntelligence:    t(`${p}.dashboard.refreshIntelligence`),
      markReviewed:           t(`${p}.dashboard.markReviewed`),
    },
    briefing: {
      today:           t(`${p}.briefing.today`),
      thisWeek:        t(`${p}.briefing.thisWeek`),
      thisMonth:       t(`${p}.briefing.thisMonth`),
      thisQuarter:     t(`${p}.briefing.thisQuarter`),
      summary:         t(`${p}.briefing.summary`),
      keyObservations: t(`${p}.briefing.keyObservations`),
      suggestedActions:t(`${p}.briefing.suggestedActions`),
      reviewItems:     t(`${p}.briefing.reviewItems`),
      generate:        t(`${p}.briefing.generate`),
    },
    priority: {
      sourceModule:      t(`${p}.priority.sourceModule`),
      priorityLevel:     t(`${p}.priority.priorityLevel`),
      category:          t(`${p}.priority.category`),
      timeHorizon:       t(`${p}.priority.timeHorizon`),
      recommendedAction: t(`${p}.priority.recommendedAction`),
      reviewStatus:      t(`${p}.priority.reviewStatus`),
    },
    outlook: {
      "30_days":  t(`${p}.outlook.30Days`),
      "90_days":  t(`${p}.outlook.90Days`),
      "6_months": t(`${p}.outlook.6Months`),
      "12_months":t(`${p}.outlook.12Months`),
      "24_months":t(`${p}.outlook.24Months`),
    },
    priorityLevels: {
      critical: t(`${p}.priorityLevels.critical`),
      high:     t(`${p}.priorityLevels.high`),
      medium:   t(`${p}.priorityLevels.medium`),
      low:      t(`${p}.priorityLevels.low`),
    },
    reviewStatuses: {
      pending:   t(`${p}.reviewStatuses.pending`),
      in_review: t(`${p}.reviewStatuses.inReview`),
      reviewed:  t(`${p}.reviewStatuses.reviewed`),
      actioned:  t(`${p}.reviewStatuses.actioned`),
    },
    sourceModules: {
      enterprise_benchmarking:       t(`${p}.sourceModules.enterpriseBenchmarking`),
      predictive_intelligence:       t(`${p}.sourceModules.predictiveIntelligence`),
      scenario_planning:             t(`${p}.sourceModules.scenarioPlanning`),
      executive_foresight:           t(`${p}.sourceModules.executiveForesight`),
      strategic_opportunities:       t(`${p}.sourceModules.strategicOpportunities`),
      organizational_forecasting:    t(`${p}.sourceModules.organizationalForecasting`),
      enterprise_readiness:          t(`${p}.sourceModules.enterpriseReadiness`),
      cross_functional_intelligence: t(`${p}.sourceModules.crossFunctionalIntelligence`),
    },
    timelineEvents: {
      eicc_initialized:      t(`${p}.timelineEvents.eiccInitialized`),
      intelligence_refreshed:t(`${p}.timelineEvents.intelligenceRefreshed`),
      priority_reviewed:     t(`${p}.timelineEvents.priorityReviewed`),
      strategic_decision:    t(`${p}.timelineEvents.strategicDecision`),
      leadership_milestone:  t(`${p}.timelineEvents.leadershipMilestone`),
    },
    refresh: { success: t(`${p}.refresh.success`) },
    faq: {
      title:                   t(`${p}.faq.title`),
      whatIs:                  t(`${p}.faq.whatIs`),
      whatIsAnswer:            t(`${p}.faq.whatIsAnswer`),
      replacesModules:         t(`${p}.faq.replacesModules`),
      replacesModulesAnswer:   t(`${p}.faq.replacesModulesAnswer`),
      whoShouldUse:            t(`${p}.faq.whoShouldUse`),
      whoShouldUseAnswer:      t(`${p}.faq.whoShouldUseAnswer`),
    },
  };
}
