import type { ContinuityLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildContinuityLabels(t: Translator): ContinuityLabels {
  const p = "customerApp.portalStructure.continuity";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      status: t(`${p}.filters.status`),
      owner: t(`${p}.filters.owner`),
      criticality: t(`${p}.filters.criticality`),
      reviewBefore: t(`${p}.filters.reviewBefore`),
      exerciseBefore: t(`${p}.filters.exerciseBefore`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      active: t(`${p}.dashboard.active`),
      needsReview: t(`${p}.dashboard.needsReview`),
      missionCritical: t(`${p}.dashboard.missionCritical`),
      withoutOwner: t(`${p}.dashboard.withoutOwner`),
      upcomingExercises: t(`${p}.dashboard.upcomingExercises`),
      recent: t(`${p}.dashboard.recent`),
    },
    form: {
      createTitle: t(`${p}.form.createTitle`),
      title: t(`${p}.form.title`),
      description: t(`${p}.form.description`),
      category: t(`${p}.form.category`),
      criticality: t(`${p}.form.criticality`),
      reviewFrequency: t(`${p}.form.reviewFrequency`),
      recoveryObjectives: t(`${p}.form.recoveryObjectives`),
      notes: t(`${p}.form.notes`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
    },
    card: {
      owner: t(`${p}.card.owner`),
      backupOwner: t(`${p}.card.backupOwner`),
      nextReview: t(`${p}.card.nextReview`),
      criticality: t(`${p}.card.criticality`),
      view: t(`${p}.card.view`),
    },
    detail: {
      overview: t(`${p}.detail.overview`),
      ownership: t(`${p}.detail.ownership`),
      recovery: t(`${p}.detail.recovery`),
      dependencies: t(`${p}.detail.dependencies`),
      alternativeProcedures: t(`${p}.detail.alternativeProcedures`),
      escalationPaths: t(`${p}.detail.escalationPaths`),
      minimumRequirements: t(`${p}.detail.minimumRequirements`),
      relatedPlaybooks: t(`${p}.detail.relatedPlaybooks`),
      relatedRisks: t(`${p}.detail.relatedRisks`),
      relatedRelationships: t(`${p}.detail.relatedRelationships`),
      exercises: t(`${p}.detail.exercises`),
      activity: t(`${p}.detail.activity`),
      audit: t(`${p}.detail.audit`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
      recommendations: t(`${p}.detail.recommendations`),
      addExercise: t(`${p}.detail.addExercise`),
      exerciseTitle: t(`${p}.detail.exerciseTitle`),
      exerciseType: t(`${p}.detail.exerciseType`),
      exerciseDate: t(`${p}.detail.exerciseDate`),
      lessonsLearned: t(`${p}.detail.lessonsLearned`),
      improvementActions: t(`${p}.detail.improvementActions`),
    },
    categories: {
      business_continuity: t(`${p}.categories.businessContinuity`),
      incident_response: t(`${p}.categories.incidentResponse`),
      technology_recovery: t(`${p}.categories.technologyRecovery`),
      workforce_continuity: t(`${p}.categories.workforceContinuity`),
      vendor_continuity: t(`${p}.categories.vendorContinuity`),
      communications_continuity: t(`${p}.categories.communicationsContinuity`),
      executive_continuity: t(`${p}.categories.executiveContinuity`),
      operational_recovery: t(`${p}.categories.operationalRecovery`),
      facility_preparedness: t(`${p}.categories.facilityPreparedness`),
      custom_continuity_area: t(`${p}.categories.customContinuityArea`),
    },
    statuses: {
      draft: t(`${p}.statuses.draft`),
      active: t(`${p}.statuses.active`),
      under_review: t(`${p}.statuses.underReview`),
      testing: t(`${p}.statuses.testing`),
      archived: t(`${p}.statuses.archived`),
    },
    criticality: {
      low: t(`${p}.criticality.low`),
      moderate: t(`${p}.criticality.moderate`),
      high: t(`${p}.criticality.high`),
      mission_critical: t(`${p}.criticality.missionCritical`),
    },
    frequencies: {
      monthly: t(`${p}.frequencies.monthly`),
      quarterly: t(`${p}.frequencies.quarterly`),
      semi_annual: t(`${p}.frequencies.semiAnnual`),
      annual: t(`${p}.frequencies.annual`),
    },
    exerciseTypes: {
      tabletop: t(`${p}.exerciseTypes.tabletop`),
      simulation: t(`${p}.exerciseTypes.simulation`),
    },
    recommendations: {
      reviewOutdated: t(`${p}.recommendations.reviewOutdated`),
      assignBackupOwner: t(`${p}.recommendations.assignBackupOwner`),
      scheduleExercise: t(`${p}.recommendations.scheduleExercise`),
      updateDependencies: t(`${p}.recommendations.updateDependencies`),
      reviewVendorAssumptions: t(`${p}.recommendations.reviewVendorAssumptions`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      exercises: t(`${p}.faq.exercises`),
      exercisesAnswer: t(`${p}.faq.exercisesAnswer`),
      autoManage: t(`${p}.faq.autoManage`),
      autoManageAnswer: t(`${p}.faq.autoManageAnswer`),
    },
  };
}
