import { CommunityHubPanel } from "@/components/app/community-intelligence";
import { getDictionary } from "@/lib/i18n/get-dictionary";
import { getLocale } from "@/lib/i18n/get-locale";
import { createTranslator } from "@/lib/i18n/translate";

export default async function CommunityPage() {
  const dict = await getDictionary(await getLocale(), ["customerApp"]);
  const t = createTranslator(dict);
  const p = "customerApp.communityIntelligence";

  return (
    <div className="mx-auto max-w-6xl space-y-6 p-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-gray-900">{t(`${p}.title`)}</h1>
        <p className="mt-2 text-gray-600">{t(`${p}.subtitle`)}</p>
      </div>
      <CommunityHubPanel
        labels={{
          loading: t(`${p}.loading`),
          adminDashboard: t(`${p}.adminDashboard`),
          engineTitle: t(`${p}.engineTitle`),
          blueprintPhase: t(`${p}.blueprintPhase`),
          engagementSummary: t(`${p}.engagementSummary`),
          contributionsTotal: t(`${p}.contributionsTotal`),
          publishedContributions: t(`${p}.publishedContributions`),
          pendingReviewsCount: t(`${p}.pendingReviewsCount`),
          briefingsTotal: t(`${p}.briefingsTotal`),
          briefingsLast30d: t(`${p}.briefingsLast30d`),
          ratingsTotal: t(`${p}.ratingsTotal`),
          healthScore: t(`${p}.healthScore`),
          intelligenceScore: t(`${p}.intelligenceScore`),
          contributionScore: t(`${p}.contributionScore`),
          generateBriefing: t(`${p}.generateBriefing`),
          scoreComponents: t(`${p}.scoreComponents`),
          communityObjectives: t(`${p}.communityObjectives`),
          collectiveInsightExamples: t(`${p}.collectiveInsightExamples`),
          privacyPrinciples: t(`${p}.privacyPrinciples`),
          communityContributions: t(`${p}.communityContributions`),
          companionExamples: t(`${p}.companionExamples`),
          successCriteria: t(`${p}.successCriteria`),
          selfLoveConnection: t(`${p}.selfLoveConnection`),
          openSelfLove: t(`${p}.openSelfLove`),
          trustConnection: t(`${p}.trustConnection`),
          dogfooding: t(`${p}.dogfooding`),
          aipifyGroup: t(`${p}.aipifyGroup`),
          unonightPilot: t(`${p}.unonightPilot`),
          visionPhrases: t(`${p}.visionPhrases`),
          featuredLearnings: t(`${p}.featuredLearnings`),
          featuredInsights: t(`${p}.featuredInsights`),
          bestPractices: t(`${p}.bestPractices`),
          topRated: t(`${p}.topRated`),
          popularResources: t(`${p}.popularResources`),
          recentlyValidated: t(`${p}.recentlyValidated`),
          industryInsights: t(`${p}.industryInsights`),
          blueprintRecommendations: t(`${p}.blueprintRecommendations`),
          intelligenceCategories: t(`${p}.intelligenceCategories`),
          noInsights: t(`${p}.noInsights`),
          rate: t(`${p}.rate`),
          briefings: t(`${p}.briefings`),
          approvalWorkflow: t(`${p}.approvalWorkflow`),
          clwbpEngineTitle: t(`${p}.clwbpEngineTitle`),
          clwbpObjectives: t(`${p}.clwbpObjectives`),
          collectiveSummary: t(`${p}.collectiveSummary`),
          tenantContributionsTotal: t(`${p}.tenantContributionsTotal`),
          tenantPublished: t(`${p}.tenantPublished`),
          ecosystemPublishedTotal: t(`${p}.ecosystemPublishedTotal`),
          ecosystemRecent90d: t(`${p}.ecosystemRecent90d`),
          ecosystemAvgRating: t(`${p}.ecosystemAvgRating`),
          ecosystemCategories: t(`${p}.ecosystemCategories`),
          ecosystemContributionTypes: t(`${p}.ecosystemContributionTypes`),
          collectiveObservations: t(`${p}.collectiveObservations`),
          bestPracticeEvolution: t(`${p}.bestPracticeEvolution`),
          clwbpAnonymizationPrinciples: t(`${p}.clwbpAnonymizationPrinciples`),
          knowledgeCenterConnection: t(`${p}.knowledgeCenterConnection`),
          salesExpertConnection: t(`${p}.salesExpertConnection`),
          executiveConnection: t(`${p}.executiveConnection`),
          clwbpSuccessCriteria: t(`${p}.clwbpSuccessCriteria`),
          clwbpSelfLoveConnection: t(`${p}.clwbpSelfLoveConnection`),
          clwbpTrustConnection: t(`${p}.clwbpTrustConnection`),
          clwbpDogfooding: t(`${p}.clwbpDogfooding`),
          clwbpVisionPhrases: t(`${p}.clwbpVisionPhrases`),
          ccibp89EngineTitle: t(`${p}.ccibp89EngineTitle`),
          ccibp89Objectives: t(`${p}.ccibp89Objectives`),
          collectiveIntelligenceSources: t(`${p}.collectiveIntelligenceSources`),
          communityObservations: t(`${p}.communityObservations`),
          ideaDiscovery: t(`${p}.ideaDiscovery`),
          ideaDiscoveryCategories: t(`${p}.ideaDiscoveryCategories`),
          companionGuidance: t(`${p}.companionGuidance`),
          communityRecognition: t(`${p}.communityRecognition`),
          openGratitudeRecognition: t(`${p}.openGratitudeRecognition`),
          learningOrganizationConnection: t(`${p}.learningOrganizationConnection`),
          ccibp89PrivacyPrinciples: t(`${p}.ccibp89PrivacyPrinciples`),
          ccibp89SuccessCriteria: t(`${p}.ccibp89SuccessCriteria`),
          ccibp89SelfLoveConnection: t(`${p}.ccibp89SelfLoveConnection`),
          ccibp89TrustConnection: t(`${p}.ccibp89TrustConnection`),
          ccibp89Dogfooding: t(`${p}.ccibp89Dogfooding`),
          ccibp89EngagementSummary: t(`${p}.ccibp89EngagementSummary`),
          ccsbp117EngineTitle: t(`${p}.ccsbp117EngineTitle`),
          ccsbp117Objectives: t(`${p}.ccsbp117Objectives`),
          communitySpaces: t(`${p}.communitySpaces`),
          ccsbp117Contributions: t(`${p}.ccsbp117Contributions`),
          collectiveIntelligencePatterns: t(`${p}.collectiveIntelligencePatterns`),
          mentorshipProgram: t(`${p}.mentorshipProgram`),
          openSalesCommunity: t(`${p}.openSalesCommunity`),
          ccsbp117Recognition: t(`${p}.ccsbp117Recognition`),
          communityEvents: t(`${p}.communityEvents`),
          safetyFramework: t(`${p}.safetyFramework`),
          knowledgeVault: t(`${p}.knowledgeVault`),
          openKnowledgeCenter: t(`${p}.openKnowledgeCenter`),
          companionParticipation: t(`${p}.companionParticipation`),
          companionMustNever: t(`${p}.companionMustNever`),
          growthPartnerNetwork: t(`${p}.growthPartnerNetwork`),
          openGrowthPartnerOps: t(`${p}.openGrowthPartnerOps`),
          communityAnalytics: t(`${p}.communityAnalytics`),
          companionAdaptation: t(`${p}.companionAdaptation`),
          limitationPrinciples: t(`${p}.limitationPrinciples`),
          ccsbp117SuccessCriteria: t(`${p}.ccsbp117SuccessCriteria`),
          successMetrics: t(`${p}.successMetrics`),
          ccsbp117SelfLoveConnection: t(`${p}.ccsbp117SelfLoveConnection`),
          ccsbp117EngagementSummary: t(`${p}.ccsbp117EngagementSummary`),
        }}
      />
    </div>
  );
}
