import type { Translator } from "@/lib/i18n/translate";
import type { PlatformCustomerAgreementsLabels } from "./customer-agreements";
import type { PlatformCustomerSuccessLabels } from "./customer-success";
import type {
  PlatformPortalCommercialPlanLabels,
  PlatformPortalCustomerCreationLabels,
  PlatformPortalCustomerDetailLabels,
  PlatformPortalCustomersLabels,
  PlatformPortalDomainInstallationLabels,
  PlatformPortalLabels,
  PlatformPortalLicenseProvisioningLabels,
  PlatformPortalWebsiteKompisLabels,
} from "./types";

export function buildPlatformPortalLabels(t: Translator): PlatformPortalLabels {
  const d = "platform.portalStructure.dashboard";
  const f = "platform.portalStructure.foundation";
  const billingNav = "platform.billingCommerceCenter.nav";

  return {
    dashboard: {
      title: t(`${d}.title`),
      subtitle: t(`${d}.subtitle`),
      loading: t(`${d}.loading`),
      principle: t(`${d}.principle`),
      privacyNote: t(`${d}.privacyNote`),
      organizationsRequiringAttention: t(`${d}.organizationsRequiringAttention`),
      activeSubscriptions: t(`${d}.activeSubscriptions`),
      openSupportWorkload: t(`${d}.openSupportWorkload`),
      paymentStatusSummary: t(`${d}.paymentStatusSummary`),
      paymentActive: t(`${d}.paymentActive`),
      paymentPastDue: t(`${d}.paymentPastDue`),
      paymentTrialing: t(`${d}.paymentTrialing`),
      invoices: t(`${billingNav}.invoices`),
      paymentProviders: t(`${billingNav}.paymentProviders`),
      accountingIntegration: t(`${billingNav}.accountingIntegration`),
      customerSuccessIndicators: t(`${d}.customerSuccessIndicators`),
      healthyRatio: t(`${d}.healthyRatio`),
      marketplaceModeration: t(`${d}.marketplaceModeration`),
      pendingReview: t(`${d}.pendingReview`),
      published: t(`${d}.published`),
      partnerProgramSummary: t(`${d}.partnerProgramSummary`),
      activePrograms: t(`${d}.activePrograms`),
      pendingApplications: t(`${d}.pendingApplications`),
      productDeploymentUpdates: t(`${d}.productDeploymentUpdates`),
      noUpdates: t(`${d}.noUpdates`),
      portalModules: t(`${d}.portalModules`),
      openModule: t(`${d}.openModule`),
      loadErrorTitle: t(`${d}.loadErrorTitle`),
      loadErrorMessage: t(`${d}.loadErrorMessage`),
      retry: t(`${d}.retry`),
      lastChecked: t(`${d}.lastChecked`),
      unknownStatus: t(`${d}.unknownStatus`),
      updateClassifications: {
        patch: t(`${d}.updateClassifications.patch`),
        minor: t(`${d}.updateClassifications.minor`),
        major: t(`${d}.updateClassifications.major`),
        security: t(`${d}.updateClassifications.security`),
        database_migration: t(`${d}.updateClassifications.database_migration`),
      },
    },
    foundation: {
      loading: t(`${f}.loading`),
      back: t(`${f}.back`),
      structureNote: t(`${f}.structureNote`),
    },
  };
}

export function buildPlatformCustomerSuccessLabels(
  t: Translator,
): PlatformCustomerSuccessLabels {
  const c = "platform.customers.successOverview";
  return {
    title: t(`${c}.title`),
    subtitle: t(`${c}.subtitle`),
    lastChecked: t(`${c}.lastChecked`),
    searchPlaceholder: t(`${c}.searchPlaceholder`),
    filterAll: t(`${c}.filterAll`),
    filterHealthy: t(`${c}.filterHealthy`),
    filterAttention: t(`${c}.filterAttention`),
    filterCritical: t(`${c}.filterCritical`),
    filterIncomplete: t(`${c}.filterIncomplete`),
    filterUnknown: t(`${c}.filterUnknown`),
    filterAgreement: t(`${c}.filterAgreement`),
    filterLicense: t(`${c}.filterLicense`),
    filterService: t(`${c}.filterService`),
    filterCountry: t(`${c}.filterCountry`),
    kpiTotal: t(`${c}.kpiTotal`),
    kpiHealthy: t(`${c}.kpiHealthy`),
    kpiAttention: t(`${c}.kpiAttention`),
    kpiCritical: t(`${c}.kpiCritical`),
    kpiIncomplete: t(`${c}.kpiIncomplete`),
    columnCustomer: t(`${c}.columnCustomer`),
    columnStatus: t(`${c}.columnStatus`),
    columnAgreement: t(`${c}.columnAgreement`),
    columnLicenseSetup: t(`${c}.columnLicenseSetup`),
    columnDomains: t(`${c}.columnDomains`),
    columnInstallations: t(`${c}.columnInstallations`),
    columnServices: t(`${c}.columnServices`),
    columnUsers: t(`${c}.columnUsers`),
    columnFollowUp: t(`${c}.columnFollowUp`),
    openCustomer: t(`${c}.openCustomer`),
    notAvailable: t(`${c}.notAvailable`),
    emptyTitle: t(`${c}.emptyTitle`),
    emptyDescription: t(`${c}.emptyDescription`),
    filteredEmptyTitle: t(`${c}.filteredEmptyTitle`),
    filteredEmptyDescription: t(`${c}.filteredEmptyDescription`),
    errorTitle: t(`${c}.errorTitle`),
    errorDescription: t(`${c}.errorDescription`),
    retry: t(`${c}.retry`),
    moreReasons: t(`${c}.moreReasons`),
    licenseActive: t(`${c}.licenseActive`),
    licenseMissing: t(`${c}.licenseMissing`),
    domainsCount: t(`${c}.domainsCount`),
    verifiedCount: t(`${c}.verifiedCount`),
    installationsCount: t(`${c}.installationsCount`),
    revokedHighlight: t(`${c}.revokedHighlight`),
    servicesCount: t(`${c}.servicesCount`),
    websiteKompis: t(`${c}.websiteKompis`),
    clearFilters: t(`${c}.clearFilters`),
    unknownStatus: t(`${c}.unknownStatus`),
    successStatuses: {
      healthy: t(`${c}.successStatuses.healthy`),
      attention: t(`${c}.successStatuses.attention`),
      critical: t(`${c}.successStatuses.critical`),
      incomplete: t(`${c}.successStatuses.incomplete`),
      unknown: t(`${c}.successStatuses.unknown`),
    },
    reasonCodes: {
      agreement_active: t(`${c}.reasonCodes.agreement_active`),
      agreement_missing: t(`${c}.reasonCodes.agreement_missing`),
      agreement_pending: t(`${c}.reasonCodes.agreement_pending`),
      agreement_suspended: t(`${c}.reasonCodes.agreement_suspended`),
      agreement_past_due: t(`${c}.reasonCodes.agreement_past_due`),
      license_active: t(`${c}.reasonCodes.license_active`),
      license_missing: t(`${c}.reasonCodes.license_missing`),
      license_pending: t(`${c}.reasonCodes.license_pending`),
      license_suspended: t(`${c}.reasonCodes.license_suspended`),
      domain_missing: t(`${c}.reasonCodes.domain_missing`),
      domain_unverified: t(`${c}.reasonCodes.domain_unverified`),
      installation_missing: t(`${c}.reasonCodes.installation_missing`),
      installation_revoked: t(`${c}.reasonCodes.installation_revoked`),
      service_ready_for_activation: t(`${c}.reasonCodes.service_ready_for_activation`),
      service_active: t(`${c}.reasonCodes.service_active`),
      setup_failed: t(`${c}.reasonCodes.setup_failed`),
      setup_incomplete: t(`${c}.reasonCodes.setup_incomplete`),
      setup_complete: t(`${c}.reasonCodes.setup_complete`),
      status_unknown: t(`${c}.reasonCodes.status_unknown`),
    },
    agreementStatuses: {
      active: t(`${c}.agreementStatuses.active`),
      trialing: t(`${c}.agreementStatuses.trialing`),
      past_due: t(`${c}.agreementStatuses.past_due`),
      unpaid: t(`${c}.agreementStatuses.unpaid`),
      paused: t(`${c}.agreementStatuses.paused`),
      suspended: t(`${c}.agreementStatuses.suspended`),
      cancelled: t(`${c}.agreementStatuses.cancelled`),
      pending: t(`${c}.agreementStatuses.pending`),
    },
    durationLabels: {
      lifetime: t(`${c}.durationLabels.lifetime`),
      monthly: t(`${c}.durationLabels.monthly`),
      yearly: t(`${c}.durationLabels.yearly`),
      annual: t(`${c}.durationLabels.annual`),
    },
    licenseStatuses: {
      active: t(`${c}.licenseStatuses.active`),
      pending: t(`${c}.licenseStatuses.pending`),
      suspended: t(`${c}.licenseStatuses.suspended`),
      expired: t(`${c}.licenseStatuses.expired`),
      revoked: t(`${c}.licenseStatuses.revoked`),
    },
    setupStatuses: {
      requires_domain: t(`${c}.setupStatuses.requires_domain`),
      requires_installation: t(`${c}.setupStatuses.requires_installation`),
      ready_for_activation: t(`${c}.setupStatuses.ready_for_activation`),
      active: t(`${c}.setupStatuses.active`),
      failed: t(`${c}.setupStatuses.failed`),
      pending: t(`${c}.setupStatuses.pending`),
    },
    serviceStatuses: {
      active: t(`${c}.serviceStatuses.active`),
      ready_for_activation: t(`${c}.serviceStatuses.ready_for_activation`),
      not_ready: t(`${c}.serviceStatuses.not_ready`),
      suspended: t(`${c}.serviceStatuses.suspended`),
    },
  };
}

export function buildPlatformCustomerAgreementsLabels(
  t: Translator,
): PlatformCustomerAgreementsLabels {
  const c = "platform.customers.agreementsOverview";
  return {
    title: t(`${c}.title`),
    subtitle: t(`${c}.subtitle`),
    lastChecked: t(`${c}.lastChecked`),
    searchPlaceholder: t(`${c}.searchPlaceholder`),
    filterAll: t(`${c}.filterAll`),
    filterActive: t(`${c}.filterActive`),
    filterTrial: t(`${c}.filterTrial`),
    filterAttention: t(`${c}.filterAttention`),
    filterEnded: t(`${c}.filterEnded`),
    filterExpired: t(`${c}.filterExpired`),
    filterUnknown: t(`${c}.filterUnknown`),
    filterDurationAll: t(`${c}.filterDurationAll`),
    filterDurationMonthly: t(`${c}.filterDurationMonthly`),
    filterDurationYearly: t(`${c}.filterDurationYearly`),
    filterDurationUnlimited: t(`${c}.filterDurationUnlimited`),
    filterCountry: t(`${c}.filterCountry`),
    kpiTotal: t(`${c}.kpiTotal`),
    kpiActive: t(`${c}.kpiActive`),
    kpiTrial: t(`${c}.kpiTrial`),
    kpiAttention: t(`${c}.kpiAttention`),
    kpiEnded: t(`${c}.kpiEnded`),
    kpiUnlimited: t(`${c}.kpiUnlimited`),
    columnCustomer: t(`${c}.columnCustomer`),
    columnAgreement: t(`${c}.columnAgreement`),
    columnStatus: t(`${c}.columnStatus`),
    columnDuration: t(`${c}.columnDuration`),
    columnPeriod: t(`${c}.columnPeriod`),
    columnRenewal: t(`${c}.columnRenewal`),
    columnAmount: t(`${c}.columnAmount`),
    columnFollowUp: t(`${c}.columnFollowUp`),
    startDate: t(`${c}.startDate`),
    endDate: t(`${c}.endDate`),
    noEndDate: t(`${c}.noEndDate`),
    noTrial: t(`${c}.noTrial`),
    currentAgreement: t(`${c}.currentAgreement`),
    historicalAgreement: t(`${c}.historicalAgreement`),
    openCustomer: t(`${c}.openCustomer`),
    notAvailable: t(`${c}.notAvailable`),
    emptyTitle: t(`${c}.emptyTitle`),
    emptyDescription: t(`${c}.emptyDescription`),
    filteredEmptyTitle: t(`${c}.filteredEmptyTitle`),
    filteredEmptyDescription: t(`${c}.filteredEmptyDescription`),
    errorTitle: t(`${c}.errorTitle`),
    errorDescription: t(`${c}.errorDescription`),
    retry: t(`${c}.retry`),
    clearFilters: t(`${c}.clearFilters`),
    unknownStatus: t(`${c}.unknownStatus`),
    agreementStatuses: {
      active: t(`${c}.agreementStatuses.active`),
      trialing: t(`${c}.agreementStatuses.trialing`),
      pending: t(`${c}.agreementStatuses.pending`),
      past_due: t(`${c}.agreementStatuses.past_due`),
      paused: t(`${c}.agreementStatuses.paused`),
      suspended: t(`${c}.agreementStatuses.suspended`),
      cancelled: t(`${c}.agreementStatuses.cancelled`),
      canceled: t(`${c}.agreementStatuses.cancelled`),
      expired: t(`${c}.agreementStatuses.expired`),
      unpaid: t(`${c}.agreementStatuses.unpaid`),
      unknown: t(`${c}.unknownStatus`),
    },
    durationLabels: {
      lifetime: t(`${c}.durationLabels.lifetime`),
      monthly: t(`${c}.durationLabels.monthly`),
      yearly: t(`${c}.durationLabels.yearly`),
      annual: t(`${c}.durationLabels.yearly`),
      unknown: t(`${c}.notAvailable`),
    },
    unonightPilotAgreement: t(`${c}.unonightPilotAgreement`),
    unonightUnlimitedAgreement: t(`${c}.unonightUnlimitedAgreement`),
    lifetimeAgreement: t(`${c}.lifetimeAgreement`),
  };
}

export function buildPlatformPortalWebsiteKompisLabels(
  t: Translator,
): PlatformPortalWebsiteKompisLabels {
  const c = "platform.customers.websiteKompis";
  return {
    title: t(`${c}.title`),
    serviceName: t(`${c}.serviceName`),
    sectionActivatedServices: t(`${c}.sectionActivatedServices`),
    statusLabel: t(`${c}.statusLabel`),
    notReady: t(`${c}.notReady`),
    readyForActivation: t(`${c}.readyForActivation`),
    activating: t(`${c}.activating`),
    active: t(`${c}.active`),
    suspended: t(`${c}.suspended`),
    failed: t(`${c}.failed`),
    revoked: t(`${c}.revoked`),
    activate: t(`${c}.activate`),
    activatingAction: t(`${c}.activatingAction`),
    summary: t(`${c}.summary`),
    agreement: t(`${c}.agreement`),
    licensePackage: t(`${c}.licensePackage`),
    appLicense: t(`${c}.appLicense`),
    setupStatus: t(`${c}.setupStatus`),
    domain: t(`${c}.domain`),
    installation: t(`${c}.installation`),
    installKey: t(`${c}.installKey`),
    prerequisites: t(`${c}.prerequisites`),
    internalReason: t(`${c}.internalReason`),
    reasonRequired: t(`${c}.reasonRequired`),
    confirmRequired: t(`${c}.confirmRequired`),
    summaryTitle: t(`${c}.summaryTitle`),
    summaryActivates: t(`${c}.summaryActivates`),
    summaryAgreementUnchanged: t(`${c}.summaryAgreementUnchanged`),
    summaryLicenseUnchanged: t(`${c}.summaryLicenseUnchanged`),
    summaryDomainUnchanged: t(`${c}.summaryDomainUnchanged`),
    summaryInstallationUnchanged: t(`${c}.summaryInstallationUnchanged`),
    summaryNoPayment: t(`${c}.summaryNoPayment`),
    summaryNoEmail: t(`${c}.summaryNoEmail`),
    summaryNoDns: t(`${c}.summaryNoDns`),
    cancel: t(`${c}.cancel`),
    close: t(`${c}.close`),
    retry: t(`${c}.retry`),
    success: t(`${c}.success`),
    error: t(`${c}.error`),
    notEligible: t(`${c}.notEligible`),
    alreadyActive: t(`${c}.alreadyActive`),
    unauthorized: t(`${c}.unauthorized`),
    forbidden: t(`${c}.forbidden`),
    viewService: t(`${c}.viewService`),
    loading: t(`${c}.loading`),
    reasonLabels: {
      agreement_activeOk: t(`${c}.reasons.agreementActiveOk`),
      agreement_activeMissing: t(`${c}.reasons.agreementActiveMissing`),
      license_activeOk: t(`${c}.reasons.licenseActiveOk`),
      license_activeMissing: t(`${c}.reasons.licenseActiveMissing`),
      license_product_supportedOk: t(`${c}.reasons.licenseProductSupportedOk`),
      license_product_supportedMissing: t(
        `${c}.reasons.licenseProductSupportedMissing`,
      ),
      domain_linkedOk: t(`${c}.reasons.domainLinkedOk`),
      domain_linkedMissing: t(`${c}.reasons.domainLinkedMissing`),
      domain_verifiedOk: t(`${c}.reasons.domainVerifiedOk`),
      domain_verifiedMissing: t(`${c}.reasons.domainVerifiedMissing`),
      installation_linkedOk: t(`${c}.reasons.installationLinkedOk`),
      installation_linkedMissing: t(`${c}.reasons.installationLinkedMissing`),
      install_id_presentOk: t(`${c}.reasons.installIdPresentOk`),
      install_id_presentMissing: t(`${c}.reasons.installIdPresentMissing`),
      approval_satisfiedOk: t(`${c}.reasons.approvalSatisfiedOk`),
      approval_satisfiedMissing: t(`${c}.reasons.approvalSatisfiedMissing`),
      activation_not_conflictingOk: t(`${c}.reasons.activationNotConflictingOk`),
      activation_not_conflictingMissing: t(
        `${c}.reasons.activationNotConflictingMissing`,
      ),
      notEligible: t(`${c}.notEligible`),
    },
    activationStatuses: {
      not_ready: t(`${c}.notReady`),
      ready_for_activation: t(`${c}.readyForActivation`),
      activating: t(`${c}.activating`),
      active: t(`${c}.active`),
      suspended: t(`${c}.suspended`),
      failed: t(`${c}.failed`),
      revoked: t(`${c}.revoked`),
    },
  };
}

export function buildPlatformPortalCustomersLabels(
  t: Translator,
): PlatformPortalCustomersLabels {
  const c = "platform.customers";
  const customerStatus = "platform.status.customer";
  const subscriptionStatus = "platform.status.subscription";

  return {
    title: t(`${c}.registryTitle`),
    description: t(`${c}.registryDescription`),
    summaryTotal: t(`${c}.summaryTotal`),
    summaryActive: t(`${c}.summaryActive`),
    summaryNew: t(`${c}.summaryNew`),
    summaryAttention: t(`${c}.summaryAttention`),
    loading: t(`${c}.loading`),
    error: t(`${c}.error`),
    retry: t(`${c}.retry`),
    emptyTitle: t(`${c}.emptyTitle`),
    emptyDescription: t(`${c}.emptyDescription`),
    searchPlaceholder: t(`${c}.searchPlaceholder`),
    filterAll: t(`${c}.filterAll`),
    filterStatus: t(`${c}.filterStatus`),
    filterSubscription: t(`${c}.filterSubscription`),
    filterAttribution: t(`${c}.filterAttribution`),
    filterPartner: t(`${c}.filterPartner`),
    filterDirect: t(`${c}.filterDirect`),
    clearFilters: t(`${c}.clearFilters`),
    columnCustomer: t(`${c}.columnCustomer`),
    columnOrganizationNumber: t(`${c}.columnOrganizationNumber`),
    columnStatus: t(`${c}.columnStatus`),
    columnSubscription: t(`${c}.columnSubscription`),
    columnMembers: t(`${c}.columnMembers`),
    columnAttribution: t(`${c}.columnAttribution`),
    columnSupport: t(`${c}.columnSupport`),
    columnLastActivity: t(`${c}.columnLastActivity`),
    columnActions: t(`${c}.columnActions`),
    requiresAttention: t(`${c}.requiresAttention`),
    lifetime: t(`${c}.lifetime`),
    partnerCustomer: t(`${c}.partnerCustomer`),
    directCustomer: t(`${c}.directCustomer`),
    noSubscription: t(`${c}.noSubscription`),
    notAvailable: t(`${c}.notAvailable`),
    openCustomer: t(`${c}.openCustomer`),
    noOpenSupport: t(`${c}.noOpenSupport`),
    createCustomer: t(`${c}.createCustomer`),
    customerStatuses: {
      trial: t(`${customerStatus}.trial`),
      active: t(`${customerStatus}.active`),
      paused: t(`${customerStatus}.paused`),
      cancelled: t(`${customerStatus}.cancelled`),
      overdue: t(`${customerStatus}.overdue`),
    },
    subscriptionStatuses: {
      active: t(`${subscriptionStatus}.active`),
      trialing: t(`${subscriptionStatus}.trialing`),
      past_due: t(`${subscriptionStatus}.past_due`),
      unpaid: t(`${subscriptionStatus}.unpaid`),
      paused: t(`${subscriptionStatus}.paused`),
      suspended: t(`${subscriptionStatus}.suspended`),
      pending: t(`${subscriptionStatus}.pending`),
      cancelled: t(`${subscriptionStatus}.cancelled`),
      canceled: t(`${subscriptionStatus}.canceled`),
      expired: t(`${subscriptionStatus}.expired`),
    },
    agreementDisplayNames: {
      unonightPilotAgreement: t(
        "platform.customers.detail.agreementDisplayNames.unonightPilotAgreement",
      ),
      unonightUnlimitedAgreement: t(
        "platform.customers.detail.agreementDisplayNames.unonightUnlimitedAgreement",
      ),
    },
  };
}

export function buildPlatformPortalCustomerDetailLabels(
  t: Translator,
): PlatformPortalCustomerDetailLabels {
  const d = "platform.customers.detail";
  const customerStatus = "platform.status.customer";
  const subscriptionStatus = "platform.status.subscription";
  const installationStatus = "platform.status.installation";

  return {
    title: t(`${d}.title`),
    backToCustomers: t(`${d}.backToCustomers`),
    loading: t(`${d}.loading`),
    error: t(`${d}.error`),
    retry: t(`${d}.retry`),
    notFound: t(`${d}.notFound`),
    forbidden: t(`${d}.forbidden`),
    unauthorized: t(`${d}.unauthorized`),
    sectionBusiness: t(`${d}.sectionBusiness`),
    sectionCommercial: t(`${d}.sectionCommercial`),
    sectionLicenses: t(`${d}.sectionLicenses`),
    sectionDomains: t(`${d}.sectionDomains`),
    sectionEntitlements: t(`${d}.sectionEntitlements`),
    sectionStatus: t(`${d}.sectionStatus`),
    organizationNumber: t(`${d}.organizationNumber`),
    legalName: t(`${d}.legalName`),
    customerName: t(`${d}.customerName`),
    customerId: t(`${d}.customerId`),
    companyId: t(`${d}.companyId`),
    createdAt: t(`${d}.createdAt`),
    updatedAt: t(`${d}.updatedAt`),
    subscription: t(`${d}.subscription`),
    lifetime: t(`${d}.lifetime`),
    duration: t(`${d}.duration`),
    plan: t(`${d}.plan`),
    trialPeriod: t(`${d}.trialPeriod`),
    noTrial: t(`${d}.noTrial`),
    activePeriod: t(`${d}.activePeriod`),
    directCustomer: t(`${d}.directCustomer`),
    partnerCustomer: t(`${d}.partnerCustomer`),
    members: t(`${d}.members`),
    activeLicenses: t(`${d}.activeLicenses`),
    domains: t(`${d}.domains`),
    installations: t(`${d}.installations`),
    domainsAndInstallations: t(`${d}.domainsAndInstallations`),
    domainCountLabel: t(`${d}.domainCountLabel`),
    installationCountLabel: t(`${d}.installationCountLabel`),
    openSupport: t(`${d}.openSupport`),
    notAvailable: t(`${d}.notAvailable`),
    requiresAttention: t(`${d}.requiresAttention`),
    healthy: t(`${d}.healthy`),
    emptyLicenses: t(`${d}.emptyLicenses`),
    emptyDomains: t(`${d}.emptyDomains`),
    emptyEntitlements: t(`${d}.emptyEntitlements`),
    copy: t(`${d}.copy`),
    copied: t(`${d}.copied`),
    generatedAt: t(`${d}.generatedAt`),
    lastChecked: t(`${d}.lastChecked`),
    slug: t(`${d}.slug`),
    slugHelp: t(`${d}.slugHelp`),
    product: t(`${d}.product`),
    status: t(`${d}.status`),
    domain: t(`${d}.domain`),
    domainRole: t(`${d}.domainRole`),
    installId: t(`${d}.installId`),
    activatedAt: t(`${d}.activatedAt`),
    expiresAt: t(`${d}.expiresAt`),
    hostname: t(`${d}.hostname`),
    verifiedAt: t(`${d}.verifiedAt`),
    code: t(`${d}.code`),
    name: t(`${d}.name`),
    grantedAt: t(`${d}.grantedAt`),
    unknownStatus: t(`${d}.unknownStatus`),
    customerStatuses: {
      trial: t(`${customerStatus}.trial`),
      active: t(`${customerStatus}.active`),
      paused: t(`${customerStatus}.paused`),
      cancelled: t(`${customerStatus}.cancelled`),
      overdue: t(`${customerStatus}.overdue`),
    },
    subscriptionStatuses: {
      active: t(`${subscriptionStatus}.active`),
      trialing: t(`${subscriptionStatus}.trialing`),
      past_due: t(`${subscriptionStatus}.past_due`),
      unpaid: t(`${subscriptionStatus}.unpaid`),
      paused: t(`${subscriptionStatus}.paused`),
      suspended: t(`${subscriptionStatus}.suspended`),
      pending: t(`${subscriptionStatus}.pending`),
      cancelled: t(`${subscriptionStatus}.cancelled`),
      canceled: t(`${subscriptionStatus}.canceled`),
      expired: t(`${subscriptionStatus}.expired`),
    },
    licenseStatuses: {
      pending: t(`${d}.licenseStatuses.pending`),
      active: t(`${d}.licenseStatuses.active`),
      suspended: t(`${d}.licenseStatuses.suspended`),
      expired: t(`${d}.licenseStatuses.expired`),
      cancelled: t(`${d}.licenseStatuses.cancelled`),
      canceled: t(`${d}.licenseStatuses.cancelled`),
    },
    domainStatuses: {
      active: t(`${d}.domainStatuses.active`),
      pending: t(`${d}.domainStatuses.pending`),
      verified: t(`${d}.domainStatuses.verified`),
      disabled: t(`${d}.domainStatuses.disabled`),
      removed: t(`${d}.domainStatuses.removed`),
      unknown: t(`${d}.domainStatuses.unknown`),
      paused: t(`${installationStatus}.paused`),
      revoked: t(`${installationStatus}.revoked`),
    },
    domainRoles: {
      customer: t(`${d}.domainRoles.customer`),
      runtime: t(`${d}.domainRoles.runtime`),
      license: t(`${d}.domainRoles.license`),
      historical: t(`${d}.domainRoles.historical`),
      unknown: t(`${d}.domainRoles.unknown`),
    },
    entitlementStatuses: {
      active: t(`${d}.entitlementStatuses.active`),
      licensed: t(`${d}.entitlementStatuses.licensed`),
      inactive: t(`${d}.entitlementStatuses.inactive`),
      expired: t(`${d}.entitlementStatuses.expired`),
      deactivated: t(`${d}.entitlementStatuses.deactivated`),
    },
    provisioningStatuses: {
      requires_domain: t(`${d}.provisioningStatuses.requires_domain`),
      domain_linked: t(`${d}.provisioningStatuses.domain_linked`),
      requires_installation: t(`${d}.provisioningStatuses.requires_installation`),
      pending: t(`${d}.provisioningStatuses.pending`),
      provisioned: t(`${d}.provisioningStatuses.provisioned`),
      ready_for_activation: t(`${d}.provisioningStatuses.ready_for_activation`),
      active: t(`${d}.provisioningStatuses.active`),
      failed: t(`${d}.provisioningStatuses.failed`),
    },
    licenseProductNames: {
      app_subscription: t(`${d}.licenseProductNames.app_subscription`),
    },
    licenseProductDescriptions: {
      app_subscription: t(`${d}.licenseProductDescriptions.app_subscription`),
    },
    agreementDisplayNames: {
      unonightPilotAgreement: t(`${d}.agreementDisplayNames.unonightPilotAgreement`),
      unonightUnlimitedAgreement: t(
        `${d}.agreementDisplayNames.unonightUnlimitedAgreement`,
      ),
    },
    managePlan: t(`${d}.managePlan`),
    createLicense: t(`${d}.createLicense`),
    viewLicense: t(`${d}.viewLicense`),
    addDomainInstallation: t(`${d}.addDomainInstallation`),
    viewSetup: t(`${d}.viewSetup`),
    licenseAlreadyCreated: t(`${d}.licenseAlreadyCreated`),
    licenseAlreadyConfigured: t(`${d}.licenseAlreadyConfigured`),
    licenseMissingLink: t(`${d}.licenseMissingLink`),
    noNewLicenseNeeded: t(`${d}.noNewLicenseNeeded`),
    noNewDomainInstallationNeeded: t(`${d}.noNewDomainInstallationNeeded`),
  };
}

export function buildPlatformPortalCustomerCreationLabels(
  t: Translator,
): PlatformPortalCustomerCreationLabels {
  const c = "platform.customers.creation";
  return {
    title: t(`${c}.title`),
    description: t(`${c}.description`),
    backToCustomers: t(`${c}.backToCustomers`),
    sectionIdentity: t(`${c}.sectionIdentity`),
    sectionPlatform: t(`${c}.sectionPlatform`),
    sectionSummary: t(`${c}.sectionSummary`),
    organizationNumber: t(`${c}.organizationNumber`),
    registrationNumber: t(`${c}.registrationNumber`),
    registrationNumberHelp: t(`${c}.registrationNumberHelp`),
    legalName: t(`${c}.legalName`),
    customerName: t(`${c}.customerName`),
    slug: t(`${c}.slug`),
    country: t(`${c}.country`),
    selectCountry: t(`${c}.selectCountry`),
    searchNorwegianCompany: t(`${c}.searchNorwegianCompany`),
    searchNameOrNumber: t(`${c}.searchNameOrNumber`),
    companyNameOrNumber: t(`${c}.companyNameOrNumber`),
    lookupAction: t(`${c}.lookupAction`),
    lookupLoading: t(`${c}.lookupLoading`),
    lookupSuccess: t(`${c}.lookupSuccess`),
    lookupNotFound: t(`${c}.lookupNotFound`),
    lookupUnavailable: t(`${c}.lookupUnavailable`),
    lookupMultiple: t(`${c}.lookupMultiple`),
    selectCompany: t(`${c}.selectCompany`),
    selectedCompany: t(`${c}.selectedCompany`),
    lookupAvailableNorway: t(`${c}.lookupAvailableNorway`),
    lookupUnavailableCountry: t(`${c}.lookupUnavailableCountry`),
    enterManually: t(`${c}.enterManually`),
    queryTooShort: t(`${c}.queryTooShort`),
    registryNoResponse: t(`${c}.registryNoResponse`),
    invalidOrganizationNumber: t(`${c}.invalidOrganizationNumber`),
    registrationNumberRequired: t(`${c}.registrationNumberRequired`),
    duplicateOrganizationNumber: t(`${c}.duplicateOrganizationNumber`),
    invalidSlug: t(`${c}.invalidSlug`),
    duplicateSlug: t(`${c}.duplicateSlug`),
    reservedSlug: t(`${c}.reservedSlug`),
    summaryTitle: t(`${c}.summaryTitle`),
    createsTitle: t(`${c}.createsTitle`),
    createsNotTitle: t(`${c}.createsNotTitle`),
    createsItems: [
      t(`${c}.creates.company`),
      t(`${c}.creates.organization`),
      t(`${c}.creates.customer`),
    ],
    createsNotItems: [
      t(`${c}.createsNot.subscription`),
      t(`${c}.createsNot.license`),
      t(`${c}.createsNot.domain`),
      t(`${c}.createsNot.auth`),
      t(`${c}.createsNot.email`),
    ],
    submit: t(`${c}.submit`),
    cancel: t(`${c}.cancel`),
    submitting: t(`${c}.submitting`),
    success: t(`${c}.success`),
    error: t(`${c}.error`),
    unauthorized: t(`${c}.unauthorized`),
    forbidden: t(`${c}.forbidden`),
    retry: t(`${c}.retry`),
    slugPreview: t(`${c}.slugPreview`),
    addressUnavailableNote: t(`${c}.addressUnavailableNote`),
  };
}

export function buildPlatformPortalCommercialPlanLabels(
  t: Translator,
): PlatformPortalCommercialPlanLabels {
  const c = "platform.customers.commercialPlan";
  const subscriptionStatus = "platform.status.subscription";
  return {
    managePlan: t(`${c}.managePlan`),
    title: t(`${c}.title`),
    currentPlan: t(`${c}.currentPlan`),
    availablePlans: t(`${c}.availablePlans`),
    lifetime: t(`${c}.lifetime`),
    recurring: t(`${c}.recurring`),
    monthly: t(`${c}.monthly`),
    yearly: t(`${c}.yearly`),
    duration: t(`${c}.duration`),
    agreement: t(`${c}.agreement`),
    trialPeriod: t(`${c}.trialPeriod`),
    noTrial: t(`${c}.noTrial`),
    active: t(`${c}.active`),
    trialing: t(`${c}.trialing`),
    pending: t(`${c}.pending`),
    cancelled: t(`${c}.cancelled`),
    paused: t(`${c}.paused`),
    pastDue: t(`${c}.pastDue`),
    unknownStatus: t(`${c}.unknownStatus`),
    planDescription: t(`${c}.planDescription`),
    price: t(`${c}.price`),
    billingCycle: t(`${c}.billingCycle`),
    startNow: t(`${c}.startNow`),
    startTrial: t(`${c}.startTrial`),
    trialDays: t(`${c}.trialDays`),
    internalReason: t(`${c}.internalReason`),
    reasonRequired: t(`${c}.reasonRequired`),
    summary: t(`${c}.summary`),
    summaryCreates: t(`${c}.summaryCreates`),
    summaryNoPayment: t(`${c}.summaryNoPayment`),
    summaryNoLicense: t(`${c}.summaryNoLicense`),
    activate: t(`${c}.activate`),
    activating: t(`${c}.activating`),
    success: t(`${c}.success`),
    activePlanConflict: t(`${c}.activePlanConflict`),
    activeAgreementChangeUnsupported: t(`${c}.activeAgreementChangeUnsupported`),
    planLifetimeUnsupported: t(`${c}.planLifetimeUnsupported`),
    planRecurringUnsupported: t(`${c}.planRecurringUnsupported`),
    planTrialUnsupported: t(`${c}.planTrialUnsupported`),
    loadPlansError: t(`${c}.loadPlansError`),
    activateError: t(`${c}.activateError`),
    emptyPlans: t(`${c}.emptyPlans`),
    forbidden: t(`${c}.forbidden`),
    unauthorized: t(`${c}.unauthorized`),
    cancel: t(`${c}.cancel`),
    close: t(`${c}.close`),
    retry: t(`${c}.retry`),
    confirmRequired: t(`${c}.confirmRequired`),
    selectPlan: t(`${c}.selectPlan`),
    noPrice: t(`${c}.noPrice`),
    loadingPlans: t(`${c}.loadingPlans`),
    subscriptionStatuses: {
      active: t(`${subscriptionStatus}.active`),
      trialing: t(`${subscriptionStatus}.trialing`),
      past_due: t(`${subscriptionStatus}.past_due`),
      unpaid: t(`${subscriptionStatus}.unpaid`),
      paused: t(`${subscriptionStatus}.paused`),
      cancelled: t(`${subscriptionStatus}.cancelled`),
      canceled: t(`${subscriptionStatus}.canceled`),
    },
  };
}

export function buildPlatformPortalLicenseProvisioningLabels(
  t: Translator,
): PlatformPortalLicenseProvisioningLabels {
  const c = "platform.customers.licenseProvisioning";
  return {
    createLicense: t(`${c}.createLicense`),
    title: t(`${c}.title`),
    currentLicenses: t(`${c}.currentLicenses`),
    availableProducts: t(`${c}.availableProducts`),
    licenseProduct: t(`${c}.licenseProduct`),
    productCode: t(`${c}.productCode`),
    productName: t(`${c}.productName`),
    licenseStatus: t(`${c}.licenseStatus`),
    provisioningStatus: t(`${c}.provisioningStatus`),
    licenseCode: t(`${c}.licenseCode`),
    maskedLicenseCode: t(`${c}.maskedLicenseCode`),
    requiresCommercialPlan: t(`${c}.requiresCommercialPlan`),
    commercialPlanActive: t(`${c}.commercialPlanActive`),
    commercialPlanMissing: t(`${c}.commercialPlanMissing`),
    requiresEntitlement: t(`${c}.requiresEntitlement`),
    domainLater: t(`${c}.domainLater`),
    installationLater: t(`${c}.installationLater`),
    internalReason: t(`${c}.internalReason`),
    reasonRequired: t(`${c}.reasonRequired`),
    summary: t(`${c}.summary`),
    summaryCreates: t(`${c}.summaryCreates`),
    summaryNoDomain: t(`${c}.summaryNoDomain`),
    summaryNoWebsiteKompis: t(`${c}.summaryNoWebsiteKompis`),
    create: t(`${c}.create`),
    creating: t(`${c}.creating`),
    success: t(`${c}.success`),
    alreadyExists: t(`${c}.alreadyExists`),
    productUnavailable: t(`${c}.productUnavailable`),
    productNotAssignable: t(`${c}.productNotAssignable`),
    emptyProducts: t(`${c}.emptyProducts`),
    emptyLicenses: t(`${c}.emptyLicenses`),
    waitingProvisioning: t(`${c}.waitingProvisioning`),
    requiresDomain: t(`${c}.requiresDomain`),
    requiresInstallation: t(`${c}.requiresInstallation`),
    active: t(`${c}.active`),
    pending: t(`${c}.pending`),
    suspended: t(`${c}.suspended`),
    expired: t(`${c}.expired`),
    revoked: t(`${c}.revoked`),
    failed: t(`${c}.failed`),
    forbidden: t(`${c}.forbidden`),
    unauthorized: t(`${c}.unauthorized`),
    loadProductsError: t(`${c}.loadProductsError`),
    createError: t(`${c}.createError`),
    cancel: t(`${c}.cancel`),
    retry: t(`${c}.retry`),
    confirmRequired: t(`${c}.confirmRequired`),
    loadingProducts: t(`${c}.loadingProducts`),
    close: t(`${c}.close`),
    productNames: {
      app_subscription: t(`${c}.productNames.app_subscription`),
    },
    productDescriptions: {
      app_subscription: t(`${c}.productDescriptions.app_subscription`),
    },
    licenseStatuses: {
      pending: t(`${c}.licenseStatuses.pending`),
      active: t(`${c}.licenseStatuses.active`),
      suspended: t(`${c}.licenseStatuses.suspended`),
      expired: t(`${c}.licenseStatuses.expired`),
      cancelled: t(`${c}.licenseStatuses.cancelled`),
      canceled: t(`${c}.licenseStatuses.cancelled`),
      revoked: t(`${c}.licenseStatuses.revoked`),
      failed: t(`${c}.licenseStatuses.failed`),
    },
    provisioningStatuses: {
      requires_domain: t(`${c}.provisioningStatuses.requires_domain`),
      domain_linked: t(`${c}.provisioningStatuses.domain_linked`),
      requires_installation: t(`${c}.provisioningStatuses.requires_installation`),
      pending: t(`${c}.provisioningStatuses.pending`),
      provisioned: t(`${c}.provisioningStatuses.provisioned`),
      ready_for_activation: t(`${c}.provisioningStatuses.ready_for_activation`),
      active: t(`${c}.provisioningStatuses.active`),
      failed: t(`${c}.provisioningStatuses.failed`),
    },
  };
}

export function buildPlatformPortalDomainInstallationLabels(
  t: Translator,
): PlatformPortalDomainInstallationLabels {
  const c = "platform.customers.domainInstallation";
  return {
    addDomainInstallation: t(`${c}.addDomainInstallation`),
    title: t(`${c}.title`),
    currentDomains: t(`${c}.currentDomains`),
    currentInstallations: t(`${c}.currentInstallations`),
    selectLicense: t(`${c}.selectLicense`),
    eligibleLicenses: t(`${c}.eligibleLicenses`),
    noEligibleLicenses: t(`${c}.noEligibleLicenses`),
    hostname: t(`${c}.hostname`),
    canonicalHostname: t(`${c}.canonicalHostname`),
    domainId: t(`${c}.domainId`),
    domainStatus: t(`${c}.domainStatus`),
    installation: t(`${c}.installation`),
    installationId: t(`${c}.installationId`),
    installId: t(`${c}.installId`),
    installationStatus: t(`${c}.installationStatus`),
    notVerified: t(`${c}.notVerified`),
    waitingVerification: t(`${c}.waitingVerification`),
    readyForActivation: t(`${c}.readyForActivation`),
    active: t(`${c}.active`),
    suspended: t(`${c}.suspended`),
    failed: t(`${c}.failed`),
    domainNotAutoVerified: t(`${c}.domainNotAutoVerified`),
    dnsNotChanged: t(`${c}.dnsNotChanged`),
    websiteKompisNotActivated: t(`${c}.websiteKompisNotActivated`),
    internalReason: t(`${c}.internalReason`),
    reasonRequired: t(`${c}.reasonRequired`),
    summary: t(`${c}.summary`),
    summaryCreates: t(`${c}.summaryCreates`),
    create: t(`${c}.create`),
    creating: t(`${c}.creating`),
    success: t(`${c}.success`),
    domainAlreadyRegistered: t(`${c}.domainAlreadyRegistered`),
    licenseAlreadyHasDomain: t(`${c}.licenseAlreadyHasDomain`),
    licenseAlreadyHasInstallation: t(`${c}.licenseAlreadyHasInstallation`),
    hostnameInvalid: t(`${c}.hostnameInvalid`),
    emptyDomains: t(`${c}.emptyDomains`),
    emptyInstallations: t(`${c}.emptyInstallations`),
    forbidden: t(`${c}.forbidden`),
    unauthorized: t(`${c}.unauthorized`),
    loadDomainsError: t(`${c}.loadDomainsError`),
    loadInstallationsError: t(`${c}.loadInstallationsError`),
    createError: t(`${c}.createError`),
    cancel: t(`${c}.cancel`),
    retry: t(`${c}.retry`),
    confirmRequired: t(`${c}.confirmRequired`),
    loadingEligible: t(`${c}.loadingEligible`),
    close: t(`${c}.close`),
    installIdHelp: t(`${c}.installIdHelp`),
    conflictReadOnly: t(`${c}.conflictReadOnly`),
    productNames: {
      app_subscription: t(`${c}.productNames.app_subscription`),
    },
    domainStatuses: {
      pending: t(`${c}.domainStatuses.pending`),
      active: t(`${c}.domainStatuses.active`),
      verified: t(`${c}.domainStatuses.verified`),
      unverified: t(`${c}.domainStatuses.unverified`),
      suspended: t(`${c}.domainStatuses.suspended`),
      failed: t(`${c}.domainStatuses.failed`),
      removed: t(`${c}.domainStatuses.removed`),
      disabled: t(`${c}.domainStatuses.disabled`),
      unknown: t(`${c}.domainStatuses.unknown`),
    },
    installationStatuses: {
      draft: t(`${c}.installationStatuses.draft`),
      pending_verification: t(`${c}.installationStatuses.pending_verification`),
      ready: t(`${c}.installationStatuses.ready`),
      installing: t(`${c}.installationStatuses.installing`),
      active: t(`${c}.installationStatuses.active`),
      warning: t(`${c}.installationStatuses.warning`),
      failed: t(`${c}.installationStatuses.failed`),
      suspended: t(`${c}.installationStatuses.suspended`),
      archived: t(`${c}.installationStatuses.archived`),
    },
    provisioningStatuses: {
      requires_domain: t(`${c}.provisioningStatuses.requires_domain`),
      domain_linked: t(`${c}.provisioningStatuses.domain_linked`),
      requires_installation: t(`${c}.provisioningStatuses.requires_installation`),
      pending: t(`${c}.provisioningStatuses.pending`),
      provisioned: t(`${c}.provisioningStatuses.provisioned`),
      ready_for_activation: t(`${c}.provisioningStatuses.ready_for_activation`),
      active: t(`${c}.provisioningStatuses.active`),
      failed: t(`${c}.provisioningStatuses.failed`),
    },
  };
}
