import type { Translator } from "@/lib/i18n/translate";
import type {
  PlatformPortalCommercialPlanLabels,
  PlatformPortalCustomerCreationLabels,
  PlatformPortalCustomerDetailLabels,
  PlatformPortalCustomersLabels,
  PlatformPortalDomainInstallationLabels,
  PlatformPortalLabels,
  PlatformPortalLicenseProvisioningLabels,
} from "./types";

export function buildPlatformPortalLabels(t: Translator): PlatformPortalLabels {
  const d = "platform.portalStructure.dashboard";
  const f = "platform.portalStructure.foundation";
  const billingNav = "platform.billingCommerceCenter.nav";

  return {
    dashboard: {
      title: t(`${d}.title`),
      subtitle: t(`${d}.subtitle`),
      loading: t(`${d}.loading`),
      principle: t(`${d}.principle`),
      privacyNote: t(`${d}.privacyNote`),
      organizationsRequiringAttention: t(`${d}.organizationsRequiringAttention`),
      activeSubscriptions: t(`${d}.activeSubscriptions`),
      openSupportWorkload: t(`${d}.openSupportWorkload`),
      paymentStatusSummary: t(`${d}.paymentStatusSummary`),
      paymentActive: t(`${d}.paymentActive`),
      paymentPastDue: t(`${d}.paymentPastDue`),
      paymentTrialing: t(`${d}.paymentTrialing`),
      invoices: t(`${billingNav}.invoices`),
      paymentProviders: t(`${billingNav}.paymentProviders`),
      accountingIntegration: t(`${billingNav}.accountingIntegration`),
      customerSuccessIndicators: t(`${d}.customerSuccessIndicators`),
      healthyRatio: t(`${d}.healthyRatio`),
      marketplaceModeration: t(`${d}.marketplaceModeration`),
      pendingReview: t(`${d}.pendingReview`),
      published: t(`${d}.published`),
      partnerProgramSummary: t(`${d}.partnerProgramSummary`),
      activePrograms: t(`${d}.activePrograms`),
      pendingApplications: t(`${d}.pendingApplications`),
      productDeploymentUpdates: t(`${d}.productDeploymentUpdates`),
      noUpdates: t(`${d}.noUpdates`),
      portalModules: t(`${d}.portalModules`),
      openModule: t(`${d}.openModule`),
      loadErrorTitle: t(`${d}.loadErrorTitle`),
      loadErrorMessage: t(`${d}.loadErrorMessage`),
      retry: t(`${d}.retry`),
    },
    foundation: {
      loading: t(`${f}.loading`),
      back: t(`${f}.back`),
      structureNote: t(`${f}.structureNote`),
    },
  };
}

export function buildPlatformPortalCustomersLabels(
  t: Translator,
): PlatformPortalCustomersLabels {
  const c = "platform.customers";
  const customerStatus = "platform.status.customer";
  const subscriptionStatus = "platform.status.subscription";

  return {
    title: t(`${c}.registryTitle`),
    description: t(`${c}.registryDescription`),
    summaryTotal: t(`${c}.summaryTotal`),
    summaryActive: t(`${c}.summaryActive`),
    summaryNew: t(`${c}.summaryNew`),
    summaryAttention: t(`${c}.summaryAttention`),
    loading: t(`${c}.loading`),
    error: t(`${c}.error`),
    retry: t(`${c}.retry`),
    emptyTitle: t(`${c}.emptyTitle`),
    emptyDescription: t(`${c}.emptyDescription`),
    searchPlaceholder: t(`${c}.searchPlaceholder`),
    filterAll: t(`${c}.filterAll`),
    filterStatus: t(`${c}.filterStatus`),
    filterSubscription: t(`${c}.filterSubscription`),
    filterAttribution: t(`${c}.filterAttribution`),
    filterPartner: t(`${c}.filterPartner`),
    filterDirect: t(`${c}.filterDirect`),
    clearFilters: t(`${c}.clearFilters`),
    columnCustomer: t(`${c}.columnCustomer`),
    columnOrganizationNumber: t(`${c}.columnOrganizationNumber`),
    columnStatus: t(`${c}.columnStatus`),
    columnSubscription: t(`${c}.columnSubscription`),
    columnMembers: t(`${c}.columnMembers`),
    columnAttribution: t(`${c}.columnAttribution`),
    columnSupport: t(`${c}.columnSupport`),
    columnLastActivity: t(`${c}.columnLastActivity`),
    columnActions: t(`${c}.columnActions`),
    requiresAttention: t(`${c}.requiresAttention`),
    lifetime: t(`${c}.lifetime`),
    partnerCustomer: t(`${c}.partnerCustomer`),
    directCustomer: t(`${c}.directCustomer`),
    noSubscription: t(`${c}.noSubscription`),
    notAvailable: t(`${c}.notAvailable`),
    openCustomer: t(`${c}.openCustomer`),
    noOpenSupport: t(`${c}.noOpenSupport`),
    createCustomer: t(`${c}.createCustomer`),
    customerStatuses: {
      trial: t(`${customerStatus}.trial`),
      active: t(`${customerStatus}.active`),
      paused: t(`${customerStatus}.paused`),
      cancelled: t(`${customerStatus}.cancelled`),
      overdue: t(`${customerStatus}.overdue`),
    },
    subscriptionStatuses: {
      active: t(`${subscriptionStatus}.active`),
      trialing: t(`${subscriptionStatus}.trialing`),
      past_due: t(`${subscriptionStatus}.past_due`),
      unpaid: t(`${subscriptionStatus}.unpaid`),
      paused: t(`${subscriptionStatus}.paused`),
      cancelled: t(`${subscriptionStatus}.cancelled`),
      canceled: t(`${subscriptionStatus}.canceled`),
    },
  };
}

export function buildPlatformPortalCustomerDetailLabels(
  t: Translator,
): PlatformPortalCustomerDetailLabels {
  const d = "platform.customers.detail";
  const customerStatus = "platform.status.customer";
  const subscriptionStatus = "platform.status.subscription";
  const installationStatus = "platform.status.installation";

  return {
    title: t(`${d}.title`),
    backToCustomers: t(`${d}.backToCustomers`),
    loading: t(`${d}.loading`),
    error: t(`${d}.error`),
    retry: t(`${d}.retry`),
    notFound: t(`${d}.notFound`),
    forbidden: t(`${d}.forbidden`),
    unauthorized: t(`${d}.unauthorized`),
    sectionBusiness: t(`${d}.sectionBusiness`),
    sectionCommercial: t(`${d}.sectionCommercial`),
    sectionLicenses: t(`${d}.sectionLicenses`),
    sectionDomains: t(`${d}.sectionDomains`),
    sectionEntitlements: t(`${d}.sectionEntitlements`),
    sectionStatus: t(`${d}.sectionStatus`),
    organizationNumber: t(`${d}.organizationNumber`),
    legalName: t(`${d}.legalName`),
    customerName: t(`${d}.customerName`),
    customerId: t(`${d}.customerId`),
    companyId: t(`${d}.companyId`),
    createdAt: t(`${d}.createdAt`),
    updatedAt: t(`${d}.updatedAt`),
    subscription: t(`${d}.subscription`),
    lifetime: t(`${d}.lifetime`),
    duration: t(`${d}.duration`),
    plan: t(`${d}.plan`),
    trialPeriod: t(`${d}.trialPeriod`),
    noTrial: t(`${d}.noTrial`),
    activePeriod: t(`${d}.activePeriod`),
    directCustomer: t(`${d}.directCustomer`),
    partnerCustomer: t(`${d}.partnerCustomer`),
    members: t(`${d}.members`),
    activeLicenses: t(`${d}.activeLicenses`),
    domains: t(`${d}.domains`),
    installations: t(`${d}.installations`),
    domainsAndInstallations: t(`${d}.domainsAndInstallations`),
    openSupport: t(`${d}.openSupport`),
    notAvailable: t(`${d}.notAvailable`),
    requiresAttention: t(`${d}.requiresAttention`),
    healthy: t(`${d}.healthy`),
    emptyLicenses: t(`${d}.emptyLicenses`),
    emptyDomains: t(`${d}.emptyDomains`),
    emptyEntitlements: t(`${d}.emptyEntitlements`),
    copy: t(`${d}.copy`),
    copied: t(`${d}.copied`),
    generatedAt: t(`${d}.generatedAt`),
    slug: t(`${d}.slug`),
    slugHelp: t(`${d}.slugHelp`),
    product: t(`${d}.product`),
    status: t(`${d}.status`),
    domain: t(`${d}.domain`),
    installId: t(`${d}.installId`),
    activatedAt: t(`${d}.activatedAt`),
    expiresAt: t(`${d}.expiresAt`),
    hostname: t(`${d}.hostname`),
    verifiedAt: t(`${d}.verifiedAt`),
    code: t(`${d}.code`),
    name: t(`${d}.name`),
    grantedAt: t(`${d}.grantedAt`),
    unknownStatus: t(`${d}.unknownStatus`),
    customerStatuses: {
      trial: t(`${customerStatus}.trial`),
      active: t(`${customerStatus}.active`),
      paused: t(`${customerStatus}.paused`),
      cancelled: t(`${customerStatus}.cancelled`),
      overdue: t(`${customerStatus}.overdue`),
    },
    subscriptionStatuses: {
      active: t(`${subscriptionStatus}.active`),
      trialing: t(`${subscriptionStatus}.trialing`),
      past_due: t(`${subscriptionStatus}.past_due`),
      unpaid: t(`${subscriptionStatus}.unpaid`),
      paused: t(`${subscriptionStatus}.paused`),
      cancelled: t(`${subscriptionStatus}.cancelled`),
      canceled: t(`${subscriptionStatus}.canceled`),
    },
    licenseStatuses: {
      pending: t(`${d}.licenseStatuses.pending`),
      active: t(`${d}.licenseStatuses.active`),
      suspended: t(`${d}.licenseStatuses.suspended`),
      expired: t(`${d}.licenseStatuses.expired`),
      cancelled: t(`${d}.licenseStatuses.cancelled`),
      canceled: t(`${d}.licenseStatuses.cancelled`),
    },
    domainStatuses: {
      active: t(`${d}.domainStatuses.active`),
      pending: t(`${d}.domainStatuses.pending`),
      verified: t(`${d}.domainStatuses.verified`),
      disabled: t(`${d}.domainStatuses.disabled`),
      removed: t(`${d}.domainStatuses.removed`),
      unknown: t(`${d}.domainStatuses.unknown`),
      paused: t(`${installationStatus}.paused`),
      revoked: t(`${installationStatus}.revoked`),
    },
    entitlementStatuses: {
      active: t(`${d}.entitlementStatuses.active`),
      licensed: t(`${d}.entitlementStatuses.licensed`),
      inactive: t(`${d}.entitlementStatuses.inactive`),
      expired: t(`${d}.entitlementStatuses.expired`),
      deactivated: t(`${d}.entitlementStatuses.deactivated`),
    },
    provisioningStatuses: {
      requires_domain: t(`${d}.provisioningStatuses.requires_domain`),
      domain_linked: t(`${d}.provisioningStatuses.domain_linked`),
      requires_installation: t(`${d}.provisioningStatuses.requires_installation`),
      pending: t(`${d}.provisioningStatuses.pending`),
      provisioned: t(`${d}.provisioningStatuses.provisioned`),
      ready_for_activation: t(`${d}.provisioningStatuses.ready_for_activation`),
      active: t(`${d}.provisioningStatuses.active`),
      failed: t(`${d}.provisioningStatuses.failed`),
    },
    licenseProductNames: {
      app_subscription: t(`${d}.licenseProductNames.app_subscription`),
    },
    licenseProductDescriptions: {
      app_subscription: t(`${d}.licenseProductDescriptions.app_subscription`),
    },
    managePlan: t(`${d}.managePlan`),
    createLicense: t(`${d}.createLicense`),
    addDomainInstallation: t(`${d}.addDomainInstallation`),
  };
}

export function buildPlatformPortalCustomerCreationLabels(
  t: Translator,
): PlatformPortalCustomerCreationLabels {
  const c = "platform.customers.creation";
  return {
    title: t(`${c}.title`),
    description: t(`${c}.description`),
    backToCustomers: t(`${c}.backToCustomers`),
    sectionIdentity: t(`${c}.sectionIdentity`),
    sectionPlatform: t(`${c}.sectionPlatform`),
    sectionSummary: t(`${c}.sectionSummary`),
    organizationNumber: t(`${c}.organizationNumber`),
    registrationNumber: t(`${c}.registrationNumber`),
    registrationNumberHelp: t(`${c}.registrationNumberHelp`),
    legalName: t(`${c}.legalName`),
    customerName: t(`${c}.customerName`),
    slug: t(`${c}.slug`),
    country: t(`${c}.country`),
    selectCountry: t(`${c}.selectCountry`),
    searchNorwegianCompany: t(`${c}.searchNorwegianCompany`),
    searchNameOrNumber: t(`${c}.searchNameOrNumber`),
    companyNameOrNumber: t(`${c}.companyNameOrNumber`),
    lookupAction: t(`${c}.lookupAction`),
    lookupLoading: t(`${c}.lookupLoading`),
    lookupSuccess: t(`${c}.lookupSuccess`),
    lookupNotFound: t(`${c}.lookupNotFound`),
    lookupUnavailable: t(`${c}.lookupUnavailable`),
    lookupMultiple: t(`${c}.lookupMultiple`),
    selectCompany: t(`${c}.selectCompany`),
    selectedCompany: t(`${c}.selectedCompany`),
    lookupAvailableNorway: t(`${c}.lookupAvailableNorway`),
    lookupUnavailableCountry: t(`${c}.lookupUnavailableCountry`),
    enterManually: t(`${c}.enterManually`),
    queryTooShort: t(`${c}.queryTooShort`),
    registryNoResponse: t(`${c}.registryNoResponse`),
    invalidOrganizationNumber: t(`${c}.invalidOrganizationNumber`),
    registrationNumberRequired: t(`${c}.registrationNumberRequired`),
    duplicateOrganizationNumber: t(`${c}.duplicateOrganizationNumber`),
    invalidSlug: t(`${c}.invalidSlug`),
    duplicateSlug: t(`${c}.duplicateSlug`),
    reservedSlug: t(`${c}.reservedSlug`),
    summaryTitle: t(`${c}.summaryTitle`),
    createsTitle: t(`${c}.createsTitle`),
    createsNotTitle: t(`${c}.createsNotTitle`),
    createsItems: [
      t(`${c}.creates.company`),
      t(`${c}.creates.organization`),
      t(`${c}.creates.customer`),
    ],
    createsNotItems: [
      t(`${c}.createsNot.subscription`),
      t(`${c}.createsNot.license`),
      t(`${c}.createsNot.domain`),
      t(`${c}.createsNot.auth`),
      t(`${c}.createsNot.email`),
    ],
    submit: t(`${c}.submit`),
    cancel: t(`${c}.cancel`),
    submitting: t(`${c}.submitting`),
    success: t(`${c}.success`),
    error: t(`${c}.error`),
    unauthorized: t(`${c}.unauthorized`),
    forbidden: t(`${c}.forbidden`),
    retry: t(`${c}.retry`),
    slugPreview: t(`${c}.slugPreview`),
    addressUnavailableNote: t(`${c}.addressUnavailableNote`),
  };
}

export function buildPlatformPortalCommercialPlanLabels(
  t: Translator,
): PlatformPortalCommercialPlanLabels {
  const c = "platform.customers.commercialPlan";
  const subscriptionStatus = "platform.status.subscription";
  return {
    managePlan: t(`${c}.managePlan`),
    title: t(`${c}.title`),
    currentPlan: t(`${c}.currentPlan`),
    availablePlans: t(`${c}.availablePlans`),
    lifetime: t(`${c}.lifetime`),
    recurring: t(`${c}.recurring`),
    monthly: t(`${c}.monthly`),
    yearly: t(`${c}.yearly`),
    duration: t(`${c}.duration`),
    agreement: t(`${c}.agreement`),
    trialPeriod: t(`${c}.trialPeriod`),
    noTrial: t(`${c}.noTrial`),
    active: t(`${c}.active`),
    trialing: t(`${c}.trialing`),
    pending: t(`${c}.pending`),
    cancelled: t(`${c}.cancelled`),
    paused: t(`${c}.paused`),
    pastDue: t(`${c}.pastDue`),
    unknownStatus: t(`${c}.unknownStatus`),
    planDescription: t(`${c}.planDescription`),
    price: t(`${c}.price`),
    billingCycle: t(`${c}.billingCycle`),
    startNow: t(`${c}.startNow`),
    startTrial: t(`${c}.startTrial`),
    trialDays: t(`${c}.trialDays`),
    internalReason: t(`${c}.internalReason`),
    reasonRequired: t(`${c}.reasonRequired`),
    summary: t(`${c}.summary`),
    summaryCreates: t(`${c}.summaryCreates`),
    summaryNoPayment: t(`${c}.summaryNoPayment`),
    summaryNoLicense: t(`${c}.summaryNoLicense`),
    activate: t(`${c}.activate`),
    activating: t(`${c}.activating`),
    success: t(`${c}.success`),
    activePlanConflict: t(`${c}.activePlanConflict`),
    activeAgreementChangeUnsupported: t(`${c}.activeAgreementChangeUnsupported`),
    planLifetimeUnsupported: t(`${c}.planLifetimeUnsupported`),
    planRecurringUnsupported: t(`${c}.planRecurringUnsupported`),
    planTrialUnsupported: t(`${c}.planTrialUnsupported`),
    loadPlansError: t(`${c}.loadPlansError`),
    activateError: t(`${c}.activateError`),
    emptyPlans: t(`${c}.emptyPlans`),
    forbidden: t(`${c}.forbidden`),
    unauthorized: t(`${c}.unauthorized`),
    cancel: t(`${c}.cancel`),
    close: t(`${c}.close`),
    retry: t(`${c}.retry`),
    confirmRequired: t(`${c}.confirmRequired`),
    selectPlan: t(`${c}.selectPlan`),
    noPrice: t(`${c}.noPrice`),
    loadingPlans: t(`${c}.loadingPlans`),
    subscriptionStatuses: {
      active: t(`${subscriptionStatus}.active`),
      trialing: t(`${subscriptionStatus}.trialing`),
      past_due: t(`${subscriptionStatus}.past_due`),
      unpaid: t(`${subscriptionStatus}.unpaid`),
      paused: t(`${subscriptionStatus}.paused`),
      cancelled: t(`${subscriptionStatus}.cancelled`),
      canceled: t(`${subscriptionStatus}.canceled`),
    },
  };
}

export function buildPlatformPortalLicenseProvisioningLabels(
  t: Translator,
): PlatformPortalLicenseProvisioningLabels {
  const c = "platform.customers.licenseProvisioning";
  return {
    createLicense: t(`${c}.createLicense`),
    title: t(`${c}.title`),
    currentLicenses: t(`${c}.currentLicenses`),
    availableProducts: t(`${c}.availableProducts`),
    licenseProduct: t(`${c}.licenseProduct`),
    productCode: t(`${c}.productCode`),
    productName: t(`${c}.productName`),
    licenseStatus: t(`${c}.licenseStatus`),
    provisioningStatus: t(`${c}.provisioningStatus`),
    licenseCode: t(`${c}.licenseCode`),
    maskedLicenseCode: t(`${c}.maskedLicenseCode`),
    requiresCommercialPlan: t(`${c}.requiresCommercialPlan`),
    commercialPlanActive: t(`${c}.commercialPlanActive`),
    commercialPlanMissing: t(`${c}.commercialPlanMissing`),
    requiresEntitlement: t(`${c}.requiresEntitlement`),
    domainLater: t(`${c}.domainLater`),
    installationLater: t(`${c}.installationLater`),
    internalReason: t(`${c}.internalReason`),
    reasonRequired: t(`${c}.reasonRequired`),
    summary: t(`${c}.summary`),
    summaryCreates: t(`${c}.summaryCreates`),
    summaryNoDomain: t(`${c}.summaryNoDomain`),
    summaryNoWebsiteKompis: t(`${c}.summaryNoWebsiteKompis`),
    create: t(`${c}.create`),
    creating: t(`${c}.creating`),
    success: t(`${c}.success`),
    alreadyExists: t(`${c}.alreadyExists`),
    productUnavailable: t(`${c}.productUnavailable`),
    productNotAssignable: t(`${c}.productNotAssignable`),
    emptyProducts: t(`${c}.emptyProducts`),
    emptyLicenses: t(`${c}.emptyLicenses`),
    waitingProvisioning: t(`${c}.waitingProvisioning`),
    requiresDomain: t(`${c}.requiresDomain`),
    requiresInstallation: t(`${c}.requiresInstallation`),
    active: t(`${c}.active`),
    pending: t(`${c}.pending`),
    suspended: t(`${c}.suspended`),
    expired: t(`${c}.expired`),
    revoked: t(`${c}.revoked`),
    failed: t(`${c}.failed`),
    forbidden: t(`${c}.forbidden`),
    unauthorized: t(`${c}.unauthorized`),
    loadProductsError: t(`${c}.loadProductsError`),
    createError: t(`${c}.createError`),
    cancel: t(`${c}.cancel`),
    retry: t(`${c}.retry`),
    confirmRequired: t(`${c}.confirmRequired`),
    loadingProducts: t(`${c}.loadingProducts`),
    close: t(`${c}.close`),
    productNames: {
      app_subscription: t(`${c}.productNames.app_subscription`),
    },
    productDescriptions: {
      app_subscription: t(`${c}.productDescriptions.app_subscription`),
    },
    licenseStatuses: {
      pending: t(`${c}.licenseStatuses.pending`),
      active: t(`${c}.licenseStatuses.active`),
      suspended: t(`${c}.licenseStatuses.suspended`),
      expired: t(`${c}.licenseStatuses.expired`),
      cancelled: t(`${c}.licenseStatuses.cancelled`),
      canceled: t(`${c}.licenseStatuses.cancelled`),
      revoked: t(`${c}.licenseStatuses.revoked`),
      failed: t(`${c}.licenseStatuses.failed`),
    },
    provisioningStatuses: {
      requires_domain: t(`${c}.provisioningStatuses.requires_domain`),
      domain_linked: t(`${c}.provisioningStatuses.domain_linked`),
      requires_installation: t(`${c}.provisioningStatuses.requires_installation`),
      pending: t(`${c}.provisioningStatuses.pending`),
      provisioned: t(`${c}.provisioningStatuses.provisioned`),
      ready_for_activation: t(`${c}.provisioningStatuses.ready_for_activation`),
      active: t(`${c}.provisioningStatuses.active`),
      failed: t(`${c}.provisioningStatuses.failed`),
    },
  };
}

export function buildPlatformPortalDomainInstallationLabels(
  t: Translator,
): PlatformPortalDomainInstallationLabels {
  const c = "platform.customers.domainInstallation";
  return {
    addDomainInstallation: t(`${c}.addDomainInstallation`),
    title: t(`${c}.title`),
    currentDomains: t(`${c}.currentDomains`),
    currentInstallations: t(`${c}.currentInstallations`),
    selectLicense: t(`${c}.selectLicense`),
    eligibleLicenses: t(`${c}.eligibleLicenses`),
    noEligibleLicenses: t(`${c}.noEligibleLicenses`),
    hostname: t(`${c}.hostname`),
    canonicalHostname: t(`${c}.canonicalHostname`),
    domainId: t(`${c}.domainId`),
    domainStatus: t(`${c}.domainStatus`),
    installation: t(`${c}.installation`),
    installationId: t(`${c}.installationId`),
    installId: t(`${c}.installId`),
    installationStatus: t(`${c}.installationStatus`),
    notVerified: t(`${c}.notVerified`),
    waitingVerification: t(`${c}.waitingVerification`),
    readyForActivation: t(`${c}.readyForActivation`),
    active: t(`${c}.active`),
    suspended: t(`${c}.suspended`),
    failed: t(`${c}.failed`),
    domainNotAutoVerified: t(`${c}.domainNotAutoVerified`),
    dnsNotChanged: t(`${c}.dnsNotChanged`),
    websiteKompisNotActivated: t(`${c}.websiteKompisNotActivated`),
    internalReason: t(`${c}.internalReason`),
    reasonRequired: t(`${c}.reasonRequired`),
    summary: t(`${c}.summary`),
    summaryCreates: t(`${c}.summaryCreates`),
    create: t(`${c}.create`),
    creating: t(`${c}.creating`),
    success: t(`${c}.success`),
    domainAlreadyRegistered: t(`${c}.domainAlreadyRegistered`),
    licenseAlreadyHasDomain: t(`${c}.licenseAlreadyHasDomain`),
    licenseAlreadyHasInstallation: t(`${c}.licenseAlreadyHasInstallation`),
    hostnameInvalid: t(`${c}.hostnameInvalid`),
    emptyDomains: t(`${c}.emptyDomains`),
    emptyInstallations: t(`${c}.emptyInstallations`),
    forbidden: t(`${c}.forbidden`),
    unauthorized: t(`${c}.unauthorized`),
    loadDomainsError: t(`${c}.loadDomainsError`),
    loadInstallationsError: t(`${c}.loadInstallationsError`),
    createError: t(`${c}.createError`),
    cancel: t(`${c}.cancel`),
    retry: t(`${c}.retry`),
    confirmRequired: t(`${c}.confirmRequired`),
    loadingEligible: t(`${c}.loadingEligible`),
    close: t(`${c}.close`),
    installIdHelp: t(`${c}.installIdHelp`),
    conflictReadOnly: t(`${c}.conflictReadOnly`),
    productNames: {
      app_subscription: t(`${c}.productNames.app_subscription`),
    },
    domainStatuses: {
      pending: t(`${c}.domainStatuses.pending`),
      active: t(`${c}.domainStatuses.active`),
      verified: t(`${c}.domainStatuses.verified`),
      unverified: t(`${c}.domainStatuses.unverified`),
      suspended: t(`${c}.domainStatuses.suspended`),
      failed: t(`${c}.domainStatuses.failed`),
      removed: t(`${c}.domainStatuses.removed`),
      disabled: t(`${c}.domainStatuses.disabled`),
      unknown: t(`${c}.domainStatuses.unknown`),
    },
    installationStatuses: {
      draft: t(`${c}.installationStatuses.draft`),
      pending_verification: t(`${c}.installationStatuses.pending_verification`),
      ready: t(`${c}.installationStatuses.ready`),
      installing: t(`${c}.installationStatuses.installing`),
      active: t(`${c}.installationStatuses.active`),
      warning: t(`${c}.installationStatuses.warning`),
      failed: t(`${c}.installationStatuses.failed`),
      suspended: t(`${c}.installationStatuses.suspended`),
      archived: t(`${c}.installationStatuses.archived`),
    },
    provisioningStatuses: {
      requires_domain: t(`${c}.provisioningStatuses.requires_domain`),
      domain_linked: t(`${c}.provisioningStatuses.domain_linked`),
      requires_installation: t(`${c}.provisioningStatuses.requires_installation`),
      pending: t(`${c}.provisioningStatuses.pending`),
      provisioned: t(`${c}.provisioningStatuses.provisioned`),
      ready_for_activation: t(`${c}.provisioningStatuses.ready_for_activation`),
      active: t(`${c}.provisioningStatuses.active`),
      failed: t(`${c}.provisioningStatuses.failed`),
    },
  };
}
