import type { Translator } from "@/lib/i18n/translate";
import type {
  PlatformPortalCustomerCreationLabels,
  PlatformPortalCustomerDetailLabels,
  PlatformPortalCustomersLabels,
  PlatformPortalLabels,
} from "./types";

export function buildPlatformPortalLabels(t: Translator): PlatformPortalLabels {
  const d = "platform.portalStructure.dashboard";
  const f = "platform.portalStructure.foundation";
  const billingNav = "platform.billingCommerceCenter.nav";

  return {
    dashboard: {
      title: t(`${d}.title`),
      subtitle: t(`${d}.subtitle`),
      loading: t(`${d}.loading`),
      principle: t(`${d}.principle`),
      privacyNote: t(`${d}.privacyNote`),
      organizationsRequiringAttention: t(`${d}.organizationsRequiringAttention`),
      activeSubscriptions: t(`${d}.activeSubscriptions`),
      openSupportWorkload: t(`${d}.openSupportWorkload`),
      paymentStatusSummary: t(`${d}.paymentStatusSummary`),
      paymentActive: t(`${d}.paymentActive`),
      paymentPastDue: t(`${d}.paymentPastDue`),
      paymentTrialing: t(`${d}.paymentTrialing`),
      invoices: t(`${billingNav}.invoices`),
      paymentProviders: t(`${billingNav}.paymentProviders`),
      accountingIntegration: t(`${billingNav}.accountingIntegration`),
      customerSuccessIndicators: t(`${d}.customerSuccessIndicators`),
      healthyRatio: t(`${d}.healthyRatio`),
      marketplaceModeration: t(`${d}.marketplaceModeration`),
      pendingReview: t(`${d}.pendingReview`),
      published: t(`${d}.published`),
      partnerProgramSummary: t(`${d}.partnerProgramSummary`),
      activePrograms: t(`${d}.activePrograms`),
      pendingApplications: t(`${d}.pendingApplications`),
      productDeploymentUpdates: t(`${d}.productDeploymentUpdates`),
      noUpdates: t(`${d}.noUpdates`),
      portalModules: t(`${d}.portalModules`),
      openModule: t(`${d}.openModule`),
      loadErrorTitle: t(`${d}.loadErrorTitle`),
      loadErrorMessage: t(`${d}.loadErrorMessage`),
      retry: t(`${d}.retry`),
    },
    foundation: {
      loading: t(`${f}.loading`),
      back: t(`${f}.back`),
      structureNote: t(`${f}.structureNote`),
    },
  };
}

export function buildPlatformPortalCustomersLabels(
  t: Translator,
): PlatformPortalCustomersLabels {
  const c = "platform.customers";
  const customerStatus = "platform.status.customer";
  const subscriptionStatus = "platform.status.subscription";

  return {
    title: t(`${c}.registryTitle`),
    description: t(`${c}.registryDescription`),
    summaryTotal: t(`${c}.summaryTotal`),
    summaryActive: t(`${c}.summaryActive`),
    summaryNew: t(`${c}.summaryNew`),
    summaryAttention: t(`${c}.summaryAttention`),
    loading: t(`${c}.loading`),
    error: t(`${c}.error`),
    retry: t(`${c}.retry`),
    emptyTitle: t(`${c}.emptyTitle`),
    emptyDescription: t(`${c}.emptyDescription`),
    searchPlaceholder: t(`${c}.searchPlaceholder`),
    filterAll: t(`${c}.filterAll`),
    filterStatus: t(`${c}.filterStatus`),
    filterSubscription: t(`${c}.filterSubscription`),
    filterAttribution: t(`${c}.filterAttribution`),
    filterPartner: t(`${c}.filterPartner`),
    filterDirect: t(`${c}.filterDirect`),
    clearFilters: t(`${c}.clearFilters`),
    columnCustomer: t(`${c}.columnCustomer`),
    columnOrganizationNumber: t(`${c}.columnOrganizationNumber`),
    columnStatus: t(`${c}.columnStatus`),
    columnSubscription: t(`${c}.columnSubscription`),
    columnMembers: t(`${c}.columnMembers`),
    columnAttribution: t(`${c}.columnAttribution`),
    columnSupport: t(`${c}.columnSupport`),
    columnLastActivity: t(`${c}.columnLastActivity`),
    columnActions: t(`${c}.columnActions`),
    requiresAttention: t(`${c}.requiresAttention`),
    lifetime: t(`${c}.lifetime`),
    partnerCustomer: t(`${c}.partnerCustomer`),
    directCustomer: t(`${c}.directCustomer`),
    noSubscription: t(`${c}.noSubscription`),
    notAvailable: t(`${c}.notAvailable`),
    openCustomer: t(`${c}.openCustomer`),
    noOpenSupport: t(`${c}.noOpenSupport`),
    createCustomer: t(`${c}.createCustomer`),
    customerStatuses: {
      trial: t(`${customerStatus}.trial`),
      active: t(`${customerStatus}.active`),
      paused: t(`${customerStatus}.paused`),
      cancelled: t(`${customerStatus}.cancelled`),
      overdue: t(`${customerStatus}.overdue`),
    },
    subscriptionStatuses: {
      active: t(`${subscriptionStatus}.active`),
      trialing: t(`${subscriptionStatus}.trialing`),
      past_due: t(`${subscriptionStatus}.past_due`),
      unpaid: t(`${subscriptionStatus}.unpaid`),
      paused: t(`${subscriptionStatus}.paused`),
      cancelled: t(`${subscriptionStatus}.cancelled`),
      canceled: t(`${subscriptionStatus}.canceled`),
    },
  };
}

export function buildPlatformPortalCustomerDetailLabels(
  t: Translator,
): PlatformPortalCustomerDetailLabels {
  const d = "platform.customers.detail";
  const customerStatus = "platform.status.customer";
  const subscriptionStatus = "platform.status.subscription";
  const installationStatus = "platform.status.installation";

  return {
    title: t(`${d}.title`),
    backToCustomers: t(`${d}.backToCustomers`),
    loading: t(`${d}.loading`),
    error: t(`${d}.error`),
    retry: t(`${d}.retry`),
    notFound: t(`${d}.notFound`),
    forbidden: t(`${d}.forbidden`),
    unauthorized: t(`${d}.unauthorized`),
    sectionBusiness: t(`${d}.sectionBusiness`),
    sectionCommercial: t(`${d}.sectionCommercial`),
    sectionLicenses: t(`${d}.sectionLicenses`),
    sectionDomains: t(`${d}.sectionDomains`),
    sectionEntitlements: t(`${d}.sectionEntitlements`),
    sectionStatus: t(`${d}.sectionStatus`),
    organizationNumber: t(`${d}.organizationNumber`),
    legalName: t(`${d}.legalName`),
    customerName: t(`${d}.customerName`),
    customerId: t(`${d}.customerId`),
    companyId: t(`${d}.companyId`),
    createdAt: t(`${d}.createdAt`),
    updatedAt: t(`${d}.updatedAt`),
    subscription: t(`${d}.subscription`),
    lifetime: t(`${d}.lifetime`),
    plan: t(`${d}.plan`),
    trialPeriod: t(`${d}.trialPeriod`),
    activePeriod: t(`${d}.activePeriod`),
    directCustomer: t(`${d}.directCustomer`),
    partnerCustomer: t(`${d}.partnerCustomer`),
    members: t(`${d}.members`),
    activeLicenses: t(`${d}.activeLicenses`),
    domains: t(`${d}.domains`),
    installations: t(`${d}.installations`),
    openSupport: t(`${d}.openSupport`),
    notAvailable: t(`${d}.notAvailable`),
    requiresAttention: t(`${d}.requiresAttention`),
    healthy: t(`${d}.healthy`),
    emptyLicenses: t(`${d}.emptyLicenses`),
    emptyDomains: t(`${d}.emptyDomains`),
    emptyEntitlements: t(`${d}.emptyEntitlements`),
    copy: t(`${d}.copy`),
    copied: t(`${d}.copied`),
    generatedAt: t(`${d}.generatedAt`),
    slug: t(`${d}.slug`),
    product: t(`${d}.product`),
    status: t(`${d}.status`),
    domain: t(`${d}.domain`),
    installId: t(`${d}.installId`),
    activatedAt: t(`${d}.activatedAt`),
    expiresAt: t(`${d}.expiresAt`),
    hostname: t(`${d}.hostname`),
    verifiedAt: t(`${d}.verifiedAt`),
    code: t(`${d}.code`),
    name: t(`${d}.name`),
    grantedAt: t(`${d}.grantedAt`),
    customerStatuses: {
      trial: t(`${customerStatus}.trial`),
      active: t(`${customerStatus}.active`),
      paused: t(`${customerStatus}.paused`),
      cancelled: t(`${customerStatus}.cancelled`),
      overdue: t(`${customerStatus}.overdue`),
    },
    subscriptionStatuses: {
      active: t(`${subscriptionStatus}.active`),
      trialing: t(`${subscriptionStatus}.trialing`),
      past_due: t(`${subscriptionStatus}.past_due`),
      unpaid: t(`${subscriptionStatus}.unpaid`),
      paused: t(`${subscriptionStatus}.paused`),
      cancelled: t(`${subscriptionStatus}.cancelled`),
      canceled: t(`${subscriptionStatus}.canceled`),
    },
    licenseStatuses: {
      pending: t(`${d}.licenseStatuses.pending`),
      active: t(`${d}.licenseStatuses.active`),
      suspended: t(`${d}.licenseStatuses.suspended`),
      expired: t(`${d}.licenseStatuses.expired`),
      cancelled: t(`${d}.licenseStatuses.cancelled`),
      canceled: t(`${d}.licenseStatuses.cancelled`),
    },
    domainStatuses: {
      active: t(`${d}.domainStatuses.active`),
      pending: t(`${d}.domainStatuses.pending`),
      verified: t(`${d}.domainStatuses.verified`),
      disabled: t(`${d}.domainStatuses.disabled`),
      removed: t(`${d}.domainStatuses.removed`),
      unknown: t(`${d}.domainStatuses.unknown`),
      paused: t(`${installationStatus}.paused`),
      revoked: t(`${installationStatus}.revoked`),
    },
    entitlementStatuses: {
      active: t(`${d}.entitlementStatuses.active`),
      licensed: t(`${d}.entitlementStatuses.licensed`),
      inactive: t(`${d}.entitlementStatuses.inactive`),
      expired: t(`${d}.entitlementStatuses.expired`),
      deactivated: t(`${d}.entitlementStatuses.deactivated`),
    },
  };
}

export function buildPlatformPortalCustomerCreationLabels(
  t: Translator,
): PlatformPortalCustomerCreationLabels {
  const c = "platform.customers.creation";
  return {
    title: t(`${c}.title`),
    description: t(`${c}.description`),
    backToCustomers: t(`${c}.backToCustomers`),
    sectionIdentity: t(`${c}.sectionIdentity`),
    sectionPlatform: t(`${c}.sectionPlatform`),
    sectionSummary: t(`${c}.sectionSummary`),
    organizationNumber: t(`${c}.organizationNumber`),
    legalName: t(`${c}.legalName`),
    customerName: t(`${c}.customerName`),
    slug: t(`${c}.slug`),
    country: t(`${c}.country`),
    lookupAction: t(`${c}.lookupAction`),
    lookupLoading: t(`${c}.lookupLoading`),
    lookupSuccess: t(`${c}.lookupSuccess`),
    lookupNotFound: t(`${c}.lookupNotFound`),
    lookupUnavailable: t(`${c}.lookupUnavailable`),
    invalidOrganizationNumber: t(`${c}.invalidOrganizationNumber`),
    duplicateOrganizationNumber: t(`${c}.duplicateOrganizationNumber`),
    invalidSlug: t(`${c}.invalidSlug`),
    duplicateSlug: t(`${c}.duplicateSlug`),
    reservedSlug: t(`${c}.reservedSlug`),
    summaryTitle: t(`${c}.summaryTitle`),
    createsTitle: t(`${c}.createsTitle`),
    createsNotTitle: t(`${c}.createsNotTitle`),
    createsItems: [
      t(`${c}.creates.company`),
      t(`${c}.creates.organization`),
      t(`${c}.creates.customer`),
    ],
    createsNotItems: [
      t(`${c}.createsNot.subscription`),
      t(`${c}.createsNot.license`),
      t(`${c}.createsNot.domain`),
      t(`${c}.createsNot.auth`),
      t(`${c}.createsNot.email`),
    ],
    submit: t(`${c}.submit`),
    cancel: t(`${c}.cancel`),
    submitting: t(`${c}.submitting`),
    success: t(`${c}.success`),
    error: t(`${c}.error`),
    unauthorized: t(`${c}.unauthorized`),
    forbidden: t(`${c}.forbidden`),
    retry: t(`${c}.retry`),
    slugPreview: t(`${c}.slugPreview`),
    addressUnavailableNote: t(`${c}.addressUnavailableNote`),
  };
}
