import type { SkillsMarketplaceLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildSkillsMarketplaceLabels(t: Translator, namespace: "customerApp" | "platform"): SkillsMarketplaceLabels {
  const prefix = namespace === "platform" ? "platform.skillsMarketplace" : "customerApp.skillsMarketplace";

  return {
    title: t(`${prefix}.title`),
    subtitle: t(`${prefix}.subtitle`),
    loading: t(`${prefix}.loading`),
    empty: t(`${prefix}.empty`),
    principle: t(`${prefix}.principle`),
    privacy: t(`${prefix}.privacy`),
    sections: {
      overview: t(`${prefix}.sections.overview`),
      installed: t(`${prefix}.sections.installed`),
      recommended: t(`${prefix}.sections.recommended`),
      marketplace: t(`${prefix}.sections.marketplace`),
      pipeline: t(`${prefix}.sections.pipeline`),
      governance: t(`${prefix}.sections.governance`),
      performance: t(`${prefix}.sections.performance`),
    },
    overview: {
      installed: t(`${prefix}.overview.installed`),
      available: t(`${prefix}.overview.available`),
      pilot: t(`${prefix}.overview.pilot`),
      pendingReviews: t(`${prefix}.overview.pendingReviews`),
    },
    status: {
      operational: t(`${prefix}.status.operational`),
      pilot: t(`${prefix}.status.pilot`),
      beta: t(`${prefix}.status.beta`),
      paused: t(`${prefix}.status.paused`),
      requires_attention: t(`${prefix}.status.requiresAttention`),
    },
    environment: {
      production: t(`${prefix}.environment.production`),
      testing: t(`${prefix}.environment.testing`),
    },
    categories: {
      executive: t(`${prefix}.categories.executive`),
      support: t(`${prefix}.categories.support`),
      commerce: t(`${prefix}.categories.commerce`),
      operations: t(`${prefix}.categories.operations`),
      knowledge: t(`${prefix}.categories.knowledge`),
      growth: t(`${prefix}.categories.growth`),
      compliance: t(`${prefix}.categories.compliance`),
      automation: t(`${prefix}.categories.automation`),
      companion: t(`${prefix}.categories.companion`),
    },
    pipelineStages: {
      internal_development: t(`${prefix}.pipelineStages.internalDevelopment`),
      customer_zero: t(`${prefix}.pipelineStages.customerZero`),
      pilot_customers: t(`${prefix}.pipelineStages.pilotCustomers`),
      growth_partners: t(`${prefix}.pipelineStages.growthPartners`),
      stable_release: t(`${prefix}.pipelineStages.stableRelease`),
    },
    activation: {
      activate: t(`${prefix}.activation.activate`),
      request_access: t(`${prefix}.activation.requestAccess`),
      coming_soon: t(`${prefix}.activation.comingSoon`),
      active: t(`${prefix}.activation.active`),
    },
    actions: {
      activate: t(`${prefix}.actions.activate`),
      learnMore: t(`${prefix}.actions.learnMore`),
      requestAccess: t(`${prefix}.actions.requestAccess`),
      comingSoon: t(`${prefix}.actions.comingSoon`),
      viewDetails: t(`${prefix}.actions.viewDetails`),
      manage: t(`${prefix}.actions.manage`),
      history: t(`${prefix}.actions.history`),
    },
    installed: {
      version: t(`${prefix}.installed.version`),
      environment: t(`${prefix}.installed.environment`),
      owner: t(`${prefix}.installed.owner`),
      status: t(`${prefix}.installed.status`),
      empty: t(`${prefix}.installed.empty`),
    },
    recommended: {
      why: t(`${prefix}.recommended.why`),
      impact: t(`${prefix}.recommended.impact`),
      empty: t(`${prefix}.recommended.empty`),
    },
    marketplace: {
      allCategories: t(`${prefix}.marketplace.allCategories`),
      estimatedValue: t(`${prefix}.marketplace.estimatedValue`),
      empty: t(`${prefix}.marketplace.empty`),
    },
    governance: {
      permissionScope: t(`${prefix}.governance.permissionScope`),
      riskLevel: t(`${prefix}.governance.riskLevel`),
      owner: t(`${prefix}.governance.owner`),
      lastReview: t(`${prefix}.governance.lastReview`),
      empty: t(`${prefix}.governance.empty`),
      pendingApproval: t(`${prefix}.governance.pendingApproval`),
      underReview: t(`${prefix}.governance.underReview`),
    },
    performance: {
      successRate: t(`${prefix}.performance.successRate`),
      usage: t(`${prefix}.performance.usage`),
      satisfaction: t(`${prefix}.performance.satisfaction`),
      actionsPerWeek: t(`${prefix}.performance.actionsPerWeek`),
      empty: t(`${prefix}.performance.empty`),
    },
    reasons: {
      executive_visibility: t(`${prefix}.reasons.executiveVisibility`),
      support_efficiency: t(`${prefix}.reasons.supportEfficiency`),
      commerce_margins: t(`${prefix}.reasons.commerceMargins`),
      knowledge_retention: t(`${prefix}.reasons.knowledgeRetention`),
      growth_expansion: t(`${prefix}.reasons.growthExpansion`),
      automation_efficiency: t(`${prefix}.reasons.automationEfficiency`),
      companion_productivity: t(`${prefix}.reasons.companionProductivity`),
      compliance_confidence: t(`${prefix}.reasons.complianceConfidence`),
      operations_efficiency: t(`${prefix}.reasons.operationsEfficiency`),
    },
    impacts: {
      executive_impact: t(`${prefix}.impacts.executiveImpact`),
      support_impact: t(`${prefix}.impacts.supportImpact`),
      commerce_impact: t(`${prefix}.impacts.commerceImpact`),
      knowledge_impact: t(`${prefix}.impacts.knowledgeImpact`),
      growth_impact: t(`${prefix}.impacts.growthImpact`),
      automation_impact: t(`${prefix}.impacts.automationImpact`),
      companion_impact: t(`${prefix}.impacts.companionImpact`),
      compliance_impact: t(`${prefix}.impacts.complianceImpact`),
      operations_impact: t(`${prefix}.impacts.operationsImpact`),
    },
    detail: {
      overview: t(`${prefix}.detail.overview`),
      capabilities: t(`${prefix}.detail.capabilities`),
      permissions: t(`${prefix}.detail.permissions`),
      audit: t(`${prefix}.detail.audit`),
      performance: t(`${prefix}.detail.performance`),
      deployment: t(`${prefix}.detail.deployment`),
      faq: t(`${prefix}.detail.faq`),
      controls: t(`${prefix}.detail.controls`),
      back: t(`${prefix}.detail.back`),
      notFound: t(`${prefix}.detail.notFound`),
      install: t(`${prefix}.detail.install`),
      installWithApproval: t(`${prefix}.detail.installWithApproval`),
      disable: t(`${prefix}.detail.disable`),
      noPermissions: t(`${prefix}.detail.noPermissions`),
      noAudit: t(`${prefix}.detail.noAudit`),
    },
  };
}
