import type { ScenarioPlanningLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildScenarioPlanningLabels(t: Translator): ScenarioPlanningLabels {
  const p = "customerApp.portalStructure.scenarioPlanning";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    isolationNote: t(`${p}.isolationNote`),
    simulationLabLink: t(`${p}.simulationLabLink`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      scenarioType: t(`${p}.filters.scenarioType`),
      planningStatus: t(`${p}.filters.planningStatus`),
      timeHorizon: t(`${p}.filters.timeHorizon`),
      organizationalArea: t(`${p}.filters.organizationalArea`),
      timePeriod: t(`${p}.filters.timePeriod`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      planningSummary: t(`${p}.dashboard.planningSummary`),
      executiveSummary: t(`${p}.dashboard.executiveSummary`),
      strategicPriorities: t(`${p}.dashboard.strategicPriorities`),
      riskScenarios: t(`${p}.dashboard.riskScenarios`),
      scenarios: t(`${p}.dashboard.scenarios`),
      comparisons: t(`${p}.dashboard.comparisons`),
      recommendations: t(`${p}.dashboard.recommendations`),
      timeline: t(`${p}.dashboard.timeline`),
      viewScenario: t(`${p}.dashboard.viewScenario`),
      runSimulation: t(`${p}.dashboard.runSimulation`),
      compareScenarios: t(`${p}.dashboard.compareScenarios`),
      markReviewed: t(`${p}.dashboard.markReviewed`),
    },
    card: {
      category: t(`${p}.card.category`),
      scenarioType: t(`${p}.card.scenarioType`),
      planningStatus: t(`${p}.card.planningStatus`),
      timeHorizon: t(`${p}.card.timeHorizon`),
      lastSimulated: t(`${p}.card.lastSimulated`),
      assumptions: t(`${p}.card.assumptions`),
      variables: t(`${p}.card.variables`),
      projectedOutcomes: t(`${p}.card.projectedOutcomes`),
    },
    detail: {
      back: t(`${p}.detail.back`),
      simulations: t(`${p}.detail.simulations`),
      outcomeSummary: t(`${p}.detail.outcomeSummary`),
      riskNotes: t(`${p}.detail.riskNotes`),
      opportunityNotes: t(`${p}.detail.opportunityNotes`),
      reviewNotes: t(`${p}.detail.reviewNotes`),
      submitReview: t(`${p}.detail.submitReview`),
      reviewSuccess: t(`${p}.detail.reviewSuccess`),
      simulateSuccess: t(`${p}.detail.simulateSuccess`),
      isolationNote: t(`${p}.detail.isolationNote`),
    },
    initialize: {
      success: t(`${p}.initialize.success`),
      governanceNote: t(`${p}.initialize.governanceNote`),
    },
    categories: {
      strategic: t(`${p}.categories.strategic`),
      operational: t(`${p}.categories.operational`),
      capacity: t(`${p}.categories.capacity`),
      market: t(`${p}.categories.market`),
      governance: t(`${p}.categories.governance`),
      risk: t(`${p}.categories.risk`),
    },
    scenarioTypes: {
      best_case: t(`${p}.scenarioTypes.bestCase`),
      expected: t(`${p}.scenarioTypes.expected`),
      challenging: t(`${p}.scenarioTypes.challenging`),
      custom: t(`${p}.scenarioTypes.custom`),
    },
    planningStatuses: {
      draft: t(`${p}.planningStatuses.draft`),
      active: t(`${p}.planningStatuses.active`),
      simulated: t(`${p}.planningStatuses.simulated`),
      reviewed: t(`${p}.planningStatuses.reviewed`),
      archived: t(`${p}.planningStatuses.archived`),
    },
    timeHorizons: {
      next_30_days: t(`${p}.timeHorizons.next30Days`),
      next_quarter: t(`${p}.timeHorizons.nextQuarter`),
      next_6_months: t(`${p}.timeHorizons.next6Months`),
      next_12_months: t(`${p}.timeHorizons.next12Months`),
    },
    recommendations: {
      rehearseChallengingScenarios: t(`${p}.recommendations.rehearseChallengingScenarios`),
      reviewCapacityScenarios: t(`${p}.recommendations.reviewCapacityScenarios`),
      scheduleExecutiveScenarioReview: t(`${p}.recommendations.scheduleExecutiveScenarioReview`),
      compareBestExpectedChallenging: t(`${p}.recommendations.compareBestExpectedChallenging`),
      crossLinkSimulationLab: t(`${p}.recommendations.crossLinkSimulationLab`),
    },
    timelineEvents: {
      scenarios_initialized: t(`${p}.timelineEvents.scenariosInitialized`),
      scenarios_refreshed: t(`${p}.timelineEvents.scenariosRefreshed`),
      simulation_completed: t(`${p}.timelineEvents.simulationCompleted`),
      scenarios_compared: t(`${p}.timelineEvents.scenariosCompared`),
      scenario_reviewed: t(`${p}.timelineEvents.scenarioReviewed`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      executesActions: t(`${p}.faq.executesActions`),
      executesActionsAnswer: t(`${p}.faq.executesActionsAnswer`),
      whoCanAccess: t(`${p}.faq.whoCanAccess`),
      whoCanAccessAnswer: t(`${p}.faq.whoCanAccessAnswer`),
    },
  };
}
