import type { CrossFunctionalIntelligenceLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildCFILabels(t: Translator): CrossFunctionalIntelligenceLabels {
  const p = "customerApp.portalStructure.crossFunctionalIntelligence";
  return {
    title:        t(`${p}.title`),
    subtitle:     t(`${p}.subtitle`),
    loading:      t(`${p}.loading`),
    principle:    t(`${p}.principle`),
    advisoryNote: t(`${p}.advisoryNote`),
    emptyTitle:   t(`${p}.emptyTitle`),
    emptyBody:    t(`${p}.emptyBody`),
    emptyCta:     t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search:         t(`${p}.filters.search`),
      department:     t(`${p}.filters.department`),
      team:           t(`${p}.filters.team`),
      dependencyType: t(`${p}.filters.dependencyType`),
      riskLevel:      t(`${p}.filters.riskLevel`),
      priority:       t(`${p}.filters.priority`),
      reviewStatus:   t(`${p}.filters.reviewStatus`),
      all:            t(`${p}.filters.all`),
    },
    dashboard: {
      healthScore:             t(`${p}.dashboard.healthScore`),
      collaborationScore:      t(`${p}.dashboard.collaborationScore`),
      dependencyScore:         t(`${p}.dashboard.dependencyScore`),
      processAlignmentScore:   t(`${p}.dashboard.processAlignmentScore`),
      executiveSummary:        t(`${p}.dashboard.executiveSummary`),
      areasRequiringAttention: t(`${p}.dashboard.areasRequiringAttention`),
      improvementOpportunities:t(`${p}.dashboard.improvementOpportunities`),
      dependencyMap:           t(`${p}.dashboard.dependencyMap`),
      collaborationInsights:   t(`${p}.dashboard.collaborationInsights`),
      frictionView:            t(`${p}.dashboard.frictionView`),
      heatmap:                 t(`${p}.dashboard.heatmap`),
      recommendations:         t(`${p}.dashboard.recommendations`),
      timeline:                t(`${p}.dashboard.timeline`),
      reviewQuestions:         t(`${p}.dashboard.reviewQuestions`),
      beginReview:             t(`${p}.dashboard.beginReview`),
    },
    dependency: {
      from:              t(`${p}.dependency.from`),
      to:                t(`${p}.dependency.to`),
      type:              t(`${p}.dependency.type`),
      strength:          t(`${p}.dependency.strength`),
      riskLevel:         t(`${p}.dependency.riskLevel`),
      owner:             t(`${p}.dependency.owner`),
      recommendedReview: t(`${p}.dependency.recommendedReview`),
    },
    collaboration: {
      departments: t(`${p}.collaboration.departments`),
      category:    t(`${p}.collaboration.category`),
      type:        t(`${p}.collaboration.type`),
      healthStatus:t(`${p}.collaboration.healthStatus`),
      opportunity: t(`${p}.collaboration.opportunity`),
      priority:    t(`${p}.collaboration.priority`),
    },
    friction: {
      type:               t(`${p}.friction.type`),
      severity:           t(`${p}.friction.severity`),
      affectedDepartments:t(`${p}.friction.affectedDepartments`),
      recommendedAction:  t(`${p}.friction.recommendedAction`),
      status:             t(`${p}.friction.status`),
    },
    heatmapLegend: {
      healthy:        t(`${p}.heatmapLegend.healthy`),
      stable:         t(`${p}.heatmapLegend.stable`),
      needsAttention: t(`${p}.heatmapLegend.needsAttention`),
      highPriority:   t(`${p}.heatmapLegend.highPriority`),
    },
    detail: {
      reviewNotes:   t(`${p}.detail.reviewNotes`),
      submitReview:  t(`${p}.detail.submitReview`),
      reviewSuccess: t(`${p}.detail.reviewSuccess`),
      advisoryNote:  t(`${p}.detail.advisoryNote`),
    },
    beginReview: { success: t(`${p}.beginReview.success`) },
    categories: {
      leadership_collaboration:   t(`${p}.categories.leadershipCollaboration`),
      operations_alignment:       t(`${p}.categories.operationsAlignment`),
      customer_journey_alignment: t(`${p}.categories.customerJourneyAlignment`),
      sales_support_alignment:    t(`${p}.categories.salesSupportAlignment`),
      product_customer_alignment: t(`${p}.categories.productCustomerAlignment`),
      workforce_collaboration:    t(`${p}.categories.workforceCollaboration`),
      knowledge_sharing:          t(`${p}.categories.knowledgeSharing`),
      process_coordination:       t(`${p}.categories.processCoordination`),
      communication_efficiency:   t(`${p}.categories.communicationEfficiency`),
      organizational_dependencies:t(`${p}.categories.organizationalDependencies`),
    },
    dependencyTypes: {
      operational:    t(`${p}.dependencyTypes.operational`),
      informational:  t(`${p}.dependencyTypes.informational`),
      approval:       t(`${p}.dependencyTypes.approval`),
      resource:       t(`${p}.dependencyTypes.resource`),
      knowledge:      t(`${p}.dependencyTypes.knowledge`),
      process:        t(`${p}.dependencyTypes.process`),
      communication:  t(`${p}.dependencyTypes.communication`),
    },
    dependencyStrengths: {
      low: t(`${p}.dependencyStrengths.low`), moderate: t(`${p}.dependencyStrengths.moderate`),
      high: t(`${p}.dependencyStrengths.high`), critical: t(`${p}.dependencyStrengths.critical`),
    },
    riskLevels: {
      low: t(`${p}.riskLevels.low`), moderate: t(`${p}.riskLevels.moderate`),
      high: t(`${p}.riskLevels.high`), critical: t(`${p}.riskLevels.critical`),
    },
    collaborationTypes: {
      strong:   t(`${p}.collaborationTypes.strong`),
      emerging: t(`${p}.collaborationTypes.emerging`),
      weak:     t(`${p}.collaborationTypes.weak`),
      gap:      t(`${p}.collaborationTypes.gap`),
    },
    healthStatuses: {
      healthy:         t(`${p}.healthStatuses.healthy`),
      stable:          t(`${p}.healthStatuses.stable`),
      needs_attention: t(`${p}.healthStatuses.needsAttention`),
      high_priority:   t(`${p}.healthStatuses.highPriority`),
    },
    frictionTypes: {
      bottleneck:              t(`${p}.frictionTypes.bottleneck`),
      delayed_workflow:        t(`${p}.frictionTypes.delayedWorkflow`),
      repeated_escalation:     t(`${p}.frictionTypes.repeatedEscalation`),
      duplicate_effort:        t(`${p}.frictionTypes.duplicateEffort`),
      knowledge_silo:          t(`${p}.frictionTypes.knowledgeSilo`),
      coordination_challenge:  t(`${p}.frictionTypes.coordinationChallenge`),
    },
    frictionSeverities: {
      low: t(`${p}.frictionSeverities.low`), moderate: t(`${p}.frictionSeverities.moderate`),
      high: t(`${p}.frictionSeverities.high`), critical: t(`${p}.frictionSeverities.critical`),
    },
    priorities: {
      low: t(`${p}.priorities.low`), moderate: t(`${p}.priorities.moderate`),
      high: t(`${p}.priorities.high`), critical: t(`${p}.priorities.critical`),
    },
    reviewStatuses: {
      pending: t(`${p}.reviewStatuses.pending`), in_review: t(`${p}.reviewStatuses.inReview`),
      reviewed: t(`${p}.reviewStatuses.reviewed`), needs_follow_up: t(`${p}.reviewStatuses.needsFollowUp`),
    },
    recommendations: {
      improveInformationSharing:      t(`${p}.recommendations.improveInformationSharing`),
      clarifyOwnershipResponsibilities: t(`${p}.recommendations.clarifyOwnershipResponsibilities`),
      establishCrossFunctionalReviews:t(`${p}.recommendations.establishCrossFunctionalReviews`),
      reduceProcessDuplication:       t(`${p}.recommendations.reduceProcessDuplication`),
      improveCommunicationChannels:   t(`${p}.recommendations.improveCommunicationChannels`),
      strengthenCollaborationRoutines:t(`${p}.recommendations.strengthenCollaborationRoutines`),
    },
    timelineEvents: {
      cfi_initialized:           t(`${p}.timelineEvents.cfiInitialized`),
      collaboration_review_begun:t(`${p}.timelineEvents.collaborationReviewBegun`),
      cfi_review_completed:      t(`${p}.timelineEvents.reviewCompleted`),
      dependency_change:         t(`${p}.timelineEvents.dependencyChange`),
      improvement_launched:      t(`${p}.timelineEvents.improvementLaunched`),
      lesson_learned:            t(`${p}.timelineEvents.lessonLearned`),
    },
    reviewQuestions: [
      t(`${p}.reviewQuestions.teamsDependOn`),
      t(`${p}.reviewQuestions.whereDelaysOriginate`),
      t(`${p}.reviewQuestions.crossDeptProcesses`),
      t(`${p}.reviewQuestions.communicationGaps`),
      t(`${p}.reviewQuestions.shouldCollaborateMore`),
      t(`${p}.reviewQuestions.dependenciesCreateRisk`),
    ],
    faq: {
      title:                 t(`${p}.faq.title`),
      whatIs:                t(`${p}.faq.whatIs`),
      whatIsAnswer:          t(`${p}.faq.whatIsAnswer`),
      whyImportant:          t(`${p}.faq.whyImportant`),
      whyImportantAnswer:    t(`${p}.faq.whyImportantAnswer`),
      whoShouldUse:          t(`${p}.faq.whoShouldUse`),
      whoShouldUseAnswer:    t(`${p}.faq.whoShouldUseAnswer`),
    },
  };
}
