import type { Translator } from "@/lib/i18n/translate";

export function buildCorporateMemoryLabels(t: Translator) {
  const p = "customerApp.corporateMemory";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    philosophy: t(`${p}.philosophy`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    articles: t(`${p}.articles`),
    documents: t(`${p}.documents`),
    policies: t(`${p}.policies`),
    procedures: t(`${p}.procedures`),
    playbooks: t(`${p}.playbooks`),
    templates: t(`${p}.templates`),
    corporateMemory: t(`${p}.corporateMemory`),
    search: t(`${p}.search`),
    reports: t(`${p}.reports`),
    publishedArticles: t(`${p}.publishedArticles`),
    publishedDocuments: t(`${p}.publishedDocuments`),
    playbookCount: t(`${p}.playbookCount`),
    memoryItems: t(`${p}.memoryItems`),
    pendingContributions: t(`${p}.pendingContributions`),
    pendingReviews: t(`${p}.pendingReviews`),
    templateCount: t(`${p}.templateCount`),
    searchPlaceholder: t(`${p}.searchPlaceholder`),
    createPlaybook: t(`${p}.createPlaybook`),
    playbookTitle: t(`${p}.playbookTitle`),
    submitContribution: t(`${p}.submitContribution`),
    contributionTitle: t(`${p}.contributionTitle`),
    approveContribution: t(`${p}.approveContribution`),
    rejectContribution: t(`${p}.rejectContribution`),
    publishPlaybook: t(`${p}.publishPlaybook`),
    createMemory: t(`${p}.createMemory`),
    memoryTitle: t(`${p}.memoryTitle`),
    noArticles: t(`${p}.noArticles`),
    noDocuments: t(`${p}.noDocuments`),
    noPlaybooks: t(`${p}.noPlaybooks`),
    noMemory: t(`${p}.noMemory`),
    emptyHint: t(`${p}.emptyHint`),
    viewDocuments: t(`${p}.viewDocuments`),
    knowledgeUsage: t(`${p}.knowledgeUsage`),
    documentViews: t(`${p}.documentViews`),
    missingKnowledge: t(`${p}.missingKnowledge`),
    companionSearches: t(`${p}.companionSearches`),
    auditLog: t(`${p}.auditLog`),
    status: t(`${p}.status`),
    mobileReady: t(`${p}.mobileReady`),
  };
}

export type CorporateMemoryLabels = ReturnType<typeof buildCorporateMemoryLabels>;
