import type { PackRecommendationLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildPackRecommendationLabels(t: Translator): PackRecommendationLabels {
  const p = "customerApp.portalStructure.businessPackRecommendations";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      industry: t(`${p}.filters.industry`),
      category: t(`${p}.filters.category`),
      complexity: t(`${p}.filters.complexity`),
      businessImpact: t(`${p}.filters.businessImpact`),
      confidenceLevel: t(`${p}.filters.confidenceLevel`),
      installedStatus: t(`${p}.filters.installedStatus`),
      all: t(`${p}.filters.all`),
      installed: t(`${p}.filters.installed`),
      notInstalled: t(`${p}.filters.notInstalled`),
    },
    dashboard: {
      recommendedPacks: t(`${p}.dashboard.recommendedPacks`),
      installedPacks: t(`${p}.dashboard.installedPacks`),
      savedRecommendations: t(`${p}.dashboard.savedRecommendations`),
      recentlyViewed: t(`${p}.dashboard.recentlyViewed`),
      operationalCategories: t(`${p}.dashboard.operationalCategories`),
      comparePacks: t(`${p}.dashboard.comparePacks`),
    },
    card: {
      confidenceScore: t(`${p}.card.confidenceScore`),
      reason: t(`${p}.card.reason`),
      benefits: t(`${p}.card.benefits`),
      complexity: t(`${p}.card.complexity`),
      suggestedUsers: t(`${p}.card.suggestedUsers`),
      relatedPacks: t(`${p}.card.relatedPacks`),
      learnMore: t(`${p}.card.learnMore`),
      saveRecommendation: t(`${p}.card.saveRecommendation`),
      dismiss: t(`${p}.card.dismiss`),
      saved: t(`${p}.card.saved`),
    },
    compare: {
      title: t(`${p}.compare.title`),
      features: t(`${p}.compare.features`),
      benefits: t(`${p}.compare.benefits`),
      complexity: t(`${p}.compare.complexity`),
      impact: t(`${p}.compare.impact`),
      audience: t(`${p}.compare.audience`),
      related: t(`${p}.compare.related`),
      runCompare: t(`${p}.compare.runCompare`),
      selectTwo: t(`${p}.compare.selectTwo`),
    },
    categories: {
      operational: t(`${p}.categories.operational`),
      security: t(`${p}.categories.security`),
      efficiency: t(`${p}.categories.efficiency`),
      customer_success: t(`${p}.categories.customerSuccess`),
      executive: t(`${p}.categories.executive`),
      industry_based: t(`${p}.categories.industryBased`),
      role_based: t(`${p}.categories.roleBased`),
      maturity_based: t(`${p}.categories.maturityBased`),
    },
    confidenceLevels: {
      exploratory: t(`${p}.confidenceLevels.exploratory`),
      suggested: t(`${p}.confidenceLevels.suggested`),
      strong_match: t(`${p}.confidenceLevels.strongMatch`),
      highly_relevant: t(`${p}.confidenceLevels.highlyRelevant`),
    },
    complexityLevels: {
      simple: t(`${p}.complexityLevels.simple`),
      moderate: t(`${p}.complexityLevels.moderate`),
      advanced: t(`${p}.complexityLevels.advanced`),
    },
    impactLevels: {
      incremental_improvement: t(`${p}.impactLevels.incrementalImprovement`),
      meaningful_improvement: t(`${p}.impactLevels.meaningfulImprovement`),
      high_business_impact: t(`${p}.impactLevels.highBusinessImpact`),
      strategic_transformation: t(`${p}.impactLevels.strategicTransformation`),
    },
    reasons: {
      similarOrganizationsInstall: t(`${p}.reasons.similarOrganizationsInstall`),
      complementsExisting: t(`${p}.reasons.complementsExisting`),
      maturityReadiness: t(`${p}.reasons.maturityReadiness`),
      securityPostureBenefit: t(`${p}.reasons.securityPostureBenefit`),
      teamsSimilarNeeds: t(`${p}.reasons.teamsSimilarNeeds`),
      operationalMaturity: t(`${p}.reasons.operationalMaturity`),
    },
    benefits: {
      hostsBenefits: t(`${p}.benefits.hostsBenefits`),
      governanceBenefits: t(`${p}.benefits.governanceBenefits`),
      commerceBenefits: t(`${p}.benefits.commerceBenefits`),
      supportBenefits: t(`${p}.benefits.supportBenefits`),
      executiveBenefits: t(`${p}.benefits.executiveBenefits`),
      analyticsBenefits: t(`${p}.benefits.analyticsBenefits`),
      workflowsBenefits: t(`${p}.benefits.workflowsBenefits`),
    },
    aipifySuggestions: {
      considerAipifyHosts: t(`${p}.aipifySuggestions.considerAipifyHosts`),
      exploreGovernance: t(`${p}.aipifySuggestions.exploreGovernance`),
      reviewCommerceIntelligence: t(`${p}.aipifySuggestions.reviewCommerceIntelligence`),
      strengthenSupport: t(`${p}.aipifySuggestions.strengthenSupport`),
      expandExecutiveIntelligence: t(`${p}.aipifySuggestions.expandExecutiveIntelligence`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      autoInstall: t(`${p}.faq.autoInstall`),
      autoInstallAnswer: t(`${p}.faq.autoInstallAnswer`),
      whyChange: t(`${p}.faq.whyChange`),
      whyChangeAnswer: t(`${p}.faq.whyChangeAnswer`),
    },
  };
}
