import type { PackValueLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildPackValueLabels(t: Translator): PackValueLabels {
  const p = "customerApp.portalStructure.businessPackValue";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      packKey: t(`${p}.filters.packKey`),
      valueCategory: t(`${p}.filters.valueCategory`),
      department: t(`${p}.filters.department`),
      periodFrom: t(`${p}.filters.periodFrom`),
      roiIndicator: t(`${p}.filters.roiIndicator`),
      adoptionStatus: t(`${p}.filters.adoptionStatus`),
      all: t(`${p}.filters.all`),
      lowAdoption: t(`${p}.filters.lowAdoption`),
      healthyAdoption: t(`${p}.filters.healthyAdoption`),
      highAdoption: t(`${p}.filters.highAdoption`),
    },
    dashboard: {
      totalEstimatedValue: t(`${p}.dashboard.totalEstimatedValue`),
      totalTimeSaved: t(`${p}.dashboard.totalTimeSaved`),
      highestValuePacks: t(`${p}.dashboard.highestValuePacks`),
      valueTrends: t(`${p}.dashboard.valueTrends`),
      realizedVsPotential: t(`${p}.dashboard.realizedVsPotential`),
      recommendedActions: t(`${p}.dashboard.recommendedActions`),
      executiveSummary: t(`${p}.dashboard.executiveSummary`),
      installedPacks: t(`${p}.dashboard.installedPacks`),
      valueTimeline: t(`${p}.dashboard.valueTimeline`),
      executiveReport: t(`${p}.dashboard.executiveReport`),
      exportReport: t(`${p}.dashboard.exportReport`),
    },
    card: {
      estimatedValue: t(`${p}.card.estimatedValue`),
      timeSaved: t(`${p}.card.timeSaved`),
      adoptionScore: t(`${p}.card.adoptionScore`),
      utilizationRate: t(`${p}.card.utilizationRate`),
      valueTrend: t(`${p}.card.valueTrend`),
      roiIndicator: t(`${p}.card.roiIndicator`),
      improvementOpportunities: t(`${p}.card.improvementOpportunities`),
      executiveSummary: t(`${p}.card.executiveSummary`),
      viewDetails: t(`${p}.card.viewDetails`),
      keyWins: t(`${p}.card.keyWins`),
      strategicObservations: t(`${p}.card.strategicObservations`),
    },
    export: {
      pdf: t(`${p}.export.pdf`),
      excel: t(`${p}.export.excel`),
      csv: t(`${p}.export.csv`),
      exporting: t(`${p}.export.exporting`),
      success: t(`${p}.export.success`),
      estimateNote: t(`${p}.export.estimateNote`),
    },
    categories: {
      productivity_value: t(`${p}.categories.productivityValue`),
      operational_efficiency: t(`${p}.categories.operationalEfficiency`),
      customer_experience: t(`${p}.categories.customerExperience`),
      revenue_enablement: t(`${p}.categories.revenueEnablement`),
      cost_reduction: t(`${p}.categories.costReduction`),
      risk_reduction: t(`${p}.categories.riskReduction`),
      employee_experience: t(`${p}.categories.employeeExperience`),
      strategic_value: t(`${p}.categories.strategicValue`),
    },
    roiIndicators: {
      emerging_value: t(`${p}.roiIndicators.emergingValue`),
      positive_roi: t(`${p}.roiIndicators.positiveRoi`),
      strong_roi: t(`${p}.roiIndicators.strongRoi`),
      strategic_roi_leader: t(`${p}.roiIndicators.strategicRoiLeader`),
    },
    valueTrends: {
      increasing: t(`${p}.valueTrends.increasing`),
      stable: t(`${p}.valueTrends.stable`),
      declining: t(`${p}.valueTrends.declining`),
      unrealized_opportunity: t(`${p}.valueTrends.unrealizedOpportunity`),
    },
    recommendations: {
      increaseAdoption: t(`${p}.recommendations.increaseAdoption`),
      completeTraining: t(`${p}.recommendations.completeTraining`),
      expandImplementations: t(`${p}.recommendations.expandImplementations`),
      reviewUnrealized: t(`${p}.recommendations.reviewUnrealized`),
      scheduleValueReview: t(`${p}.recommendations.scheduleValueReview`),
      recognizeHighPerforming: t(`${p}.recommendations.recognizeHighPerforming`),
    },
    timelineEvents: {
      adoption_milestone: t(`${p}.timelineEvents.adoptionMilestone`),
      value_milestone: t(`${p}.timelineEvents.valueMilestone`),
      improvement_achieved: t(`${p}.timelineEvents.improvementAchieved`),
      optimization_completed: t(`${p}.timelineEvents.optimizationCompleted`),
      strategic_achievement: t(`${p}.timelineEvents.strategicAchievement`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      exactRoi: t(`${p}.faq.exactRoi`),
      exactRoiAnswer: t(`${p}.faq.exactRoiAnswer`),
      whyImportant: t(`${p}.faq.whyImportant`),
      whyImportantAnswer: t(`${p}.faq.whyImportantAnswer`),
    },
  };
}
