import type { ExecutivePortfolioLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildExecutivePortfolioLabels(t: Translator): ExecutivePortfolioLabels {
  const p = "customerApp.portalStructure.businessPackExecutivePortfolio";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      portfolioStatus: t(`${p}.filters.portfolioStatus`),
      packKey: t(`${p}.filters.packKey`),
      maturityLevel: t(`${p}.filters.maturityLevel`),
      executiveSponsor: t(`${p}.filters.executiveSponsor`),
      priorityLevel: t(`${p}.filters.priorityLevel`),
      reviewPeriod: t(`${p}.filters.reviewPeriod`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      portfolioHealthScore: t(`${p}.dashboard.portfolioHealthScore`),
      totalInstalled: t(`${p}.dashboard.totalInstalled`),
      totalActive: t(`${p}.dashboard.totalActive`),
      totalValueRealized: t(`${p}.dashboard.totalValueRealized`),
      packsRequiringAttention: t(`${p}.dashboard.packsRequiringAttention`),
      portfolioGrowthTrend: t(`${p}.dashboard.portfolioGrowthTrend`),
      executiveSummary: t(`${p}.dashboard.executiveSummary`),
      portfolioOverview: t(`${p}.dashboard.portfolioOverview`),
      portfolioInsights: t(`${p}.dashboard.portfolioInsights`),
      recommendedActions: t(`${p}.dashboard.recommendedActions`),
      timeline: t(`${p}.dashboard.timeline`),
      healthOverview: t(`${p}.dashboard.healthOverview`),
      maturityLevel: t(`${p}.dashboard.maturityLevel`),
    },
    overview: {
      installedPacks: t(`${p}.overview.installedPacks`),
      adoptionOverview: t(`${p}.overview.adoptionOverview`),
      governanceOverview: t(`${p}.overview.governanceOverview`),
      complianceOverview: t(`${p}.overview.complianceOverview`),
      valueOverview: t(`${p}.overview.valueOverview`),
      lifecycleOverview: t(`${p}.overview.lifecycleOverview`),
      ecosystemOverview: t(`${p}.overview.ecosystemOverview`),
    },
    card: {
      portfolioStatus: t(`${p}.card.portfolioStatus`),
      adoptionScore: t(`${p}.card.adoptionScore`),
      valueScore: t(`${p}.card.valueScore`),
      governanceScore: t(`${p}.card.governanceScore`),
      complianceStatus: t(`${p}.card.complianceStatus`),
      lifecycleStage: t(`${p}.card.lifecycleStage`),
      executiveSponsor: t(`${p}.card.executiveSponsor`),
      recommendedAction: t(`${p}.card.recommendedAction`),
      viewDetails: t(`${p}.card.viewDetails`),
      completeReview: t(`${p}.card.completeReview`),
    },
    review: {
      title: t(`${p}.review.title`),
      notes: t(`${p}.review.notes`),
      reviewType: t(`${p}.review.reviewType`),
      reviewOutcome: t(`${p}.review.reviewOutcome`),
      submit: t(`${p}.review.submit`),
      success: t(`${p}.review.success`),
      governanceNote: t(`${p}.review.governanceNote`),
    },
    portfolioStatuses: {
      high_performing: t(`${p}.portfolioStatuses.highPerforming`),
      healthy: t(`${p}.portfolioStatuses.healthy`),
      stable: t(`${p}.portfolioStatuses.stable`),
      requires_optimization: t(`${p}.portfolioStatuses.requiresOptimization`),
      executive_attention_required: t(`${p}.portfolioStatuses.executiveAttentionRequired`),
    },
    maturityLevels: {
      emerging_portfolio: t(`${p}.maturityLevels.emergingPortfolio`),
      developing_portfolio: t(`${p}.maturityLevels.developingPortfolio`),
      mature_portfolio: t(`${p}.maturityLevels.maturePortfolio`),
      strategic_portfolio: t(`${p}.maturityLevels.strategicPortfolio`),
      transformational_portfolio: t(`${p}.maturityLevels.transformationalPortfolio`),
    },
    priorityLevels: {
      informational: t(`${p}.priorityLevels.informational`),
      opportunity: t(`${p}.priorityLevels.opportunity`),
      important: t(`${p}.priorityLevels.important`),
      executive_attention_required: t(`${p}.priorityLevels.executiveAttentionRequired`),
    },
    reviewTypes: {
      quarterly_executive: t(`${p}.reviewTypes.quarterlyExecutive`),
      semi_annual: t(`${p}.reviewTypes.semiAnnual`),
      annual_portfolio: t(`${p}.reviewTypes.annualPortfolio`),
      ad_hoc: t(`${p}.reviewTypes.adHoc`),
    },
    reviewOutcomes: {
      continue_investment: t(`${p}.reviewOutcomes.continueInvestment`),
      optimize_investment: t(`${p}.reviewOutcomes.optimizeInvestment`),
      expand_investment: t(`${p}.reviewOutcomes.expandInvestment`),
      retire_capability: t(`${p}.reviewOutcomes.retireCapability`),
      further_investigation_required: t(`${p}.reviewOutcomes.furtherInvestigationRequired`),
    },
    growthTrends: {
      growing: t(`${p}.growthTrends.growing`),
      stable: t(`${p}.growthTrends.stable`),
      emerging: t(`${p}.growthTrends.emerging`),
    },
    recommendations: {
      expandSuccessfulPacks: t(`${p}.recommendations.expandSuccessfulPacks`),
      scheduleExecutiveReviews: t(`${p}.recommendations.scheduleExecutiveReviews`),
      strengthenGovernance: t(`${p}.recommendations.strengthenGovernance`),
      reviewUnderperforming: t(`${p}.recommendations.reviewUnderperforming`),
      celebratePortfolioSuccess: t(`${p}.recommendations.celebratePortfolioSuccess`),
      prioritizeOptimization: t(`${p}.recommendations.prioritizeOptimization`),
    },
    insights: {
      highestPerforming: t(`${p}.insights.highestPerforming`),
      underutilized: t(`${p}.insights.underutilized`),
      strongestRoi: t(`${p}.insights.strongestRoi`),
      governanceAttention: t(`${p}.insights.governanceAttention`),
      optimizationOpportunities: t(`${p}.insights.optimizationOpportunities`),
      maturityObservations: t(`${p}.insights.maturityObservations`),
    },
    timelineEvents: {
      pack_introduced: t(`${p}.timelineEvents.packIntroduced`),
      portfolio_review_completed: t(`${p}.timelineEvents.portfolioReviewCompleted`),
      governance_improvement: t(`${p}.timelineEvents.governanceImprovement`),
      value_milestone: t(`${p}.timelineEvents.valueMilestone`),
      strategic_decision: t(`${p}.timelineEvents.strategicDecision`),
      executive_action: t(`${p}.timelineEvents.executiveAction`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      investmentDecisions: t(`${p}.faq.investmentDecisions`),
      investmentDecisionsAnswer: t(`${p}.faq.investmentDecisionsAnswer`),
      whyOversight: t(`${p}.faq.whyOversight`),
      whyOversightAnswer: t(`${p}.faq.whyOversightAnswer`),
    },
  };
}
