import type { PlaybooksLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildPlaybooksLabels(t: Translator): PlaybooksLabels {
  const p = "customerApp.portalStructure.playbooks";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      status: t(`${p}.filters.status`),
      owner: t(`${p}.filters.owner`),
      recentlyUpdated: t(`${p}.filters.recentlyUpdated`),
      relatedModule: t(`${p}.filters.relatedModule`),
      all: t(`${p}.filters.all`),
      yes: t(`${p}.filters.yes`),
      no: t(`${p}.filters.no`),
    },
    dashboard: {
      active: t(`${p}.dashboard.active`),
      draft: t(`${p}.dashboard.draft`),
      archived: t(`${p}.dashboard.archived`),
      needsReview: t(`${p}.dashboard.needsReview`),
      recent: t(`${p}.dashboard.recent`),
      mostAccessed: t(`${p}.dashboard.mostAccessed`),
    },
    form: {
      createTitle: t(`${p}.form.createTitle`),
      title: t(`${p}.form.title`),
      description: t(`${p}.form.description`),
      category: t(`${p}.form.category`),
      owner: t(`${p}.form.owner`),
      reviewFrequency: t(`${p}.form.reviewFrequency`),
      notes: t(`${p}.form.notes`),
      stepTitle: t(`${p}.form.stepTitle`),
      stepDescription: t(`${p}.form.stepDescription`),
      responsibleRole: t(`${p}.form.responsibleRole`),
      requiresApproval: t(`${p}.form.requiresApproval`),
      addStep: t(`${p}.form.addStep`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
    },
    card: {
      owner: t(`${p}.card.owner`),
      version: t(`${p}.card.version`),
      lastReviewed: t(`${p}.card.lastReviewed`),
      view: t(`${p}.card.view`),
      steps: t(`${p}.card.steps`),
    },
    detail: {
      overview: t(`${p}.detail.overview`),
      steps: t(`${p}.detail.steps`),
      versionHistory: t(`${p}.detail.versionHistory`),
      contributors: t(`${p}.detail.contributors`),
      relatedModules: t(`${p}.detail.relatedModules`),
      relatedArticles: t(`${p}.detail.relatedArticles`),
      activity: t(`${p}.detail.activity`),
      audit: t(`${p}.detail.audit`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
      recommendations: t(`${p}.detail.recommendations`),
      changeSummary: t(`${p}.detail.changeSummary`),
      checklist: t(`${p}.detail.checklist`),
      resources: t(`${p}.detail.resources`),
    },
    categories: {
      customer_support: t(`${p}.categories.customerSupport`),
      employee_onboarding: t(`${p}.categories.employeeOnboarding`),
      incident_response: t(`${p}.categories.incidentResponse`),
      security_procedures: t(`${p}.categories.securityProcedures`),
      billing_operations: t(`${p}.categories.billingOperations`),
      approval_processes: t(`${p}.categories.approvalProcesses`),
      business_pack_operations: t(`${p}.categories.businessPackOperations`),
      integration_management: t(`${p}.categories.integrationManagement`),
      executive_processes: t(`${p}.categories.executiveProcesses`),
      custom: t(`${p}.categories.custom`),
    },
    statuses: {
      draft: t(`${p}.statuses.draft`),
      active: t(`${p}.statuses.active`),
      under_review: t(`${p}.statuses.underReview`),
      archived: t(`${p}.statuses.archived`),
    },
    frequencies: {
      monthly: t(`${p}.frequencies.monthly`),
      quarterly: t(`${p}.frequencies.quarterly`),
      semi_annual: t(`${p}.frequencies.semiAnnual`),
      annual: t(`${p}.frequencies.annual`),
    },
    recommendations: {
      reviewOutdated: t(`${p}.recommendations.reviewOutdated`),
      addOwnership: t(`${p}.recommendations.addOwnership`),
      archiveUnused: t(`${p}.recommendations.archiveUnused`),
      createRecurring: t(`${p}.recommendations.createRecurring`),
      updateAfterChanges: t(`${p}.recommendations.updateAfterChanges`),
      activateDraft: t(`${p}.recommendations.activateDraft`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      versions: t(`${p}.faq.versions`),
      versionsAnswer: t(`${p}.faq.versionsAnswer`),
      autoCreate: t(`${p}.faq.autoCreate`),
      autoCreateAnswer: t(`${p}.faq.autoCreateAnswer`),
    },
  };
}
