import type { Translator } from "@/lib/i18n/translate";
import type { PlatformProviderOnboardingLabels } from "./panel-props";

/** Expandable Platform Admin copy for structured onboarding administration. */
export function buildPlatformProviderOnboardingLabels(t: Translator): PlatformProviderOnboardingLabels {
  const p = "platform.providerOnboarding";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    loadFailed: t(`${p}.loadFailed`),
    pageLoadFailed: t(`${p}.pageLoadFailed`),
    retry: t(`${p}.retry`),
    goBack: t(`${p}.goBack`),
    providers: t(`${p}.providers`),
    fixtures: t(`${p}.fixtures`),
    save: t(`${p}.save`),
    saved: t(`${p}.saved`),
    invalidContract: t(`${p}.invalidContract`),
    invalidContractBody: t(`${p}.invalidContractBody`),
    partialLoadWarning: t(`${p}.partialLoadWarning`),
    openContract: t(`${p}.openContract`),
    contactAdmin: t(`${p}.contactAdmin`),
    technicalReference: t(`${p}.technicalReference`),
    denied: t(`${p}.denied`),
    advancedEditor: t(`${p}.advancedEditor`),
    selectProvider: t(`${p}.selectProvider`),
    available: t(`${p}.available`),
    unavailable: t(`${p}.unavailable`),
    preview: t(`${p}.preview`),
    backHref: "/platform",
    searchPlaceholder: t(`${p}.searchPlaceholder`),
    filterAll: t(`${p}.filterAll`),
    filterAvailable: t(`${p}.filterAvailable`),
    filterReference: t(`${p}.filterReference`),
    filterNeedsContract: t(`${p}.filterNeedsContract`),
    filterInvalid: t(`${p}.filterInvalid`),
    tabOverview: t(`${p}.tabOverview`),
    tabEdit: t(`${p}.tabEdit`),
    tabPreview: t(`${p}.tabPreview`),
    tabAdvancedJson: t(`${p}.tabAdvancedJson`),
    editContract: t(`${p}.editContract`),
    previewInApp: t(`${p}.previewInApp`),
    validateContract: t(`${p}.validateContract`),
    viewHistory: t(`${p}.viewHistory`),
    advancedJsonWarning: t(`${p}.advancedJsonWarning`),
    formatJson: t(`${p}.formatJson`),
    copyJson: t(`${p}.copyJson`),
    resetJson: t(`${p}.resetJson`),
    unsavedChanges: t(`${p}.unsavedChanges`),
    cancel: t(`${p}.cancel`),
    createContract: t(`${p}.createContract`),
    contractMissing: t(`${p}.contractMissing`),
    contractMissingBody: t(`${p}.contractMissingBody`),
    referenceBadge: t(`${p}.referenceBadge`),
    referenceOnlyNotice: t(`${p}.referenceOnlyNotice`),
    previewPurpose: t(`${p}.previewPurpose`),
    previewDesktop: t(`${p}.previewDesktop`),
    previewMobile: t(`${p}.previewMobile`),
    previewLight: t(`${p}.previewLight`),
    previewDark: t(`${p}.previewDark`),
    showDetails: t(`${p}.showDetails`),
    validateContracts: t(`${p}.validateContracts`),
    openFirstIssue: t(`${p}.openFirstIssue`),
    issuesCount: t(`${p}.issuesCount`),
    providerKeySecondary: t(`${p}.providerKeySecondary`),
    lastUpdated: t(`${p}.lastUpdated`),
    sectionBasics: t(`${p}.sectionBasics`),
    sectionConnection: t(`${p}.sectionConnection`),
    sectionCapabilities: t(`${p}.sectionCapabilities`),
    sectionScopes: t(`${p}.sectionScopes`),
    sectionResponsibilities: t(`${p}.sectionResponsibilities`),
    sectionDocs: t(`${p}.sectionDocs`),
    sectionPolicies: t(`${p}.sectionPolicies`),
    validationPassed: t(`${p}.validationPassed`),
    validationFailed: t(`${p}.validationFailed`),
    dirtyIndicator: t(`${p}.dirtyIndicator`),
    openProviderList: t(`${p}.openProviderList`),
    closeProviderList: t(`${p}.closeProviderList`),
    status: {
      active: t(`${p}.status.active`),
      production_ready: t(`${p}.status.production_ready`),
      preview: t(`${p}.status.preview`),
      development: t(`${p}.status.development`),
      not_available_yet: t(`${p}.status.not_available_yet`),
      blocked: t(`${p}.status.blocked`),
      contract_required: t(`${p}.status.contract_required`),
      contract_invalid: t(`${p}.status.contract_invalid`),
      deprecated: t(`${p}.status.deprecated`),
      reference_only: t(`${p}.status.reference_only`),
    },
  };
}
