import type { ComplianceLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildComplianceLabels(t: Translator): ComplianceLabels {
  const p = "customerApp.portalStructure.compliance";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      status: t(`${p}.filters.status`),
      owner: t(`${p}.filters.owner`),
      audience: t(`${p}.filters.audience`),
      recentlyUpdated: t(`${p}.filters.recentlyUpdated`),
      all: t(`${p}.filters.all`),
      yes: t(`${p}.filters.yes`),
      no: t(`${p}.filters.no`),
    },
    dashboard: {
      active: t(`${p}.dashboard.active`),
      needsReview: t(`${p}.dashboard.needsReview`),
      outstandingAck: t(`${p}.dashboard.outstandingAck`),
      withoutOwner: t(`${p}.dashboard.withoutOwner`),
      recent: t(`${p}.dashboard.recent`),
      readiness: t(`${p}.dashboard.readiness`),
      readinessLabels: {
        building: t(`${p}.dashboard.readinessBuilding`),
        strong: t(`${p}.dashboard.readinessStrong`),
        moderate: t(`${p}.dashboard.readinessModerate`),
        needs_attention: t(`${p}.dashboard.readinessNeedsAttention`),
      },
    },
    form: {
      createTitle: t(`${p}.form.createTitle`),
      title: t(`${p}.form.title`),
      description: t(`${p}.form.description`),
      category: t(`${p}.form.category`),
      owner: t(`${p}.form.owner`),
      audience: t(`${p}.form.audience`),
      effectiveDate: t(`${p}.form.effectiveDate`),
      reviewDate: t(`${p}.form.reviewDate`),
      reviewFrequency: t(`${p}.form.reviewFrequency`),
      notes: t(`${p}.form.notes`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
    },
    card: {
      owner: t(`${p}.card.owner`),
      version: t(`${p}.card.version`),
      effectiveDate: t(`${p}.card.effectiveDate`),
      reviewDate: t(`${p}.card.reviewDate`),
      acknowledgement: t(`${p}.card.acknowledgement`),
      view: t(`${p}.card.view`),
    },
    detail: {
      overview: t(`${p}.detail.overview`),
      versionHistory: t(`${p}.detail.versionHistory`),
      contributors: t(`${p}.detail.contributors`),
      acknowledgements: t(`${p}.detail.acknowledgements`),
      acknowledge: t(`${p}.detail.acknowledge`),
      acknowledged: t(`${p}.detail.acknowledged`),
      activity: t(`${p}.detail.activity`),
      audit: t(`${p}.detail.audit`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
      recommendations: t(`${p}.detail.recommendations`),
      changeSummary: t(`${p}.detail.changeSummary`),
      completionRate: t(`${p}.detail.completionRate`),
      outstanding: t(`${p}.detail.outstanding`),
    },
    categories: {
      information_security: t(`${p}.categories.informationSecurity`),
      privacy_data_protection: t(`${p}.categories.privacyDataProtection`),
      employee_policies: t(`${p}.categories.employeePolicies`),
      acceptable_use: t(`${p}.categories.acceptableUse`),
      incident_response: t(`${p}.categories.incidentResponse`),
      vendor_management: t(`${p}.categories.vendorManagement`),
      financial_controls: t(`${p}.categories.financialControls`),
      business_continuity: t(`${p}.categories.businessContinuity`),
      operational_procedures: t(`${p}.categories.operationalProcedures`),
      custom: t(`${p}.categories.custom`),
    },
    statuses: {
      draft: t(`${p}.statuses.draft`),
      active: t(`${p}.statuses.active`),
      under_review: t(`${p}.statuses.underReview`),
      retired: t(`${p}.statuses.retired`),
    },
    audiences: {
      all_organization_members: t(`${p}.audiences.allMembers`),
      managers: t(`${p}.audiences.managers`),
      owners_admins: t(`${p}.audiences.ownersAdmins`),
      custom: t(`${p}.audiences.custom`),
    },
    frequencies: {
      monthly: t(`${p}.frequencies.monthly`),
      quarterly: t(`${p}.frequencies.quarterly`),
      semi_annual: t(`${p}.frequencies.semiAnnual`),
      annual: t(`${p}.frequencies.annual`),
    },
    recommendations: {
      reviewOverdue: t(`${p}.recommendations.reviewOverdue`),
      assignOwner: t(`${p}.recommendations.assignOwner`),
      updateOutdated: t(`${p}.recommendations.updateOutdated`),
      requestAcknowledgements: t(`${p}.recommendations.requestAcknowledgements`),
      archiveRetired: t(`${p}.recommendations.archiveRetired`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      legalAdvice: t(`${p}.faq.legalAdvice`),
      legalAdviceAnswer: t(`${p}.faq.legalAdviceAnswer`),
      acknowledgements: t(`${p}.faq.acknowledgements`),
      acknowledgementsAnswer: t(`${p}.faq.acknowledgementsAnswer`),
    },
  };
}
