import type { RisksLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildRisksLabels(t: Translator): RisksLabels {
  const p = "customerApp.portalStructure.risks";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      status: t(`${p}.filters.status`),
      owner: t(`${p}.filters.owner`),
      overallLevel: t(`${p}.filters.overallLevel`),
      recentlyUpdated: t(`${p}.filters.recentlyUpdated`),
      all: t(`${p}.filters.all`),
      yes: t(`${p}.filters.yes`),
      no: t(`${p}.filters.no`),
    },
    dashboard: {
      active: t(`${p}.dashboard.active`),
      highRisk: t(`${p}.dashboard.highRisk`),
      needsReview: t(`${p}.dashboard.needsReview`),
      withoutOwner: t(`${p}.dashboard.withoutOwner`),
      approachingReview: t(`${p}.dashboard.approachingReview`),
      recentlyResolved: t(`${p}.dashboard.recentlyResolved`),
    },
    form: {
      createTitle: t(`${p}.form.createTitle`),
      title: t(`${p}.form.title`),
      description: t(`${p}.form.description`),
      category: t(`${p}.form.category`),
      owner: t(`${p}.form.owner`),
      likelihood: t(`${p}.form.likelihood`),
      impact: t(`${p}.form.impact`),
      mitigationStrategy: t(`${p}.form.mitigationStrategy`),
      contingencyPlan: t(`${p}.form.contingencyPlan`),
      reviewFrequency: t(`${p}.form.reviewFrequency`),
      notes: t(`${p}.form.notes`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
    },
    card: {
      owner: t(`${p}.card.owner`),
      level: t(`${p}.card.level`),
      likelihood: t(`${p}.card.likelihood`),
      impact: t(`${p}.card.impact`),
      nextReview: t(`${p}.card.nextReview`),
      view: t(`${p}.card.view`),
    },
    detail: {
      overview: t(`${p}.detail.overview`),
      mitigation: t(`${p}.detail.mitigation`),
      contingency: t(`${p}.detail.contingency`),
      mitigations: t(`${p}.detail.mitigations`),
      contributors: t(`${p}.detail.contributors`),
      relatedFollowUps: t(`${p}.detail.relatedFollowUps`),
      relatedDecisions: t(`${p}.detail.relatedDecisions`),
      activity: t(`${p}.detail.activity`),
      audit: t(`${p}.detail.audit`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
      recommendations: t(`${p}.detail.recommendations`),
      addMitigation: t(`${p}.detail.addMitigation`),
      actionTaken: t(`${p}.detail.actionTaken`),
      effectivenessReview: t(`${p}.detail.effectivenessReview`),
      residualLikelihood: t(`${p}.detail.residualLikelihood`),
      residualImpact: t(`${p}.detail.residualImpact`),
      escalationRequired: t(`${p}.detail.escalationRequired`),
      submitMitigation: t(`${p}.detail.submitMitigation`),
    },
    categories: {
      operational: t(`${p}.categories.operational`),
      financial: t(`${p}.categories.financial`),
      security: t(`${p}.categories.security`),
      compliance: t(`${p}.categories.compliance`),
      customer: t(`${p}.categories.customer`),
      vendor: t(`${p}.categories.vendor`),
      strategic: t(`${p}.categories.strategic`),
      technology: t(`${p}.categories.technology`),
      reputational: t(`${p}.categories.reputational`),
      workforce: t(`${p}.categories.workforce`),
    },
    statuses: {
      identified: t(`${p}.statuses.identified`),
      under_review: t(`${p}.statuses.underReview`),
      mitigation_in_progress: t(`${p}.statuses.mitigationInProgress`),
      monitoring: t(`${p}.statuses.monitoring`),
      accepted: t(`${p}.statuses.accepted`),
      resolved: t(`${p}.statuses.resolved`),
      archived: t(`${p}.statuses.archived`),
    },
    likelihoods: {
      very_low: t(`${p}.likelihoods.veryLow`),
      low: t(`${p}.likelihoods.low`),
      moderate: t(`${p}.likelihoods.moderate`),
      high: t(`${p}.likelihoods.high`),
      very_high: t(`${p}.likelihoods.veryHigh`),
    },
    impacts: {
      negligible: t(`${p}.impacts.negligible`),
      minor: t(`${p}.impacts.minor`),
      moderate: t(`${p}.impacts.moderate`),
      major: t(`${p}.impacts.major`),
      critical: t(`${p}.impacts.critical`),
    },
    overallLevels: {
      low: t(`${p}.overallLevels.low`),
      medium: t(`${p}.overallLevels.medium`),
      high: t(`${p}.overallLevels.high`),
      critical: t(`${p}.overallLevels.critical`),
    },
    frequencies: {
      monthly: t(`${p}.frequencies.monthly`),
      quarterly: t(`${p}.frequencies.quarterly`),
      semi_annual: t(`${p}.frequencies.semiAnnual`),
      annual: t(`${p}.frequencies.annual`),
    },
    recommendations: {
      assignOwner: t(`${p}.recommendations.assignOwner`),
      reviewOverdue: t(`${p}.recommendations.reviewOverdue`),
      escalateCritical: t(`${p}.recommendations.escalateCritical`),
      updateMitigation: t(`${p}.recommendations.updateMitigation`),
      archiveResolved: t(`${p}.recommendations.archiveResolved`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      howCalculated: t(`${p}.faq.howCalculated`),
      howCalculatedAnswer: t(`${p}.faq.howCalculatedAnswer`),
      eliminate: t(`${p}.faq.eliminate`),
      eliminateAnswer: t(`${p}.faq.eliminateAnswer`),
    },
  };
}
