import type { EcosystemLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildEcosystemLabels(t: Translator): EcosystemLabels {
  const p = "customerApp.portalStructure.businessPackEcosystemIntelligence";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      packKey: t(`${p}.filters.packKey`),
      coverageCategory: t(`${p}.filters.coverageCategory`),
      ecosystemStatus: t(`${p}.filters.ecosystemStatus`),
      relationshipStrength: t(`${p}.filters.relationshipStrength`),
      priorityLevel: t(`${p}.filters.priorityLevel`),
      periodFrom: t(`${p}.filters.periodFrom`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      healthScore: t(`${p}.dashboard.healthScore`),
      relationshipMap: t(`${p}.dashboard.relationshipMap`),
      coverageOverview: t(`${p}.dashboard.coverageOverview`),
      crossUtilization: t(`${p}.dashboard.crossUtilization`),
      opportunities: t(`${p}.dashboard.opportunities`),
      risks: t(`${p}.dashboard.risks`),
      executiveSummary: t(`${p}.dashboard.executiveSummary`),
      recommendedActions: t(`${p}.dashboard.recommendedActions`),
      ecosystemStatus: t(`${p}.dashboard.ecosystemStatus`),
      coverageAnalysis: t(`${p}.dashboard.coverageAnalysis`),
      timeline: t(`${p}.dashboard.timeline`),
      installedPacks: t(`${p}.dashboard.installedPacks`),
    },
    card: {
      adoptionScore: t(`${p}.card.adoptionScore`),
      crossUtilization: t(`${p}.card.crossUtilization`),
      coverageCategory: t(`${p}.card.coverageCategory`),
      coverageStatus: t(`${p}.card.coverageStatus`),
    },
    ecosystemStatuses: {
      thriving: t(`${p}.ecosystemStatuses.thriving`),
      healthy: t(`${p}.ecosystemStatuses.healthy`),
      stable: t(`${p}.ecosystemStatuses.stable`),
      requires_optimization: t(`${p}.ecosystemStatuses.requiresOptimization`),
      fragmented: t(`${p}.ecosystemStatuses.fragmented`),
    },
    relationshipStrengths: {
      strong: t(`${p}.relationshipStrengths.strong`),
      moderate: t(`${p}.relationshipStrengths.moderate`),
      emerging: t(`${p}.relationshipStrengths.emerging`),
      underutilized: t(`${p}.relationshipStrengths.underutilized`),
    },
    coverageCategories: {
      operational: t(`${p}.coverageCategories.operational`),
      executive: t(`${p}.coverageCategories.executive`),
      governance: t(`${p}.coverageCategories.governance`),
      customer: t(`${p}.coverageCategories.customer`),
      knowledge: t(`${p}.coverageCategories.knowledge`),
      growth: t(`${p}.coverageCategories.growth`),
    },
    coverageStatuses: {
      comprehensive: t(`${p}.coverageStatuses.comprehensive`),
      well_covered: t(`${p}.coverageStatuses.wellCovered`),
      moderate_coverage: t(`${p}.coverageStatuses.moderateCoverage`),
      limited_coverage: t(`${p}.coverageStatuses.limitedCoverage`),
      coverage_gap_identified: t(`${p}.coverageStatuses.coverageGapIdentified`),
    },
    priorityLevels: {
      opportunity: t(`${p}.priorityLevels.opportunity`),
      recommended: t(`${p}.priorityLevels.recommended`),
      important: t(`${p}.priorityLevels.important`),
      immediate_attention: t(`${p}.priorityLevels.immediateAttention`),
    },
    opportunities: {
      greaterValueTogether: t(`${p}.opportunities.greaterValueTogether`),
      ecosystemTraining: t(`${p}.opportunities.ecosystemTraining`),
      expandCrossFunctional: t(`${p}.opportunities.expandCrossFunctional`),
      strengthenGovernance: t(`${p}.opportunities.strengthenGovernance`),
      improveExecutiveVisibility: t(`${p}.opportunities.improveExecutiveVisibility`),
    },
    risks: {
      underutilizedPacks: t(`${p}.risks.underutilizedPacks`),
      missingOwnership: t(`${p}.risks.missingOwnership`),
      duplicateCapabilities: t(`${p}.risks.duplicateCapabilities`),
      fragmentedAdoption: t(`${p}.risks.fragmentedAdoption`),
      lowIntegration: t(`${p}.risks.lowIntegration`),
    },
    recommendations: {
      encourageCrossFunctional: t(`${p}.recommendations.encourageCrossFunctional`),
      reviewEcosystemOwnership: t(`${p}.recommendations.reviewEcosystemOwnership`),
      strengthenCollaboration: t(`${p}.recommendations.strengthenCollaboration`),
      expandEcosystemLearning: t(`${p}.recommendations.expandEcosystemLearning`),
      addressCoverageGaps: t(`${p}.recommendations.addressCoverageGaps`),
      celebrateMaturity: t(`${p}.recommendations.celebrateMaturity`),
    },
    timelineEvents: {
      pack_added: t(`${p}.timelineEvents.packAdded`),
      relationship_strengthened: t(`${p}.timelineEvents.relationshipStrengthened`),
      adoption_improved: t(`${p}.timelineEvents.adoptionImproved`),
      optimization_completed: t(`${p}.timelineEvents.optimizationCompleted`),
      ecosystem_review: t(`${p}.timelineEvents.ecosystemReview`),
      value_milestone: t(`${p}.timelineEvents.valueMilestone`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      autoOptimize: t(`${p}.faq.autoOptimize`),
      autoOptimizeAnswer: t(`${p}.faq.autoOptimizeAnswer`),
      whyRelationships: t(`${p}.faq.whyRelationships`),
      whyRelationshipsAnswer: t(`${p}.faq.whyRelationshipsAnswer`),
    },
  };
}
