import type { Translator } from "@/lib/i18n/translate";

export type KompisAiGovernanceLabels = {
  title: string;
  subtitle: string;
  liveAi: string;
  safeFallback: string;
  liveAiActive: string;
  liveAiNotEnabled: string;
  liveAiTemporarilyLimited: string;
  usingSafeFallback: string;
  providerStatus: string;
  modelProfile: string;
  systemPromptVersion: string;
  plannerVersion: string;
  operationsStatus: string;
  ready: string;
  limited: string;
  cooldown: string;
  unavailable: string;
  disabled: string;
  lastCheck: string;
  lastSuccessfulCall: string;
  responseTime: string;
  usageLast24h: string;
  fallbackPlanning: string;
  fallbackShare: string;
  capacityLimit: string;
  checkProvider: string;
  checkSucceeded: string;
  checkFailed: string;
  noSensitiveInfo: string;
  configurationMissing: string;
  environmentVariable: string;
  mustConfigureSecurely: string;
  tryAgainLater: string;
  continuesWithSafeFeatures: string;
  retry: string;
  loading: string;
  errorTitle: string;
  events: string;
  success: string;
  fallback: string;
  errors: string;
  activeOrganizations: string;
  circuitBreaker: string;
  open: string;
  closed: string;
};

export function buildKompisAiGovernanceLabels(t: Translator): KompisAiGovernanceLabels {
  return {
    title: t("platform.kompisAi.title"),
    subtitle: t("platform.kompisAi.subtitle"),
    liveAi: t("platform.kompisAi.liveAi"),
    safeFallback: t("platform.kompisAi.safeFallback"),
    liveAiActive: t("platform.kompisAi.liveAiActive"),
    liveAiNotEnabled: t("platform.kompisAi.liveAiNotEnabled"),
    liveAiTemporarilyLimited: t("platform.kompisAi.liveAiTemporarilyLimited"),
    usingSafeFallback: t("platform.kompisAi.usingSafeFallback"),
    providerStatus: t("platform.kompisAi.providerStatus"),
    modelProfile: t("platform.kompisAi.modelProfile"),
    systemPromptVersion: t("platform.kompisAi.systemPromptVersion"),
    plannerVersion: t("platform.kompisAi.plannerVersion"),
    operationsStatus: t("platform.kompisAi.operationsStatus"),
    ready: t("platform.kompisAi.ready"),
    limited: t("platform.kompisAi.limited"),
    cooldown: t("platform.kompisAi.cooldown"),
    unavailable: t("platform.kompisAi.unavailable"),
    disabled: t("platform.kompisAi.disabled"),
    lastCheck: t("platform.kompisAi.lastCheck"),
    lastSuccessfulCall: t("platform.kompisAi.lastSuccessfulCall"),
    responseTime: t("platform.kompisAi.responseTime"),
    usageLast24h: t("platform.kompisAi.usageLast24h"),
    fallbackPlanning: t("platform.kompisAi.fallbackPlanning"),
    fallbackShare: t("platform.kompisAi.fallbackShare"),
    capacityLimit: t("platform.kompisAi.capacityLimit"),
    checkProvider: t("platform.kompisAi.checkProvider"),
    checkSucceeded: t("platform.kompisAi.checkSucceeded"),
    checkFailed: t("platform.kompisAi.checkFailed"),
    noSensitiveInfo: t("platform.kompisAi.noSensitiveInfo"),
    configurationMissing: t("platform.kompisAi.configurationMissing"),
    environmentVariable: t("platform.kompisAi.environmentVariable"),
    mustConfigureSecurely: t("platform.kompisAi.mustConfigureSecurely"),
    tryAgainLater: t("platform.kompisAi.tryAgainLater"),
    continuesWithSafeFeatures: t("platform.kompisAi.continuesWithSafeFeatures"),
    retry: t("platform.kompisAi.retry"),
    loading: t("platform.kompisAi.loading"),
    errorTitle: t("platform.kompisAi.errorTitle"),
    events: t("platform.kompisAi.events"),
    success: t("platform.kompisAi.success"),
    fallback: t("platform.kompisAi.fallback"),
    errors: t("platform.kompisAi.errors"),
    activeOrganizations: t("platform.kompisAi.activeOrganizations"),
    circuitBreaker: t("platform.kompisAi.circuitBreaker"),
    open: t("platform.kompisAi.open"),
    closed: t("platform.kompisAi.closed"),
  };
}
