import type { StrategicOpportunitiesLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildStrategicOpportunitiesLabels(t: Translator): StrategicOpportunitiesLabels {
  const p = "customerApp.portalStructure.strategicOpportunities";
  return {
    title:        t(`${p}.title`),
    subtitle:     t(`${p}.subtitle`),
    loading:      t(`${p}.loading`),
    principle:    t(`${p}.principle`),
    advisoryNote: t(`${p}.advisoryNote`),
    emptyTitle:   t(`${p}.emptyTitle`),
    emptyBody:    t(`${p}.emptyBody`),
    emptyCta:     t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search:           t(`${p}.filters.search`),
      category:         t(`${p}.filters.category`),
      status:           t(`${p}.filters.status`),
      department:       t(`${p}.filters.department`),
      strategicPriority:t(`${p}.filters.strategicPriority`),
      executiveOwner:   t(`${p}.filters.executiveOwner`),
      timeHorizon:      t(`${p}.filters.timeHorizon`),
      all:              t(`${p}.filters.all`),
    },
    dashboard: {
      healthScore:         t(`${p}.dashboard.healthScore`),
      executiveSummary:    t(`${p}.dashboard.executiveSummary`),
      highPotential:       t(`${p}.dashboard.highPotential`),
      requiresExploration: t(`${p}.dashboard.requiresExploration`),
      underReview:         t(`${p}.dashboard.underReview`),
      inProgress:          t(`${p}.dashboard.inProgress`),
      realized:            t(`${p}.dashboard.realized`),
      opportunities:       t(`${p}.dashboard.opportunities`),
      recommendations:     t(`${p}.dashboard.recommendations`),
      timeline:            t(`${p}.dashboard.timeline`),
      reviewQuestions:     t(`${p}.dashboard.reviewQuestions`),
      viewOpportunity:     t(`${p}.dashboard.viewOpportunity`),
      addOpportunity:      t(`${p}.dashboard.addOpportunity`),
      updateStatus:        t(`${p}.dashboard.updateStatus`),
    },
    card: {
      category:           t(`${p}.card.category`),
      status:             t(`${p}.card.status`),
      strategicPriority:  t(`${p}.card.strategicPriority`),
      estimatedImpact:    t(`${p}.card.estimatedImpact`),
      estimatedComplexity:t(`${p}.card.estimatedComplexity`),
      orgReadiness:       t(`${p}.card.orgReadiness`),
      reviewPriority:     t(`${p}.card.reviewPriority`),
      owner:              t(`${p}.card.owner`),
      timeHorizon:        t(`${p}.card.timeHorizon`),
      potentialValue:     t(`${p}.card.potentialValue`),
      estimatedEffort:    t(`${p}.card.estimatedEffort`),
    },
    detail: {
      back:          t(`${p}.detail.back`),
      scorecard:     t(`${p}.detail.scorecard`),
      nextSteps:     t(`${p}.detail.nextSteps`),
      relatedDepartments: t(`${p}.detail.relatedDepartments`),
      reviewHistory: t(`${p}.detail.reviewHistory`),
      reviewNotes:   t(`${p}.detail.reviewNotes`),
      newStatus:     t(`${p}.detail.newStatus`),
      submitReview:  t(`${p}.detail.submitReview`),
      reviewSuccess: t(`${p}.detail.reviewSuccess`),
      advisoryNote:  t(`${p}.detail.advisoryNote`),
    },
    create: {
      titlePlaceholder:       t(`${p}.create.titlePlaceholder`),
      descriptionPlaceholder: t(`${p}.create.descriptionPlaceholder`),
      success:                t(`${p}.create.success`),
    },
    categories: {
      revenue_growth:           t(`${p}.categories.revenueGrowth`),
      customer_experience:      t(`${p}.categories.customerExperience`),
      operational_efficiency:   t(`${p}.categories.operationalEfficiency`),
      cost_optimization:        t(`${p}.categories.costOptimization`),
      employee_experience:      t(`${p}.categories.employeeExperience`),
      market_expansion:         t(`${p}.categories.marketExpansion`),
      product_innovation:       t(`${p}.categories.productInnovation`),
      strategic_partnerships:   t(`${p}.categories.strategicPartnerships`),
      automation_opportunities: t(`${p}.categories.automationOpportunities`),
      knowledge_opportunities:  t(`${p}.categories.knowledgeOpportunities`),
      process_improvements:     t(`${p}.categories.processImprovements`),
      sustainability_initiatives:t(`${p}.categories.sustainabilityInitiatives`),
    },
    statuses: {
      identified:   t(`${p}.statuses.identified`),
      under_review: t(`${p}.statuses.underReview`),
      approved:     t(`${p}.statuses.approved`),
      planning:     t(`${p}.statuses.planning`),
      in_progress:  t(`${p}.statuses.inProgress`),
      completed:    t(`${p}.statuses.completed`),
      archived:     t(`${p}.statuses.archived`),
    },
    strategicPriorities: {
      low:       t(`${p}.strategicPriorities.low`),
      moderate:  t(`${p}.strategicPriorities.moderate`),
      high:      t(`${p}.strategicPriorities.high`),
      strategic: t(`${p}.strategicPriorities.strategic`),
    },
    estimatedImpacts: {
      low:             t(`${p}.estimatedImpacts.low`),
      moderate:        t(`${p}.estimatedImpacts.moderate`),
      high:            t(`${p}.estimatedImpacts.high`),
      transformational:t(`${p}.estimatedImpacts.transformational`),
    },
    estimatedComplexities: {
      low:      t(`${p}.estimatedComplexities.low`),
      moderate: t(`${p}.estimatedComplexities.moderate`),
      high:     t(`${p}.estimatedComplexities.high`),
      very_high:t(`${p}.estimatedComplexities.veryHigh`),
    },
    orgReadiness: {
      not_ready: t(`${p}.orgReadiness.notReady`),
      low:       t(`${p}.orgReadiness.low`),
      moderate:  t(`${p}.orgReadiness.moderate`),
      high:      t(`${p}.orgReadiness.high`),
    },
    reviewPriorities: {
      low:       t(`${p}.reviewPriorities.low`),
      normal:    t(`${p}.reviewPriorities.normal`),
      high:      t(`${p}.reviewPriorities.high`),
      immediate: t(`${p}.reviewPriorities.immediate`),
    },
    timeHorizons: {
      "30_days":  t(`${p}.timeHorizons.30Days`),
      "90_days":  t(`${p}.timeHorizons.90Days`),
      "6_months": t(`${p}.timeHorizons.6Months`),
      "12_months":t(`${p}.timeHorizons.12Months`),
      "24_months":t(`${p}.timeHorizons.24Months`),
      "36_months":t(`${p}.timeHorizons.36Months`),
    },
    recommendations: {
      scheduleExploratoryWorkshop: t(`${p}.recommendations.scheduleExploratoryWorkshop`),
      assignExecutiveSponsor:      t(`${p}.recommendations.assignExecutiveSponsor`),
      gatherSupportingData:        t(`${p}.recommendations.gatherSupportingData`),
      initiatePilotProject:        t(`${p}.recommendations.initiatePilotProject`),
      conductStakeholderReview:    t(`${p}.recommendations.conductStakeholderReview`),
      monitorFutureDevelopments:   t(`${p}.recommendations.monitorFutureDevelopments`),
    },
    timelineEvents: {
      opportunities_initialized: t(`${p}.timelineEvents.opportunitiesInitialized`),
      opportunity_identified:    t(`${p}.timelineEvents.opportunityIdentified`),
      status_updated:            t(`${p}.timelineEvents.statusUpdated`),
      opportunity_reviewed:      t(`${p}.timelineEvents.opportunityReviewed`),
      opportunity_approved:      t(`${p}.timelineEvents.opportunityApproved`),
      opportunity_completed:     t(`${p}.timelineEvents.opportunityCompleted`),
      lesson_captured:           t(`${p}.timelineEvents.lessonCaptured`),
      value_realized:            t(`${p}.timelineEvents.valueRealized`),
    },
    reviewQuestions: [
      t(`${p}.reviewQuestions.underexplored`),
      t(`${p}.reviewQuestions.alignsStrategic`),
      t(`${p}.reviewQuestions.capabilitiesRequired`),
      t(`${p}.reviewQuestions.stakeholders`),
      t(`${p}.reviewQuestions.barriers`),
      t(`${p}.reviewQuestions.rightTime`),
    ],
    faq: {
      title:                 t(`${p}.faq.title`),
      whatAre:               t(`${p}.faq.whatAre`),
      whatAreAnswer:         t(`${p}.faq.whatAreAnswer`),
      autoImplement:         t(`${p}.faq.autoImplement`),
      autoImplementAnswer:   t(`${p}.faq.autoImplementAnswer`),
      whoShouldUse:          t(`${p}.faq.whoShouldUse`),
      whoShouldUseAnswer:    t(`${p}.faq.whoShouldUseAnswer`),
    },
  };
}
