import type { NormalizedBriefingEvent } from "../types";

/** Sample Unonight pilot briefing events for observation-mode demos. */
export const UNONIGHT_BRIEFING_EVENTS: NormalizedBriefingEvent[] = [
  {
    source_module: "unonight",
    source_type: "registration",
    event_key: "briefing.unonight.registrations.sample",
    title: "7 new members registered",
    summary: "Registrations since last login across public signup flow.",
    severity: "info",
    requires_action: false,
    action_url: "/platform/customers",
  },
  {
    source_module: "unonight",
    source_type: "verification_queue",
    event_key: "briefing.unonight.verifications.pending",
    title: "3 verifications waiting",
    summary: "Member verifications need admin review.",
    severity: "high",
    requires_action: true,
    action_url: "/app/quality",
  },
  {
    source_module: "support",
    source_type: "support_draft",
    event_key: "briefing.unonight.support.drafts",
    title: "2 support drafts ready for approval",
    summary: "Support Specialist prepared drafts that need human review.",
    severity: "medium",
    requires_action: true,
    action_url: "/app/approvals",
  },
  {
    source_module: "unonight",
    source_type: "marketplace_listing",
    event_key: "briefing.unonight.marketplace.pending",
    title: "1 marketplace listing needs approval",
    summary: "A new listing is waiting in the moderation queue.",
    severity: "medium",
    requires_action: true,
    action_url: "/app/quality",
  },
  {
    source_module: "quality",
    source_type: "quality_incident",
    event_key: "briefing.unonight.images.mobile",
    title: "4 images should be optimized for mobile",
    summary: "Oversized homepage and marketplace images may slow mobile users.",
    severity: "high",
    requires_action: true,
    action_url: "/app/quality/images",
  },
  {
    source_module: "integrations",
    source_type: "integration_error",
    event_key: "briefing.unonight.shopify.webhook",
    title: "Shopify webhook responded slowly once",
    summary: "Membership upgrade webhook was slower than normal. No persistent failure detected.",
    severity: "medium",
    requires_action: false,
    action_url: "/app/governance",
  },
];
