import type { QualityCheckDefinition } from "../types";

/** Unonight pilot quality checks — tenant-specific preset, not core logic. */
export const UNONIGHT_QUALITY_CHECKS: QualityCheckDefinition[] = [
  {
    check_key: "unonight.registration",
    scanner_type: "journey_monitor",
    category: "journeys",
    title: "Registration flow",
    expected_behavior: "New members can complete registration without errors.",
    metadata: { journey: "registration" },
  },
  {
    check_key: "unonight.email_verification",
    scanner_type: "journey_monitor",
    category: "journeys",
    title: "Email verification",
    expected_behavior: "Verification emails are sent and confirmation links work.",
    metadata: { journey: "email_verification" },
  },
  {
    check_key: "unonight.chat",
    scanner_type: "journey_monitor",
    category: "journeys",
    title: "Member chat",
    expected_behavior: "Verified members can open and send chat messages.",
    metadata: { journey: "chat" },
  },
  {
    check_key: "unonight.marketplace",
    scanner_type: "journey_monitor",
    category: "journeys",
    title: "Marketplace browsing",
    expected_behavior: "Members can browse marketplace listings without 404 errors.",
    metadata: { journey: "marketplace" },
  },
  {
    check_key: "unonight.upgrade_button",
    scanner_type: "journey_monitor",
    category: "journeys",
    title: "Membership upgrade",
    expected_behavior: "Upgrade button routes to shop checkout and returns successfully.",
    metadata: { journey: "upgrade" },
  },
  {
    check_key: "unonight.gifts",
    scanner_type: "journey_monitor",
    category: "journeys",
    title: "Gift functionality",
    expected_behavior: "Members can view wishlists and initiate gift purchases.",
    metadata: { journey: "gifts" },
  },
  {
    check_key: "unonight.verification_queue",
    scanner_type: "workflow_validator",
    category: "workflow",
    title: "Verification queue",
    workflow_key: "unonight.account_verification",
    expected_behavior: "Account verification queue receives and surfaces pending items.",
  },
  {
    check_key: "unonight.digital_approval_queue",
    scanner_type: "workflow_validator",
    category: "workflow",
    title: "Digital product approval queue",
    workflow_key: "unonight.digital_product_approval",
    expected_behavior: "Digital products enter approval queue and appear for moderators.",
  },
  {
    check_key: "unonight.image_moderation_queue",
    scanner_type: "workflow_validator",
    category: "workflow",
    title: "Image moderation queue",
    workflow_key: "unonight.image_moderation",
    expected_behavior: "Uploaded images appear in moderation queue within expected SLA.",
  },
  {
    check_key: "unonight.language_selector",
    scanner_type: "translation_monitor",
    category: "translation",
    title: "Language selector",
    locale_codes: ["en", "no", "sv", "da"],
    expected_behavior: "Language selector switches UI locale without missing translation keys.",
  },
  {
    check_key: "unonight.mobile_experience",
    scanner_type: "mobile_monitor",
    category: "mobile",
    title: "Mobile layout",
    expected_behavior: "Core journeys render correctly on mobile viewports without layout breakage.",
    metadata: { viewport: "390x844" },
  },
  {
    check_key: "unonight.supabase_integration",
    scanner_type: "integration_monitor",
    category: "integrations",
    title: "Supabase integration",
    integration_key: "supabase",
    expected_behavior: "Supabase integration reports connected status and successful read sync.",
  },
  {
    check_key: "unonight.shopify_integration",
    scanner_type: "integration_monitor",
    category: "integrations",
    title: "Shopify integration",
    integration_key: "shopify",
    expected_behavior: "Shopify webhooks and order sync respond without repeated failures.",
  },
  {
    check_key: "unonight.resend_integration",
    scanner_type: "integration_monitor",
    category: "integrations",
    title: "Resend integration",
    integration_key: "resend",
    expected_behavior: "Resend email delivery succeeds for verification and support templates.",
  },
  {
    check_key: "unonight.home_link",
    scanner_type: "link_monitor",
    category: "links",
    title: "Home page",
    target_url: "https://unonight.com/",
    expected_behavior: "Home page returns HTTP 200 without redirect loops.",
  },
];
