import type { BusinessPackSuccessLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildBusinessPackSuccessLabels(t: Translator): BusinessPackSuccessLabels {
  const p = "customerApp.portalStructure.businessPackSuccess";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      pack: t(`${p}.filters.pack`),
      adoptionStatus: t(`${p}.filters.adoptionStatus`),
      priority: t(`${p}.filters.priority`),
      successStatus: t(`${p}.filters.successStatus`),
      periodFrom: t(`${p}.filters.periodFrom`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      installedPacks: t(`${p}.dashboard.installedPacks`),
      overallAdoptionScore: t(`${p}.dashboard.overallAdoptionScore`),
      mostActivePacks: t(`${p}.dashboard.mostActivePacks`),
      underutilizedPacks: t(`${p}.dashboard.underutilizedPacks`),
      recommendedNextActions: t(`${p}.dashboard.recommendedNextActions`),
      successMilestones: t(`${p}.dashboard.successMilestones`),
      learningOpportunities: t(`${p}.dashboard.learningOpportunities`),
      adoptionInsights: t(`${p}.dashboard.adoptionInsights`),
      successTimeline: t(`${p}.dashboard.successTimeline`),
      onboardingChecklist: t(`${p}.dashboard.onboardingChecklist`),
    },
    packCard: {
      status: t(`${p}.packCard.status`),
      adoptionScore: t(`${p}.packCard.adoptionScore`),
      usageTrend: t(`${p}.packCard.usageTrend`),
      usersAssigned: t(`${p}.packCard.usersAssigned`),
      featuresActivated: t(`${p}.packCard.featuresActivated`),
      lastActivity: t(`${p}.packCard.lastActivity`),
      recommendedActions: t(`${p}.packCard.recommendedActions`),
      viewDetails: t(`${p}.packCard.viewDetails`),
    },
    packStatus: {
      getting_started: t(`${p}.packStatus.gettingStarted`),
      active: t(`${p}.packStatus.active`),
      healthy: t(`${p}.packStatus.healthy`),
      optimized: t(`${p}.packStatus.optimized`),
      requires_attention: t(`${p}.packStatus.requiresAttention`),
    },
    usageTrends: {
      growing: t(`${p}.usageTrends.growing`),
      stable: t(`${p}.usageTrends.stable`),
      declining: t(`${p}.usageTrends.declining`),
    },
    priorityLevels: {
      opportunity: t(`${p}.priorityLevels.opportunity`),
      recommended: t(`${p}.priorityLevels.recommended`),
      important: t(`${p}.priorityLevels.important`),
      high_impact: t(`${p}.priorityLevels.highImpact`),
    },
    recommendations: {
      completeOnboardingSteps: t(`${p}.recommendations.completeOnboardingSteps`),
      exploreAdvancedCapabilities: t(`${p}.recommendations.exploreAdvancedCapabilities`),
      trainAdditionalUsers: t(`${p}.recommendations.trainAdditionalUsers`),
      activateRecommendedIntegrations: t(`${p}.recommendations.activateRecommendedIntegrations`),
      reviewBestPractices: t(`${p}.recommendations.reviewBestPractices`),
      scheduleBusinessPackReview: t(`${p}.recommendations.scheduleBusinessPackReview`),
      exploreBusinessPacks: t(`${p}.recommendations.exploreBusinessPacks`),
    },
    milestones: {
      installed_successfully: t(`${p}.milestones.installedSuccessfully`),
      first_user_assigned: t(`${p}.milestones.firstUserAssigned`),
      first_workflow_completed: t(`${p}.milestones.firstWorkflowCompleted`),
      first_report_generated: t(`${p}.milestones.firstReportGenerated`),
      recommended_setup_completed: t(`${p}.milestones.recommendedSetupCompleted`),
      team_training_completed: t(`${p}.milestones.teamTrainingCompleted`),
      adoption_threshold_reached: t(`${p}.milestones.adoptionThresholdReached`),
    },
    onboarding: {
      initial_setup: t(`${p}.onboarding.initialSetup`),
      recommended_configuration: t(`${p}.onboarding.recommendedConfiguration`),
      assign_users: t(`${p}.onboarding.assignUsers`),
      integration_setup: t(`${p}.onboarding.integrationSetup`),
      governance_review: t(`${p}.onboarding.governanceReview`),
    },
    insights: {
      featuresFrequentlyUsed: t(`${p}.insights.featuresFrequentlyUsed`),
      featuresRarelyUsed: t(`${p}.insights.featuresRarelyUsed`),
      usersActivelyEngaging: t(`${p}.insights.usersActivelyEngaging`),
      areasRequiringOnboarding: t(`${p}.insights.areasRequiringOnboarding`),
      learningOpportunities: t(`${p}.insights.learningOpportunities`),
      recommendedConfigurations: t(`${p}.insights.recommendedConfigurations`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      improveAutomatically: t(`${p}.faq.improveAutomatically`),
      improveAutomaticallyAnswer: t(`${p}.faq.improveAutomaticallyAnswer`),
      whyImportant: t(`${p}.faq.whyImportant`),
      whyImportantAnswer: t(`${p}.faq.whyImportantAnswer`),
    },
  };
}
