import type { SuccessValueLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildSuccessValueLabels(t: Translator): SuccessValueLabels {
  const p = "customerApp.portalStructure.successValue";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      status: t(`${p}.filters.status`),
      owner: t(`${p}.filters.owner`),
      sponsor: t(`${p}.filters.sponsor`),
      valueLevel: t(`${p}.filters.valueLevel`),
      reviewFrom: t(`${p}.filters.reviewFrom`),
      reviewTo: t(`${p}.filters.reviewTo`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      active: t(`${p}.dashboard.active`),
      recentlyRealized: t(`${p}.dashboard.recentlyRealized`),
      underReview: t(`${p}.dashboard.underReview`),
      highestImpact: t(`${p}.dashboard.highestImpact`),
      missingMeasurements: t(`${p}.dashboard.missingMeasurements`),
      successTrends: t(`${p}.dashboard.successTrends`),
    },
    form: {
      createTitle: t(`${p}.form.createTitle`),
      title: t(`${p}.form.title`),
      description: t(`${p}.form.description`),
      category: t(`${p}.form.category`),
      valueLevel: t(`${p}.form.valueLevel`),
      expectedOutcomes: t(`${p}.form.expectedOutcomes`),
      valueHypothesis: t(`${p}.form.valueHypothesis`),
      measurementMethod: t(`${p}.form.measurementMethod`),
      notes: t(`${p}.form.notes`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
    },
    card: {
      owner: t(`${p}.card.owner`),
      sponsor: t(`${p}.card.sponsor`),
      valueLevel: t(`${p}.card.valueLevel`),
      expected: t(`${p}.card.expected`),
      actual: t(`${p}.card.actual`),
      reviewDate: t(`${p}.card.reviewDate`),
      view: t(`${p}.card.view`),
    },
    detail: {
      overview: t(`${p}.detail.overview`),
      expectedVsActual: t(`${p}.detail.expectedVsActual`),
      ownership: t(`${p}.detail.ownership`),
      outcomeAnalysis: t(`${p}.detail.outcomeAnalysis`),
      goalsAchieved: t(`${p}.detail.goalsAchieved`),
      goalsMissed: t(`${p}.detail.goalsMissed`),
      unexpectedBenefits: t(`${p}.detail.unexpectedBenefits`),
      unexpectedConsequences: t(`${p}.detail.unexpectedConsequences`),
      recommendedAdjustments: t(`${p}.detail.recommendedAdjustments`),
      replicationOpportunities: t(`${p}.detail.replicationOpportunities`),
      lessonsLearned: t(`${p}.detail.lessonsLearned`),
      relatedDecisions: t(`${p}.detail.relatedDecisions`),
      relatedFollowUps: t(`${p}.detail.relatedFollowUps`),
      reviewTimeline: t(`${p}.detail.reviewTimeline`),
      audit: t(`${p}.detail.audit`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
      recommendations: t(`${p}.detail.recommendations`),
    },
    categories: {
      financial_value: t(`${p}.categories.financialValue`),
      operational_value: t(`${p}.categories.operationalValue`),
      customer_value: t(`${p}.categories.customerValue`),
      employee_value: t(`${p}.categories.employeeValue`),
      strategic_value: t(`${p}.categories.strategicValue`),
      productivity_value: t(`${p}.categories.productivityValue`),
      quality_improvement: t(`${p}.categories.qualityImprovement`),
      risk_reduction: t(`${p}.categories.riskReduction`),
      innovation_value: t(`${p}.categories.innovationValue`),
      custom_value_category: t(`${p}.categories.customValueCategory`),
    },
    statuses: {
      planned: t(`${p}.statuses.planned`),
      in_progress: t(`${p}.statuses.inProgress`),
      measuring: t(`${p}.statuses.measuring`),
      successful: t(`${p}.statuses.successful`),
      partially_successful: t(`${p}.statuses.partiallySuccessful`),
      did_not_meet_expectations: t(`${p}.statuses.didNotMeetExpectations`),
      archived: t(`${p}.statuses.archived`),
    },
    valueLevels: {
      emerging_value: t(`${p}.valueLevels.emergingValue`),
      moderate_value: t(`${p}.valueLevels.moderateValue`),
      significant_value: t(`${p}.valueLevels.significantValue`),
      transformational_value: t(`${p}.valueLevels.transformationalValue`),
    },
    recommendations: {
      reviewMeasurements: t(`${p}.recommendations.reviewMeasurements`),
      celebrateSuccess: t(`${p}.recommendations.celebrateSuccess`),
      reevaluateUnderperforming: t(`${p}.recommendations.reevaluateUnderperforming`),
      shareSuccess: t(`${p}.recommendations.shareSuccess`),
      replicatePractices: t(`${p}.recommendations.replicatePractices`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      whyMeasure: t(`${p}.faq.whyMeasure`),
      whyMeasureAnswer: t(`${p}.faq.whyMeasureAnswer`),
      autoDetermine: t(`${p}.faq.autoDetermine`),
      autoDetermineAnswer: t(`${p}.faq.autoDetermineAnswer`),
    },
  };
}
