import type { DecisionCenterLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildDecisionCenterLabels(t: Translator): DecisionCenterLabels {
  const p = "customerApp.portalStructure.decisionCenter";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    recordDecision: t(`${p}.recordDecision`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    readOnly: t(`${p}.readOnly`),
    filters: {
      title: t(`${p}.filters.title`),
      category: t(`${p}.filters.category`),
      status: t(`${p}.filters.status`),
      owner: t(`${p}.filters.owner`),
      impact: t(`${p}.filters.impact`),
      dateFrom: t(`${p}.filters.dateFrom`),
      dateTo: t(`${p}.filters.dateTo`),
      outcomeRating: t(`${p}.filters.outcomeRating`),
      search: t(`${p}.filters.search`),
      searchPlaceholder: t(`${p}.filters.searchPlaceholder`),
      all: t(`${p}.filters.all`),
    },
    card: {
      owner: t(`${p}.card.owner`),
      date: t(`${p}.card.date`),
      status: t(`${p}.card.status`),
      impact: t(`${p}.card.impact`),
      expectedOutcome: t(`${p}.card.expectedOutcome`),
      category: t(`${p}.card.category`),
    },
    detail: {
      description: t(`${p}.detail.description`),
      contributors: t(`${p}.detail.contributors`),
      supportingEvidence: t(`${p}.detail.supportingEvidence`),
      relatedApprovals: t(`${p}.detail.relatedApprovals`),
      linkedFollowUps: t(`${p}.detail.linkedFollowUps`),
      timeline: t(`${p}.detail.timeline`),
      outcomeEvaluation: t(`${p}.detail.outcomeEvaluation`),
      auditHistory: t(`${p}.detail.auditHistory`),
      expectedOutcome: t(`${p}.detail.expectedOutcome`),
      businessPacks: t(`${p}.detail.businessPacks`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
      evaluate: t(`${p}.detail.evaluate`),
      outcomeRating: t(`${p}.detail.outcomeRating`),
      lessonsLearned: t(`${p}.detail.lessonsLearned`),
      unexpectedConsequences: t(`${p}.detail.unexpectedConsequences`),
      wouldRepeat: t(`${p}.detail.wouldRepeat`),
    },
    sections: {
      items: t(`${p}.sections.items`),
      suggestions: t(`${p}.sections.suggestions`),
    },
    suggestions: {
      accept: t(`${p}.suggestions.accept`),
      requiresReview: t(`${p}.suggestions.requiresReview`),
    },
    categories: {
      strategic: t(`${p}.categories.strategic`),
      financial: t(`${p}.categories.financial`),
      operational: t(`${p}.categories.operational`),
      customer_experience: t(`${p}.categories.customerExperience`),
      human_resources: t(`${p}.categories.humanResources`),
      security: t(`${p}.categories.security`),
      technology: t(`${p}.categories.technology`),
      compliance: t(`${p}.categories.compliance`),
      marketing: t(`${p}.categories.marketing`),
      growth: t(`${p}.categories.growth`),
    },
    statuses: {
      proposed: t(`${p}.statuses.proposed`),
      under_review: t(`${p}.statuses.underReview`),
      approved: t(`${p}.statuses.approved`),
      rejected: t(`${p}.statuses.rejected`),
      implemented: t(`${p}.statuses.implemented`),
      evaluated: t(`${p}.statuses.evaluated`),
    },
    impactLevels: {
      low: t(`${p}.impactLevels.low`),
      moderate: t(`${p}.impactLevels.moderate`),
      high: t(`${p}.impactLevels.high`),
      critical: t(`${p}.impactLevels.critical`),
    },
    wouldRepeat: {
      yes: t(`${p}.wouldRepeat.yes`),
      partially: t(`${p}.wouldRepeat.partially`),
      no: t(`${p}.wouldRepeat.no`),
    },
    form: {
      title: t(`${p}.form.title`),
      titlePlaceholder: t(`${p}.form.titlePlaceholder`),
      description: t(`${p}.form.description`),
      category: t(`${p}.form.category`),
      impact: t(`${p}.form.impact`),
      expectedOutcome: t(`${p}.form.expectedOutcome`),
      status: t(`${p}.form.status`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      whyDocument: t(`${p}.faq.whyDocument`),
      whyDocumentAnswer: t(`${p}.faq.whyDocumentAnswer`),
      autoDecide: t(`${p}.faq.autoDecide`),
      autoDecideAnswer: t(`${p}.faq.autoDecideAnswer`),
    },
  };
}
