import type { ComplianceLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildComplianceLabels(t: Translator): ComplianceLabels {
  const p = "customerApp.portalStructure.businessPackCompliance";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      complianceStatus: t(`${p}.filters.complianceStatus`),
      packKey: t(`${p}.filters.packKey`),
      policyCategory: t(`${p}.filters.policyCategory`),
      reviewer: t(`${p}.filters.reviewer`),
      reviewPeriod: t(`${p}.filters.reviewPeriod`),
      priorityLevel: t(`${p}.filters.priorityLevel`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      complianceHealthScore: t(`${p}.dashboard.complianceHealthScore`),
      packsUnderReview: t(`${p}.dashboard.packsUnderReview`),
      packsMissingReviews: t(`${p}.dashboard.packsMissingReviews`),
      upcomingReviews: t(`${p}.dashboard.upcomingReviews`),
      recentlyCompleted: t(`${p}.dashboard.recentlyCompleted`),
      openRecommendations: t(`${p}.dashboard.openRecommendations`),
      executiveSummary: t(`${p}.dashboard.executiveSummary`),
      complianceInsights: t(`${p}.dashboard.complianceInsights`),
      recommendedActions: t(`${p}.dashboard.recommendedActions`),
      timeline: t(`${p}.dashboard.timeline`),
      policyAlignment: t(`${p}.dashboard.policyAlignment`),
      healthOverview: t(`${p}.dashboard.healthOverview`),
    },
    policyAlignment: {
      reviewed: t(`${p}.policyAlignment.reviewed`),
      acknowledged: t(`${p}.policyAlignment.acknowledged`),
      requiringReview: t(`${p}.policyAlignment.requiringReview`),
      pendingApproval: t(`${p}.policyAlignment.pendingApproval`),
      requiringUpdates: t(`${p}.policyAlignment.requiringUpdates`),
    },
    card: {
      complianceStatus: t(`${p}.card.complianceStatus`),
      assignedReviewer: t(`${p}.card.assignedReviewer`),
      lastReview: t(`${p}.card.lastReview`),
      nextReview: t(`${p}.card.nextReview`),
      policiesLinked: t(`${p}.card.policiesLinked`),
      openRecommendations: t(`${p}.card.openRecommendations`),
      governanceNotes: t(`${p}.card.governanceNotes`),
      reviewFrequency: t(`${p}.card.reviewFrequency`),
      viewDetails: t(`${p}.card.viewDetails`),
      completeReview: t(`${p}.card.completeReview`),
    },
    review: {
      title: t(`${p}.review.title`),
      notes: t(`${p}.review.notes`),
      submit: t(`${p}.review.submit`),
      success: t(`${p}.review.success`),
      governanceNote: t(`${p}.review.governanceNote`),
    },
    complianceStatuses: {
      aligned: t(`${p}.complianceStatuses.aligned`),
      healthy: t(`${p}.complianceStatuses.healthy`),
      requires_review: t(`${p}.complianceStatuses.requiresReview`),
      review_overdue: t(`${p}.complianceStatuses.reviewOverdue`),
      immediate_attention: t(`${p}.complianceStatuses.immediateAttention`),
    },
    policyCategories: {
      information_security: t(`${p}.policyCategories.informationSecurity`),
      data_governance: t(`${p}.policyCategories.dataGovernance`),
      access_management: t(`${p}.policyCategories.accessManagement`),
      operational_procedures: t(`${p}.policyCategories.operationalProcedures`),
      customer_policies: t(`${p}.policyCategories.customerPolicies`),
      vendor_management: t(`${p}.policyCategories.vendorManagement`),
      internal_governance: t(`${p}.policyCategories.internalGovernance`),
      business_continuity: t(`${p}.policyCategories.businessContinuity`),
      custom: t(`${p}.policyCategories.custom`),
    },
    reviewFrequencies: {
      monthly: t(`${p}.reviewFrequencies.monthly`),
      quarterly: t(`${p}.reviewFrequencies.quarterly`),
      semi_annually: t(`${p}.reviewFrequencies.semiAnnually`),
      annually: t(`${p}.reviewFrequencies.annually`),
      custom: t(`${p}.reviewFrequencies.custom`),
    },
    priorityLevels: {
      low: t(`${p}.priorityLevels.low`),
      moderate: t(`${p}.priorityLevels.moderate`),
      high: t(`${p}.priorityLevels.high`),
      critical: t(`${p}.priorityLevels.critical`),
    },
    recommendations: {
      scheduleOverdueReviews: t(`${p}.recommendations.scheduleOverdueReviews`),
      assignReviewers: t(`${p}.recommendations.assignReviewers`),
      reviewPolicyAcknowledgements: t(`${p}.recommendations.reviewPolicyAcknowledgements`),
      strengthenGovernanceDocumentation: t(`${p}.recommendations.strengthenGovernanceDocumentation`),
      improveReviewFrequency: t(`${p}.recommendations.improveReviewFrequency`),
      celebrateStrongCompliance: t(`${p}.recommendations.celebrateStrongCompliance`),
    },
    insights: {
      approachingDeadlines: t(`${p}.insights.approachingDeadlines`),
      missingAcknowledgements: t(`${p}.insights.missingAcknowledgements`),
      governanceGaps: t(`${p}.insights.governanceGaps`),
      strongPractices: t(`${p}.insights.strongPractices`),
      improvementOpportunities: t(`${p}.insights.improvementOpportunities`),
    },
    timelineEvents: {
      review_completed: t(`${p}.timelineEvents.reviewCompleted`),
      policy_updated: t(`${p}.timelineEvents.policyUpdated`),
      recommendation_resolved: t(`${p}.timelineEvents.recommendationResolved`),
      compliance_milestone: t(`${p}.timelineEvents.complianceMilestone`),
      review_assignment_changed: t(`${p}.timelineEvents.reviewAssignmentChanged`),
      compliance_improvement: t(`${p}.timelineEvents.complianceImprovement`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      legalAdvice: t(`${p}.faq.legalAdvice`),
      legalAdviceAnswer: t(`${p}.faq.legalAdviceAnswer`),
      completeCompliance: t(`${p}.faq.completeCompliance`),
      completeComplianceAnswer: t(`${p}.faq.completeComplianceAnswer`),
    },
  };
}
