export function buildPartnerMaterialsLabels(t: (key: string) => string): Record<string, string> {
  const p = "partnerMaterials";
  const keys = [
    "title",
    "subtitle",
    "loading",
    "errorTitle",
    "errorMessage",
    "retry",
    "accessDenied",
    "availableMaterials",
    "recentlyUpdated",
    "mostDownloaded",
    "recommendedMaterials",
    "languageCoverage",
    "readinessScore",
    "allMaterials",
    "favoritesTitle",
    "discoveryTitle",
    "objectionsTitle",
    "emailTitle",
    "socialTitle",
    "campaignPacksTitle",
    "searchPlaceholder",
    "filterCategory",
    "filterLanguage",
    "filterFormat",
    "filterAll",
    "version",
    "publishedDate",
    "lastUpdated",
    "downloads",
    "usageRecommendations",
    "releaseNotes",
    "download",
    "preview",
    "favorite",
    "unfavorite",
    "customizable",
    "emptyTitle",
    "emptyMessage",
    "browseMaterials",
    "actionFailed",
    "faqTitle",
    "faqWhatIs",
    "faqWhatIsAnswer",
    "faqCustomize",
    "faqCustomizeAnswer",
    "faqUpdates",
    "faqUpdatesAnswer",
    "category_product_brochure",
    "category_sales_presentation",
    "category_one_pager",
    "category_executive_summary",
    "category_proposal_template",
    "category_roi_calculator",
    "category_case_study",
    "category_demo_script",
    "category_discovery_guide",
    "category_objection_guide",
    "category_pricing_guide",
    "category_business_pack_guide",
    "category_industry_playbook",
    "category_competitive_comparison",
    "category_email_template",
    "category_social_asset",
    "category_video_material",
    "category_webinar_material",
    "category_campaign_pack",
    "format_pdf",
    "format_pptx",
    "format_docx",
    "format_xlsx",
    "format_video",
    "format_image",
    "format_canva",
    "format_adobe",
  ];
  return Object.fromEntries(keys.map((key) => [key, t(`${p}.${key}`)]));
}

export function categoryLabel(labels: Record<string, string>, category: string): string {
  return labels[`category_${category}`] ?? category.replace(/_/g, " ");
}

export function formatLabel(labels: Record<string, string>, format: string): string {
  return labels[`format_${format}`] ?? format.toUpperCase();
}
