import type { MomentumLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildMomentumLabels(t: Translator): MomentumLabels {
  const p = "customerApp.portalStructure.momentum";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      momentumStatus: t(`${p}.filters.momentumStatus`),
      team: t(`${p}.filters.team`),
      owner: t(`${p}.filters.owner`),
      trend: t(`${p}.filters.trend`),
      priority: t(`${p}.filters.priority`),
      periodFrom: t(`${p}.filters.periodFrom`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      momentumScore: t(`${p}.dashboard.momentumScore`),
      executionTrend: t(`${p}.dashboard.executionTrend`),
      highMomentum: t(`${p}.dashboard.highMomentum`),
      slowing: t(`${p}.dashboard.slowing`),
      stalled: t(`${p}.dashboard.stalled`),
      teamsAttention: t(`${p}.dashboard.teamsAttention`),
      positiveSignals: t(`${p}.dashboard.positiveSignals`),
      openRecommendations: t(`${p}.dashboard.openRecommendations`),
      momentumStatus: t(`${p}.dashboard.momentumStatus`),
    },
    signals: {
      title: t(`${p}.signals.title`),
      goalProgress: t(`${p}.signals.goalProgress`),
      followUpCompletion: t(`${p}.signals.followUpCompletion`),
      commitmentFulfillment: t(`${p}.signals.commitmentFulfillment`),
      decisionImplementation: t(`${p}.signals.decisionImplementation`),
      strategicMovement: t(`${p}.signals.strategicMovement`),
      learningImplementation: t(`${p}.signals.learningImplementation`),
      meetingActionCompletion: t(`${p}.signals.meetingActionCompletion`),
      successInitiativeProgress: t(`${p}.signals.successInitiativeProgress`),
    },
    initiatives: {
      title: t(`${p}.initiatives.title`),
      owner: t(`${p}.initiatives.owner`),
      progress: t(`${p}.initiatives.progress`),
      status: t(`${p}.initiatives.status`),
      trend: t(`${p}.initiatives.trend`),
      blockers: t(`${p}.initiatives.blockers`),
      nextMilestone: t(`${p}.initiatives.nextMilestone`),
      activity: t(`${p}.initiatives.activity`),
    },
    bottlenecks: { title: t(`${p}.bottlenecks.title`) },
    timeline: { title: t(`${p}.timeline.title`) },
    team: { title: t(`${p}.team.title`) },
    statuses: {
      accelerating: t(`${p}.statuses.accelerating`),
      healthy: t(`${p}.statuses.healthy`),
      stable: t(`${p}.statuses.stable`),
      slowing: t(`${p}.statuses.slowing`),
      stalled: t(`${p}.statuses.stalled`),
    },
    trends: {
      improving: t(`${p}.trends.improving`),
      stable: t(`${p}.trends.stable`),
      declining: t(`${p}.trends.declining`),
    },
    priorities: {
      opportunity: t(`${p}.priorities.opportunity`),
      recommended: t(`${p}.priorities.recommended`),
      important: t(`${p}.priorities.important`),
      immediate_attention: t(`${p}.priorities.immediateAttention`),
    },
    recommendations: {
      reviewStalledInitiatives: t(`${p}.recommendations.reviewStalledInitiatives`),
      escalateUnresolvedBlockers: t(`${p}.recommendations.escalateUnresolvedBlockers`),
      celebrateHighPerformingTeams: t(`${p}.recommendations.celebrateHighPerformingTeams`),
      clarifyOwnership: t(`${p}.recommendations.clarifyOwnership`),
      reduceCompetingPriorities: t(`${p}.recommendations.reduceCompetingPriorities`),
      reviewCapacityAssumptions: t(`${p}.recommendations.reviewCapacityAssumptions`),
    },
    bottleneckKeys: {
      approvalDelays: t(`${p}.bottleneckKeys.approvalDelays`),
      resourceConstraints: t(`${p}.bottleneckKeys.resourceConstraints`),
      missingOwnership: t(`${p}.bottleneckKeys.missingOwnership`),
      dependenciesUnresolved: t(`${p}.bottleneckKeys.dependenciesUnresolved`),
      lackOfFollowUp: t(`${p}.bottleneckKeys.lackOfFollowUp`),
      conflictingPriorities: t(`${p}.bottleneckKeys.conflictingPriorities`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      howCalculated: t(`${p}.faq.howCalculated`),
      howCalculatedAnswer: t(`${p}.faq.howCalculatedAnswer`),
      autoIncrease: t(`${p}.faq.autoIncrease`),
      autoIncreaseAnswer: t(`${p}.faq.autoIncreaseAnswer`),
    },
  };
}
