export const BRAND_IDENTITY_PRINCIPLE =
  "Aipify is the product name. Artificial Intelligence is the underlying technology.";

export const BRAND_PERSONALITY_TRAITS = [
  "helpful",
  "professional",
  "calm",
  "trustworthy",
  "proactive",
  "respectful",
  "human-centered",
] as const;

export const BRAND_ADDRESS_RESPONSES = {
  greeting_aipify: "Hello. How can Aipify help you today?",
  greeting_ai_alias: "Hello. Aipify is ready to help.",
  generic_help: "Yes. Aipify can help with that.",
  report_request: "Yes. Aipify can generate reports in multiple formats.",
} as const;

export type BrandAddressIntent = keyof typeof BRAND_ADDRESS_RESPONSES;

/** i18n keys under `customerApp.brandIdentity.address.*`. */
export const BRAND_ADDRESS_I18N_KEYS: Record<BrandAddressIntent, string> = {
  greeting_aipify: "brandIdentity.address.greetingAipify",
  greeting_ai_alias: "brandIdentity.address.greetingAiAlias",
  generic_help: "brandIdentity.address.genericHelp",
  report_request: "brandIdentity.address.reportRequest",
};

/** Global Aipify-first label replacements — customer-facing copy only. Order: longer phrases first. */
export const AIPIFY_FIRST_LABEL_REPLACEMENTS: Array<[RegExp, string]> = [
  [/\bSupport AI Engine\b/gi, "Aipify Support Engine"],
  [/\bSupport AI Principles\b/gi, "Aipify Support Principles"],
  [/\bSupport AI Statistics\b/gi, "Aipify Support Statistics"],
  [/\bSupport AI\b/gi, "Aipify Support"],
  [/\bAI Meeting Assistant\b/gi, "Aipify Meeting Companion"],
  [/\bSecure AI Actions\b/gi, "Secure Aipify Actions"],
  [/\bAI Recommendations\b/gi, "Aipify Insights"],
  [/\bAI Recommendation\b/gi, "Aipify Insight"],
  [/\bResolved by AI\b/gi, "Resolved by Aipify"],
  [/\bEscalated by AI\b/gi, "Escalated by Aipify"],
  [/\bAI Escalation\b/gi, "Escalated by Aipify"],
  [/\bAI Assistant\b/gi, "Aipify Companion"],
  [/\bAI Responses\b/gi, "Aipify Responses"],
  [/\bAI Statistics\b/gi, "Aipify Support Statistics"],
  [/\bAI usage rate\b/gi, "Aipify usage rate"],
  [/\bAI Generated\b/gi, "Generated by Aipify"],
  [/\bAI Summary\b/gi, "Aipify Summary"],
  [/\bAI Notes\b/gi, "Aipify Notes"],
  [/\bAI Notification\b/gi, "Aipify Notification"],
  [/\bAI Support\b/gi, "Aipify Support"],
  [/\bAI Coach\b/gi, "Aipify Coach"],
  [/\bAI Trainer\b/gi, "Aipify Trainer"],
  [/\bAI-powered\b/gi, "Aipify-powered"],
];

/** @deprecated Use AIPIFY_FIRST_LABEL_REPLACEMENTS — retained for Companion Naming Policy imports. */
export const COMPANION_NAMING_REWRITES = AIPIFY_FIRST_LABEL_REPLACEMENTS;

/** Companion Naming Policy — avoid → use pairs (subset documented in companion naming spec). */
export const COMPANION_NAMING_LABEL_REPLACEMENTS: Array<{ avoid: string; use: string }> = [
  { avoid: "AI Assistant", use: "Aipify Companion" },
  { avoid: "AI Support", use: "Aipify Support" },
  { avoid: "Resolved by AI", use: "Resolved by Aipify" },
  { avoid: "Escalated by AI", use: "Escalated by Aipify" },
  { avoid: "AI Escalation", use: "Escalated by Aipify" },
  { avoid: "AI Notes", use: "Aipify Notes" },
  { avoid: "AI Recommendations", use: "Aipify Insights" },
  { avoid: "AI Recommendation", use: "Aipify Insight" },
  { avoid: "AI Summary", use: "Aipify Summary" },
  { avoid: "AI Generated", use: "Generated by Aipify" },
  { avoid: "AI Notification", use: "Aipify Notification" },
  { avoid: "AI Meeting Assistant", use: "Aipify Meeting Companion" },
  { avoid: "AI Coach", use: "Aipify Coach" },
  { avoid: "AI Trainer", use: "Aipify Trainer" },
  { avoid: "AI-powered", use: "Aipify-powered or outcome-focused phrasing" },
  { avoid: "Support AI Engine", use: "Aipify Support Engine" },
  { avoid: "Support AI Principles", use: "Aipify Support Principles" },
  { avoid: "Support AI", use: "Aipify Support" },
  { avoid: "AI Responses", use: "Aipify Responses" },
  { avoid: "AI Statistics", use: "Aipify Support Statistics" },
  { avoid: "AI usage rate", use: "Aipify usage rate" },
  { avoid: "Secure AI Actions", use: "Secure Aipify Actions" },
];

/** Patterns to rewrite in generated or legacy copy. */
export const BRAND_SELF_REFERENCE_REWRITES: Array<[RegExp, string]> = [
  [/\bThe AI has\b/gi, "Aipify has"],
  [/\bThe AI recommends\b/gi, "Aipify recommends"],
  [/\bThe AI thinks\b/gi, "Aipify suggests"],
  [/\bThe AI decided\b/gi, "Aipify prepared a recommendation"],
  [/\bAI recommends\b/gi, "Aipify recommends"],
  [/\bAI has\b/gi, "Aipify has"],
  [/\bArtificial Intelligence has\b/gi, "Aipify has"],
  [/\bThe system believes\b/gi, "Aipify indicates"],
  [/\bThe algorithm recommends\b/gi, "Aipify recommends"],
  [/\bThe machine has\b/gi, "Aipify has"],
];

const AIPIFY_FIRST_LANGUAGE_REWRITES: Array<[RegExp, string]> = [
  ...AIPIFY_FIRST_LABEL_REPLACEMENTS,
  ...BRAND_SELF_REFERENCE_REWRITES,
];

/** Apply ecosystem-wide Aipify-first language policy to user-visible copy. */
export function applyAipifyFirstLanguagePolicy(text: string): string {
  let result = text;
  for (const [pattern, replacement] of AIPIFY_FIRST_LANGUAGE_REWRITES) {
    result = result.replace(pattern, replacement);
  }
  return result;
}

/** @deprecated Use applyAipifyFirstLanguagePolicy — alias for companion naming merges. */
export function applyCompanionNamingPolicy(text: string): string {
  return applyAipifyFirstLanguagePolicy(text);
}
