export const BRAND_IDENTITY_PRINCIPLE =
  "Aipify is the product name. Artificial Intelligence is the underlying technology.";

export const AIPIFY_IDENTITY_RULE =
  "Aipify must never refer to itself simply as \"AI\" in customer-facing experiences. Customers buy Aipify, not artificial intelligence.";

export const AIPIFY_IDENTITY_FOUNDATIONAL_BELIEF =
  "People remember how systems make them feel. Aipify should feel professional, dependable, thoughtful, reassuring, and human-centered — never like \"just AI.\"";

export const FORBIDDEN_IDENTITY_PHRASES = [
  "AI is thinking",
  "Loading AI dashboard",
  "AI assistant",
  "AI chat",
  "AI companion",
  "The AI has completed the task",
  "Artificial intelligence recommends",
  "Loading AI",
  "The AI thinks",
  "The AI decided",
] as const;

export const PREFERRED_COMPANION_STATUS_PHRASES = [
  "Aipify is preparing your workspace.",
  "Aipify is reviewing today's priorities.",
  "Aipify is generating your executive briefing.",
  "Aipify has identified items requiring attention.",
  "Aipify is monitoring approved systems.",
  "Aipify is ready to assist.",
] as const;

export const BRAND_PERSONALITY_TRAITS = [
  "helpful",
  "professional",
  "calm",
  "trustworthy",
  "proactive",
  "respectful",
  "human-centered",
] as const;

export const BRAND_ADDRESS_RESPONSES = {
  greeting_aipify: "Hello. How can Aipify help you today?",
  greeting_ai_alias: "Hello. Aipify is ready to help.",
  generic_help: "Yes. Aipify can help with that.",
  report_request: "Yes. Aipify can generate reports in multiple formats.",
} as const;

export type BrandAddressIntent = keyof typeof BRAND_ADDRESS_RESPONSES;

/** i18n keys under `customerApp.brandIdentity.address.*`. */
export const BRAND_ADDRESS_I18N_KEYS: Record<BrandAddressIntent, string> = {
  greeting_aipify: "brandIdentity.address.greetingAipify",
  greeting_ai_alias: "brandIdentity.address.greetingAiAlias",
  generic_help: "brandIdentity.address.genericHelp",
  report_request: "brandIdentity.address.reportRequest",
};

/** Global Aipify-first label replacements — customer-facing copy only. Order: longer phrases first. */
export const AIPIFY_FIRST_LABEL_REPLACEMENTS: Array<[RegExp, string]> = [
  [/\bSupport AI Engine\b/gi, "Aipify Support Engine"],
  [/\bSupport AI Principles\b/gi, "Aipify Support Principles"],
  [/\bSupport AI Statistics\b/gi, "Aipify Support Statistics"],
  [/\bSupport AI\b/gi, "Aipify Support"],
  [/\bAI Meeting Assistant\b/gi, "Aipify Meeting Companion"],
  [/\bSecure AI Actions\b/gi, "Secure Aipify Actions"],
  [/\bSecure AI Action Engine\b/gi, "Secure Aipify Action Engine"],
  [/\bAI Action Principles\b/gi, "Aipify Action Principles"],
  [/\bAI Action Framework\b/gi, "Aipify Action Framework"],
  [/\bRecent AI Actions\b/gi, "Recent Aipify actions"],
  [/\bPending AI Approvals\b/gi, "Pending Aipify approvals"],
  [/\bAI Activity Timeline\b/gi, "Aipify activity timeline"],
  [/\bAI Events\b/gi, "Aipify activity"],
  [/\bAI Autonomy Level\b/gi, "Companion autonomy level"],
  [/\bAI Autonomy\b/gi, "Companion autonomy"],
  [/\bAI acceptance rate\b/gi, "Aipify acceptance rate"],
  [/\bAI Risk Classification\b/gi, "Aipify risk classification"],
  [/\bAI involved\b/gi, "Aipify involved"],
  [/\bAI action governance\b/gi, "Aipify action governance"],
  [/\bAI actions\b/gi, "Aipify actions"],
  [/\bAI action\b/gi, "Aipify action"],
  [/\bAI-generated\b/gi, "Aipify-generated"],
  [/\bAI usage\b/gi, "Aipify usage"],
  [/\bYour AI Chief of Staff\b/gi, "Your executive companion"],
  [/\bAI learning assistant\b/gi, "Aipify learning companion"],
  [/\bSpecialist AI agents\b/gi, "Specialist Aipify capabilities"],
  [/\bAI Cost Governance Engine\b/gi, "Aipify Cost Governance Engine"],
  [/\bAI Cost Governance\b/gi, "Aipify Cost Governance"],
  [/\bCommerce AI\b/gi, "Aipify Commerce"],
  [/\bLoading AI dashboard\b/gi, "Updating operational overview"],
  [/\bLoading AI\b/gi, "Updating operational overview"],
  [/\bAI is thinking\b/gi, "Aipify is preparing your workspace"],
  [/\bAI Chat\b/gi, "Aipify Companion"],
  [/\bAI Companion\b/gi, "Aipify Companion"],
  [/\bAI Hosts?\b/gi, "Aipify Hosts"],
  [/\bAI Recommendations\b/gi, "Aipify Recommendations"],
  [/\bAI Recommendation\b/gi, "Aipify Recommendation"],
  [/\bAI Insights\b/gi, "Aipify Insights"],
  [/\bResolved by AI\b/gi, "Resolved by Aipify"],
  [/\bEscalated by AI\b/gi, "Escalated by Aipify"],
  [/\bAI Escalation\b/gi, "Escalated by Aipify"],
  [/\bAI Assistant\b/gi, "Aipify Companion"],
  [/\bAI Responses\b/gi, "Aipify Responses"],
  [/\bAI Statistics\b/gi, "Aipify Support Statistics"],
  [/\bAI usage rate\b/gi, "Aipify usage rate"],
  [/\bAI Generated\b/gi, "Generated by Aipify"],
  [/\bAI Summary\b/gi, "Aipify Summary"],
  [/\bAI Notes\b/gi, "Aipify Notes"],
  [/\bAI Notification\b/gi, "Aipify Notification"],
  [/\bAI Support\b/gi, "Aipify Support"],
  [/\bAI Coach\b/gi, "Aipify Coach"],
  [/\bAI Trainer\b/gi, "Aipify Trainer"],
  [/\bAI-powered\b/gi, "Aipify-powered"],
];

/** @deprecated Use AIPIFY_FIRST_LABEL_REPLACEMENTS — retained for Companion Naming Policy imports. */
export const COMPANION_NAMING_REWRITES = AIPIFY_FIRST_LABEL_REPLACEMENTS;

/** Companion Naming Policy — avoid → use pairs (subset documented in companion naming spec). */
export const COMPANION_NAMING_LABEL_REPLACEMENTS: Array<{ avoid: string; use: string }> = [
  { avoid: "AI Assistant", use: "Aipify Companion" },
  { avoid: "AI Support", use: "Aipify Support" },
  { avoid: "Resolved by AI", use: "Resolved by Aipify" },
  { avoid: "Escalated by AI", use: "Escalated by Aipify" },
  { avoid: "AI Escalation", use: "Escalated by Aipify" },
  { avoid: "AI Notes", use: "Aipify Notes" },
  { avoid: "AI Chat", use: "Aipify Companion" },
  { avoid: "AI Companion", use: "Aipify Companion" },
  { avoid: "AI Recommendations", use: "Aipify Recommendations" },
  { avoid: "AI Recommendation", use: "Aipify Recommendation" },
  { avoid: "AI Insights", use: "Aipify Insights" },
  { avoid: "AI Summary", use: "Aipify Summary" },
  { avoid: "AI Generated", use: "Generated by Aipify" },
  { avoid: "AI Notification", use: "Aipify Notification" },
  { avoid: "AI Meeting Assistant", use: "Aipify Meeting Companion" },
  { avoid: "AI Coach", use: "Aipify Coach" },
  { avoid: "AI Trainer", use: "Aipify Trainer" },
  { avoid: "AI-powered", use: "Aipify-powered or outcome-focused phrasing" },
  { avoid: "Support AI Engine", use: "Aipify Support Engine" },
  { avoid: "Support AI Principles", use: "Aipify Support Principles" },
  { avoid: "Support AI", use: "Aipify Support" },
  { avoid: "AI Responses", use: "Aipify Responses" },
  { avoid: "AI Statistics", use: "Aipify Support Statistics" },
  { avoid: "AI usage rate", use: "Aipify usage rate" },
  { avoid: "Secure AI Actions", use: "Secure Aipify Actions" },
];

/** Patterns to rewrite in generated or legacy copy. */
export const BRAND_SELF_REFERENCE_REWRITES: Array<[RegExp, string]> = [
  [/\bThe AI has completed\b/gi, "Aipify has completed"],
  [/\bThe AI has\b/gi, "Aipify has"],
  [/\bThe AI recommends\b/gi, "Aipify recommends"],
  [/\bThe AI thinks\b/gi, "Aipify suggests"],
  [/\bThe AI decided\b/gi, "Aipify prepared a recommendation"],
  [/\bArtificial intelligence recommends\b/gi, "Aipify recommends"],
  [/\bArtificial Intelligence recommends\b/gi, "Aipify recommends"],
  [/\bAI recommends\b/gi, "Aipify recommends"],
  [/\bAI has\b/gi, "Aipify has"],
  [/\bArtificial Intelligence has\b/gi, "Aipify has"],
  [/\bprohibited for autonomous AI\b/gi, "prohibited without human confirmation"],
  [/\bprohibited for AI\b/gi, "prohibited for Aipify without approval"],
  [/\bDaily AI work\b/gi, "Daily companion work"],
  [/\bAI modules\b/gi, "Aipify modules"],
  [/\bAI summaries\b/gi, "Executive summaries"],
  [/\bCommerce AI tools\b/gi, "Aipify Commerce tools"],
  [/\bCommerce AI will\b/gi, "Aipify Commerce will"],
  [/\bResponsible AI commitments\b/gi, "Responsible use commitments"],
  [/\bDocumented AI use cases\b/gi, "Documented Aipify use cases"],
  [/\bThe system believes\b/gi, "Aipify indicates"],
  [/\bThe algorithm recommends\b/gi, "Aipify recommends"],
  [/\bThe machine has\b/gi, "Aipify has"],
];

const AIPIFY_FIRST_LANGUAGE_REWRITES: Array<[RegExp, string]> = [
  ...AIPIFY_FIRST_LABEL_REPLACEMENTS,
  ...BRAND_SELF_REFERENCE_REWRITES,
];

/** Apply ecosystem-wide Aipify-first language policy to user-visible copy. */
export function applyAipifyFirstLanguagePolicy(text: string): string {
  let result = text;
  for (const [pattern, replacement] of AIPIFY_FIRST_LANGUAGE_REWRITES) {
    result = result.replace(pattern, replacement);
  }
  return result;
}

/** @deprecated Use applyAipifyFirstLanguagePolicy — alias for companion naming merges. */
export function applyCompanionNamingPolicy(text: string): string {
  return applyAipifyFirstLanguagePolicy(text);
}
