import type { BusinessPhraseEntry, BusinessPhraseIntentKey } from "./types";

export const BUSINESS_PHRASE_SAFETY_REMINDERS = [
  "I can prepare this for approval.",
  "I will not make changes without authorization.",
  "I can show you a preview first.",
  "I can recommend next steps.",
  "I can automate this within approved limits.",
  "This action requires additional review.",
] as const;

export const BUSINESS_PHRASE_VISION =
  "People should not learn how to speak like software. Aipify should learn how people actually work.";

export const BUSINESS_PHRASE_VOCABULARY: Record<BusinessPhraseIntentKey, BusinessPhraseEntry> = {
  exec_big_picture: {
    key: "exec_big_picture",
    label: "Executive summary",
    humanPhrase: "Give me the big picture.",
    meanings: ["Executive summary", "Key metrics", "Risks and opportunities"],
    response:
      "I can provide a summary of important developments, opportunities and items requiring attention.",
    domain: "executive",
    dashboardPath: "/app/settings/business-insights",
  },
  exec_morning_briefing: {
    key: "exec_morning_briefing",
    label: "Morning briefing",
    humanPhrase: "What should I know before today starts?",
    meanings: ["Daily briefing"],
    response:
      "I can prepare a morning overview including priorities, meetings, customer issues and pending approvals.",
    domain: "executive",
    dashboardPath: "/app/action-center",
  },
  exec_bottleneck: {
    key: "exec_bottleneck",
    label: "Bottleneck analysis",
    humanPhrase: "What's keeping this business from moving faster?",
    meanings: ["Bottleneck analysis"],
    response: "I can identify recurring obstacles and suggest improvement opportunities.",
    domain: "executive",
    dashboardPath: "/app/settings/business-insights",
  },
  exec_worried: {
    key: "exec_worried",
    label: "Risk detection",
    humanPhrase: "Anything I should be worried about?",
    meanings: ["Risk detection"],
    response: "I can highlight situations that may require additional attention.",
    domain: "executive",
  },
  support_waiting_long: {
    key: "support_waiting_long",
    label: "Delayed tickets",
    humanPhrase: "Who's been waiting too long?",
    meanings: ["Detect delayed tickets"],
    response: "I can identify customers who may require faster follow-up.",
    domain: "support",
    mapsToCommand: "support_priority",
    dashboardPath: "/app/settings/support-operations",
  },
  support_most_trouble: {
    key: "support_most_trouble",
    label: "Recurring support issues",
    humanPhrase: "What's causing the most trouble today?",
    meanings: ["Repeated support issues"],
    response: "I can summarize recurring issues and their impact.",
    domain: "support",
    mapsToCommand: "support_priority",
    dashboardPath: "/app/settings/support-operations",
  },
  support_answer_faster: {
    key: "support_answer_faster",
    label: "Support efficiency",
    humanPhrase: "Can we answer these faster?",
    meanings: ["Improve response efficiency"],
    response: "I can identify opportunities to streamline support processes.",
    domain: "support",
    dashboardPath: "/app/settings/support-operations",
  },
  support_angry_customers: {
    key: "support_angry_customers",
    label: "Escalation detection",
    humanPhrase: "Show me the angry customers.",
    meanings: ["Escalation detection"],
    response: "I can identify interactions that may require careful attention.",
    domain: "support",
    mapsToCommand: "support_priority",
    dashboardPath: "/app/settings/support-operations",
  },
  retail_selling_best: {
    key: "retail_selling_best",
    label: "Top products",
    humanPhrase: "What's selling best?",
    meanings: ["Top-performing products"],
    response: "I can identify products currently performing strongly.",
    domain: "retail",
    dashboardPath: "/app/settings/business-insights",
  },
  retail_not_moving: {
    key: "retail_not_moving",
    label: "Slow inventory",
    humanPhrase: "What isn't moving?",
    meanings: ["Slow inventory analysis"],
    response: "I can highlight products that may require promotional attention.",
    domain: "retail",
    dashboardPath: "/app/settings/business-insights",
  },
  retail_push_week: {
    key: "retail_push_week",
    label: "Product prioritization",
    humanPhrase: "What should we push this week?",
    meanings: ["Product prioritization"],
    response: "I can recommend products based on performance and trends.",
    domain: "retail",
    dashboardPath: "/app/settings/business-insights",
  },
  retail_stock: {
    key: "retail_stock",
    label: "Inventory review",
    humanPhrase: "Do we have enough stock?",
    meanings: ["Inventory review"],
    response: "I can identify inventory levels that may require review.",
    domain: "retail",
  },
  retail_cart_abandon: {
    key: "retail_cart_abandon",
    label: "Cart abandonment",
    humanPhrase: "Are customers abandoning their carts?",
    meanings: ["Conversion analysis"],
    response: "I can identify patterns related to incomplete purchases.",
    domain: "retail",
    dashboardPath: "/app/settings/business-insights",
  },
  sales_closest_buying: {
    key: "sales_closest_buying",
    label: "Hot opportunities",
    humanPhrase: "Who's closest to buying?",
    meanings: ["Lead prioritization"],
    response: "I can identify opportunities that appear ready for follow-up.",
    domain: "sales",
    mapsToCommand: "sales_follow_up",
    dashboardPath: "/app/action-center",
  },
  sales_gone_cold: {
    key: "sales_gone_cold",
    label: "Cold leads",
    humanPhrase: "Who has gone cold?",
    meanings: ["Detect inactive leads"],
    response: "I can identify leads that may benefit from renewed engagement.",
    domain: "sales",
    mapsToCommand: "sales_follow_up",
    dashboardPath: "/app/action-center",
  },
  sales_missing_opportunities: {
    key: "sales_missing_opportunities",
    label: "Missed opportunities",
    humanPhrase: "What opportunities are we missing?",
    meanings: ["Opportunity analysis"],
    response: "I can highlight areas where additional attention may generate results.",
    domain: "sales",
    mapsToCommand: "sales_follow_up",
    dashboardPath: "/app/action-center",
  },
  marketing_working: {
    key: "marketing_working",
    label: "Campaign effectiveness",
    humanPhrase: "What's working?",
    meanings: ["Campaign effectiveness"],
    response: "I can identify initiatives that appear to perform well.",
    domain: "marketing",
    dashboardPath: "/app/settings/business-insights",
  },
  marketing_wasting_money: {
    key: "marketing_wasting_money",
    label: "Underperforming spend",
    humanPhrase: "What's wasting money?",
    meanings: ["Performance review"],
    response: "I can identify activities that may require optimization.",
    domain: "marketing",
    dashboardPath: "/app/settings/business-insights",
  },
  marketing_test_next: {
    key: "marketing_test_next",
    label: "Experiment planning",
    humanPhrase: "What should we test next?",
    meanings: ["Experiment planning"],
    response: "I can suggest opportunities for future experimentation.",
    domain: "marketing",
  },
  accounting_paid: {
    key: "accounting_paid",
    label: "Payment review",
    humanPhrase: "Have we been paid?",
    meanings: ["Payment review"],
    response: "I can identify payment statuses based on available records.",
    domain: "accounting",
  },
  accounting_overdue: {
    key: "accounting_overdue",
    label: "Outstanding balances",
    humanPhrase: "What's overdue?",
    meanings: ["Outstanding balances"],
    response: "I can highlight items that may require follow-up.",
    domain: "accounting",
  },
  accounting_surprises: {
    key: "accounting_surprises",
    label: "Financial risk review",
    humanPhrase: "Do we have any surprises coming?",
    meanings: ["Financial risk review"],
    response: "I can summarize obligations and unusual patterns requiring attention.",
    domain: "accounting",
  },
  hr_team_status: {
    key: "hr_team_status",
    label: "Team overview",
    humanPhrase: "How is everyone doing?",
    meanings: ["Team overview"],
    response:
      "I can summarize available indicators related to workload and outstanding tasks.",
    domain: "hr",
  },
  hr_overloaded: {
    key: "hr_overloaded",
    label: "Workload balancing",
    humanPhrase: "Who's overloaded?",
    meanings: ["Workload balancing"],
    response: "I can identify employees or teams that may benefit from support.",
    domain: "hr",
  },
  project_on_track: {
    key: "project_on_track",
    label: "Project health",
    humanPhrase: "Are we on track?",
    meanings: ["Project health review"],
    response: "I can summarize current progress and identify areas requiring attention.",
    domain: "project_management",
    dashboardPath: "/app/action-center",
  },
  project_blocking: {
    key: "project_blocking",
    label: "Bottleneck detection",
    humanPhrase: "What's blocking us?",
    meanings: ["Bottleneck detection"],
    response: "I can identify issues that may be slowing progress.",
    domain: "project_management",
  },
  project_slipped: {
    key: "project_slipped",
    label: "Gap analysis",
    humanPhrase: "What slipped through the cracks?",
    meanings: ["Gap analysis"],
    response: "I can identify items that may have been overlooked.",
    domain: "project_management",
    dashboardPath: "/app/action-center",
  },
  admin_waiting: {
    key: "admin_waiting",
    label: "Pending items",
    humanPhrase: "What's still waiting for me?",
    meanings: ["Pending approvals"],
    response: "I can summarize actions requiring your attention.",
    domain: "admin",
    dashboardPath: "/app/action-center",
  },
  admin_while_away: {
    key: "admin_while_away",
    label: "Since-last-login overview",
    humanPhrase: "What happened while I was away?",
    meanings: ["Since-last-login overview"],
    response: "I can prepare a summary of important events and developments.",
    domain: "admin",
    dashboardPath: "/app/action-center",
  },
  admin_day_looking: {
    key: "admin_day_looking",
    label: "Daily agenda",
    humanPhrase: "What's my day looking like?",
    meanings: ["Daily agenda"],
    response: "I can summarize your upcoming schedule and priorities.",
    domain: "admin",
    dashboardPath: "/app/assistant/calendars",
  },
  productivity_organized: {
    key: "productivity_organized",
    label: "Get organized",
    humanPhrase: "Help me get organized.",
    meanings: ["Structure work"],
    response: "I can create a clear overview of priorities and next steps.",
    domain: "productivity",
    dashboardPath: "/app/action-center",
  },
  productivity_drowning: {
    key: "productivity_drowning",
    label: "Reduce overload",
    humanPhrase: "I'm drowning.",
    meanings: ["Reduce overload"],
    response: "I can help prioritize what deserves attention first.",
    domain: "productivity",
  },
  productivity_where_start: {
    key: "productivity_where_start",
    label: "First actions",
    humanPhrase: "Where do I even start?",
    meanings: ["Identify first actions"],
    response: "I can suggest an action plan to help you move forward.",
    domain: "productivity",
  },
  aipify_what_would_you_do: {
    key: "aipify_what_would_you_do",
    label: "Recommendation request",
    humanPhrase: "What would you do?",
    meanings: ["Recommendation request"],
    response:
      "I can suggest options based on available information, but important decisions remain yours.",
    domain: "aipify_specific",
  },
  aipify_take_care: {
    key: "aipify_take_care",
    label: "Execution evaluation",
    humanPhrase: "Can you take care of this?",
    meanings: ["Evaluate execution possibility"],
    response:
      "I can determine whether this can be prepared, approved or automated within your permissions.",
    domain: "aipify_specific",
    dashboardPath: "/app/action-center",
  },
  aipify_automate: {
    key: "aipify_automate",
    label: "Automation assessment",
    humanPhrase: "Can this be automated?",
    meanings: ["Automation assessment"],
    response: "I can evaluate whether this process is suitable for automation.",
    domain: "aipify_specific",
    mapsToCommand: "automation_rule",
    dashboardPath: "/app/action-center",
  },
  aipify_prevent_repeat: {
    key: "aipify_prevent_repeat",
    label: "Prevent recurrence",
    humanPhrase: "Make sure this doesn't happen again.",
    meanings: ["Improvement opportunity"],
    response:
      "I can suggest safeguards or automation rules that may reduce future occurrences.",
    domain: "aipify_specific",
    mapsToCommand: "automation_rule",
    dashboardPath: "/app/action-center",
  },
  vision_catch_up: {
    key: "vision_catch_up",
    label: "Catch up",
    humanPhrase: "Can you help me catch up?",
    meanings: ["Review backlog", "Prioritize outstanding work", "Suggest next steps"],
    response:
      "I can review what needs attention and help you prioritize the most important items to catch up.",
    domain: "productivity",
    dashboardPath: "/app/action-center",
  },
  vision_forgot_important: {
    key: "vision_forgot_important",
    label: "Forgotten items",
    humanPhrase: "Did I forget something important?",
    meanings: ["Gap detection", "Follow-up review"],
    response:
      "I can review outstanding items and highlight anything that may need your attention.",
    domain: "admin",
    dashboardPath: "/app/action-center",
  },
  vision_take_a_look: {
    key: "vision_take_a_look",
    label: "Review request",
    humanPhrase: "Take a look at this.",
    meanings: ["Review content", "Summarize context", "Suggest actions"],
    response:
      "I can review this and summarize what stands out, along with suggested next steps.",
    domain: "aipify_specific",
  },
  vision_make_sense: {
    key: "vision_make_sense",
    label: "Organize chaos",
    humanPhrase: "Can you make sense of this mess?",
    meanings: ["Structure information", "Identify priorities", "Create action plan"],
    response:
      "I can organize this into a clearer structure and suggest practical next steps.",
    domain: "productivity",
  },
};

export function getBusinessPhraseVocabulary(key: BusinessPhraseIntentKey): BusinessPhraseEntry {
  return BUSINESS_PHRASE_VOCABULARY[key];
}
