import type { ApprovalDelegationLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildApprovalDelegationLabels(t: Translator): ApprovalDelegationLabels {
  const p = "customerApp.actionCenter.approvalDelegation";
  return {
    centerTitle: t(`${p}.centerTitle`),
    centerSubtitle: t(`${p}.centerSubtitle`),
    tabImpact: t(`${p}.tabImpact`),
    tabApprovals: t(`${p}.tabApprovals`),
    humanOversight: t(`${p}.humanOversight`),
    sections: {
      workflow: t(`${p}.sections.workflow`),
      delegation: t(`${p}.sections.delegation`),
      sla: t(`${p}.sections.sla`),
      audit: t(`${p}.sections.audit`),
      executive: t(`${p}.sections.executive`),
      decisions: t(`${p}.sections.decisions`),
      recommendations: t(`${p}.sections.recommendations`),
      widgets: t(`${p}.sections.widgets`),
      knowledgeCenter: t(`${p}.sections.knowledgeCenter`),
    },
    workflow: {
      type: t(`${p}.workflow.type`),
      steps: t(`${p}.workflow.steps`),
      rules: t(`${p}.workflow.rules`),
      types: {
        none: t(`${p}.workflow.types.none`),
        single: t(`${p}.workflow.types.single`),
        multi_step: t(`${p}.workflow.types.multiStep`),
        parallel: t(`${p}.workflow.types.parallel`),
        executive: t(`${p}.workflow.types.executive`),
      },
    },
    delegation: {
      currentOwner: t(`${p}.delegation.currentOwner`),
      previousOwners: t(`${p}.delegation.previousOwners`),
      history: t(`${p}.delegation.history`),
      assign: t(`${p}.delegation.assign`),
      delegateTo: t(`${p}.delegation.delegateTo`),
    },
    sla: {
      status: t(`${p}.sla.status`),
      hoursWaiting: t(`${p}.sla.hoursWaiting`),
      deadline: t(`${p}.sla.deadline`),
      statuses: {
        on_track: t(`${p}.sla.statuses.onTrack`),
        approaching_deadline: t(`${p}.sla.statuses.approachingDeadline`),
        overdue: t(`${p}.sla.statuses.overdue`),
        escalated: t(`${p}.sla.statuses.escalated`),
      },
    },
    decisions: {
      approve: t(`${p}.decisions.approve`),
      approveWithConditions: t(`${p}.decisions.approveWithConditions`),
      reject: t(`${p}.decisions.reject`),
      requestInformation: t(`${p}.decisions.requestInformation`),
      delegateReview: t(`${p}.decisions.delegateReview`),
      requireExecutiveOversight: t(`${p}.decisions.requireExecutiveOversight`),
      escalate: t(`${p}.decisions.escalate`),
      returnForClarification: t(`${p}.decisions.returnForClarification`),
      comment: t(`${p}.decisions.comment`),
      conditions: t(`${p}.decisions.conditions`),
      submit: t(`${p}.decisions.submit`),
    },
    recommendations: {
      intro: t(`${p}.recommendations.intro`),
      optional: t(`${p}.recommendations.optional`),
      reasons: {
        role_permissions: t(`${p}.recommendations.reasons.rolePermissions`),
        historical_ownership: t(`${p}.recommendations.reasons.historicalOwnership`),
        department_responsibility: t(`${p}.recommendations.reasons.departmentResponsibility`),
        workload_balancing: t(`${p}.recommendations.reasons.workloadBalancing`),
        subject_matter_expertise: t(`${p}.recommendations.reasons.subjectMatterExpertise`),
      },
    },
    executive: {
      healthScore: t(`${p}.executive.healthScore`),
      criticalBlocked: t(`${p}.executive.criticalBlocked`),
      highRiskAwaiting: t(`${p}.executive.highRiskAwaiting`),
      avgCycle: t(`${p}.executive.avgCycle`),
      delegationEffectiveness: t(`${p}.executive.delegationEffectiveness`),
    },
    widgets: {
      pendingApprovals: t(`${p}.widgets.pendingApprovals`),
      awaitingMyReview: t(`${p}.widgets.awaitingMyReview`),
      recentlyApproved: t(`${p}.widgets.recentlyApproved`),
      rejected: t(`${p}.widgets.rejected`),
      escalated: t(`${p}.widgets.escalated`),
      executiveDecisions: t(`${p}.widgets.executiveDecisions`),
      empty: t(`${p}.widgets.empty`),
      viewAction: t(`${p}.widgets.viewAction`),
    },
    notifications: {
      approvalRequired: t(`${p}.notifications.approvalRequired`),
      approvalCompleted: t(`${p}.notifications.approvalCompleted`),
      delegated: t(`${p}.notifications.delegated`),
      escalated: t(`${p}.notifications.escalated`),
      overdue: t(`${p}.notifications.overdue`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIsDelegation: t(`${p}.faq.whatIsDelegation`),
      whatIsDelegationAnswer: t(`${p}.faq.whatIsDelegationAnswer`),
      whatIsWorkflow: t(`${p}.faq.whatIsWorkflow`),
      whatIsWorkflowAnswer: t(`${p}.faq.whatIsWorkflowAnswer`),
      autoApprove: t(`${p}.faq.autoApprove`),
      autoApproveAnswer: t(`${p}.faq.autoApproveAnswer`),
      howApproversSelected: t(`${p}.faq.howApproversSelected`),
      howApproversSelectedAnswer: t(`${p}.faq.howApproversSelectedAnswer`),
      delayedApprovals: t(`${p}.faq.delayedApprovals`),
      delayedApprovalsAnswer: t(`${p}.faq.delayedApprovalsAnswer`),
    },
    empty: t(`${p}.empty`),
    principle: t(`${p}.principle`),
    actions: { back: t(`${p}.actions.back`) },
  };
}
