import type { Translator } from "@/lib/i18n/translate";

export function buildLicenseManagementLabels(t: Translator) {
  const p = "customerApp.licenseManagement";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    commercialPrinciple: t(`${p}.commercialPrinciple`),
    accessDenied: t(`${p}.accessDenied`),
    appLicense: t(`${p}.appLicense`),
    domainLicenses: t(`${p}.domainLicenses`),
    capacity: t(`${p}.capacity`),
    businessPacks: t(`${p}.businessPacks`),
    usage: t(`${p}.usage`),
    renewals: t(`${p}.renewals`),
    status: t(`${p}.status`),
    domains: t(`${p}.domains`),
    employees: t(`${p}.employees`),
    packs: t(`${p}.packs`),
    renewalDate: t(`${p}.renewalDate`),
    upgradeRequired: t(`${p}.upgradeRequired`),
    nearCapacity: t(`${p}.nearCapacity`),
    unlimited: t(`${p}.unlimited`),
    upgradeCenter: t(`${p}.upgradeCenter`),
    purchaseCapacity: t(`${p}.purchaseCapacity`),
    purchaseDomain: t(`${p}.purchaseDomain`),
    upgradeSubscription: t(`${p}.upgradeSubscription`),
    installPacks: t(`${p}.installPacks`),
    enterpriseUpgrade: t(`${p}.enterpriseUpgrade`),
    reports: t(`${p}.reports`),
    licenseUsage: t(`${p}.licenseUsage`),
    domainUsage: t(`${p}.domainUsage`),
    employeeCapacity: t(`${p}.employeeCapacity`),
    packAdoption: t(`${p}.packAdoption`),
    auditLog: t(`${p}.auditLog`),
    billing: t(`${p}.billing`),
    trustCenter: t(`${p}.trustCenter`),
    manageDomains: t(`${p}.manageDomains`),
    browseStore: t(`${p}.browseStore`),
    manageEmployees: t(`${p}.manageEmployees`),
    noPacks: t(`${p}.noPacks`),
    noPacksHint: t(`${p}.noPacksHint`),
    domainInstallations: t(`${p}.domainInstallations`),
    active: t(`${p}.active`),
    trial: t(`${p}.trial`),
    gracePeriod: t(`${p}.gracePeriod`),
    suspended: t(`${p}.suspended`),
    cancelled: t(`${p}.cancelled`),
    purchaseCapacityConfirm: t(`${p}.purchaseCapacityConfirm`),
    back: t(`${p}.back`),
  };
}

export type LicenseManagementLabels = ReturnType<typeof buildLicenseManagementLabels>;
