import type { CapabilityCenterLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildCapabilityCenterLabels(t: Translator): CapabilityCenterLabels {
  const p = "customerApp.portalStructure.capabilityCenter";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    principle: t(`${p}.principle`),
    sections: {
      dashboard: t(`${p}.sections.dashboard`),
      categories: t(`${p}.sections.categories`),
      detail: t(`${p}.sections.detail`),
      recommendations: t(`${p}.sections.recommendations`),
      progress: t(`${p}.sections.progress`),
      selfAssessment: t(`${p}.sections.selfAssessment`),
    },
    dashboard: {
      overallScore: t(`${p}.dashboard.overallScore`),
      overallLevel: t(`${p}.dashboard.overallLevel`),
      trend: t(`${p}.dashboard.trend`),
      highest: t(`${p}.dashboard.highest`),
      lowest: t(`${p}.dashboard.lowest`),
      focusAreas: t(`${p}.dashboard.focusAreas`),
      advisory: t(`${p}.dashboard.advisory`),
    },
    trends: {
      improving: t(`${p}.trends.improving`),
      stable: t(`${p}.trends.stable`),
      declining: t(`${p}.trends.declining`),
    },
    levels: {
      emerging: t(`${p}.levels.emerging`),
      developing: t(`${p}.levels.developing`),
      established: t(`${p}.levels.established`),
      optimized: t(`${p}.levels.optimized`),
      exemplary: t(`${p}.levels.exemplary`),
    },
    levelNumbers: {
      1: t(`${p}.levelNumbers.1`),
      2: t(`${p}.levelNumbers.2`),
      3: t(`${p}.levelNumbers.3`),
      4: t(`${p}.levelNumbers.4`),
      5: t(`${p}.levelNumbers.5`),
    },
    categories: {
      governance: t(`${p}.categories.governance`),
      operations: t(`${p}.categories.operations`),
      collaboration: t(`${p}.categories.collaboration`),
      knowledge_management: t(`${p}.categories.knowledgeManagement`),
      customer_success: t(`${p}.categories.customerSuccess`),
      security: t(`${p}.categories.security`),
      integrations: t(`${p}.categories.integrations`),
      business_pack_adoption: t(`${p}.categories.businessPackAdoption`),
      decision_processes: t(`${p}.categories.decisionProcesses`),
      organizational_memory: t(`${p}.categories.organizationalMemory`),
    },
    strengths: {
      governanceRoles: t(`${p}.strengths.governanceRoles`),
      operationsFollowThrough: t(`${p}.strengths.operationsFollowThrough`),
      collaborationTeam: t(`${p}.strengths.collaborationTeam`),
      knowledgeFoundation: t(`${p}.strengths.knowledgeFoundation`),
      customerSuccessAdoption: t(`${p}.strengths.customerSuccessAdoption`),
      securityAwareness: t(`${p}.strengths.securityAwareness`),
      integrationsConnected: t(`${p}.strengths.integrationsConnected`),
      packsActive: t(`${p}.strengths.packsActive`),
      decisionsTracked: t(`${p}.strengths.decisionsTracked`),
      memoryActivity: t(`${p}.strengths.memoryActivity`),
    },
    improvements: {
      governanceApprovals: t(`${p}.improvements.governanceApprovals`),
      operationsBacklog: t(`${p}.improvements.operationsBacklog`),
      collaborationEngagement: t(`${p}.improvements.collaborationEngagement`),
      knowledgeDepth: t(`${p}.improvements.knowledgeDepth`),
      customerSuccessExpansion: t(`${p}.improvements.customerSuccessExpansion`),
      securityHardening: t(`${p}.improvements.securityHardening`),
      integrationsExpansion: t(`${p}.improvements.integrationsExpansion`),
      packsBreadth: t(`${p}.improvements.packsBreadth`),
      decisionsFormalization: t(`${p}.improvements.decisionsFormalization`),
      memoryDocumentation: t(`${p}.improvements.memoryDocumentation`),
    },
    actions: {
      governanceAction: t(`${p}.actions.governanceAction`),
      operationsAction: t(`${p}.actions.operationsAction`),
      collaborationAction: t(`${p}.actions.collaborationAction`),
      knowledgeAction: t(`${p}.actions.knowledgeAction`),
      customerSuccessAction: t(`${p}.actions.customerSuccessAction`),
      securityAction: t(`${p}.actions.securityAction`),
      integrationsAction: t(`${p}.actions.integrationsAction`),
      packsAction: t(`${p}.actions.packsAction`),
      decisionsAction: t(`${p}.actions.decisionsAction`),
      memoryAction: t(`${p}.actions.memoryAction`),
    },
    capabilities: {
      approvals: t(`${p}.capabilities.approvals`),
      followUps: t(`${p}.capabilities.followUps`),
      teamManagement: t(`${p}.capabilities.teamManagement`),
      knowledgeCenter: t(`${p}.capabilities.knowledgeCenter`),
      successCenter: t(`${p}.capabilities.successCenter`),
      accountSecurity: t(`${p}.capabilities.accountSecurity`),
      integrationsHub: t(`${p}.capabilities.integrationsHub`),
      businessPacks: t(`${p}.capabilities.businessPacks`),
      decisionCenter: t(`${p}.capabilities.decisionCenter`),
      activityHistory: t(`${p}.capabilities.activityHistory`),
    },
    resources: {
      knowledgeGovernance: t(`${p}.resources.knowledgeGovernance`),
      knowledgeOperations: t(`${p}.resources.knowledgeOperations`),
      knowledgeCollaboration: t(`${p}.resources.knowledgeCollaboration`),
      knowledgeResources: t(`${p}.resources.knowledgeResources`),
      knowledgeCustomerSuccess: t(`${p}.resources.knowledgeCustomerSuccess`),
      knowledgeSecurity: t(`${p}.resources.knowledgeSecurity`),
      knowledgeIntegrations: t(`${p}.resources.knowledgeIntegrations`),
      knowledgeBusinessPacks: t(`${p}.resources.knowledgeBusinessPacks`),
      knowledgeDecisions: t(`${p}.resources.knowledgeDecisions`),
      knowledgeMemory: t(`${p}.resources.knowledgeMemory`),
    },
    recommendations: {
      enable2fa: t(`${p}.recommendations.enable2fa`),
      improveFollowUps: t(`${p}.recommendations.improveFollowUps`),
      expandPacks: t(`${p}.recommendations.expandPacks`),
      formalizeDecisions: t(`${p}.recommendations.formalizeDecisions`),
      adminCoverage: t(`${p}.recommendations.adminCoverage`),
      strengthenDocs: t(`${p}.recommendations.strengthenDocs`),
      continueFocus: t(`${p}.recommendations.continueFocus`),
    },
    progress: {
      history: t(`${p}.progress.history`),
      milestones: t(`${p}.progress.milestones`),
      continuedFocus: t(`${p}.progress.continuedFocus`),
    },
    selfAssessment: {
      category: t(`${p}.selfAssessment.category`),
      level: t(`${p}.selfAssessment.level`),
      notes: t(`${p}.selfAssessment.notes`),
      submit: t(`${p}.selfAssessment.submit`),
      success: t(`${p}.selfAssessment.success`),
      selectCategory: t(`${p}.selfAssessment.selectCategory`),
    },
    detail: {
      strengths: t(`${p}.detail.strengths`),
      improvements: t(`${p}.detail.improvements`),
      actions: t(`${p}.detail.actions`),
      capabilities: t(`${p}.detail.capabilities`),
      resources: t(`${p}.detail.resources`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      howDetermined: t(`${p}.faq.howDetermined`),
      howDeterminedAnswer: t(`${p}.faq.howDeterminedAnswer`),
      comparison: t(`${p}.faq.comparison`),
      comparisonAnswer: t(`${p}.faq.comparisonAnswer`),
    },
  };
}
