import type { GovernanceLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildGovernanceLabels(t: Translator): GovernanceLabels {
  const p = "customerApp.portalStructure.businessPackGovernance";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      governanceStatus: t(`${p}.filters.governanceStatus`),
      department: t(`${p}.filters.department`),
      primaryOwner: t(`${p}.filters.primaryOwner`),
      backupOwner: t(`${p}.filters.backupOwner`),
      reviewFrequency: t(`${p}.filters.reviewFrequency`),
      periodFrom: t(`${p}.filters.periodFrom`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      totalPacks: t(`${p}.dashboard.totalPacks`),
      packsWithOwners: t(`${p}.dashboard.packsWithOwners`),
      packsMissingOwners: t(`${p}.dashboard.packsMissingOwners`),
      governanceHealthScore: t(`${p}.dashboard.governanceHealthScore`),
      upcomingReviews: t(`${p}.dashboard.upcomingReviews`),
      ownershipChanges: t(`${p}.dashboard.ownershipChanges`),
      executiveSummary: t(`${p}.dashboard.executiveSummary`),
      governanceInsights: t(`${p}.dashboard.governanceInsights`),
      recommendedActions: t(`${p}.dashboard.recommendedActions`),
      timeline: t(`${p}.dashboard.timeline`),
      healthOverview: t(`${p}.dashboard.healthOverview`),
    },
    card: {
      primaryOwner: t(`${p}.card.primaryOwner`),
      backupOwner: t(`${p}.card.backupOwner`),
      department: t(`${p}.card.department`),
      governanceStatus: t(`${p}.card.governanceStatus`),
      healthStatus: t(`${p}.card.healthStatus`),
      lastReview: t(`${p}.card.lastReview`),
      nextReview: t(`${p}.card.nextReview`),
      relatedRisks: t(`${p}.card.relatedRisks`),
      recommendedActions: t(`${p}.card.recommendedActions`),
      reviewFrequency: t(`${p}.card.reviewFrequency`),
      viewDetails: t(`${p}.card.viewDetails`),
      completeReview: t(`${p}.card.completeReview`),
    },
    review: {
      title: t(`${p}.review.title`),
      notes: t(`${p}.review.notes`),
      frequency: t(`${p}.review.frequency`),
      submit: t(`${p}.review.submit`),
      success: t(`${p}.review.success`),
      governanceNote: t(`${p}.review.governanceNote`),
    },
    governanceStatuses: {
      well_governed: t(`${p}.governanceStatuses.wellGoverned`),
      healthy: t(`${p}.governanceStatuses.healthy`),
      stable: t(`${p}.governanceStatuses.stable`),
      requires_review: t(`${p}.governanceStatuses.requiresReview`),
      governance_gap_identified: t(`${p}.governanceStatuses.governanceGapIdentified`),
    },
    healthStatuses: {
      thriving: t(`${p}.healthStatuses.thriving`),
      healthy: t(`${p}.healthStatuses.healthy`),
      stable: t(`${p}.healthStatuses.stable`),
      requires_attention: t(`${p}.healthStatuses.requiresAttention`),
      critical_governance_gap: t(`${p}.healthStatuses.criticalGovernanceGap`),
    },
    reviewFrequencies: {
      monthly: t(`${p}.reviewFrequencies.monthly`),
      quarterly: t(`${p}.reviewFrequencies.quarterly`),
      semi_annually: t(`${p}.reviewFrequencies.semiAnnually`),
      annually: t(`${p}.reviewFrequencies.annually`),
      custom: t(`${p}.reviewFrequencies.custom`),
    },
    recommendations: {
      assignPrimaryOwner: t(`${p}.recommendations.assignPrimaryOwner`),
      appointBackupOwner: t(`${p}.recommendations.appointBackupOwner`),
      scheduleOverdueReviews: t(`${p}.recommendations.scheduleOverdueReviews`),
      reduceOwnershipConcentration: t(`${p}.recommendations.reduceOwnershipConcentration`),
      improveDepartmentalAccountability: t(`${p}.recommendations.improveDepartmentalAccountability`),
      reviewGovernanceResponsibilities: t(`${p}.recommendations.reviewGovernanceResponsibilities`),
    },
    insights: {
      packsWithoutOwnership: t(`${p}.insights.packsWithoutOwnership`),
      packsOverdueReview: t(`${p}.insights.packsOverdueReview`),
      ownershipConcentration: t(`${p}.insights.ownershipConcentration`),
      strongestDepartments: t(`${p}.insights.strongestDepartments`),
      improvementOpportunities: t(`${p}.insights.improvementOpportunities`),
    },
    timelineEvents: {
      ownership_assigned: t(`${p}.timelineEvents.ownershipAssigned`),
      review_completed: t(`${p}.timelineEvents.reviewCompleted`),
      governance_change: t(`${p}.timelineEvents.governanceChange`),
      recommendation_accepted: t(`${p}.timelineEvents.recommendationAccepted`),
      governance_risk_identified: t(`${p}.timelineEvents.governanceRiskIdentified`),
      governance_milestone: t(`${p}.timelineEvents.governanceMilestone`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      whyOwners: t(`${p}.faq.whyOwners`),
      whyOwnersAnswer: t(`${p}.faq.whyOwnersAnswer`),
      autoAssign: t(`${p}.faq.autoAssign`),
      autoAssignAnswer: t(`${p}.faq.autoAssignAnswer`),
    },
  };
}
