import type { Translator } from "@/lib/i18n/translate";

export function buildAutomationOperationsLabels(t: Translator) {
  const p = "customerApp.automationOperations";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    workflows: t(`${p}.workflows`),
    triggers: t(`${p}.triggers`),
    actions: t(`${p}.actions`),
    approvals: t(`${p}.approvals`),
    conditions: t(`${p}.conditions`),
    templates: t(`${p}.templates`),
    history: t(`${p}.history`),
    reports: t(`${p}.reports`),
    activeWorkflows: t(`${p}.activeWorkflows`),
    draftWorkflows: t(`${p}.draftWorkflows`),
    needsReview: t(`${p}.needsReview`),
    approvalRequired: t(`${p}.approvalRequired`),
    disabledWorkflows: t(`${p}.disabledWorkflows`),
    templatesAvailable: t(`${p}.templatesAvailable`),
    executions7d: t(`${p}.executions7d`),
    successRate: t(`${p}.successRate`),
    createWorkflow: t(`${p}.createWorkflow`),
    activateWorkflow: t(`${p}.activateWorkflow`),
    disableWorkflow: t(`${p}.disableWorkflow`),
    executeWorkflow: t(`${p}.executeWorkflow`),
    grantApproval: t(`${p}.grantApproval`),
    createFromTemplate: t(`${p}.createFromTemplate`),
    emergencyStop: t(`${p}.emergencyStop`),
    resumeAutomation: t(`${p}.resumeAutomation`),
    workflowName: t(`${p}.workflowName`),
    noWorkflows: t(`${p}.noWorkflows`),
    noTemplates: t(`${p}.noTemplates`),
    noHistory: t(`${p}.noHistory`),
    noApprovals: t(`${p}.noApprovals`),
    emptyHint: t(`${p}.emptyHint`),
    companionInsights: t(`${p}.companionInsights`),
    companionIntegration: t(`${p}.companionIntegration`),
    safetyControls: t(`${p}.safetyControls`),
    auditLog: t(`${p}.auditLog`),
    workflowsTitle: t(`${p}.workflowsTitle`),
    templatesTitle: t(`${p}.templatesTitle`),
    monitoring: t(`${p}.monitoring`),
    pendingApprovals: t(`${p}.pendingApprovals`),
    failedExecutions: t(`${p}.failedExecutions`),
    approvalAware: t(`${p}.approvalAware`),
    save: t(`${p}.save`),
  };
}

export type AutomationOperationsLabels = ReturnType<typeof buildAutomationOperationsLabels>;
