import type { Translator } from "@/lib/i18n/translate";

export function buildAosCenterLabels(t: Translator) {
  const p = "customerApp.aosCenter";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    privacyNote: t(`${p}.privacyNote`),
    loading: t(`${p}.loading`),
    empty: t(`${p}.empty`),
    refresh: t(`${p}.refresh`),
    companionRecommendations: t(`${p}.companionRecommendations`),
    noRecords: t(`${p}.noRecords`),
    unifiedOrgModel: t(`${p}.unifiedOrgModel`),
    unifiedEntityEngine: t(`${p}.unifiedEntityEngine`),
    crossModuleIntelligence: t(`${p}.crossModuleIntelligence`),
    organizationalAwareness: t(`${p}.organizationalAwareness`),
    executiveOperatingModel: t(`${p}.executiveOperatingModel`),
    businessPackOrchestration: t(`${p}.businessPackOrchestration`),
    digitalTwinConnections: t(`${p}.digitalTwinConnections`),
    globalContextEngine: t(`${p}.globalContextEngine`),
    globalSearchEngine: t(`${p}.globalSearchEngine`),
    globalReportingEngine: t(`${p}.globalReportingEngine`),
    organizationalHealthScore: t(`${p}.organizationalHealthScore`),
    platformIntelligenceBus: t(`${p}.platformIntelligenceBus`),
    companionOrchestration: t(`${p}.companionOrchestration`),
    businessOsApi: t(`${p}.businessOsApi`),
    maturityCheckpoint: t(`${p}.maturityCheckpoint`),
    executiveDashboard: t(`${p}.executiveDashboard`),
    mobileAccess: t(`${p}.mobileAccess`),
    sections: {
      overview: t(`${p}.sections.overview`),
      organization: t(`${p}.sections.organization`),
      operations: t(`${p}.sections.operations`),
      companion: t(`${p}.sections.companion`),
      intelligence: t(`${p}.sections.intelligence`),
      businessPacks: t(`${p}.sections.businessPacks`),
      signals: t(`${p}.sections.signals`),
      governance: t(`${p}.sections.governance`),
      reports: t(`${p}.sections.reports`),
    },
    stats: {
      orgDimensions: t(`${p}.stats.orgDimensions`),
      entities: t(`${p}.stats.entities`),
      healthDimensions: t(`${p}.stats.healthDimensions`),
      intelligenceSignals: t(`${p}.stats.intelligenceSignals`),
      orchestrationLayers: t(`${p}.stats.orchestrationLayers`),
      reportTypes: t(`${p}.stats.reportTypes`),
    },
    executive: {
      connectedModules: t(`${p}.executive.connectedModules`),
      orgHealthScore: t(`${p}.executive.orgHealthScore`),
      orgHealthBand: t(`${p}.executive.orgHealthBand`),
      activeSignals: t(`${p}.executive.activeSignals`),
      crossModuleChains: t(`${p}.executive.crossModuleChains`),
      unifiedEntities: t(`${p}.executive.unifiedEntities`),
      searchDomains: t(`${p}.executive.searchDomains`),
    },
    healthBands: {
      excellent: t(`${p}.healthBands.excellent`),
      healthy: t(`${p}.healthBands.healthy`),
      attention: t(`${p}.healthBands.attention`),
      risk: t(`${p}.healthBands.risk`),
    },
  };
}
