import type { OrganizationalGoalsLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildOrganizationalGoalsLabels(t: Translator): OrganizationalGoalsLabels {
  const p = "customerApp.portalStructure.organizationalGoals";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    filters: {
      search: t(`${p}.filters.search`),
      goalType: t(`${p}.filters.goalType`),
      status: t(`${p}.filters.status`),
      priority: t(`${p}.filters.priority`),
      owner: t(`${p}.filters.owner`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      active: t(`${p}.dashboard.active`),
      achievedQuarter: t(`${p}.dashboard.achievedQuarter`),
      attention: t(`${p}.dashboard.attention`),
      upcoming: t(`${p}.dashboard.upcoming`),
    },
    form: {
      createTitle: t(`${p}.form.createTitle`),
      title: t(`${p}.form.title`),
      description: t(`${p}.form.description`),
      goalType: t(`${p}.form.goalType`),
      priority: t(`${p}.form.priority`),
      status: t(`${p}.form.status`),
      startDate: t(`${p}.form.startDate`),
      targetDate: t(`${p}.form.targetDate`),
      successCriteria: t(`${p}.form.successCriteria`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
    },
    card: {
      progress: t(`${p}.card.progress`),
      owner: t(`${p}.card.owner`),
      targetDate: t(`${p}.card.targetDate`),
      view: t(`${p}.card.view`),
    },
    detail: {
      overview: t(`${p}.detail.overview`),
      successCriteria: t(`${p}.detail.successCriteria`),
      contributors: t(`${p}.detail.contributors`),
      progressTimeline: t(`${p}.detail.progressTimeline`),
      relatedActions: t(`${p}.detail.relatedActions`),
      relatedDecisions: t(`${p}.detail.relatedDecisions`),
      relatedFollowUps: t(`${p}.detail.relatedFollowUps`),
      activityHistory: t(`${p}.detail.activityHistory`),
      auditHistory: t(`${p}.detail.auditHistory`),
      recommendations: t(`${p}.detail.recommendations`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
      progressUpdate: t(`${p}.detail.progressUpdate`),
      updateType: t(`${p}.detail.updateType`),
      progressPercent: t(`${p}.detail.progressPercent`),
      milestoneTitle: t(`${p}.detail.milestoneTitle`),
      notes: t(`${p}.detail.notes`),
      recordProgress: t(`${p}.detail.recordProgress`),
    },
    goalTypes: {
      strategic: t(`${p}.goalTypes.strategic`),
      operational: t(`${p}.goalTypes.operational`),
      customer_experience: t(`${p}.goalTypes.customerExperience`),
      employee_experience: t(`${p}.goalTypes.employeeExperience`),
      revenue: t(`${p}.goalTypes.revenue`),
      security: t(`${p}.goalTypes.security`),
      growth: t(`${p}.goalTypes.growth`),
      innovation: t(`${p}.goalTypes.innovation`),
      compliance: t(`${p}.goalTypes.compliance`),
    },
    statuses: {
      draft: t(`${p}.statuses.draft`),
      active: t(`${p}.statuses.active`),
      at_risk: t(`${p}.statuses.atRisk`),
      on_track: t(`${p}.statuses.onTrack`),
      achieved: t(`${p}.statuses.achieved`),
      cancelled: t(`${p}.statuses.cancelled`),
    },
    priorities: {
      low: t(`${p}.priorities.low`),
      medium: t(`${p}.priorities.medium`),
      high: t(`${p}.priorities.high`),
      critical: t(`${p}.priorities.critical`),
    },
    progressTypes: {
      milestone_achieved: t(`${p}.progressTypes.milestoneAchieved`),
      progress_change: t(`${p}.progressTypes.progressChange`),
      challenge: t(`${p}.progressTypes.challenge`),
      lesson_learned: t(`${p}.progressTypes.lessonLearned`),
      support_needed: t(`${p}.progressTypes.supportNeeded`),
    },
    recommendations: {
      reviewDeadlines: t(`${p}.recommendations.reviewDeadlines`),
      assignContributors: t(`${p}.recommendations.assignContributors`),
      linkFollowUps: t(`${p}.recommendations.linkFollowUps`),
      celebrateCompleted: t(`${p}.recommendations.celebrateCompleted`),
      updateProgress: t(`${p}.recommendations.updateProgress`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      updated: t(`${p}.faq.updated`),
      updatedAnswer: t(`${p}.faq.updatedAnswer`),
      autoComplete: t(`${p}.faq.autoComplete`),
      autoCompleteAnswer: t(`${p}.faq.autoCompleteAnswer`),
    },
  };
}
