import type { CustomerAcademyLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildCustomerAcademyLabels(t: Translator): CustomerAcademyLabels {
  const p = "customerApp.portalStructure.customerAcademy";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      completionStatus: t(`${p}.filters.completionStatus`),
      certificationType: t(`${p}.filters.certificationType`),
      department: t(`${p}.filters.department`),
      difficulty: t(`${p}.filters.difficulty`),
      all: t(`${p}.filters.all`),
      notStarted: t(`${p}.filters.notStarted`),
      completed: t(`${p}.filters.completed`),
    },
    dashboard: {
      progress: t(`${p}.dashboard.progress`),
      completionRate: t(`${p}.dashboard.completionRate`),
      recommended: t(`${p}.dashboard.recommended`),
      assigned: t(`${p}.dashboard.assigned`),
      certifications: t(`${p}.dashboard.certifications`),
      teamRate: t(`${p}.dashboard.teamRate`),
      recentlyReleased: t(`${p}.dashboard.recentlyReleased`),
      suggestedPaths: t(`${p}.dashboard.suggestedPaths`),
      coursesStarted: t(`${p}.dashboard.coursesStarted`),
      coursesCompleted: t(`${p}.dashboard.coursesCompleted`),
      outstanding: t(`${p}.dashboard.outstanding`),
    },
    sections: {
      gettingStarted: t(`${p}.sections.gettingStarted`),
      productTraining: t(`${p}.sections.productTraining`),
      teamTraining: t(`${p}.sections.teamTraining`),
      certifications: t(`${p}.sections.certifications`),
      knowledgeCenter: t(`${p}.sections.knowledgeCenter`),
      teamReporting: t(`${p}.sections.teamReporting`),
    },
    assign: {
      title: t(`${p}.assign.title`),
      course: t(`${p}.assign.course`),
      department: t(`${p}.assign.department`),
      required: t(`${p}.assign.required`),
      dueDate: t(`${p}.assign.dueDate`),
      notes: t(`${p}.assign.notes`),
      submit: t(`${p}.assign.submit`),
      cancel: t(`${p}.assign.cancel`),
      supportTeam: t(`${p}.assign.supportTeam`),
      operationsTeam: t(`${p}.assign.operationsTeam`),
      leadershipTeam: t(`${p}.assign.leadershipTeam`),
    },
    course: {
      complete: t(`${p}.course.complete`),
      completed: t(`${p}.course.completed`),
      minutes: t(`${p}.course.minutes`),
      required: t(`${p}.course.required`),
      optional: t(`${p}.course.optional`),
      overdue: t(`${p}.course.overdue`),
    },
    team: {
      assigned: t(`${p}.team.assigned`),
      completionRate: t(`${p}.team.completionRate`),
      overdue: t(`${p}.team.overdue`),
      recommendedActions: t(`${p}.team.recommendedActions`),
    },
    certifications: {
      aipify_certified_user: t(`${p}.certifications.certifiedUser`),
      aipify_operations_user: t(`${p}.certifications.operationsUser`),
      aipify_support_user: t(`${p}.certifications.supportUser`),
      aipify_executive_user: t(`${p}.certifications.executiveUser`),
    },
    difficulties: {
      beginner: t(`${p}.difficulties.beginner`),
      intermediate: t(`${p}.difficulties.intermediate`),
      advanced: t(`${p}.difficulties.advanced`),
    },
    contentTypes: {
      course: t(`${p}.contentTypes.course`),
      faq: t(`${p}.contentTypes.faq`),
      article: t(`${p}.contentTypes.article`),
      video: t(`${p}.contentTypes.video`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      managersAssign: t(`${p}.faq.managersAssign`),
      managersAssignAnswer: t(`${p}.faq.managersAssignAnswer`),
      partnerAcademy: t(`${p}.faq.partnerAcademy`),
      partnerAcademyAnswer: t(`${p}.faq.partnerAcademyAnswer`),
    },
  };
}
