import type { CustomerAcademyLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildCustomerAcademyLabels(t: Translator): CustomerAcademyLabels {
  const p = "customerApp.portalStructure.customerAcademy";
  return {
    eyebrow: t(`${p}.eyebrow`),
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    breadcrumbSupport: t(`${p}.breadcrumbSupport`),
    breadcrumbAcademy: t(`${p}.breadcrumbAcademy`),
    backToSupport: t(`${p}.backToSupport`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      sortBy: t(`${p}.filters.sortBy`),
      sortTitle: t(`${p}.filters.sortTitle`),
      sortDuration: t(`${p}.filters.sortDuration`),
      sortDifficulty: t(`${p}.filters.sortDifficulty`),
      sortSection: t(`${p}.filters.sortSection`),
      sortProgress: t(`${p}.filters.sortProgress`),
      category: t(`${p}.filters.category`),
      completionStatus: t(`${p}.filters.completionStatus`),
      difficulty: t(`${p}.filters.difficulty`),
      all: t(`${p}.filters.all`),
      notStarted: t(`${p}.filters.notStarted`),
      inProgress: t(`${p}.filters.inProgress`),
      completed: t(`${p}.filters.completed`),
    },
    overview: {
      available: t(`${p}.overview.available`),
      assigned: t(`${p}.overview.assigned`),
      started: t(`${p}.overview.started`),
      inProgress: t(`${p}.overview.inProgress`),
      completed: t(`${p}.overview.completed`),
      overdue: t(`${p}.overview.overdue`),
      personalCompletion: t(`${p}.overview.personalCompletion`),
    },
    sections: {
      continueLearning: t(`${p}.sections.continueLearning`),
      recommended: t(`${p}.sections.recommended`),
      gettingStarted: t(`${p}.sections.gettingStarted`),
      productTraining: t(`${p}.sections.productTraining`),
      certifications: t(`${p}.sections.certifications`),
      teamLearning: t(`${p}.sections.teamLearning`),
      suggestedPaths: t(`${p}.sections.suggestedPaths`),
      knowledgeCenter: t(`${p}.sections.knowledgeCenter`),
      understanding: t(`${p}.sections.understanding`),
    },
    courseStates: {
      not_started: t(`${p}.courseStates.notStarted`),
      in_progress: t(`${p}.courseStates.inProgress`),
      completed: t(`${p}.courseStates.completed`),
      locked: t(`${p}.courseStates.locked`),
      assigned: t(`${p}.courseStates.assigned`),
      overdue: t(`${p}.courseStates.overdue`),
    },
    courseActions: {
      start: t(`${p}.courseActions.start`),
      continue: t(`${p}.courseActions.continue`),
      review: t(`${p}.courseActions.review`),
      complete: t(`${p}.courseActions.complete`),
    },
    certificationStates: {
      earned: t(`${p}.certificationStates.earned`),
      in_progress: t(`${p}.certificationStates.inProgress`),
      not_started: t(`${p}.certificationStates.notStarted`),
      expired: t(`${p}.certificationStates.expired`),
    },
    assign: {
      title: t(`${p}.assign.title`),
      course: t(`${p}.assign.course`),
      department: t(`${p}.assign.department`),
      required: t(`${p}.assign.required`),
      dueDate: t(`${p}.assign.dueDate`),
      submit: t(`${p}.assign.submit`),
      cancel: t(`${p}.assign.cancel`),
      supportTeam: t(`${p}.assign.supportTeam`),
      operationsTeam: t(`${p}.assign.operationsTeam`),
      leadershipTeam: t(`${p}.assign.leadershipTeam`),
      action: t(`${p}.assign.action`),
    },
    team: {
      noAssignments: t(`${p}.team.noAssignments`),
      assigned: t(`${p}.team.assigned`),
      completionRate: t(`${p}.team.completionRate`),
      overdue: t(`${p}.team.overdue`),
    },
    recommendations: {
      onboarding: t(`${p}.recommendations.onboarding`),
      security: t(`${p}.recommendations.security`),
      businessPacks: t(`${p}.recommendations.businessPacks`),
      adoption: t(`${p}.recommendations.adoption`),
    },
    difficulties: {
      beginner: t(`${p}.difficulties.beginner`),
      intermediate: t(`${p}.difficulties.intermediate`),
      advanced: t(`${p}.difficulties.advanced`),
    },
    contentTypes: {
      course: t(`${p}.contentTypes.course`),
      faq: t(`${p}.contentTypes.faq`),
      article: t(`${p}.contentTypes.article`),
      video: t(`${p}.contentTypes.video`),
      guide: t(`${p}.contentTypes.guide`),
    },
    certifications: {
      aipify_certified_user: t(`${p}.certifications.certifiedUser`),
      aipify_operations_user: t(`${p}.certifications.operationsUser`),
      aipify_support_user: t(`${p}.certifications.supportUser`),
      aipify_executive_user: t(`${p}.certifications.executiveUser`),
    },
    understanding: {
      whatIs: t(`${p}.understanding.whatIs`),
      whatIsAnswer: t(`${p}.understanding.whatIsAnswer`),
      managersAssign: t(`${p}.understanding.managersAssign`),
      managersAssignAnswer: t(`${p}.understanding.managersAssignAnswer`),
      partnerAcademy: t(`${p}.understanding.partnerAcademy`),
      partnerAcademyAnswer: t(`${p}.understanding.partnerAcademyAnswer`),
    },
    empty: {
      continueLearning: t(`${p}.empty.continueLearning`),
      teamLearning: t(`${p}.empty.teamLearning`),
    },
    error: {
      title: t(`${p}.error.title`),
      body: t(`${p}.error.body`),
      retry: t(`${p}.error.retry`),
    },
  };
}
