import type { BoardInvestorIntelligenceLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildBoardInvestorIntelligenceLabels(t: Translator): BoardInvestorIntelligenceLabels {
  const p = "customerApp.boardInvestorIntelligence";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    humanOversight: t(`${p}.humanOversight`),
    principle: t(`${p}.principle`),
    executiveLink: t(`${p}.executiveLink`),
    cockpitLink: t(`${p}.cockpitLink`),
    earlyWarningLink: t(`${p}.earlyWarningLink`),
    generateNarrative: t(`${p}.generateNarrative`),
    generateBriefing: t(`${p}.generateBriefing`),
    recorded: t(`${p}.recorded`),
    tabs: {
      board: t(`${p}.tabs.board`),
      investor: t(`${p}.tabs.investor`),
      meeting: t(`${p}.tabs.meeting`),
      decisions: t(`${p}.tabs.decisions`),
      performance: t(`${p}.tabs.performance`),
      briefing: t(`${p}.tabs.briefing`),
      governance: t(`${p}.tabs.governance`),
      scenarios: t(`${p}.tabs.scenarios`),
      narrative: t(`${p}.tabs.narrative`),
      learning: t(`${p}.tabs.learning`),
    },
    board: {
      title: t(`${p}.board.title`),
      onTrack: t(`${p}.board.onTrack`),
      atRisk: t(`${p}.board.atRisk`),
      executivePriorities: t(`${p}.board.executivePriorities`),
      orgHealth: t(`${p}.board.orgHealth`),
      financialTrend: t(`${p}.board.financialTrend`),
      riskLandscape: t(`${p}.board.riskLandscape`),
      opportunities: t(`${p}.board.opportunities`),
      attentionItems: t(`${p}.board.attentionItems`),
    },
    investor: {
      title: t(`${p}.investor.title`),
      revenueTrajectory: t(`${p}.investor.revenueTrajectory`),
      revenueNote: t(`${p}.investor.revenueNote`),
      customerGrowth: t(`${p}.investor.customerGrowth`),
      retention: t(`${p}.investor.retention`),
      productAdoption: t(`${p}.investor.productAdoption`),
      expansionReadiness: t(`${p}.investor.expansionReadiness`),
      operationalMaturity: t(`${p}.investor.operationalMaturity`),
      governanceMaturity: t(`${p}.investor.governanceMaturity`),
    },
    meeting: {
      title: t(`${p}.meeting.title`),
      highlights: t(`${p}.meeting.highlights`),
      accomplishments: t(`${p}.meeting.accomplishments`),
      strategicUpdates: t(`${p}.meeting.strategicUpdates`),
      risks: t(`${p}.meeting.risks`),
      opportunities: t(`${p}.meeting.opportunities`),
      decisions: t(`${p}.meeting.decisions`),
      actionItems: t(`${p}.meeting.actionItems`),
    },
    decisions: {
      title: t(`${p}.decisions.title`),
      decision: t(`${p}.decisions.decision`),
      outcome: t(`${p}.decisions.outcome`),
      rationale: t(`${p}.decisions.rationale`),
      status: t(`${p}.decisions.status`),
      followUp: t(`${p}.decisions.followUp`),
      empty: t(`${p}.decisions.empty`),
    },
    performance: { title: t(`${p}.performance.title`), note: t(`${p}.performance.note`) },
    briefing: {
      title: t(`${p}.briefing.title`),
      position: t(`${p}.briefing.position`),
      opportunities: t(`${p}.briefing.opportunities`),
      growth: t(`${p}.briefing.growth`),
      strengths: t(`${p}.briefing.strengths`),
      risks: t(`${p}.briefing.risks`),
      focus: t(`${p}.briefing.focus`),
      confidence: t(`${p}.briefing.confidence`),
      disclaimer: t(`${p}.briefing.disclaimer`),
    },
    governance: {
      title: t(`${p}.governance.title`),
      overall: t(`${p}.governance.overall`),
      decisionTransparency: t(`${p}.governance.decisionTransparency`),
      approvalDiscipline: t(`${p}.governance.approvalDiscipline`),
      riskOversight: t(`${p}.governance.riskOversight`),
      policyCompliance: t(`${p}.governance.policyCompliance`),
      executiveAccountability: t(`${p}.governance.executiveAccountability`),
      auditReadiness: t(`${p}.governance.auditReadiness`),
      boardEffectiveness: t(`${p}.governance.boardEffectiveness`),
      statuses: {
        strong: t(`${p}.governance.statuses.strong`),
        healthy: t(`${p}.governance.statuses.healthy`),
        monitor: t(`${p}.governance.statuses.monitor`),
        needs_attention: t(`${p}.governance.statuses.needsAttention`),
        critical: t(`${p}.governance.statuses.critical`),
      },
    },
    scenarios: { title: t(`${p}.scenarios.title`), certaintyNote: t(`${p}.scenarios.certaintyNote`) },
    narrative: {
      title: t(`${p}.narrative.title`),
      summary: t(`${p}.narrative.summary`),
      achievements: t(`${p}.narrative.achievements`),
      challenges: t(`${p}.narrative.challenges`),
      risks: t(`${p}.narrative.risks`),
      opportunities: t(`${p}.narrative.opportunities`),
      priorities: t(`${p}.narrative.priorities`),
      suitableFor: t(`${p}.narrative.suitableFor`),
    },
    learning: { title: t(`${p}.learning.title`) },
    faq: {
      title: t(`${p}.faq.title`),
      whatIsBoard: t(`${p}.faq.whatIsBoard`),
      whatIsBoardAnswer: t(`${p}.faq.whatIsBoardAnswer`),
      governanceSupport: t(`${p}.faq.governanceSupport`),
      governanceSupportAnswer: t(`${p}.faq.governanceSupportAnswer`),
      replaceDecisions: t(`${p}.faq.replaceDecisions`),
      replaceDecisionsAnswer: t(`${p}.faq.replaceDecisionsAnswer`),
      investorInsights: t(`${p}.faq.investorInsights`),
      investorInsightsAnswer: t(`${p}.faq.investorInsightsAnswer`),
      confidenceScores: t(`${p}.faq.confidenceScores`),
      confidenceScoresAnswer: t(`${p}.faq.confidenceScoresAnswer`),
    },
    upgradeTitle: t(`${p}.upgrade.title`),
    upgradeBody: t(`${p}.upgrade.body`),
    upgradeCta: t(`${p}.upgrade.cta`),
  };
}
