import type { Translator } from "@/lib/i18n/translate";

export function buildBusinessContinuityLabels(t: Translator) {
  const p = "customerApp.businessContinuity";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    privacyNote: t(`${p}.privacyNote`),
    loading: t(`${p}.loading`),
    empty: t(`${p}.empty`),
    refresh: t(`${p}.refresh`),
    noRecords: t(`${p}.noRecords`),
    companionRecommendations: t(`${p}.companionRecommendations`),
    executiveDashboard: t(`${p}.executiveDashboard`),
    continuityStatus: t(`${p}.continuityStatus`),
    readinessScore: t(`${p}.readinessScore`),
    phaseIntegrations: t(`${p}.phaseIntegrations`),
    governanceRules: t(`${p}.governanceRules`),
    crisisDashboard: t(`${p}.crisisDashboard`),
    recoveryBoard: t(`${p}.recoveryBoard`),
    openCrisisDashboard: t(`${p}.openCrisisDashboard`),
    openRecoveryBoard: t(`${p}.openRecoveryBoard`),
    sections: {
      overview: t(`${p}.sections.overview`),
      plans: t(`${p}.sections.plans`),
      criticalOperations: t(`${p}.sections.criticalOperations`),
      businessImpact: t(`${p}.sections.businessImpact`),
      crisisMode: t(`${p}.sections.crisisMode`),
      recoveryPlans: t(`${p}.sections.recoveryPlans`),
      emergencyContacts: t(`${p}.sections.emergencyContacts`),
      communication: t(`${p}.sections.communication`),
      dependencies: t(`${p}.sections.dependencies`),
      exercises: t(`${p}.sections.exercises`),
      evidence: t(`${p}.sections.evidence`),
      reports: t(`${p}.sections.reports`),
    },
    stats: {
      continuityScopes: t(`${p}.stats.continuityScopes`),
      biaAssessments: t(`${p}.stats.biaAssessments`),
      continuityPlans: t(`${p}.stats.continuityPlans`),
      dependencies: t(`${p}.stats.dependencies`),
      emergencyContacts: t(`${p}.stats.emergencyContacts`),
      exercises: t(`${p}.stats.exercises`),
      recoveryPlans: t(`${p}.stats.recoveryPlans`),
    },
    executive: {
      readinessScore: t(`${p}.executive.readinessScore`),
      activePlans: t(`${p}.executive.activePlans`),
      criticalOperations: t(`${p}.executive.criticalOperations`),
      singlePointsOfFailure: t(`${p}.executive.singlePointsOfFailure`),
      crisisModeStatus: t(`${p}.executive.crisisModeStatus`),
      recoveryPlansReady: t(`${p}.executive.recoveryPlansReady`),
    },
    groups: {
      continuityPlans: t(`${p}.groups.continuityPlans`),
      planReviewCycles: t(`${p}.groups.planReviewCycles`),
      criticalOperations: t(`${p}.groups.criticalOperations`),
      continuityScopes: t(`${p}.groups.continuityScopes`),
      businessImpact: t(`${p}.groups.businessImpact`),
      recoveryObjectives: t(`${p}.groups.recoveryObjectives`),
      crisisModes: t(`${p}.groups.crisisModes`),
      crisisCommand: t(`${p}.groups.crisisCommand`),
      crisisTimeline: t(`${p}.groups.crisisTimeline`),
      crisisDecisions: t(`${p}.groups.crisisDecisions`),
      minimumOperating: t(`${p}.groups.minimumOperating`),
      temporaryWorkflows: t(`${p}.groups.temporaryWorkflows`),
      recoveryPlans: t(`${p}.groups.recoveryPlans`),
      recoveryTasks: t(`${p}.groups.recoveryTasks`),
      returnToNormal: t(`${p}.groups.returnToNormal`),
      postCrisisReviews: t(`${p}.groups.postCrisisReviews`),
      emergencyContacts: t(`${p}.groups.emergencyContacts`),
      communications: t(`${p}.groups.communications`),
      dependencies: t(`${p}.groups.dependencies`),
      supplierContinuity: t(`${p}.groups.supplierContinuity`),
      connectedApps: t(`${p}.groups.connectedApps`),
      domainContinuity: t(`${p}.groups.domainContinuity`),
      exercises: t(`${p}.groups.exercises`),
      readinessScores: t(`${p}.groups.readinessScores`),
      criticalDocuments: t(`${p}.groups.criticalDocuments`),
      dataContinuity: t(`${p}.groups.dataContinuity`),
      financialContinuity: t(`${p}.groups.financialContinuity`),
      customerService: t(`${p}.groups.customerService`),
      salesContinuity: t(`${p}.groups.salesContinuity`),
      partnerCommission: t(`${p}.groups.partnerCommission`),
      reports: t(`${p}.groups.reports`),
      auditRecent: t(`${p}.groups.auditRecent`),
    },
  };
}

export function buildPartnerBusinessContinuityLabels(t: Translator) {
  const p = "partnersPortal.businessContinuity";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    privacyNote: t(`${p}.privacyNote`),
    customerOwnershipNote: t(`${p}.customerOwnershipNote`),
    loading: t(`${p}.loading`),
    empty: t(`${p}.empty`),
    refresh: t(`${p}.refresh`),
    noRecords: t(`${p}.noRecords`),
    companionRecommendations: t(`${p}.companionRecommendations`),
    executiveDashboard: t(`${p}.executiveDashboard`),
    continuityStatus: t(`${p}.continuityStatus`),
    readinessScore: t(`${p}.readinessScore`),
    sections: {
      overview: t(`${p}.sections.overview`),
      portfolio: t(`${p}.sections.portfolio`),
      commission: t(`${p}.sections.commission`),
      communications: t(`${p}.sections.communications`),
      reports: t(`${p}.sections.reports`),
    },
    stats: {
      portfolioSegments: t(`${p}.stats.portfolioSegments`),
      commissionProtections: t(`${p}.stats.commissionProtections`),
      referralContinuity: t(`${p}.stats.referralContinuity`),
      communications: t(`${p}.stats.communications`),
    },
    executive: {
      readinessScore: t(`${p}.executive.readinessScore`),
      portfolioCustomers: t(`${p}.executive.portfolioCustomers`),
      commissionProtected: t(`${p}.executive.commissionProtected`),
      referralsPreserved: t(`${p}.executive.referralsPreserved`),
    },
    groups: {
      portfolioContinuity: t(`${p}.groups.portfolioContinuity`),
      commissionProtection: t(`${p}.groups.commissionProtection`),
      referralContinuity: t(`${p}.groups.referralContinuity`),
      communications: t(`${p}.groups.communications`),
      readinessScores: t(`${p}.groups.readinessScores`),
      reports: t(`${p}.groups.reports`),
      auditRecent: t(`${p}.groups.auditRecent`),
    },
  };
}
