import type { Translator } from "@/lib/i18n/translate";

export function buildIntegrationHubLabels(t: Translator) {
  const p = "customerApp.integrationHubOperations";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    installed: t(`${p}.installed`),
    marketplace: t(`${p}.marketplace`),
    connectedSystems: t(`${p}.connectedSystems`),
    domains: t(`${p}.domains`),
    apiKeys: t(`${p}.apiKeys`),
    webhooks: t(`${p}.webhooks`),
    sync: t(`${p}.sync`),
    reports: t(`${p}.reports`),
    companion: t(`${p}.companion`),
    installedCount: t(`${p}.installedCount`),
    activeCount: t(`${p}.activeCount`),
    marketplaceCount: t(`${p}.marketplaceCount`),
    webhookCount: t(`${p}.webhookCount`),
    apiKeyCount: t(`${p}.apiKeyCount`),
    criticalHealth: t(`${p}.criticalHealth`),
    failedSyncs: t(`${p}.failedSyncs`),
    connectorGovernance: t(`${p}.connectorGovernance`),
    installationWorkflow: t(`${p}.installationWorkflow`),
    healthMonitoring: t(`${p}.healthMonitoring`),
    syncHistory: t(`${p}.syncHistory`),
    businessPackIntegration: t(`${p}.businessPackIntegration`),
    domainIntelligence: t(`${p}.domainIntelligence`),
    executiveDashboard: t(`${p}.executiveDashboard`),
    companionIntegration: t(`${p}.companionIntegration`),
    externalActions: t(`${p}.externalActions`),
    searchIntegration: t(`${p}.searchIntegration`),
    searchPlaceholder: t(`${p}.searchPlaceholder`),
    searchHub: t(`${p}.searchHub`),
    installConnector: t(`${p}.installConnector`),
    testConnection: t(`${p}.testConnection`),
    startSync: t(`${p}.startSync`),
    noItems: t(`${p}.noItems`),
    emptyHint: t(`${p}.emptyHint`),
    auditLog: t(`${p}.auditLog`),
    mobileReady: t(`${p}.mobileReady`),
    statusActive: t(`${p}.statusActive`),
    statusConnecting: t(`${p}.statusConnecting`),
    statusAttention: t(`${p}.statusAttention`),
    statusPermission: t(`${p}.statusPermission`),
    statusDisconnected: t(`${p}.statusDisconnected`),
    healthHealthy: t(`${p}.healthHealthy`),
    healthDegraded: t(`${p}.healthDegraded`),
    healthCritical: t(`${p}.healthCritical`),
    marketplaceTitle: t(`${p}.marketplaceTitle`),
    marketplaceSubtitle: t(`${p}.marketplaceSubtitle`),
    syncTitle: t(`${p}.syncTitle`),
    syncSubtitle: t(`${p}.syncSubtitle`),
    webhooksTitle: t(`${p}.webhooksTitle`),
    webhooksSubtitle: t(`${p}.webhooksSubtitle`),
    apiTitle: t(`${p}.apiTitle`),
    apiSubtitle: t(`${p}.apiSubtitle`),
  };
}

export type IntegrationHubLabels = ReturnType<typeof buildIntegrationHubLabels>;
