import type { Translator } from "@/lib/i18n/translate";
import type { SubscriptionOperationsLabels } from "./types";
import { FILTER_PRESETS, HEALTH_BANDS, PLAN_TYPES, RISK_LEVELS, SUBSCRIPTION_STATUSES } from "./constants";

export function buildSubscriptionOperationsLabels(t: Translator): SubscriptionOperationsLabels {
  const p = "platform.subscriptionOperations";

  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    back: t(`${p}.back`),
    principle: t(`${p}.principle`),
    emptyState: t(`${p}.emptyState`),
    sections: {
      executiveSnapshot: t(`${p}.sections.executiveSnapshot`),
      overview: t(`${p}.sections.overview`),
      subscriptions: t(`${p}.sections.subscriptions`),
      healthScoring: t(`${p}.sections.healthScoring`),
      trials: t(`${p}.sections.trials`),
      upgrades: t(`${p}.sections.upgrades`),
      downgrades: t(`${p}.sections.downgrades`),
      renewals: t(`${p}.sections.renewals`),
      pastDue: t(`${p}.sections.pastDue`),
      enterpriseContracts: t(`${p}.sections.enterpriseContracts`),
      lifecycleTimeline: t(`${p}.sections.lifecycleTimeline`),
      executiveInsights: t(`${p}.sections.executiveInsights`),
      revenueAtRisk: t(`${p}.sections.revenueAtRisk`),
      growthOpportunities: t(`${p}.sections.growthOpportunities`),
      audit: t(`${p}.sections.audit`),
      filters: t(`${p}.sections.filters`),
      forecasting: t(`${p}.sections.forecasting`),
    },
    executive: {
      mrr: t(`${p}.executive.mrr`),
      arr: t(`${p}.executive.arr`),
      netGrowth: t(`${p}.executive.netGrowth`),
      conversionRate: t(`${p}.executive.conversionRate`),
      renewalRisk: t(`${p}.executive.renewalRisk`),
      acv: t(`${p}.executive.acv`),
      active: t(`${p}.executive.active`),
      trials: t(`${p}.executive.trials`),
      renewals: t(`${p}.executive.renewals`),
      upgrades: t(`${p}.executive.upgrades`),
      downgrades: t(`${p}.executive.downgrades`),
      cancelled: t(`${p}.executive.cancelled`),
    },
    health: Object.fromEntries(
      HEALTH_BANDS.map((band) => [band, t(`${p}.health.${band}`)])
    ) as SubscriptionOperationsLabels["health"],
    healthDescription: t(`${p}.healthDescription`),
    table: {
      customer: t(`${p}.table.customer`),
      plan: t(`${p}.table.plan`),
      users: t(`${p}.table.users`),
      billingProvider: t(`${p}.table.billingProvider`),
      monthlyValue: t(`${p}.table.monthlyValue`),
      mrrContribution: t(`${p}.table.mrrContribution`),
      renewalDate: t(`${p}.table.renewalDate`),
      status: t(`${p}.table.status`),
      actions: t(`${p}.table.actions`),
      previousPlan: t(`${p}.table.previousPlan`),
      newPlan: t(`${p}.table.newPlan`),
      effectiveDate: t(`${p}.table.effectiveDate`),
      revenueImpact: t(`${p}.table.revenueImpact`),
      mrrImpact: t(`${p}.table.mrrImpact`),
      reason: t(`${p}.table.reason`),
      trialStart: t(`${p}.table.trialStart`),
      trialEnd: t(`${p}.table.trialEnd`),
      daysRemaining: t(`${p}.table.daysRemaining`),
      conversionProbability: t(`${p}.table.conversionProbability`),
      usageScore: t(`${p}.table.usageScore`),
      growthPartner: t(`${p}.table.growthPartner`),
      outstandingAmount: t(`${p}.table.outstandingAmount`),
      daysOverdue: t(`${p}.table.daysOverdue`),
      paymentProvider: t(`${p}.table.paymentProvider`),
      recommendedAction: t(`${p}.table.recommendedAction`),
      contractStart: t(`${p}.table.contractStart`),
      contractEnd: t(`${p}.table.contractEnd`),
      contractValue: t(`${p}.table.contractValue`),
      paymentTerms: t(`${p}.table.paymentTerms`),
      accountManager: t(`${p}.table.accountManager`),
      event: t(`${p}.table.event`),
      healthScore: t(`${p}.table.healthScore`),
      renewalProbability: t(`${p}.table.renewalProbability`),
      contractType: t(`${p}.table.contractType`),
      accountOwner: t(`${p}.table.accountOwner`),
      lastInteraction: t(`${p}.table.lastInteraction`),
      riskLevel: t(`${p}.table.riskLevel`),
      retryAttempts: t(`${p}.table.retryAttempts`),
      nextStep: t(`${p}.table.nextStep`),
      expansionOpportunity: t(`${p}.table.expansionOpportunity`),
      contractHealth: t(`${p}.table.contractHealth`),
      upcomingMilestone: t(`${p}.table.upcomingMilestone`),
      actor: t(`${p}.table.actor`),
      financialImpact: t(`${p}.table.financialImpact`),
      automation: t(`${p}.table.automation`),
      approval: t(`${p}.table.approval`),
      date: t(`${p}.table.date`),
      signal: t(`${p}.table.signal`),
      recommendation: t(`${p}.table.recommendation`),
      priority: t(`${p}.table.priority`),
    },
    statuses: Object.fromEntries(
      SUBSCRIPTION_STATUSES.map((status) => [status, t(`${p}.statuses.${status}`)])
    ) as SubscriptionOperationsLabels["statuses"],
    riskLevels: Object.fromEntries(
      RISK_LEVELS.map((level) => [level, t(`${p}.riskLevels.${level}`)])
    ) as SubscriptionOperationsLabels["riskLevels"],
    expansion: {
      high: t(`${p}.expansion.high`),
      medium: t(`${p}.expansion.medium`),
      low: t(`${p}.expansion.low`),
    },
    actions: {
      view: t(`${p}.actions.view`),
      upgrade: t(`${p}.actions.upgrade`),
      downgrade: t(`${p}.actions.downgrade`),
      extendTrial: t(`${p}.actions.extendTrial`),
      suspend: t(`${p}.actions.suspend`),
      reactivate: t(`${p}.actions.reactivate`),
      cancel: t(`${p}.actions.cancel`),
      convertToPaid: t(`${p}.actions.convertToPaid`),
      sendReminder: t(`${p}.actions.sendReminder`),
      offerOnboarding: t(`${p}.actions.offerOnboarding`),
      discountCampaign: t(`${p}.actions.discountCampaign`),
      escalateSales: t(`${p}.actions.escalateSales`),
      retryPayment: t(`${p}.actions.retryPayment`),
      contactCustomer: t(`${p}.actions.contactCustomer`),
      switchPaymentMethod: t(`${p}.actions.switchPaymentMethod`),
      moveToCollections: t(`${p}.actions.moveToCollections`),
      pauseAccess: t(`${p}.actions.pauseAccess`),
      applying: t(`${p}.actions.applying`),
    },
    filters: {
      plan: t(`${p}.filters.plan`),
      status: t(`${p}.filters.status`),
      country: t(`${p}.filters.country`),
      provider: t(`${p}.filters.provider`),
      renewalPeriod: t(`${p}.filters.renewalPeriod`),
      growthPartner: t(`${p}.filters.growthPartner`),
      accountManager: t(`${p}.filters.accountManager`),
      allPlans: t(`${p}.filters.allPlans`),
      allStatuses: t(`${p}.filters.allStatuses`),
      allCountries: t(`${p}.filters.allCountries`),
      allProviders: t(`${p}.filters.allProviders`),
      allRenewals: t(`${p}.filters.allRenewals`),
      allPartners: t(`${p}.filters.allPartners`),
      allManagers: t(`${p}.filters.allManagers`),
      apply: t(`${p}.filters.apply`),
      presets: Object.fromEntries(
        FILTER_PRESETS.map((preset) => [preset, t(`${p}.filters.presets.${preset}`)])
      ) as SubscriptionOperationsLabels["filters"]["presets"],
    },
    renewals: {
      within7: t(`${p}.renewals.within7`),
      within30: t(`${p}.renewals.within30`),
      within90: t(`${p}.renewals.within90`),
      commandCenter: t(`${p}.renewals.commandCenter`),
    },
    insights: {
      recommendedAction: t(`${p}.insights.recommendedAction`),
      empty: t(`${p}.insights.empty`),
    },
    revenueAtRisk: {
      title: t(`${p}.revenueAtRisk.title`),
      pastDue: t(`${p}.revenueAtRisk.pastDue`),
      lowHealth: t(`${p}.revenueAtRisk.lowHealth`),
      enterpriseRenewals: t(`${p}.revenueAtRisk.enterpriseRenewals`),
      decliningUsage: t(`${p}.revenueAtRisk.decliningUsage`),
      total: t(`${p}.revenueAtRisk.total`),
    },
    growth: {
      empty: t(`${p}.growth.empty`),
    },
    lifecycle: {
      empty: t(`${p}.lifecycle.empty`),
    },
    forecasting: {
      futureNote: t(`${p}.forecasting.futureNote`),
    },
    plans: Object.fromEntries(
      PLAN_TYPES.map((plan) => [plan, t(`${p}.plans.${plan}`)])
    ) as SubscriptionOperationsLabels["plans"],
  };
}
