import type { IntegrationProviderManifest } from "../../types";

/** Pilot provider manifest — Unonight validates the generic contract; not core product logic. */
export const UNONIGHT_INTEGRATION_MANIFEST: IntegrationProviderManifest = {
  provider: "unonight",
  displayName: "Unonight",
  displayNameKey: "customerApp.companionPlatformKnowledge.integrationIntelligence.providers.unonight.displayName",
  capabilities: [
    {
      key: "platform_snapshot",
      description: "Returns safe live platform metadata",
      fields: [
        "status",
        "environment",
        "version",
        "supported_locales",
        "active_modules",
        "checked_at",
      ],
    },
    {
      key: "connection_status",
      description: "Returns verified connection metadata",
      fields: [
        "organization",
        "scopes",
        "access_mode",
        "last_verified",
        "last_used",
      ],
    },
  ],
  entities: [
    {
      type: "module",
      key: "registration",
      displayNameKey: "customerApp.companionPlatformKnowledge.platformSnapshot.modules.registration",
      aliases: {
        no: ["registrering", "brukerregistrering", "nye medlemmer", "registreringen"],
        en: ["registration", "user registration", "sign up"],
        sv: ["registrering"],
        da: ["registrering"],
        es: ["registro"],
        pl: ["rejestracja"],
        uk: ["reiestratsiia"],
      },
    },
    {
      type: "module",
      key: "marketplace",
      displayNameKey: "customerApp.companionPlatformKnowledge.platformSnapshot.modules.marketplace",
      aliases: {
        no: ["markedsplass", "markedsplassen", "marketplace", "butikk", "kjop og salg"],
        en: ["marketplace", "store", "shop"],
        sv: ["marknadsplats", "marknadsplatsen"],
        da: ["markedsplads", "markedspladsen"],
        es: ["mercado"],
        pl: ["marketplace"],
        uk: ["marketpleis"],
      },
    },
    {
      type: "module",
      key: "chat",
      displayNameKey: "customerApp.companionPlatformKnowledge.platformSnapshot.modules.chat",
      aliases: {
        no: ["chat", "meldinger"],
        en: ["chat", "messaging"],
        sv: ["chatt"],
        da: ["chat"],
        es: ["chat"],
        pl: ["czat"],
        uk: ["chat"],
      },
    },
    {
      type: "module",
      key: "public_chat",
      displayNameKey: "customerApp.companionPlatformKnowledge.platformSnapshot.modules.public_chat",
      aliases: {
        no: ["offentlig chat", "felleschat", "hovedchat", "hovedrom", "offentlig samtale"],
        en: ["public chat"],
        sv: ["offentlig chatt"],
        da: ["offentlig chat"],
        es: ["chat publico"],
        pl: ["czat publiczny"],
        uk: ["publichnii chat"],
      },
    },
    {
      type: "module",
      key: "private_chat",
      displayNameKey: "customerApp.companionPlatformKnowledge.platformSnapshot.modules.private_chat",
      aliases: {
        no: ["privat chat", "private meldinger", "en-til-en-chat", "direktemeldinger"],
        en: ["private chat", "direct messages", "one to one chat"],
        sv: ["privat chatt"],
        da: ["privat chat"],
        es: ["chat privado"],
        pl: ["czat prywatny"],
        uk: ["pryvatnyi chat"],
      },
    },
    {
      type: "module",
      key: "referrals",
      displayNameKey: "customerApp.companionPlatformKnowledge.platformSnapshot.modules.referrals",
      aliases: {
        no: ["verveprogram", "verving", "invitasjoner", "henvisninger"],
        en: ["referrals", "referral program"],
        sv: ["varvningsprogram"],
        da: ["henvisningsprogram"],
        es: ["programa de referidos"],
        pl: ["program polecen"],
        uk: ["referalna prohrama"],
      },
    },
    {
      type: "module",
      key: "gifts",
      displayNameKey: "customerApp.companionPlatformKnowledge.platformSnapshot.modules.gifts",
      aliases: {
        no: ["gaver", "gavene", "virtuelle gaver"],
        en: ["gifts"],
        sv: ["gavor"],
        da: ["gaver"],
        es: ["regalos"],
        pl: ["prezenty"],
        uk: ["podarunky"],
      },
    },
    {
      type: "module",
      key: "birthday_rewards",
      displayNameKey: "customerApp.companionPlatformKnowledge.platformSnapshot.modules.birthday_rewards",
      aliases: {
        no: [
          "bursdagsbelonninger",
          "bursdagsbelonningene",
          "bursdagsgaver",
          "bursdagspoeng",
          "bursdagsfunksjon",
        ],
        en: ["birthday rewards", "birthday gifts"],
        sv: ["fodelsedagsbeloningar"],
        da: ["fodselsdagsbelonninger"],
        es: ["recompensas de cumpleanos"],
        pl: ["nagrody urodzinowe"],
        uk: ["nagorody do dnia narodzhennia"],
      },
    },
    {
      type: "module",
      key: "mobile_api",
      displayNameKey: "customerApp.companionPlatformKnowledge.platformSnapshot.modules.mobile_api",
      aliases: {
        no: ["mobil-api", "mobil api", "mobiltilgang", "mobilfunksjoner"],
        en: ["mobile api", "mobile access"],
        sv: ["mobil-api"],
        da: ["mobil-api"],
        es: ["api movil"],
        pl: ["mobilne api"],
        uk: ["mobilnyi api"],
      },
    },
  ],
};
