import type { LearningImprovementLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildLearningImprovementLabels(t: Translator): LearningImprovementLabels {
  const p = "customerApp.portalStructure.learningImprovement";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      status: t(`${p}.filters.status`),
      owner: t(`${p}.filters.owner`),
      impact: t(`${p}.filters.impact`),
      identifiedFrom: t(`${p}.filters.identifiedFrom`),
      identifiedTo: t(`${p}.filters.identifiedTo`),
      recentlyImplemented: t(`${p}.filters.recentlyImplemented`),
      all: t(`${p}.filters.all`),
      yes: t(`${p}.filters.yes`),
      no: t(`${p}.filters.no`),
    },
    dashboard: {
      recentlyIdentified: t(`${p}.dashboard.recentlyIdentified`),
      implemented: t(`${p}.dashboard.implemented`),
      awaitingReview: t(`${p}.dashboard.awaitingReview`),
      highImpact: t(`${p}.dashboard.highImpact`),
      recurringThemes: t(`${p}.dashboard.recurringThemes`),
      recentlyArchived: t(`${p}.dashboard.recentlyArchived`),
    },
    patterns: {
      title: t(`${p}.patterns.title`),
      repeatedBottlenecks: t(`${p}.patterns.repeatedBottlenecks`),
      commonSupportIssues: t(`${p}.patterns.commonSupportIssues`),
      delayedActivities: t(`${p}.patterns.delayedActivities`),
      approvalChallenges: t(`${p}.patterns.approvalChallenges`),
      onboardingObstacles: t(`${p}.patterns.onboardingObstacles`),
      inactive: t(`${p}.patterns.inactive`),
    },
    form: {
      createTitle: t(`${p}.form.createTitle`),
      title: t(`${p}.form.title`),
      description: t(`${p}.form.description`),
      category: t(`${p}.form.category`),
      impact: t(`${p}.form.impact`),
      notes: t(`${p}.form.notes`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
    },
    card: {
      submittedBy: t(`${p}.card.submittedBy`),
      owner: t(`${p}.card.owner`),
      impact: t(`${p}.card.impact`),
      dateIdentified: t(`${p}.card.dateIdentified`),
      dateImplemented: t(`${p}.card.dateImplemented`),
      view: t(`${p}.card.view`),
    },
    detail: {
      overview: t(`${p}.detail.overview`),
      ownership: t(`${p}.detail.ownership`),
      actions: t(`${p}.detail.actions`),
      relatedFollowUps: t(`${p}.detail.relatedFollowUps`),
      relatedDecisions: t(`${p}.detail.relatedDecisions`),
      activity: t(`${p}.detail.activity`),
      audit: t(`${p}.detail.audit`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
      recommendations: t(`${p}.detail.recommendations`),
      addAction: t(`${p}.detail.addAction`),
      actionTitle: t(`${p}.detail.actionTitle`),
      rootCauses: t(`${p}.detail.rootCauses`),
      recommendedActions: t(`${p}.detail.recommendedActions`),
      successCriteria: t(`${p}.detail.successCriteria`),
      expectedOutcomes: t(`${p}.detail.expectedOutcomes`),
      lessonsApplied: t(`${p}.detail.lessonsApplied`),
    },
    categories: {
      operational_improvement: t(`${p}.categories.operationalImprovement`),
      customer_experience: t(`${p}.categories.customerExperience`),
      security_improvement: t(`${p}.categories.securityImprovement`),
      incident_learning: t(`${p}.categories.incidentLearning`),
      leadership_learning: t(`${p}.categories.leadershipLearning`),
      process_improvement: t(`${p}.categories.processImprovement`),
      team_collaboration: t(`${p}.categories.teamCollaboration`),
      technology_learning: t(`${p}.categories.technologyLearning`),
      vendor_learning: t(`${p}.categories.vendorLearning`),
      custom_learning: t(`${p}.categories.customLearning`),
    },
    statuses: {
      identified: t(`${p}.statuses.identified`),
      under_review: t(`${p}.statuses.underReview`),
      approved: t(`${p}.statuses.approved`),
      in_progress: t(`${p}.statuses.inProgress`),
      implemented: t(`${p}.statuses.implemented`),
      archived: t(`${p}.statuses.archived`),
    },
    impact: {
      minor_improvement: t(`${p}.impact.minorImprovement`),
      moderate_improvement: t(`${p}.impact.moderateImprovement`),
      significant_improvement: t(`${p}.impact.significantImprovement`),
      transformational_improvement: t(`${p}.impact.transformationalImprovement`),
    },
    recommendations: {
      reviewRepeated: t(`${p}.recommendations.reviewRepeated`),
      assignOwner: t(`${p}.recommendations.assignOwner`),
      shareSuccess: t(`${p}.recommendations.shareSuccess`),
      evaluatePatterns: t(`${p}.recommendations.evaluatePatterns`),
      celebrateImplemented: t(`${p}.recommendations.celebrateImplemented`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      document: t(`${p}.faq.document`),
      documentAnswer: t(`${p}.faq.documentAnswer`),
      autoImplement: t(`${p}.faq.autoImplement`),
      autoImplementAnswer: t(`${p}.faq.autoImplementAnswer`),
    },
  };
}
