import type { EnterpriseReadinessLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildEnterpriseReadinessLabels(t: Translator): EnterpriseReadinessLabels {
  const p = "customerApp.portalStructure.enterpriseReadiness";
  return {
    title:        t(`${p}.title`),
    subtitle:     t(`${p}.subtitle`),
    loading:      t(`${p}.loading`),
    principle:    t(`${p}.principle`),
    advisoryNote: t(`${p}.advisoryNote`),
    emptyTitle:   t(`${p}.emptyTitle`),
    emptyBody:    t(`${p}.emptyBody`),
    emptyCta:     t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search:         t(`${p}.filters.search`),
      category:       t(`${p}.filters.category`),
      readinessLevel: t(`${p}.filters.readinessLevel`),
      priority:       t(`${p}.filters.priority`),
      department:     t(`${p}.filters.department`),
      owner:          t(`${p}.filters.owner`),
      reviewStatus:   t(`${p}.filters.reviewStatus`),
      all:            t(`${p}.filters.all`),
    },
    dashboard: {
      readinessScore:      t(`${p}.dashboard.readinessScore`),
      overallLevel:        t(`${p}.dashboard.overallLevel`),
      executiveSummary:    t(`${p}.dashboard.executiveSummary`),
      operationalReadiness:t(`${p}.dashboard.operationalReadiness`),
      leadershipReadiness: t(`${p}.dashboard.leadershipReadiness`),
      workforceReadiness:  t(`${p}.dashboard.workforceReadiness`),
      technologyReadiness: t(`${p}.dashboard.technologyReadiness`),
      securityReadiness:   t(`${p}.dashboard.securityReadiness`),
      complianceReadiness: t(`${p}.dashboard.complianceReadiness`),
      growthReadiness:     t(`${p}.dashboard.growthReadiness`),
      identifiedGaps:      t(`${p}.dashboard.identifiedGaps`),
      allAssessments:      t(`${p}.dashboard.allAssessments`),
      recommendations:     t(`${p}.dashboard.recommendations`),
      timeline:            t(`${p}.dashboard.timeline`),
      reviewQuestions:     t(`${p}.dashboard.reviewQuestions`),
      viewAssessment:      t(`${p}.dashboard.viewAssessment`),
      startAssessment:     t(`${p}.dashboard.startAssessment`),
    },
    scorecard: {
      currentScore:       t(`${p}.scorecard.currentScore`),
      targetScore:        t(`${p}.scorecard.targetScore`),
      trend:              t(`${p}.scorecard.trend`),
      priority:           t(`${p}.scorecard.priority`),
      owner:              t(`${p}.scorecard.owner`),
      reviewDate:         t(`${p}.scorecard.reviewDate`),
      department:         t(`${p}.scorecard.department`),
      recommendedAction:  t(`${p}.scorecard.recommendedAction`),
    },
    gap: {
      impactLevel:       t(`${p}.gap.impactLevel`),
      recommendedAction: t(`${p}.gap.recommendedAction`),
      suggestedOwner:    t(`${p}.gap.suggestedOwner`),
      reviewTimeline:    t(`${p}.gap.reviewTimeline`),
      status:            t(`${p}.gap.status`),
    },
    detail: {
      back:          t(`${p}.detail.back`),
      scorecard:     t(`${p}.detail.scorecard`),
      reviewHistory: t(`${p}.detail.reviewHistory`),
      reviewNotes:   t(`${p}.detail.reviewNotes`),
      newScore:      t(`${p}.detail.newScore`),
      submitReview:  t(`${p}.detail.submitReview`),
      reviewSuccess: t(`${p}.detail.reviewSuccess`),
      advisoryNote:  t(`${p}.detail.advisoryNote`),
    },
    startAssessment: {
      success:        t(`${p}.startAssessment.success`),
      governanceNote: t(`${p}.startAssessment.governanceNote`),
    },
    categories: {
      leadership:           t(`${p}.categories.leadership`),
      governance:           t(`${p}.categories.governance`),
      operations:           t(`${p}.categories.operations`),
      security:             t(`${p}.categories.security`),
      compliance:           t(`${p}.categories.compliance`),
      workforce:            t(`${p}.categories.workforce`),
      technology:           t(`${p}.categories.technology`),
      customer_success:     t(`${p}.categories.customerSuccess`),
      knowledge_management: t(`${p}.categories.knowledgeManagement`),
      business_continuity:  t(`${p}.categories.businessContinuity`),
      vendor_management:    t(`${p}.categories.vendorManagement`),
      risk_management:      t(`${p}.categories.riskManagement`),
    },
    readinessLevels: {
      emerging:        t(`${p}.readinessLevels.emerging`),
      developing:      t(`${p}.readinessLevels.developing`),
      established:     t(`${p}.readinessLevels.established`),
      advanced:        t(`${p}.readinessLevels.advanced`),
      enterprise_ready:t(`${p}.readinessLevels.enterpriseReady`),
    },
    trends: {
      improving: t(`${p}.trends.improving`),
      stable:    t(`${p}.trends.stable`),
      declining: t(`${p}.trends.declining`),
    },
    priorities: {
      low:      t(`${p}.priorities.low`),
      moderate: t(`${p}.priorities.moderate`),
      high:     t(`${p}.priorities.high`),
      critical: t(`${p}.priorities.critical`),
    },
    reviewStatuses: {
      pending:        t(`${p}.reviewStatuses.pending`),
      in_review:      t(`${p}.reviewStatuses.inReview`),
      reviewed:       t(`${p}.reviewStatuses.reviewed`),
      needs_follow_up:t(`${p}.reviewStatuses.needsFollowUp`),
    },
    gapStatuses: {
      identified: t(`${p}.gapStatuses.identified`),
      in_progress:t(`${p}.gapStatuses.inProgress`),
      resolved:   t(`${p}.gapStatuses.resolved`),
      accepted:   t(`${p}.gapStatuses.accepted`),
    },
    impactLevels: {
      low:      t(`${p}.impactLevels.low`),
      moderate: t(`${p}.impactLevels.moderate`),
      high:     t(`${p}.impactLevels.high`),
      critical: t(`${p}.impactLevels.critical`),
    },
    recommendations: {
      reviewSecurityControls:     t(`${p}.recommendations.reviewSecurityControls`),
      strengthenGovernanceProcesses: t(`${p}.recommendations.strengthenGovernanceProcesses`),
      improveDocumentation:       t(`${p}.recommendations.improveDocumentation`),
      expandLeadershipPlanning:   t(`${p}.recommendations.expandLeadershipPlanning`),
      increaseWorkforceReadiness: t(`${p}.recommendations.increaseWorkforceReadiness`),
      improveOperationalConsistency: t(`${p}.recommendations.improveOperationalConsistency`),
    },
    timelineEvents: {
      readiness_initialized:        t(`${p}.timelineEvents.readinessInitialized`),
      readiness_assessment_started: t(`${p}.timelineEvents.assessmentStarted`),
      readiness_review_completed:   t(`${p}.timelineEvents.reviewCompleted`),
      gap_identified:               t(`${p}.timelineEvents.gapIdentified`),
      improvement_plan_created:     t(`${p}.timelineEvents.improvementPlanCreated`),
      readiness_milestone:          t(`${p}.timelineEvents.readinessMilestone`),
      action_completed:             t(`${p}.timelineEvents.actionCompleted`),
    },
    reviewQuestions: [
      t(`${p}.reviewQuestions.systemsScalable`),
      t(`${p}.reviewQuestions.leadershipSupport`),
      t(`${p}.reviewQuestions.processesDocumented`),
      t(`${p}.reviewQuestions.complianceUnderstood`),
      t(`${p}.reviewQuestions.workforceSufficient`),
      t(`${p}.reviewQuestions.risksManaged`),
      t(`${p}.reviewQuestions.knowledgeRetained`),
    ],
    faq: {
      title:                 t(`${p}.faq.title`),
      whatIs:                t(`${p}.faq.whatIs`),
      whatIsAnswer:          t(`${p}.faq.whatIsAnswer`),
      certifies:             t(`${p}.faq.certifies`),
      certifiesAnswer:       t(`${p}.faq.certifiesAnswer`),
      whoShouldUse:          t(`${p}.faq.whoShouldUse`),
      whoShouldUseAnswer:    t(`${p}.faq.whoShouldUseAnswer`),
    },
  };
}
