import type { Translator } from "@/lib/i18n/translate";

export function buildRevenueGrowthCenterLabels(t: Translator) {
  const p = "customerApp.revenueGrowthCenter";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    corePrinciple: t(`${p}.corePrinciple`),
    governanceNote: t(`${p}.governanceNote`),
    privacyNote: t(`${p}.privacyNote`),
    refresh: t(`${p}.refresh`),
    accessDenied: t(`${p}.accessDenied`),
    companionAdviceTitle: t(`${p}.companionAdviceTitle`),
    topRecommendations: t(`${p}.topRecommendations`),
    auditHistory: t(`${p}.auditHistory`),
    noAudit: t(`${p}.noAudit`),
    relatedLinks: t(`${p}.relatedLinks`),
    customerSuccessCenter: t(`${p}.customerSuccessCenter`),
    onboardingCenter: t(`${p}.onboardingCenter`),
    renewalDate: t(`${p}.renewalDate`),
    renewalRisk: t(`${p}.renewalRisk`),
    health: t(`${p}.health`),
    owner: t(`${p}.owner`),
    pipeline: t(`${p}.pipeline`),
    potentialRevenue: t(`${p}.potentialRevenue`),
    confidence: t(`${p}.confidence`),
    suggestion: t(`${p}.suggestion`),
    expectedAdoption: t(`${p}.expectedAdoption`),
    departmentUsage: t(`${p}.departmentUsage`),
    intervention: t(`${p}.intervention`),
    steps: t(`${p}.steps`),
    growthPartner: t(`${p}.growthPartner`),
    notAttributed: t(`${p}.notAttributed`),
    atRiskRenewals: t(`${p}.atRiskRenewals`),
    sections: {
      overview: t(`${p}.sections.overview`),
      renewals: t(`${p}.sections.renewals`),
      expansion: t(`${p}.sections.expansion`),
      subscription: t(`${p}.sections.subscription`),
      businessPacks: t(`${p}.sections.businessPacks`),
      forecast: t(`${p}.sections.forecast`),
      clv: t(`${p}.sections.clv`),
      retention: t(`${p}.sections.retention`),
      recommendations: t(`${p}.sections.recommendations`),
      executive: t(`${p}.sections.executive`),
      partner: t(`${p}.sections.partner`),
      playbooks: t(`${p}.sections.playbooks`),
      governance: t(`${p}.sections.governance`),
    },
    renewalStatus: {
      upcoming: t(`${p}.renewalStatus.upcoming`),
      in_review: t(`${p}.renewalStatus.inReview`),
      renewed: t(`${p}.renewalStatus.renewed`),
      at_risk: t(`${p}.renewalStatus.atRisk`),
      lost: t(`${p}.renewalStatus.lost`),
    },
    forecastPeriod: {
      "30_days": t(`${p}.forecastPeriod.days30`),
      "90_days": t(`${p}.forecastPeriod.days90`),
      "6_months": t(`${p}.forecastPeriod.months6`),
      "12_months": t(`${p}.forecastPeriod.months12`),
    },
    status: {
      completed: t(`${p}.status.completed`),
      notAllowed: t(`${p}.status.notAllowed`),
      requiresAttention: t(`${p}.status.requiresAttention`),
      information: t(`${p}.status.information`),
      restricted: t(`${p}.status.restricted`),
      verified: t(`${p}.status.verified`),
      waiting: t(`${p}.status.waiting`),
    },
  };
}

export type RevenueGrowthCenterLabels = ReturnType<typeof buildRevenueGrowthCenterLabels>;
