import type { SupportHistoryLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildSupportHistoryLabels(t: Translator): SupportHistoryLabels {
  const p = "customerApp.portalStructure.supportHistory";
  return {
    eyebrow: t(`${p}.eyebrow`),
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    breadcrumbSupport: t(`${p}.breadcrumbSupport`),
    breadcrumbHistory: t(`${p}.breadcrumbHistory`),
    backToSupport: t(`${p}.backToSupport`),
    createRequest: t(`${p}.createRequest`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyAction: t(`${p}.emptyAction`),
    errorTitle: t(`${p}.errorTitle`),
    errorBody: t(`${p}.errorBody`),
    retry: t(`${p}.retry`),
    sections: {
      overview: t(`${p}.sections.overview`),
      filters: t(`${p}.sections.filters`),
      cases: t(`${p}.sections.cases`),
      insights: t(`${p}.sections.insights`),
      understanding: t(`${p}.sections.understanding`),
    },
    overview: {
      totalHistorical: t(`${p}.overview.totalHistorical`),
      resolved: t(`${p}.overview.resolved`),
      closed: t(`${p}.overview.closed`),
      reopened: t(`${p}.overview.reopened`),
      archived: t(`${p}.overview.archived`),
      avgResolutionDays: t(`${p}.overview.avgResolutionDays`),
      daysUnit: t(`${p}.overview.daysUnit`),
    },
    filters: {
      search: t(`${p}.filters.search`),
      searchPlaceholder: t(`${p}.filters.searchPlaceholder`),
      status: t(`${p}.filters.status`),
      category: t(`${p}.filters.category`),
      priority: t(`${p}.filters.priority`),
      channel: t(`${p}.filters.channel`),
      assigned: t(`${p}.filters.assigned`),
      dateFrom: t(`${p}.filters.dateFrom`),
      dateTo: t(`${p}.filters.dateTo`),
      sort: t(`${p}.filters.sort`),
      all: t(`${p}.filters.all`),
      apply: t(`${p}.filters.apply`),
      clear: t(`${p}.filters.clear`),
    },
    sortOptions: {
      updated_desc: t(`${p}.sortOptions.updatedDesc`),
      updated_asc: t(`${p}.sortOptions.updatedAsc`),
      created_desc: t(`${p}.sortOptions.createdDesc`),
      created_asc: t(`${p}.sortOptions.createdAsc`),
      priority_desc: t(`${p}.sortOptions.priorityDesc`),
      title_asc: t(`${p}.sortOptions.titleAsc`),
    },
    card: {
      viewCase: t(`${p}.card.viewCase`),
      createdBy: t(`${p}.card.createdBy`),
      created: t(`${p}.card.created`),
      updated: t(`${p}.card.updated`),
      resolved: t(`${p}.card.resolved`),
      status: t(`${p}.card.status`),
      priority: t(`${p}.card.priority`),
      category: t(`${p}.card.category`),
      channel: t(`${p}.card.channel`),
      assignee: t(`${p}.card.assignee`),
      module: t(`${p}.card.module`),
    },
    pagination: {
      previous: t(`${p}.pagination.previous`),
      next: t(`${p}.pagination.next`),
      page: t(`${p}.pagination.page`),
    },
    insights: {
      topCategories: t(`${p}.insights.topCategories`),
      reopenRate: t(`${p}.insights.reopenRate`),
      recentResolution: t(`${p}.insights.recentResolution`),
      noInsights: t(`${p}.insights.noInsights`),
    },
    understanding: {
      title: t(`${p}.understanding.title`),
      body: t(`${p}.understanding.body`),
      auditTitle: t(`${p}.understanding.auditTitle`),
      auditBody: t(`${p}.understanding.auditBody`),
      reopenTitle: t(`${p}.understanding.reopenTitle`),
      reopenBody: t(`${p}.understanding.reopenBody`),
    },
    categories: {
      technical: t(`${p}.categories.technical`),
      billing: t(`${p}.categories.billing`),
      integrations: t(`${p}.categories.integrations`),
      business_packs: t(`${p}.categories.businessPacks`),
      account: t(`${p}.categories.account`),
      security: t(`${p}.categories.security`),
      general: t(`${p}.categories.general`),
    },
    priorities: {
      low: t(`${p}.priorities.low`),
      medium: t(`${p}.priorities.medium`),
      high: t(`${p}.priorities.high`),
      urgent: t(`${p}.priorities.urgent`),
    },
    statuses: {
      open: t(`${p}.statuses.open`),
      in_review: t(`${p}.statuses.inReview`),
      waiting_for_customer: t(`${p}.statuses.waitingForCustomer`),
      waiting_for_aipify: t(`${p}.statuses.waitingForAipify`),
      resolved: t(`${p}.statuses.resolved`),
      closed: t(`${p}.statuses.closed`),
      reopened: t(`${p}.statuses.reopened`),
      archived: t(`${p}.statuses.archived`),
    },
    channels: {
      app_portal: t(`${p}.channels.appPortal`),
      email: t(`${p}.channels.email`),
      chat: t(`${p}.channels.chat`),
      phone: t(`${p}.channels.phone`),
      assistant: t(`${p}.channels.assistant`),
    },
    detail: {
      reopen: t(`${p}.detail.reopen`),
      reopenTitle: t(`${p}.detail.reopenTitle`),
      reopenReason: t(`${p}.detail.reopenReason`),
      reopenReasonPlaceholder: t(`${p}.detail.reopenReasonPlaceholder`),
      reopenConfirm: t(`${p}.detail.reopenConfirm`),
      reopenCancel: t(`${p}.detail.reopenCancel`),
      reopenSuccess: t(`${p}.detail.reopenSuccess`),
      resolution: t(`${p}.detail.resolution`),
      resolutionSummary: t(`${p}.detail.resolutionSummary`),
      backToHistory: t(`${p}.detail.backToHistory`),
      backToRequests: t(`${p}.detail.backToRequests`),
    },
  };
}
