import type { AutomationLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildAutomationLabels(t: Translator): AutomationLabels {
  const p = "customerApp.portalStructure.businessPackAutomation";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      status: t(`${p}.filters.status`),
      owner: t(`${p}.filters.owner`),
      packKey: t(`${p}.filters.packKey`),
      healthStatus: t(`${p}.filters.healthStatus`),
      periodFrom: t(`${p}.filters.periodFrom`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      totalAutomations: t(`${p}.dashboard.totalAutomations`),
      activeAutomations: t(`${p}.dashboard.activeAutomations`),
      recommendedAutomations: t(`${p}.dashboard.recommendedAutomations`),
      requiringReview: t(`${p}.dashboard.requiringReview`),
      timeSaved: t(`${p}.dashboard.timeSaved`),
      healthOverview: t(`${p}.dashboard.healthOverview`),
      executiveSummary: t(`${p}.dashboard.executiveSummary`),
      recommendedActions: t(`${p}.dashboard.recommendedActions`),
      automationInsights: t(`${p}.dashboard.automationInsights`),
      timeline: t(`${p}.dashboard.timeline`),
      approvalHistory: t(`${p}.dashboard.approvalHistory`),
    },
    card: {
      category: t(`${p}.card.category`),
      status: t(`${p}.card.status`),
      healthStatus: t(`${p}.card.healthStatus`),
      trigger: t(`${p}.card.trigger`),
      action: t(`${p}.card.action`),
      estimatedValue: t(`${p}.card.estimatedValue`),
      owner: t(`${p}.card.owner`),
      lastExecution: t(`${p}.card.lastExecution`),
      successRate: t(`${p}.card.successRate`),
      improvements: t(`${p}.card.improvements`),
      viewDetails: t(`${p}.card.viewDetails`),
      approve: t(`${p}.card.approve`),
    },
    approval: {
      title: t(`${p}.approval.title`),
      notes: t(`${p}.approval.notes`),
      reviewSchedule: t(`${p}.approval.reviewSchedule`),
      submit: t(`${p}.approval.submit`),
      success: t(`${p}.approval.success`),
      governanceNote: t(`${p}.approval.governanceNote`),
    },
    statuses: {
      recommended: t(`${p}.statuses.recommended`),
      draft: t(`${p}.statuses.draft`),
      active: t(`${p}.statuses.active`),
      paused: t(`${p}.statuses.paused`),
      requires_review: t(`${p}.statuses.requiresReview`),
      retired: t(`${p}.statuses.retired`),
    },
    categories: {
      operational: t(`${p}.categories.operational`),
      support: t(`${p}.categories.support`),
      governance: t(`${p}.categories.governance`),
      executive: t(`${p}.categories.executive`),
      notification: t(`${p}.categories.notification`),
      business_pack: t(`${p}.categories.businessPack`),
      customer_success: t(`${p}.categories.customerSuccess`),
      custom: t(`${p}.categories.custom`),
    },
    healthStatuses: {
      healthy: t(`${p}.healthStatuses.healthy`),
      stable: t(`${p}.healthStatuses.stable`),
      requires_attention: t(`${p}.healthStatuses.requiresAttention`),
      at_risk: t(`${p}.healthStatuses.atRisk`),
    },
    recommendations: {
      automateNotifications: t(`${p}.recommendations.automateNotifications`),
      introduceApprovals: t(`${p}.recommendations.introduceApprovals`),
      expandSuccessful: t(`${p}.recommendations.expandSuccessful`),
      reviewFailing: t(`${p}.recommendations.reviewFailing`),
      reduceManualEffort: t(`${p}.recommendations.reduceManualEffort`),
      explorePackAutomation: t(`${p}.recommendations.explorePackAutomation`),
    },
    insights: {
      mostValuable: t(`${p}.insights.mostValuable`),
      underutilized: t(`${p}.insights.underutilized`),
      frequentlyUsed: t(`${p}.insights.frequentlyUsed`),
      failedAttention: t(`${p}.insights.failedAttention`),
      expansionOpportunities: t(`${p}.insights.expansionOpportunities`),
    },
    timelineEvents: {
      automation_activated: t(`${p}.timelineEvents.automationActivated`),
      automation_recommended: t(`${p}.timelineEvents.automationRecommended`),
      review_completed: t(`${p}.timelineEvents.reviewCompleted`),
      improvement_implemented: t(`${p}.timelineEvents.improvementImplemented`),
      recommendation_accepted: t(`${p}.timelineEvents.recommendationAccepted`),
      performance_milestone: t(`${p}.timelineEvents.performanceMilestone`),
      automation_retired: t(`${p}.timelineEvents.automationRetired`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      autoActivate: t(`${p}.faq.autoActivate`),
      autoActivateAnswer: t(`${p}.faq.autoActivateAnswer`),
      whyGovernance: t(`${p}.faq.whyGovernance`),
      whyGovernanceAnswer: t(`${p}.faq.whyGovernanceAnswer`),
    },
  };
}
