import { buildPartnerPortalSectionLabels } from "@/lib/partner-portal/labels";
import type { PartnerPortalSectionKey } from "@/lib/partner-portal";

export function buildPartnerPortalPanelLabels(
  t: (key: string) => string,
  section: PartnerPortalSectionKey,
): Record<string, string> {
  const p = "partnerPortal";
  const sectionLabels = buildPartnerPortalSectionLabels(t, section);

  const keys = [
    "loading",
    "errorTitle",
    "errorMessage",
    "retry",
    "healthScore",
    "activeOpportunities",
    "customersIntroduced",
    "pendingCommissions",
    "pendingSettlements",
    "certificationStatus",
    "certificationProgress",
    "performanceOverview",
    "leadsThisMonth",
    "activeReferrals",
    "conversionRate",
    "onboardingProgress",
    "nextStep",
    "completeOnboarding",
    "activityFeed",
    "emptyWelcomeTitle",
    "emptyWelcomeMessage",
    "advisorDescription",
    "advisorNote",
    "businessInformation",
    "saveProfile",
    "profileSaved",
    "onboardingStarted",
    "actionFailed",
    "verificationTitle",
    "submitVerification",
    "securityTitle",
    "twoFactorEnabled",
    "twoFactorRequired",
    "manageTwoFactor",
    "teamTitle",
    "activeMembers",
    "invitedMembers",
    "company",
    "contact",
    "status",
    "prospect",
    "customer",
    "amount",
    "period",
    "emptyOpportunities",
    "emptyCustomers",
    "emptyCommissions",
    "emptySettlements",
    "emptyAcademy",
    "emptyMaterials",
    "partnerType_registered",
    "partnerType_certified",
    "partnerType_professional",
    "partnerType_elite",
    "partnerType_strategic",
    "certificationStatus_pending",
    "certificationStatus_certified",
    "certificationStatus_professional",
    "certificationStatus_enterprise",
    "certificationStatus_master",
    "onboardingStep_verify_business",
    "onboardingStep_configure_profile",
    "onboardingStep_complete_introduction",
    "onboardingStep_access_academy",
    "onboardingStep_become_active",
    "verificationType_company_registration",
    "verificationType_organization_number",
    "verificationType_vat",
    "verificationType_identity",
    "verificationType_banking",
    "verificationStatus_pending",
    "verificationStatus_in_review",
    "verificationStatus_verified",
    "verificationStatus_rejected",
    "teamRole_partner_owner",
    "teamRole_owner",
    "teamRole_partner_manager",
    "teamRole_manager",
    "teamRole_sales_member",
    "teamRole_sales_representative",
    "teamRole_trainer",
    "teamRole_advisor",
    "teamRole_viewer",
    "memberStatus_invited",
    "memberStatus_active",
    "memberStatus_suspended",
    "field_company_name",
    "field_organization_number",
    "field_vat_number",
    "field_business_address",
    "field_contact_email",
    "field_contact_phone",
    "field_website",
    "field_country_code",
    "field_preferred_language",
  ];

  const labels: Record<string, string> = {
    section_dashboard_title: t(`${p}.sections.dashboard.title`),
    section_dashboard_subtitle: t(`${p}.sections.dashboard.subtitle`),
    section_opportunities_title: t(`${p}.sections.opportunities.title`),
    section_opportunities_subtitle: t(`${p}.sections.opportunities.subtitle`),
    section_customers_title: t(`${p}.sections.customers.title`),
    section_customers_subtitle: t(`${p}.sections.customers.subtitle`),
    section_academy_title: t(`${p}.sections.academy.title`),
    section_academy_subtitle: t(`${p}.sections.academy.subtitle`),
    section_materials_title: t(`${p}.sections.materials.title`),
    section_materials_subtitle: t(`${p}.sections.materials.subtitle`),
    section_commissions_title: t(`${p}.sections.commissions.title`),
    section_commissions_subtitle: t(`${p}.sections.commissions.subtitle`),
    section_settlements_title: t(`${p}.sections.settlements.title`),
    section_settlements_subtitle: t(`${p}.sections.settlements.subtitle`),
    section_performance_title: t(`${p}.sections.performance.title`),
    section_performance_subtitle: t(`${p}.sections.performance.subtitle`),
    section_advisor_title: t(`${p}.sections.advisor.title`),
    section_advisor_subtitle: t(`${p}.sections.advisor.subtitle`),
    section_settings_title: t(`${p}.sections.settings.title`),
    section_settings_subtitle: t(`${p}.sections.settings.subtitle`),
    [`section_${section}_title`]: sectionLabels.title,
    [`section_${section}_subtitle`]: sectionLabels.subtitle,
  };

  for (const key of keys) {
    labels[key] = t(`${p}.${key}`);
  }

  return labels;
}
