import type { EnterpriseBenchmarkingLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildEnterpriseBenchmarkingLabels(t: Translator): EnterpriseBenchmarkingLabels {
  const p = "customerApp.portalStructure.enterpriseBenchmarking";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    anonymizedNote: t(`${p}.anonymizedNote`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      dimension: t(`${p}.filters.dimension`),
      maturityLevel: t(`${p}.filters.maturityLevel`),
      organizationalArea: t(`${p}.filters.organizationalArea`),
      priorityLevel: t(`${p}.filters.priorityLevel`),
      timePeriod: t(`${p}.filters.timePeriod`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      overallMaturity: t(`${p}.dashboard.overallMaturity`),
      operationalMaturity: t(`${p}.dashboard.operationalMaturity`),
      governanceMaturity: t(`${p}.dashboard.governanceMaturity`),
      learningMaturity: t(`${p}.dashboard.learningMaturity`),
      executiveIntelligence: t(`${p}.dashboard.executiveIntelligence`),
      businessPackMaturity: t(`${p}.dashboard.businessPackMaturity`),
      recommendedFocus: t(`${p}.dashboard.recommendedFocus`),
      executiveSummary: t(`${p}.dashboard.executiveSummary`),
      benchmarkInsights: t(`${p}.dashboard.benchmarkInsights`),
      recommendedActions: t(`${p}.dashboard.recommendedActions`),
      timeline: t(`${p}.dashboard.timeline`),
      maturityDimensions: t(`${p}.dashboard.maturityDimensions`),
      viewDimension: t(`${p}.dashboard.viewDimension`),
    },
    detail: {
      back: t(`${p}.detail.back`),
      currentLevel: t(`${p}.detail.currentLevel`),
      strengths: t(`${p}.detail.strengths`),
      opportunities: t(`${p}.detail.opportunities`),
      historicalTrends: t(`${p}.detail.historicalTrends`),
      recommendedActions: t(`${p}.detail.recommendedActions`),
      relatedCapabilities: t(`${p}.detail.relatedCapabilities`),
      learningResources: t(`${p}.detail.learningResources`),
      completeAssessment: t(`${p}.detail.completeAssessment`),
    },
    assessment: {
      title: t(`${p}.assessment.title`),
      notes: t(`${p}.assessment.notes`),
      maturityLevel: t(`${p}.assessment.maturityLevel`),
      submit: t(`${p}.assessment.submit`),
      success: t(`${p}.assessment.success`),
      governanceNote: t(`${p}.assessment.governanceNote`),
    },
    maturityLevels: {
      "1": t(`${p}.maturityLevels.level1`),
      "2": t(`${p}.maturityLevels.level2`),
      "3": t(`${p}.maturityLevels.level3`),
      "4": t(`${p}.maturityLevels.level4`),
      "5": t(`${p}.maturityLevels.level5`),
      emerging: t(`${p}.maturityLevels.emerging`),
      developing: t(`${p}.maturityLevels.developing`),
      established: t(`${p}.maturityLevels.established`),
      advanced: t(`${p}.maturityLevels.advanced`),
      transformational: t(`${p}.maturityLevels.transformational`),
    },
    dimensions: {
      leadership_decision_making: t(`${p}.dimensions.leadershipDecisionMaking`),
      operational_excellence: t(`${p}.dimensions.operationalExcellence`),
      governance_compliance: t(`${p}.dimensions.governanceCompliance`),
      learning_development: t(`${p}.dimensions.learningDevelopment`),
      customer_success: t(`${p}.dimensions.customerSuccess`),
      business_pack_adoption: t(`${p}.dimensions.businessPackAdoption`),
      strategic_execution: t(`${p}.dimensions.strategicExecution`),
      risk_resilience: t(`${p}.dimensions.riskResilience`),
      automation_readiness: t(`${p}.dimensions.automationReadiness`),
      organizational_intelligence: t(`${p}.dimensions.organizationalIntelligence`),
    },
    priorityLevels: {
      low: t(`${p}.priorityLevels.low`),
      moderate: t(`${p}.priorityLevels.moderate`),
      high: t(`${p}.priorityLevels.high`),
      critical: t(`${p}.priorityLevels.critical`),
    },
    recommendations: {
      expandLearningInitiatives: t(`${p}.recommendations.expandLearningInitiatives`),
      strengthenExecutiveReviews: t(`${p}.recommendations.strengthenExecutiveReviews`),
      increaseBusinessPackAdoption: t(`${p}.recommendations.increaseBusinessPackAdoption`),
      reviewGovernanceResponsibilities: t(`${p}.recommendations.reviewGovernanceResponsibilities`),
      prioritizeStrategicExecution: t(`${p}.recommendations.prioritizeStrategicExecution`),
      celebrateMaturityAdvancements: t(`${p}.recommendations.celebrateMaturityAdvancements`),
    },
    insights: {
      strongest: t(`${p}.insights.strongest`),
      lowest: t(`${p}.insights.lowest`),
      improvingRapidly: t(`${p}.insights.improvingRapidly`),
      limitedProgress: t(`${p}.insights.limitedProgress`),
      crossFunctional: t(`${p}.insights.crossFunctional`),
    },
    timelineEvents: {
      assessment_completed: t(`${p}.timelineEvents.assessmentCompleted`),
      maturity_baseline: t(`${p}.timelineEvents.maturityBaseline`),
      improvement_launched: t(`${p}.timelineEvents.improvementLaunched`),
      milestone_achieved: t(`${p}.timelineEvents.milestoneAchieved`),
      capability_improved: t(`${p}.timelineEvents.capabilityImproved`),
      strategic_investment: t(`${p}.timelineEvents.strategicInvestment`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      anonymous: t(`${p}.faq.anonymous`),
      anonymousAnswer: t(`${p}.faq.anonymousAnswer`),
      determinesSuccess: t(`${p}.faq.determinesSuccess`),
      determinesSuccessAnswer: t(`${p}.faq.determinesSuccessAnswer`),
    },
  };
}
