import CustomerMasterDetailView from "@/components/platform/CustomerMasterDetailView";
import {
  customerStatusLabels,
  customerTypeLabels,
  invoiceStatusLabels,
  paymentProviderLabels,
  planTypeLabels,
  subscriptionStatusLabels,
  supportCategoryLabels,
  supportPriorityLabels,
} from "@/lib/platform/labels";
import { getDictionary } from "@/lib/i18n/get-dictionary";
import { getLocale } from "@/lib/i18n/get-locale";
import { createTranslator } from "@/lib/i18n/translate";

type CustomerDetailPageProps = {
  params: Promise<{ id: string }>;
};

export default async function CustomerDetailPage({ params }: CustomerDetailPageProps) {
  const { id } = await params;
  const locale = await getLocale();
  const dict = await getDictionary(locale, ["platform", "branding"]);
  const t = createTranslator(dict);

  const statusLabels = {
    ...customerStatusLabels(t),
    ...subscriptionStatusLabels(t),
    open: t("platform.masterDetail.supportStatus.open"),
    closed: t("platform.masterDetail.supportStatus.closed"),
    escalated: t("platform.masterDetail.supportStatus.escalated"),
    pending: t("platform.masterDetail.paymentPending"),
  };

  const installationStatusLabels = {
    pending: t("platform.status.installation.pending"),
    active: t("platform.status.installation.active"),
    paused: t("platform.status.installation.paused"),
    revoked: t("platform.status.installation.revoked"),
  };

  return (
    <CustomerMasterDetailView
      customerId={id}
      locale={locale}
      labels={{
        back: t("platform.masterDetail.back"),
        commandCenterTitle: t("platform.masterDetail.commandCenterTitle"),
        commandCenterSubtitle: t("platform.masterDetail.commandCenterSubtitle"),
        loading: t("platform.masterDetail.loading"),
        notFound: t("platform.masterDetail.notFound"),
        health: t("platform.masterDetail.health"),
        healthLabels: {
          healthy: t("platform.customers.healthLabels.healthy"),
          attention: t("platform.customers.healthLabels.attention"),
          atRisk: t("platform.customers.healthLabels.atRisk"),
        },
        successScore: t("platform.masterDetail.successScore"),
        opportunities: t("platform.masterDetail.opportunities"),
        tabs: {
          overview: t("platform.masterDetail.tabs.overview"),
          users: t("platform.masterDetail.tabs.users"),
          support: t("platform.masterDetail.tabs.support"),
          automations: t("platform.masterDetail.tabs.automations"),
          aiInsights: t("platform.masterDetail.tabs.aiInsights"),
          timeline: t("platform.masterDetail.tabs.timeline"),
          integrations: t("platform.masterDetail.tabs.integrations"),
          settings: t("platform.masterDetail.tabs.settings"),
        },
        customerNumber: t("platform.customers.customerNumber"),
        customerName: t("platform.customers.name"),
        customerType: t("platform.masterDetail.customerType"),
        companyNumber: t("platform.masterDetail.companyNumber"),
        country: t("platform.customers.country"),
        language: t("platform.masterDetail.language"),
        plan: t("platform.subscriptions.plan"),
        subscriptionStatus: t("platform.masterDetail.subscriptionStatus"),
        paymentProvider: t("platform.billing.provider"),
        ownerEmail: t("platform.masterDetail.ownerEmail"),
        createdAt: t("platform.masterDetail.createdAt"),
        currentPlan: t("platform.masterDetail.currentPlan"),
        trialRemaining: t("platform.masterDetail.trialRemaining"),
        nextBillingDate: t("platform.subscriptions.nextBillingDate"),
        totalUsers: t("platform.masterDetail.totalUsers"),
        totalInstallations: t("platform.masterDetail.totalInstallations"),
        outstandingInvoices: t("platform.masterDetail.outstandingInvoices"),
        name: t("platform.masterDetail.name"),
        email: t("platform.customers.email"),
        role: t("platform.masterDetail.role"),
        status: t("platform.customers.status"),
        lastLogin: t("platform.masterDetail.lastLogin"),
        lastActive: t("platform.masterDetail.lastActive"),
        permissions: t("platform.masterDetail.permissions"),
        inviteTeam: t("platform.masterDetail.inviteTeam"),
        ownerBadge: t("platform.masterDetail.ownerBadge"),
        installationId: t("platform.masterDetail.installationId"),
        installationName: t("platform.masterDetail.installationName"),
        domain: t("platform.masterDetail.domain"),
        systemType: t("platform.masterDetail.systemType"),
        version: t("platform.masterDetail.version"),
        connectedModules: t("platform.masterDetail.connectedModules"),
        installedDate: t("platform.masterDetail.installedDate"),
        lastHealthCheck: t("platform.masterDetail.lastHealthCheck"),
        healthScore: t("platform.masterDetail.healthScore"),
        recentErrors: t("platform.masterDetail.recentErrors"),
        lastSync: t("platform.masterDetail.lastSync"),
        trialDates: t("platform.masterDetail.trialDates"),
        startDate: t("platform.masterDetail.startDate"),
        price: t("platform.subscriptions.price"),
        currency: t("platform.masterDetail.currency"),
        billingCycle: t("platform.subscriptions.billingCycle"),
        invoiceNumber: t("platform.invoices.invoiceNumber"),
        invoiceStatus: t("platform.invoices.status"),
        issueDate: t("platform.masterDetail.issueDate"),
        dueDate: t("platform.invoices.dueDate"),
        amount: t("platform.invoices.amount"),
        paymentStatus: t("platform.masterDetail.paymentStatus"),
        kid: t("platform.billing.kid"),
        view: t("platform.invoices.send"),
        download: t("platform.invoices.downloadPdf"),
        resend: t("platform.invoices.resend"),
        markPaid: t("platform.invoices.markPaid"),
        supportRequests: t("platform.masterDetail.supportRequests"),
        automatedActions: t("platform.masterDetail.automatedActions"),
        aiRecommendations: t("platform.masterDetail.aiRecommendations"),
        avgResponseTime: t("platform.masterDetail.avgResponseTime"),
        mostUsedModules: t("platform.masterDetail.mostUsedModules"),
        openTickets: t("platform.masterDetail.openTickets"),
        closedTickets: t("platform.masterDetail.closedTickets"),
        avgResolutionTime: t("platform.masterDetail.avgResolutionTime"),
        lastContact: t("platform.masterDetail.lastContact"),
        assignedAgent: t("platform.masterDetail.assignedAgent"),
        subject: t("platform.masterDetail.subject"),
        category: t("platform.masterDetail.category"),
        priority: t("platform.masterDetail.priority"),
        noData: t("platform.masterDetail.noData"),
        noErrors: t("platform.masterDetail.noErrors"),
        actionPending: t("platform.invoices.actionPending"),
        quickActionsTitle: t("platform.masterDetail.quickActionsTitle"),
        quickActions: {
          openSupport: t("platform.masterDetail.quickActions.openSupport"),
          pauseSubscription: t("platform.masterDetail.quickActions.pauseSubscription"),
          generateInvoice: t("platform.masterDetail.quickActions.generateInvoice"),
          resendWelcome: t("platform.masterDetail.quickActions.resendWelcome"),
          runHealthScan: t("platform.masterDetail.quickActions.runHealthScan"),
          scheduleOnboarding: t("platform.masterDetail.quickActions.scheduleOnboarding"),
        },
        recommendationFeed: {
          title: t("platform.masterDetail.recommendationFeed.title"),
          priority: t("platform.masterDetail.recommendationFeed.priority"),
          recommendedAction: t("platform.masterDetail.recommendationFeed.recommendedAction"),
          confidence: t("platform.masterDetail.recommendationFeed.confidence"),
          dismiss: t("platform.masterDetail.recommendationFeed.dismiss"),
          empty: t("platform.masterDetail.recommendationFeed.empty"),
        },
        priorityLabels: {
          low: t("platform.masterDetail.priorityLabels.low"),
          normal: t("platform.masterDetail.priorityLabels.normal"),
          high: t("platform.masterDetail.priorityLabels.high"),
          urgent: t("platform.masterDetail.priorityLabels.urgent"),
        },
        opportunityLabels: {
          upgrade: t("platform.masterDetail.opportunityLabels.upgrade"),
          expansion: t("platform.masterDetail.opportunityLabels.expansion"),
          retention_risk: t("platform.masterDetail.opportunityLabels.retention_risk"),
          low_engagement: t("platform.masterDetail.opportunityLabels.low_engagement"),
          advocate: t("platform.masterDetail.opportunityLabels.advocate"),
        },
        timeline: {
          empty: t("platform.masterDetail.timeline.empty"),
          categories: {
            support: t("platform.masterDetail.timeline.categories.support"),
            billing: t("platform.masterDetail.timeline.categories.billing"),
            installations: t("platform.masterDetail.timeline.categories.installations"),
            automations: t("platform.masterDetail.timeline.categories.automations"),
            users: t("platform.masterDetail.timeline.categories.users"),
            system: t("platform.masterDetail.timeline.categories.system"),
            ai_recommendations: t("platform.masterDetail.timeline.categories.ai_recommendations"),
          },
        },
        integrations: {
          connectionStatus: t("platform.masterDetail.integrations.connectionStatus"),
          lastSync: t("platform.masterDetail.integrations.lastSync"),
          health: t("platform.masterDetail.integrations.health"),
          actions: t("platform.masterDetail.integrations.actions"),
          connected: t("platform.masterDetail.integrations.connected"),
          pending: t("platform.masterDetail.integrations.pending"),
          error: t("platform.masterDetail.integrations.error"),
          webhooks: t("platform.masterDetail.integrations.webhooks"),
          customApi: t("platform.masterDetail.integrations.customApi"),
        },
        automations: {
          empty: t("platform.masterDetail.automationsTab.empty"),
          name: t("platform.masterDetail.automationsTab.name"),
          status: t("platform.masterDetail.automationsTab.status"),
          trigger: t("platform.masterDetail.automationsTab.trigger"),
          lastRun: t("platform.masterDetail.automationsTab.lastRun"),
          nextRun: t("platform.masterDetail.automationsTab.nextRun"),
          statusLabels: {
            active: t("platform.masterDetail.automationsTab.statusLabels.active"),
            paused: t("platform.masterDetail.automationsTab.statusLabels.paused"),
            warning: t("platform.masterDetail.automationsTab.statusLabels.warning"),
            failed: t("platform.masterDetail.automationsTab.statusLabels.failed"),
          },
        },
        settings: {
          billingTitle: t("platform.masterDetail.settings.billingTitle"),
          subscriptionTitle: t("platform.masterDetail.settings.subscriptionTitle"),
          invoicesTitle: t("platform.masterDetail.settings.invoicesTitle"),
        },
        inviteModal: {
          title: t("platform.masterDetail.inviteModal.title"),
          email: t("platform.masterDetail.inviteModal.email"),
          role: t("platform.masterDetail.inviteModal.role"),
          department: t("platform.masterDetail.inviteModal.department"),
          welcomeMessage: t("platform.masterDetail.inviteModal.welcomeMessage"),
          send: t("platform.masterDetail.inviteModal.send"),
          cancel: t("platform.masterDetail.inviteModal.cancel"),
          success: t("platform.masterDetail.inviteModal.success"),
        },
        invitationStatusLabels: {
          pending: t("platform.masterDetail.invitationStatus.pending"),
          accepted: t("platform.masterDetail.invitationStatus.accepted"),
          expired: t("platform.masterDetail.invitationStatus.expired"),
          cancelled: t("platform.masterDetail.invitationStatus.cancelled"),
        },
        aiInsightsTitle: t("platform.masterDetail.aiInsightsTitle"),
        statusLabels: { ...statusLabels, ...installationStatusLabels },
        typeLabels: customerTypeLabels(t),
        planTypeLabels: planTypeLabels(t),
        providerLabels: paymentProviderLabels(t),
        invoiceStatusLabels: invoiceStatusLabels(t),
        userRoleLabels: {
          owner: t("platform.masterDetail.userRoles.owner"),
          admin: t("platform.masterDetail.userRoles.admin"),
          administrator: t("platform.masterDetail.userRoles.administrator"),
          support: t("platform.masterDetail.userRoles.support"),
          moderator: t("platform.masterDetail.userRoles.moderator"),
          marketing: t("platform.masterDetail.userRoles.marketing"),
          analyst: t("platform.masterDetail.userRoles.analyst"),
          staff: t("platform.masterDetail.userRoles.staff"),
          custom: t("platform.masterDetail.userRoles.custom"),
          read_only: t("platform.masterDetail.userRoles.readOnly"),
        },
        userStatusLabels: {
          active: t("platform.masterDetail.userStatus.active"),
          invited: t("platform.masterDetail.userStatus.invited"),
          disabled: t("platform.masterDetail.userStatus.disabled"),
        },
        supportCategoryLabels: supportCategoryLabels(t),
        seconds: t("platform.metrics.seconds"),
        hours: t("platform.masterDetail.hours"),
        days: t("platform.customers.days"),
        pulseLabel: t("branding.pulseLabel"),
      }}
    />
  );
}
