import CustomerMasterDetailView from "@/components/platform/CustomerMasterDetailView";
import {
  customerStatusLabels,
  customerTypeLabels,
  invoiceStatusLabels,
  paymentProviderLabels,
  planTypeLabels,
  subscriptionStatusLabels,
  supportCategoryLabels,
  supportPriorityLabels,
} from "@/lib/platform/labels";
import { getDictionary } from "@/lib/i18n/get-dictionary";
import { getLocale } from "@/lib/i18n/get-locale";
import { createTranslator } from "@/lib/i18n/translate";

type CustomerDetailPageProps = {
  params: Promise<{ id: string }>;
};

export default async function CustomerDetailPage({ params }: CustomerDetailPageProps) {
  const { id } = await params;
  const locale = await getLocale();
  const dict = await getDictionary(locale, ["platform", "branding"]);
  const t = createTranslator(dict);

  const statusLabels = {
    ...customerStatusLabels(t),
    ...subscriptionStatusLabels(t),
    open: t("platform.masterDetail.supportStatus.open"),
    closed: t("platform.masterDetail.supportStatus.closed"),
    escalated: t("platform.masterDetail.supportStatus.escalated"),
    pending: t("platform.masterDetail.paymentPending"),
  };

  const installationStatusLabels = {
    pending: t("platform.status.installation.pending"),
    active: t("platform.status.installation.active"),
    paused: t("platform.status.installation.paused"),
    revoked: t("platform.status.installation.revoked"),
  };

  return (
    <CustomerMasterDetailView
      customerId={id}
      locale={locale}
      labels={{
        back: t("platform.masterDetail.back"),
        commandCenterTitle: t("platform.masterDetail.commandCenterTitle"),
        commandCenterSubtitle: t("platform.masterDetail.commandCenterSubtitle"),
        loading: t("platform.masterDetail.loading"),
        notFound: t("platform.masterDetail.notFound"),
        health: t("platform.masterDetail.health"),
        healthLabels: {
          healthy: t("platform.customers.healthLabels.healthy"),
          attention: t("platform.customers.healthLabels.attention"),
          atRisk: t("platform.customers.healthLabels.atRisk"),
        },
        successScore: t("platform.masterDetail.successScore"),
        successScoreLabels: {
          excellent: t("platform.masterDetail.successScoreLabels.excellent"),
          good: t("platform.masterDetail.successScoreLabels.good"),
          needs_attention: t("platform.masterDetail.successScoreLabels.needs_attention"),
          at_risk: t("platform.masterDetail.successScoreLabels.at_risk"),
        },
        installationHealthLabels: {
          healthy: t("platform.masterDetail.installationHealthLabels.healthy"),
          warning: t("platform.masterDetail.installationHealthLabels.warning"),
          critical: t("platform.masterDetail.installationHealthLabels.critical"),
        },
        opportunities: t("platform.masterDetail.opportunities"),
        tabs: {
          overview: t("platform.masterDetail.tabs.overview"),
          users: t("platform.masterDetail.tabs.users"),
          support: t("platform.masterDetail.tabs.support"),
          automations: t("platform.masterDetail.tabs.automations"),
          aiInsights: t("platform.masterDetail.tabs.aiInsights"),
          timeline: t("platform.masterDetail.tabs.timeline"),
          integrations: t("platform.masterDetail.tabs.integrations"),
          settings: t("platform.masterDetail.tabs.settings"),
        },
        customerNumber: t("platform.customers.customerNumber"),
        customerName: t("platform.customers.name"),
        customerType: t("platform.masterDetail.customerType"),
        companyNumber: t("platform.masterDetail.companyNumber"),
        country: t("platform.customers.country"),
        language: t("platform.masterDetail.language"),
        plan: t("platform.subscriptions.plan"),
        subscriptionStatus: t("platform.masterDetail.subscriptionStatus"),
        paymentProvider: t("platform.billing.provider"),
        ownerEmail: t("platform.masterDetail.ownerEmail"),
        createdAt: t("platform.masterDetail.createdAt"),
        currentPlan: t("platform.masterDetail.currentPlan"),
        trialRemaining: t("platform.masterDetail.trialRemaining"),
        nextBillingDate: t("platform.subscriptions.nextBillingDate"),
        totalUsers: t("platform.masterDetail.totalUsers"),
        totalInstallations: t("platform.masterDetail.totalInstallations"),
        outstandingInvoices: t("platform.masterDetail.outstandingInvoices"),
        name: t("platform.masterDetail.name"),
        email: t("platform.customers.email"),
        role: t("platform.masterDetail.role"),
        status: t("platform.customers.status"),
        lastLogin: t("platform.masterDetail.lastLogin"),
        lastActive: t("platform.masterDetail.lastActive"),
        permissions: t("platform.masterDetail.permissions"),
        inviteTeam: t("platform.masterDetail.inviteTeam"),
        ownerBadge: t("platform.masterDetail.ownerBadge"),
        installationId: t("platform.masterDetail.installationId"),
        installationName: t("platform.masterDetail.installationName"),
        domain: t("platform.masterDetail.domain"),
        systemType: t("platform.masterDetail.systemType"),
        version: t("platform.masterDetail.version"),
        connectedModules: t("platform.masterDetail.connectedModules"),
        installedDate: t("platform.masterDetail.installedDate"),
        lastHealthCheck: t("platform.masterDetail.lastHealthCheck"),
        healthScore: t("platform.masterDetail.healthScore"),
        recentErrors: t("platform.masterDetail.recentErrors"),
        lastSync: t("platform.masterDetail.lastSync"),
        trialDates: t("platform.masterDetail.trialDates"),
        startDate: t("platform.masterDetail.startDate"),
        price: t("platform.subscriptions.price"),
        currency: t("platform.masterDetail.currency"),
        billingCycle: t("platform.subscriptions.billingCycle"),
        invoiceNumber: t("platform.invoices.invoiceNumber"),
        invoiceStatus: t("platform.invoices.status"),
        issueDate: t("platform.masterDetail.issueDate"),
        dueDate: t("platform.invoices.dueDate"),
        amount: t("platform.invoices.amount"),
        paymentStatus: t("platform.masterDetail.paymentStatus"),
        kid: t("platform.billing.kid"),
        view: t("platform.invoices.send"),
        download: t("platform.invoices.downloadPdf"),
        resend: t("platform.invoices.resend"),
        markPaid: t("platform.invoices.markPaid"),
        supportRequests: t("platform.masterDetail.supportRequests"),
        automatedActions: t("platform.masterDetail.automatedActions"),
        aiRecommendations: t("platform.masterDetail.aiRecommendations"),
        avgResponseTime: t("platform.masterDetail.avgResponseTime"),
        mostUsedModules: t("platform.masterDetail.mostUsedModules"),
        openTickets: t("platform.masterDetail.openTickets"),
        closedTickets: t("platform.masterDetail.closedTickets"),
        avgResolutionTime: t("platform.masterDetail.avgResolutionTime"),
        lastContact: t("platform.masterDetail.lastContact"),
        assignedAgent: t("platform.masterDetail.assignedAgent"),
        subject: t("platform.masterDetail.subject"),
        category: t("platform.masterDetail.category"),
        priority: t("platform.masterDetail.priority"),
        noData: t("platform.masterDetail.noData"),
        noErrors: t("platform.masterDetail.noErrors"),
        actionPending: t("platform.invoices.actionPending"),
        quickActionsTitle: t("platform.masterDetail.quickActionsTitle"),
        quickActions: {
          openSupport: t("platform.masterDetail.quickActions.openSupport"),
          pauseSubscription: t("platform.masterDetail.quickActions.pauseSubscription"),
          generateInvoice: t("platform.masterDetail.quickActions.generateInvoice"),
          resendWelcome: t("platform.masterDetail.quickActions.resendWelcome"),
          runHealthScan: t("platform.masterDetail.quickActions.runHealthScan"),
          scheduleOnboarding: t("platform.masterDetail.quickActions.scheduleOnboarding"),
        },
        recommendationFeed: {
          title: t("platform.masterDetail.recommendationFeed.title"),
          priority: t("platform.masterDetail.recommendationFeed.priority"),
          recommendedAction: t("platform.masterDetail.recommendationFeed.recommendedAction"),
          confidence: t("platform.masterDetail.recommendationFeed.confidence"),
          dismiss: t("platform.masterDetail.recommendationFeed.dismiss"),
          empty: t("platform.masterDetail.recommendationFeed.empty"),
        },
        priorityLabels: {
          low: t("platform.masterDetail.priorityLabels.low"),
          normal: t("platform.masterDetail.priorityLabels.normal"),
          high: t("platform.masterDetail.priorityLabels.high"),
          urgent: t("platform.masterDetail.priorityLabels.urgent"),
        },
        opportunityLabels: {
          upgrade: t("platform.masterDetail.opportunityLabels.upgrade"),
          expansion: t("platform.masterDetail.opportunityLabels.expansion"),
          retention_risk: t("platform.masterDetail.opportunityLabels.retention_risk"),
          low_engagement: t("platform.masterDetail.opportunityLabels.low_engagement"),
          advocate: t("platform.masterDetail.opportunityLabels.advocate"),
        },
        foundation: {
          emptyOpportunities: t("platform.masterDetail.foundation.emptyOpportunities"),
        },
        timeline: {
          empty: t("platform.masterDetail.timeline.empty"),
          filterAll: t("platform.masterDetail.timeline.filterAll"),
          expandDetails: t("platform.masterDetail.timeline.expandDetails"),
          categories: {
            support: t("platform.masterDetail.timeline.categories.support"),
            billing: t("platform.masterDetail.timeline.categories.billing"),
            automation: t("platform.masterDetail.timeline.categories.automation"),
            installation: t("platform.masterDetail.timeline.categories.installation"),
            user: t("platform.masterDetail.timeline.categories.user"),
            integrations: t("platform.masterDetail.timeline.categories.integrations"),
            system: t("platform.masterDetail.timeline.categories.system"),
            ai_recommendation: t("platform.masterDetail.timeline.categories.ai_recommendation"),
            subscription: t("platform.masterDetail.timeline.categories.subscription"),
          },
        },
        integrations: {
          connectionStatus: t("platform.masterDetail.integrations.connectionStatus"),
          lastSync: t("platform.masterDetail.integrations.lastSync"),
          health: t("platform.masterDetail.integrations.health"),
          actions: t("platform.masterDetail.integrations.actions"),
          connected: t("platform.masterDetail.integrations.connected"),
          pending: t("platform.masterDetail.integrations.pending"),
          error: t("platform.masterDetail.integrations.error"),
          webhooks: t("platform.masterDetail.integrations.webhooks"),
          customApi: t("platform.masterDetail.integrations.customApi"),
        },
        automations: {
          empty: t("platform.masterDetail.automationsTab.empty"),
          name: t("platform.masterDetail.automationsTab.name"),
          status: t("platform.masterDetail.automationsTab.status"),
          trigger: t("platform.masterDetail.automationsTab.trigger"),
          lastRun: t("platform.masterDetail.automationsTab.lastRun"),
          nextRun: t("platform.masterDetail.automationsTab.nextRun"),
          executedAt: t("platform.masterDetail.automationsTab.executedAt"),
          duration: t("platform.masterDetail.automationsTab.duration"),
          error: t("platform.masterDetail.automationsTab.error"),
          statusLabels: {
            active: t("platform.masterDetail.automationsTab.statusLabels.active"),
            paused: t("platform.masterDetail.automationsTab.statusLabels.paused"),
            warning: t("platform.masterDetail.automationsTab.statusLabels.warning"),
            failed: t("platform.masterDetail.automationsTab.statusLabels.failed"),
          },
          runStatusLabels: {
            success: t("platform.masterDetail.automationsTab.runStatusLabels.success"),
            warning: t("platform.masterDetail.automationsTab.runStatusLabels.warning"),
            failed: t("platform.masterDetail.automationsTab.runStatusLabels.failed"),
          },
        },
        settings: {
          billingTitle: t("platform.masterDetail.settings.billingTitle"),
          subscriptionTitle: t("platform.masterDetail.settings.subscriptionTitle"),
          invoicesTitle: t("platform.masterDetail.settings.invoicesTitle"),
        },
        inviteModal: {
          title: t("platform.masterDetail.inviteModal.title"),
          email: t("platform.masterDetail.inviteModal.email"),
          role: t("platform.masterDetail.inviteModal.role"),
          department: t("platform.masterDetail.inviteModal.department"),
          welcomeMessage: t("platform.masterDetail.inviteModal.welcomeMessage"),
          send: t("platform.masterDetail.inviteModal.send"),
          cancel: t("platform.masterDetail.inviteModal.cancel"),
          success: t("platform.masterDetail.inviteModal.success"),
        },
        invitationStatusLabels: {
          pending: t("platform.masterDetail.invitationStatus.pending"),
          accepted: t("platform.masterDetail.invitationStatus.accepted"),
          expired: t("platform.masterDetail.invitationStatus.expired"),
          cancelled: t("platform.masterDetail.invitationStatus.cancelled"),
        },
        aiInsightsTitle: t("platform.masterDetail.aiInsightsTitle"),
        selfLearning: {
          title: t("platform.masterDetail.selfLearning.title"),
          environment: t("platform.masterDetail.selfLearning.environment"),
          environmentLabels: {
            internal: t("platform.masterDetail.selfLearning.environmentLabels.internal"),
            pilot: t("platform.masterDetail.selfLearning.environmentLabels.pilot"),
            customer: t("platform.masterDetail.selfLearning.environmentLabels.customer"),
            enterprise: t("platform.masterDetail.selfLearning.environmentLabels.enterprise"),
          },
          stages: {
            detection: t("platform.masterDetail.selfLearning.stages.detection"),
            diagnosis: t("platform.masterDetail.selfLearning.stages.diagnosis"),
            recommendation: t("platform.masterDetail.selfLearning.stages.recommendation"),
            healing: t("platform.masterDetail.selfLearning.stages.healing"),
          },
          learningEvents: {
            title: t("platform.masterDetail.selfLearning.learningEvents.title"),
            empty: t("platform.masterDetail.selfLearning.learningEvents.empty"),
            eventType: t("platform.masterDetail.selfLearning.learningEvents.eventType"),
            category: t("platform.masterDetail.selfLearning.learningEvents.category"),
          },
          patterns: {
            title: t("platform.masterDetail.selfLearning.patterns.title"),
            empty: t("platform.masterDetail.selfLearning.patterns.empty"),
            detections: t("platform.masterDetail.selfLearning.patterns.detections"),
            successRate: t("platform.masterDetail.selfLearning.patterns.successRate"),
            action: t("platform.masterDetail.selfLearning.patterns.action"),
          },
          effectiveness: {
            title: t("platform.masterDetail.selfLearning.effectiveness.title"),
            empty: t("platform.masterDetail.selfLearning.effectiveness.empty"),
            presented: t("platform.masterDetail.selfLearning.effectiveness.presented"),
            accepted: t("platform.masterDetail.selfLearning.effectiveness.accepted"),
            acceptanceRate: t("platform.masterDetail.selfLearning.effectiveness.acceptanceRate"),
          },
          selfHealing: {
            title: t("platform.masterDetail.selfLearning.selfHealing.title"),
            empty: t("platform.masterDetail.selfLearning.selfHealing.empty"),
            action: t("platform.masterDetail.selfLearning.selfHealing.action"),
            risk: t("platform.masterDetail.selfLearning.selfHealing.risk"),
            result: t("platform.masterDetail.selfLearning.selfHealing.result"),
            duration: t("platform.masterDetail.selfLearning.selfHealing.duration"),
            pendingApproval: t("platform.masterDetail.selfLearning.selfHealing.pendingApproval"),
          },
          riskLabels: {
            low: t("platform.masterDetail.selfLearning.riskLabels.low"),
            medium: t("platform.masterDetail.selfLearning.riskLabels.medium"),
            high: t("platform.masterDetail.selfLearning.riskLabels.high"),
            critical: t("platform.masterDetail.selfLearning.riskLabels.critical"),
          },
          resultLabels: {
            success: t("platform.masterDetail.selfLearning.resultLabels.success"),
            failed: t("platform.masterDetail.selfLearning.resultLabels.failed"),
            skipped: t("platform.masterDetail.selfLearning.resultLabels.skipped"),
            pending_approval: t("platform.masterDetail.selfLearning.resultLabels.pending_approval"),
          },
          eventTypeLabels: {
            detection: t("platform.masterDetail.selfLearning.eventTypeLabels.detection"),
            diagnosis: t("platform.masterDetail.selfLearning.eventTypeLabels.diagnosis"),
            recommendation: t("platform.masterDetail.selfLearning.eventTypeLabels.recommendation"),
            healing: t("platform.masterDetail.selfLearning.eventTypeLabels.healing"),
          },
          categoryLabels: {
            automation: t("platform.masterDetail.selfLearning.categoryLabels.automation"),
            webhook: t("platform.masterDetail.selfLearning.categoryLabels.webhook"),
            support: t("platform.masterDetail.selfLearning.categoryLabels.support"),
            integration: t("platform.masterDetail.selfLearning.categoryLabels.integration"),
            onboarding: t("platform.masterDetail.selfLearning.categoryLabels.onboarding"),
            health: t("platform.masterDetail.selfLearning.categoryLabels.health"),
            billing: t("platform.masterDetail.selfLearning.categoryLabels.billing"),
            system: t("platform.masterDetail.selfLearning.categoryLabels.system"),
          },
        },
        statusLabels: { ...statusLabels, ...installationStatusLabels },
        typeLabels: customerTypeLabels(t),
        planTypeLabels: planTypeLabels(t),
        providerLabels: paymentProviderLabels(t),
        invoiceStatusLabels: invoiceStatusLabels(t),
        userRoleLabels: {
          owner: t("platform.masterDetail.userRoles.owner"),
          admin: t("platform.masterDetail.userRoles.admin"),
          administrator: t("platform.masterDetail.userRoles.administrator"),
          support: t("platform.masterDetail.userRoles.support"),
          moderator: t("platform.masterDetail.userRoles.moderator"),
          marketing: t("platform.masterDetail.userRoles.marketing"),
          analyst: t("platform.masterDetail.userRoles.analyst"),
          staff: t("platform.masterDetail.userRoles.staff"),
          custom: t("platform.masterDetail.userRoles.custom"),
          read_only: t("platform.masterDetail.userRoles.readOnly"),
        },
        userStatusLabels: {
          active: t("platform.masterDetail.userStatus.active"),
          invited: t("platform.masterDetail.userStatus.invited"),
          disabled: t("platform.masterDetail.userStatus.disabled"),
        },
        supportCategoryLabels: supportCategoryLabels(t),
        seconds: t("platform.metrics.seconds"),
        hours: t("platform.masterDetail.hours"),
        days: t("platform.customers.days"),
        pulseLabel: t("branding.pulseLabel"),
      }}
    />
  );
}
