import type { PackLifecycleLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildPackLifecycleLabels(t: Translator): PackLifecycleLabels {
  const p = "customerApp.portalStructure.businessPackLifecycle";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      lifecycleStage: t(`${p}.filters.lifecycleStage`),
      reviewOwner: t(`${p}.filters.reviewOwner`),
      department: t(`${p}.filters.department`),
      adoptionStatus: t(`${p}.filters.adoptionStatus`),
      reviewStatus: t(`${p}.filters.reviewStatus`),
      periodFrom: t(`${p}.filters.periodFrom`),
      all: t(`${p}.filters.all`),
      lowAdoption: t(`${p}.filters.lowAdoption`),
      healthyAdoption: t(`${p}.filters.healthyAdoption`),
      highAdoption: t(`${p}.filters.highAdoption`),
    },
    dashboard: {
      totalInstalled: t(`${p}.dashboard.totalInstalled`),
      lifecycleDistribution: t(`${p}.dashboard.lifecycleDistribution`),
      packsRequiringReview: t(`${p}.dashboard.packsRequiringReview`),
      recentlyActivated: t(`${p}.dashboard.recentlyActivated`),
      recentlyRetired: t(`${p}.dashboard.recentlyRetired`),
      recommendedActions: t(`${p}.dashboard.recommendedActions`),
      upcomingReviews: t(`${p}.dashboard.upcomingReviews`),
      installedPacks: t(`${p}.dashboard.installedPacks`),
      lifecycleTimeline: t(`${p}.dashboard.lifecycleTimeline`),
      reviewCenter: t(`${p}.dashboard.reviewCenter`),
      governance: t(`${p}.dashboard.governance`),
    },
    card: {
      lifecycleStage: t(`${p}.card.lifecycleStage`),
      installedDate: t(`${p}.card.installedDate`),
      lastActivity: t(`${p}.card.lastActivity`),
      adoptionScore: t(`${p}.card.adoptionScore`),
      usersAssigned: t(`${p}.card.usersAssigned`),
      reviewFrequency: t(`${p}.card.reviewFrequency`),
      reviewOwner: t(`${p}.card.reviewOwner`),
      relatedPacks: t(`${p}.card.relatedPacks`),
      upcomingMilestones: t(`${p}.card.upcomingMilestones`),
      viewDetails: t(`${p}.card.viewDetails`),
    },
    review: {
      title: t(`${p}.review.title`),
      quarterly: t(`${p}.review.quarterly`),
      annual: t(`${p}.review.annual`),
      onDemand: t(`${p}.review.onDemand`),
      submitReview: t(`${p}.review.submitReview`),
      notes: t(`${p}.review.notes`),
      owner: t(`${p}.review.owner`),
      activelyUsed: t(`${p}.review.activelyUsed`),
      objectivesAchieved: t(`${p}.review.objectivesAchieved`),
      additionalUsers: t(`${p}.review.additionalUsers`),
      trainingRecommended: t(`${p}.review.trainingRecommended`),
      retirementAppropriate: t(`${p}.review.retirementAppropriate`),
      upgradesRecommended: t(`${p}.review.upgradesRecommended`),
    },
    governance: {
      assignedOwner: t(`${p}.governance.assignedOwner`),
      responsibleDepartment: t(`${p}.governance.responsibleDepartment`),
      reviewHistory: t(`${p}.governance.reviewHistory`),
      lifecycleNotes: t(`${p}.governance.lifecycleNotes`),
      decisionHistory: t(`${p}.governance.decisionHistory`),
      updateLifecycle: t(`${p}.governance.updateLifecycle`),
      saveNotes: t(`${p}.governance.saveNotes`),
    },
    stages: {
      planned: t(`${p}.stages.planned`),
      evaluating: t(`${p}.stages.evaluating`),
      implementing: t(`${p}.stages.implementing`),
      active: t(`${p}.stages.active`),
      optimizing: t(`${p}.stages.optimizing`),
      mature: t(`${p}.stages.mature`),
      under_review: t(`${p}.stages.underReview`),
      retiring: t(`${p}.stages.retiring`),
      retired: t(`${p}.stages.retired`),
    },
    reviewStatuses: {
      scheduled: t(`${p}.reviewStatuses.scheduled`),
      in_progress: t(`${p}.reviewStatuses.inProgress`),
      completed: t(`${p}.reviewStatuses.completed`),
      overdue: t(`${p}.reviewStatuses.overdue`),
    },
    reviewFrequencies: {
      quarterly: t(`${p}.reviewFrequencies.quarterly`),
      annual: t(`${p}.reviewFrequencies.annual`),
      on_demand: t(`${p}.reviewFrequencies.onDemand`),
    },
    timelineEvents: {
      recommendation_received: t(`${p}.timelineEvents.recommendationReceived`),
      evaluation_initiated: t(`${p}.timelineEvents.evaluationInitiated`),
      approval_completed: t(`${p}.timelineEvents.approvalCompleted`),
      installation_completed: t(`${p}.timelineEvents.installationCompleted`),
      review_conducted: t(`${p}.timelineEvents.reviewConducted`),
      retirement_initiated: t(`${p}.timelineEvents.retirementInitiated`),
      stage_updated: t(`${p}.timelineEvents.stageUpdated`),
    },
    recommendations: {
      scheduleOptimizationReview: t(`${p}.recommendations.scheduleOptimizationReview`),
      expandUsageTeams: t(`${p}.recommendations.expandUsageTeams`),
      completeTrainingInitiatives: t(`${p}.recommendations.completeTrainingInitiatives`),
      reassessRetirementCandidates: t(`${p}.recommendations.reassessRetirementCandidates`),
      reviewUnderutilizedCapabilities: t(`${p}.recommendations.reviewUnderutilizedCapabilities`),
      celebrateMatureImplementations: t(`${p}.recommendations.celebrateMatureImplementations`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      autoRetire: t(`${p}.faq.autoRetire`),
      autoRetireAnswer: t(`${p}.faq.autoRetireAnswer`),
      whyReviews: t(`${p}.faq.whyReviews`),
      whyReviewsAnswer: t(`${p}.faq.whyReviewsAnswer`),
    },
  };
}
