import type { Translator } from "@/lib/i18n/translate";

export function buildStrategicIntelligenceLabels(t: Translator) {
  const p = "customerApp.strategicIntelligence";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    executiveBriefing: t(`${p}.executiveBriefing`),
    insights: t(`${p}.insights`),
    recommendations: t(`${p}.recommendations`),
    forecasts: t(`${p}.forecasts`),
    trends: t(`${p}.trends`),
    opportunities: t(`${p}.opportunities`),
    risks: t(`${p}.risks`),
    reports: t(`${p}.reports`),
    executiveDashboard: t(`${p}.executiveDashboard`),
    organizationHealthScore: t(`${p}.organizationHealthScore`),
    healthStatus: t(`${p}.healthStatus`),
    openInsights: t(`${p}.openInsights`),
    openRecommendations: t(`${p}.openRecommendations`),
    activeForecasts: t(`${p}.activeForecasts`),
    identifiedOpportunities: t(`${p}.identifiedOpportunities`),
    trendsTracked: t(`${p}.trendsTracked`),
    boardReportsReady: t(`${p}.boardReportsReady`),
    generateBriefing: t(`${p}.generateBriefing`),
    generateInsight: t(`${p}.generateInsight`),
    generateRecommendation: t(`${p}.generateRecommendation`),
    generateForecast: t(`${p}.generateForecast`),
    generateOpportunity: t(`${p}.generateOpportunity`),
    createBoardReport: t(`${p}.createBoardReport`),
    acknowledgeRecommendation: t(`${p}.acknowledgeRecommendation`),
    refreshHealthScore: t(`${p}.refreshHealthScore`),
    insightTitle: t(`${p}.insightTitle`),
    recommendationTitle: t(`${p}.recommendationTitle`),
    forecastTitle: t(`${p}.forecastTitle`),
    opportunityTitle: t(`${p}.opportunityTitle`),
    reportTitle: t(`${p}.reportTitle`),
    noInsights: t(`${p}.noInsights`),
    noRecommendations: t(`${p}.noRecommendations`),
    noForecasts: t(`${p}.noForecasts`),
    noOpportunities: t(`${p}.noOpportunities`),
    noBoardReports: t(`${p}.noBoardReports`),
    emptyHint: t(`${p}.emptyHint`),
    whatChanged: t(`${p}.whatChanged`),
    requiresAttention: t(`${p}.requiresAttention`),
    recommendedFocus: t(`${p}.recommendedFocus`),
    companionAdvisory: t(`${p}.companionAdvisory`),
    companionInsights: t(`${p}.companionInsights`),
    decisionSupport: t(`${p}.decisionSupport`),
    auditLog: t(`${p}.auditLog`),
    briefingTitle: t(`${p}.briefingTitle`),
    recommendationsTitle: t(`${p}.recommendationsTitle`),
    boardReportsTitle: t(`${p}.boardReportsTitle`),
    save: t(`${p}.save`),
  };
}

export type StrategicIntelligenceLabels = ReturnType<typeof buildStrategicIntelligenceLabels>;
