import type { IntelligenceBriefingsLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildIntelligenceBriefingsLabels(t: Translator): IntelligenceBriefingsLabels {
  const p = "customerApp.portalStructure.intelligenceBriefings";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      type: t(`${p}.filters.type`),
      priority: t(`${p}.filters.priority`),
      periodFrom: t(`${p}.filters.periodFrom`),
      periodTo: t(`${p}.filters.periodTo`),
      audience: t(`${p}.filters.audience`),
      orgStatus: t(`${p}.filters.orgStatus`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      latest: t(`${p}.dashboard.latest`),
      previous: t(`${p}.dashboard.previous`),
      priorityItems: t(`${p}.dashboard.priorityItems`),
      emergingOpportunities: t(`${p}.dashboard.emergingOpportunities`),
      emergingRisks: t(`${p}.dashboard.emergingRisks`),
      recommendedActions: t(`${p}.dashboard.recommendedActions`),
    },
    generate: {
      title: t(`${p}.generate.title`),
      type: t(`${p}.generate.type`),
      audience: t(`${p}.generate.audience`),
      periodFrom: t(`${p}.generate.periodFrom`),
      periodTo: t(`${p}.generate.periodTo`),
      notes: t(`${p}.generate.notes`),
      submit: t(`${p}.generate.submit`),
      cancel: t(`${p}.generate.cancel`),
    },
    card: {
      type: t(`${p}.card.type`),
      priority: t(`${p}.card.priority`),
      orgStatus: t(`${p}.card.orgStatus`),
      generatedAt: t(`${p}.card.generatedAt`),
      audience: t(`${p}.card.audience`),
      view: t(`${p}.card.view`),
    },
    detail: {
      executiveSummary: t(`${p}.detail.executiveSummary`),
      keyInsights: t(`${p}.detail.keyInsights`),
      risks: t(`${p}.detail.risks`),
      opportunities: t(`${p}.detail.opportunities`),
      recommendedActions: t(`${p}.detail.recommendedActions`),
      relatedInitiatives: t(`${p}.detail.relatedInitiatives`),
      relatedCommitments: t(`${p}.detail.relatedCommitments`),
      relatedDecisions: t(`${p}.detail.relatedDecisions`),
      relatedFollowUps: t(`${p}.detail.relatedFollowUps`),
      activityTimeline: t(`${p}.detail.activityTimeline`),
      recommendations: t(`${p}.detail.recommendations`),
      reportingPeriod: t(`${p}.detail.reportingPeriod`),
    },
    types: {
      daily_briefing: t(`${p}.types.dailyBriefing`),
      weekly_briefing: t(`${p}.types.weeklyBriefing`),
      monthly_briefing: t(`${p}.types.monthlyBriefing`),
      executive_briefing: t(`${p}.types.executiveBriefing`),
      operational_briefing: t(`${p}.types.operationalBriefing`),
      strategic_briefing: t(`${p}.types.strategicBriefing`),
      risk_briefing: t(`${p}.types.riskBriefing`),
      custom_briefing: t(`${p}.types.customBriefing`),
    },
    priorities: {
      informational: t(`${p}.priorities.informational`),
      important: t(`${p}.priorities.important`),
      high_priority: t(`${p}.priorities.highPriority`),
      critical_attention_required: t(`${p}.priorities.criticalAttentionRequired`),
    },
    orgStatuses: {
      stable: t(`${p}.orgStatuses.stable`),
      improving: t(`${p}.orgStatuses.improving`),
      requires_attention: t(`${p}.orgStatuses.requiresAttention`),
      elevated_risk: t(`${p}.orgStatuses.elevatedRisk`),
    },
    recommendations: {
      reviewStrategicRisks: t(`${p}.recommendations.reviewStrategicRisks`),
      celebrateImprovements: t(`${p}.recommendations.celebrateImprovements`),
      addressCommitments: t(`${p}.recommendations.addressCommitments`),
      scheduleInitiativeReviews: t(`${p}.recommendations.scheduleInitiativeReviews`),
      operationalBottlenecks: t(`${p}.recommendations.operationalBottlenecks`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      howCreated: t(`${p}.faq.howCreated`),
      howCreatedAnswer: t(`${p}.faq.howCreatedAnswer`),
      autoDecisions: t(`${p}.faq.autoDecisions`),
      autoDecisionsAnswer: t(`${p}.faq.autoDecisionsAnswer`),
    },
  };
}
