import type { KompisWorkspaceToolDefinition } from "./types";

/**
 * Canonical Core tool patterns for authenticated customer workspace.
 * Tools call allowlisted server adapters — never direct database access.
 * Registration does not imply availability; contract must enable each tool.
 */
export const KOMPIS_WORKSPACE_TOOL_REGISTRY: readonly KompisWorkspaceToolDefinition[] = [
  {
    tool_key: "search_knowledge",
    version: "1",
    kind: "read",
    risk_classification: "low",
    default_confirmation: "none",
    module: "*",
    entity_types: [],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.searchKnowledge",
    enabled: true,
    deprecated: false,
    timeout_ms: 8000,
    rate_limit_per_minute: 60,
  },
  {
    tool_key: "get_current_page_help",
    version: "1",
    kind: "read",
    risk_classification: "low",
    default_confirmation: "none",
    module: "*",
    entity_types: [],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.getCurrentPageHelp",
    enabled: true,
    deprecated: false,
    timeout_ms: 8000,
    rate_limit_per_minute: 60,
  },
  {
    tool_key: "get_my_account_summary",
    version: "1",
    kind: "read",
    risk_classification: "low",
    default_confirmation: "none",
    module: "account",
    entity_types: ["account"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.getMyAccountSummary",
    enabled: true,
    deprecated: false,
    timeout_ms: 8000,
    rate_limit_per_minute: 60,
  },
  {
    tool_key: "get_my_access_status",
    version: "1",
    kind: "read",
    risk_classification: "low",
    default_confirmation: "none",
    module: "access",
    entity_types: ["access"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.getMyAccessStatus",
    enabled: true,
    deprecated: false,
    timeout_ms: 8000,
    rate_limit_per_minute: 60,
  },
  {
    tool_key: "get_my_verification_status",
    version: "1",
    kind: "read",
    risk_classification: "low",
    default_confirmation: "none",
    module: "verification",
    entity_types: ["verification"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.getMyVerificationStatus",
    enabled: true,
    deprecated: false,
    timeout_ms: 8000,
    rate_limit_per_minute: 60,
  },
  {
    tool_key: "get_my_support_cases",
    version: "1",
    kind: "read",
    risk_classification: "moderate",
    default_confirmation: "none",
    module: "support",
    entity_types: ["support_case"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.getMySupportCases",
    enabled: true,
    deprecated: false,
    timeout_ms: 10000,
    rate_limit_per_minute: 30,
  },
  {
    tool_key: "get_my_items",
    version: "1",
    kind: "read",
    risk_classification: "low",
    default_confirmation: "none",
    module: "catalog",
    entity_types: ["item"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.getMyItems",
    enabled: true,
    deprecated: false,
    timeout_ms: 10000,
    rate_limit_per_minute: 40,
  },
  {
    tool_key: "get_my_item",
    version: "1",
    kind: "read",
    risk_classification: "low",
    default_confirmation: "none",
    module: "catalog",
    entity_types: ["item"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.getMyItem",
    enabled: true,
    deprecated: false,
    timeout_ms: 8000,
    rate_limit_per_minute: 60,
  },
  {
    tool_key: "get_my_orders",
    version: "1",
    kind: "read",
    risk_classification: "moderate",
    default_confirmation: "none",
    module: "orders",
    entity_types: ["order"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.getMyOrders",
    enabled: true,
    deprecated: false,
    timeout_ms: 10000,
    rate_limit_per_minute: 30,
  },
  {
    tool_key: "get_my_subscriptions",
    version: "1",
    kind: "read",
    risk_classification: "moderate",
    default_confirmation: "none",
    module: "subscriptions",
    entity_types: ["subscription"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.getMySubscriptions",
    enabled: true,
    deprecated: false,
    timeout_ms: 8000,
    rate_limit_per_minute: 30,
  },
  {
    tool_key: "get_my_notifications",
    version: "1",
    kind: "read",
    risk_classification: "low",
    default_confirmation: "none",
    module: "notifications",
    entity_types: ["notification"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.getMyNotifications",
    enabled: true,
    deprecated: false,
    timeout_ms: 8000,
    rate_limit_per_minute: 60,
  },
  {
    tool_key: "get_current_page_help",
    version: "1",
    kind: "read",
    risk_classification: "low",
    default_confirmation: "none",
    module: "*",
    entity_types: [],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.getCurrentPageHelp",
    enabled: true,
    deprecated: false,
    timeout_ms: 8000,
    rate_limit_per_minute: 90,
  },
  {
    tool_key: "search_knowledge",
    version: "1",
    kind: "read",
    risk_classification: "low",
    default_confirmation: "none",
    module: "*",
    entity_types: [],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.searchKnowledge",
    enabled: true,
    deprecated: false,
    timeout_ms: 10000,
    rate_limit_per_minute: 60,
  },
  {
    tool_key: "get_product_information",
    version: "1",
    kind: "read",
    risk_classification: "low",
    default_confirmation: "none",
    module: "catalog",
    entity_types: ["product", "service"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.getProductInformation",
    enabled: true,
    deprecated: false,
    timeout_ms: 10000,
    rate_limit_per_minute: 60,
  },
  {
    tool_key: "get_feature_requirements",
    version: "1",
    kind: "read",
    risk_classification: "low",
    default_confirmation: "none",
    module: "*",
    entity_types: [],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.getFeatureRequirements",
    enabled: true,
    deprecated: false,
    timeout_ms: 8000,
    rate_limit_per_minute: 60,
  },
  {
    tool_key: "create_draft",
    version: "1",
    kind: "draft",
    risk_classification: "moderate",
    default_confirmation: "lightweight",
    module: "catalog",
    entity_types: ["item", "product", "listing"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.createDraft",
    enabled: true,
    deprecated: false,
    timeout_ms: 15000,
    rate_limit_per_minute: 20,
  },
  {
    tool_key: "update_draft",
    version: "1",
    kind: "draft",
    risk_classification: "moderate",
    default_confirmation: "lightweight",
    module: "catalog",
    entity_types: ["item", "product", "listing"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.updateDraft",
    enabled: true,
    deprecated: false,
    timeout_ms: 15000,
    rate_limit_per_minute: 30,
  },
  {
    tool_key: "suggest_improvements",
    version: "1",
    kind: "draft",
    risk_classification: "low",
    default_confirmation: "none",
    module: "*",
    entity_types: ["item", "product", "listing", "profile", "offer"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.suggestImprovements",
    enabled: true,
    deprecated: false,
    timeout_ms: 15000,
    rate_limit_per_minute: 30,
  },
  {
    tool_key: "validate_draft",
    version: "1",
    kind: "read",
    risk_classification: "low",
    default_confirmation: "none",
    module: "catalog",
    entity_types: ["item", "product", "listing"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.validateDraft",
    enabled: true,
    deprecated: false,
    timeout_ms: 10000,
    rate_limit_per_minute: 40,
  },
  {
    tool_key: "create_support_draft",
    version: "1",
    kind: "draft",
    risk_classification: "moderate",
    default_confirmation: "explicit",
    module: "support",
    entity_types: ["support_case"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.createSupportDraft",
    enabled: true,
    deprecated: false,
    timeout_ms: 15000,
    rate_limit_per_minute: 15,
  },
  {
    tool_key: "update_preference",
    version: "1",
    kind: "write",
    risk_classification: "moderate",
    default_confirmation: "explicit",
    module: "account",
    entity_types: ["preference"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.updatePreference",
    enabled: true,
    deprecated: false,
    timeout_ms: 10000,
    rate_limit_per_minute: 15,
  },
  {
    tool_key: "start_application",
    version: "1",
    kind: "write",
    risk_classification: "elevated",
    default_confirmation: "explicit",
    module: "applications",
    entity_types: ["application"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.startApplication",
    enabled: true,
    deprecated: false,
    timeout_ms: 15000,
    rate_limit_per_minute: 10,
  },
  {
    tool_key: "invite_collaborator",
    version: "1",
    kind: "write",
    risk_classification: "elevated",
    default_confirmation: "strong",
    module: "collaboration",
    entity_types: ["invitation"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.inviteCollaborator",
    enabled: true,
    deprecated: false,
    timeout_ms: 12000,
    rate_limit_per_minute: 10,
  },
  {
    tool_key: "pause_item",
    version: "1",
    kind: "write",
    risk_classification: "elevated",
    default_confirmation: "explicit",
    module: "catalog",
    entity_types: ["item"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.pauseItem",
    enabled: true,
    deprecated: false,
    timeout_ms: 10000,
    rate_limit_per_minute: 15,
  },
  {
    tool_key: "submit_for_review",
    version: "1",
    kind: "write",
    risk_classification: "elevated",
    default_confirmation: "explicit",
    module: "catalog",
    entity_types: ["item", "listing"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.submitForReview",
    enabled: true,
    deprecated: false,
    timeout_ms: 12000,
    rate_limit_per_minute: 10,
  },
  {
    tool_key: "publish_item",
    version: "1",
    kind: "write",
    risk_classification: "high",
    default_confirmation: "strong",
    module: "catalog",
    entity_types: ["item", "listing"],
    description_key: "customerApp.portalStructure.kompisWorkspace.tools.publishItem",
    enabled: true,
    deprecated: false,
    timeout_ms: 15000,
    rate_limit_per_minute: 8,
  },
] as const;

const BY_KEY = new Map(KOMPIS_WORKSPACE_TOOL_REGISTRY.map((t) => [t.tool_key, t]));

export function getKompisWorkspaceToolDefinition(
  toolKey: string
): KompisWorkspaceToolDefinition | null {
  return BY_KEY.get(toolKey) ?? null;
}

export function listKompisWorkspaceToolKeys(): readonly string[] {
  return KOMPIS_WORKSPACE_TOOL_REGISTRY.map((t) => t.tool_key);
}
