import type { SupportRequestsLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildSupportRequestsLabels(t: Translator): SupportRequestsLabels {
  const p = "customerApp.portalStructure.supportRequests";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    createRequest: t(`${p}.createRequest`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    filters: {
      title: t(`${p}.filters.title`),
      category: t(`${p}.filters.category`),
      status: t(`${p}.filters.status`),
      priority: t(`${p}.filters.priority`),
      search: t(`${p}.filters.search`),
      searchPlaceholder: t(`${p}.filters.searchPlaceholder`),
      all: t(`${p}.filters.all`),
    },
    card: {
      createdBy: t(`${p}.card.createdBy`),
      created: t(`${p}.card.created`),
      updated: t(`${p}.card.updated`),
      status: t(`${p}.card.status`),
      priority: t(`${p}.card.priority`),
      category: t(`${p}.card.category`),
      assignee: t(`${p}.card.assignee`),
      module: t(`${p}.card.module`),
    },
    detail: {
      description: t(`${p}.detail.description`),
      statusHistory: t(`${p}.detail.statusHistory`),
      timeline: t(`${p}.detail.timeline`),
      auditHistory: t(`${p}.detail.auditHistory`),
      relatedActivity: t(`${p}.detail.relatedActivity`),
      comments: t(`${p}.detail.comments`),
      commentsPlaceholder: t(`${p}.detail.commentsPlaceholder`),
      internalNotes: t(`${p}.detail.internalNotes`),
      internalNotesPlaceholder: t(`${p}.detail.internalNotesPlaceholder`),
      attachments: t(`${p}.detail.attachments`),
      attachmentsPlaceholder: t(`${p}.detail.attachmentsPlaceholder`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
    },
    categories: {
      technical: t(`${p}.categories.technical`),
      billing: t(`${p}.categories.billing`),
      integrations: t(`${p}.categories.integrations`),
      business_packs: t(`${p}.categories.businessPacks`),
      account: t(`${p}.categories.account`),
      security: t(`${p}.categories.security`),
      general: t(`${p}.categories.general`),
    },
    priorities: {
      low: t(`${p}.priorities.low`),
      medium: t(`${p}.priorities.medium`),
      high: t(`${p}.priorities.high`),
      urgent: t(`${p}.priorities.urgent`),
    },
    statuses: {
      open: t(`${p}.statuses.open`),
      in_review: t(`${p}.statuses.inReview`),
      waiting_for_customer: t(`${p}.statuses.waitingForCustomer`),
      waiting_for_aipify: t(`${p}.statuses.waitingForAipify`),
      resolved: t(`${p}.statuses.resolved`),
      closed: t(`${p}.statuses.closed`),
    },
    form: {
      title: t(`${p}.form.title`),
      titlePlaceholder: t(`${p}.form.titlePlaceholder`),
      description: t(`${p}.form.description`),
      category: t(`${p}.form.category`),
      priority: t(`${p}.form.priority`),
      module: t(`${p}.form.module`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      howContact: t(`${p}.faq.howContact`),
      howContactAnswer: t(`${p}.faq.howContactAnswer`),
      canTrack: t(`${p}.faq.canTrack`),
      canTrackAnswer: t(`${p}.faq.canTrackAnswer`),
      whoCanSee: t(`${p}.faq.whoCanSee`),
      whoCanSeeAnswer: t(`${p}.faq.whoCanSeeAnswer`),
    },
  };
}
