import type { CoreAppIntegrationProviderContract } from "./types";
import { CORE_APP_INTEGRATION_PROVIDER_CONTRACT_VERSION } from "./types";

const baseCapabilities = {
  canIssueCredential: true,
  supportsOneTimeReveal: true,
  supportsRotation: true,
  supportsRevoke: true,
  supportsReturnToApp: true,
  supportsServerExchange: false,
  requiresManualCopyPaste: true,
  supportsConnectionTest: true,
  requiresScopeReview: true,
  requiresExternalLogin: false,
  collectsBaseUrl: false,
  collectsConnectionName: false,
} as const;

/** Ordinary control-provider fixture (registry-shaped). Not for APP hardcoding. */
export const FIXTURE_PROVIDER_UNONIGHT_CONTRACT: CoreAppIntegrationProviderContract = {
  version: CORE_APP_INTEGRATION_PROVIDER_CONTRACT_VERSION,
  providerKey: "unonight",
  displayName: "Unonight",
  adminDisplayName: "Unonight Admin",
  credentialDisplayName: "read-only connection key",
  credentialType: "api_key",
  adminBaseUrl: "https://www.unonight.com",
  adminIntegrationPath: "/admin/integrations/aipify",
  adminIntegrationUrl: "https://www.unonight.com/admin/integrations/aipify",
  allowedAdminHosts: ["www.unonight.com", "unonight.com"],
  connectionTestLabel: "Test connection",
  requiredScopes: ["metadata.read", "organization.read", "integration.status.read"],
  optionalScopes: [],
  scopeLabels: {
    "metadata.read": "Basic integration metadata",
    "organization.read": "Organization identity",
    "integration.status.read": "Integration status",
  },
  scopeDescriptions: {
    "metadata.read": "Read basic integration metadata required to verify the connection.",
    "organization.read": "Read organization identity to bind the connection to the correct workspace.",
    "integration.status.read": "Read integration health and connection status.",
  },
  setupSteps: [
    { key: "open_provider_admin", actionType: "open_admin" },
    { key: "navigate_to_integration", actionType: "navigate" },
    { key: "create_credential", actionType: "create_credential" },
    { key: "confirm_scopes", actionType: "confirm_scopes" },
    { key: "copy_credential", actionType: "copy_credential" },
    { key: "return_to_app", actionType: "return_to_app" },
    { key: "save_credential", actionType: "save_credential" },
    { key: "test_connection", actionType: "test_connection" },
  ],
  helpSections: [
    {
      key: "where",
      body: "Open the provider admin panel, go to Integrations → Aipify, then create a read-only connection key.",
    },
  ],
  capabilities: {
    ...baseCapabilities,
    collectsBaseUrl: true,
    collectsConnectionName: true,
  },
  returnPolicy: {
    supportsReturnToApp: true,
    allowedReturnHosts: ["app.aipify.ai"],
  },
  testPolicy: {
    requiredBeforeActivation: true,
    supportsConnectionTest: true,
  },
  activationPolicy: {
    requiresVerifiedTest: true,
    requiresScopeApproval: true,
  },
  rotationPolicy: {
    supportsRotation: true,
    requiresNewCredential: true,
  },
  revokePolicy: {
    supportsRevoke: true,
    revokeInProviderAdmin: true,
  },
  statusPresentation: {
    pending: "Pending",
    connected: "Connected",
    failed: "Failed",
    rotationRequired: "Rotation required",
    active: "Active",
    inactive: "Inactive",
  },
  externalLoginInstruction: null,
  adminOpenInstruction: "Open Unonight Admin",
  localeFallback: "en",
};

/** Generic provider A — different scopes and no base URL field. */
export const FIXTURE_PROVIDER_A_CONTRACT: CoreAppIntegrationProviderContract = {
  version: CORE_APP_INTEGRATION_PROVIDER_CONTRACT_VERSION,
  providerKey: "provider_a",
  displayName: "Provider A",
  adminDisplayName: "Provider A Console",
  credentialDisplayName: "API key",
  credentialType: "api_key",
  adminBaseUrl: "https://console.provider-a.example",
  adminIntegrationPath: "/integrations/aipify",
  adminIntegrationUrl: "https://console.provider-a.example/integrations/aipify",
  allowedAdminHosts: ["console.provider-a.example", "provider-a.example"],
  connectionTestLabel: "Test connection",
  requiredScopes: ["read_products", "read_orders"],
  optionalScopes: ["read_customers"],
  scopeLabels: {
    read_products: "Products",
    read_orders: "Orders",
    read_customers: "Customers",
  },
  scopeDescriptions: {
    read_products: "Read product catalog metadata.",
    read_orders: "Read order metadata.",
    read_customers: "Read customer metadata.",
  },
  setupSteps: [
    { key: "open_provider_admin", actionType: "open_admin" },
    { key: "create_credential", actionType: "create_credential" },
    { key: "copy_credential", actionType: "copy_credential" },
    { key: "save_credential", actionType: "save_credential" },
    { key: "test_connection", actionType: "test_connection" },
  ],
  helpSections: [{ key: "where", body: "Create an API key in Provider A Console → Integrations." }],
  capabilities: { ...baseCapabilities },
  returnPolicy: { supportsReturnToApp: true, allowedReturnHosts: ["app.aipify.ai"] },
  testPolicy: { requiredBeforeActivation: true, supportsConnectionTest: true },
  activationPolicy: { requiresVerifiedTest: true, requiresScopeApproval: true },
  rotationPolicy: { supportsRotation: true, requiresNewCredential: true },
  revokePolicy: { supportsRevoke: true, revokeInProviderAdmin: true },
  statusPresentation: {
    pending: "Pending",
    connected: "Connected",
    failed: "Failed",
    rotationRequired: "Rotation required",
    active: "Active",
    inactive: "Inactive",
  },
  externalLoginInstruction: null,
  adminOpenInstruction: "Open Provider A Console",
  localeFallback: "en",
};

/** Generic provider B — requires external login; no connection test. */
export const FIXTURE_PROVIDER_B_CONTRACT: CoreAppIntegrationProviderContract = {
  version: CORE_APP_INTEGRATION_PROVIDER_CONTRACT_VERSION,
  providerKey: "provider_b",
  displayName: "Provider B",
  adminDisplayName: "Provider B Admin",
  credentialDisplayName: "service token",
  credentialType: "bearer",
  adminBaseUrl: "https://admin.provider-b.example",
  adminIntegrationPath: "/settings/tokens",
  adminIntegrationUrl: "https://admin.provider-b.example/settings/tokens",
  allowedAdminHosts: ["admin.provider-b.example", "provider-b.example"],
  connectionTestLabel: "Validate token",
  requiredScopes: ["read"],
  optionalScopes: [],
  scopeLabels: { read: "Read access" },
  scopeDescriptions: { read: "Read-only access to approved resources." },
  setupSteps: [
    { key: "external_login", actionType: "external_login", requiresExternalLogin: true },
    { key: "open_provider_admin", actionType: "open_admin" },
    { key: "create_credential", actionType: "create_credential" },
    { key: "copy_credential", actionType: "copy_credential" },
    { key: "save_credential", actionType: "save_credential" },
    { key: "test_connection", actionType: "test_connection" },
  ],
  helpSections: [{ key: "where", body: "Sign in to Provider B Admin, then create a service token." }],
  capabilities: {
    ...baseCapabilities,
    requiresExternalLogin: true,
    supportsConnectionTest: false,
    supportsOneTimeReveal: false,
  },
  returnPolicy: { supportsReturnToApp: false, allowedReturnHosts: ["app.aipify.ai"] },
  testPolicy: { requiredBeforeActivation: false, supportsConnectionTest: false },
  activationPolicy: { requiresVerifiedTest: false, requiresScopeApproval: true },
  rotationPolicy: { supportsRotation: true, requiresNewCredential: true },
  revokePolicy: { supportsRevoke: true, revokeInProviderAdmin: true },
  statusPresentation: {
    pending: "Pending",
    connected: "Connected",
    failed: "Failed",
    rotationRequired: "Rotation required",
    active: "Active",
    inactive: "Inactive",
  },
  externalLoginInstruction: "Log in to Provider B Admin",
  adminOpenInstruction: "Open Provider B Admin",
  localeFallback: "en",
};

export const PROVIDER_CONTRACT_FIXTURES = [
  FIXTURE_PROVIDER_UNONIGHT_CONTRACT,
  FIXTURE_PROVIDER_A_CONTRACT,
  FIXTURE_PROVIDER_B_CONTRACT,
] as const;
