export function buildPartnerCommunicationsLabels(t: (key: string) => string): Record<string, string> {
  const p = "partnerCommunications";
  const keys = [
    "title",
    "subtitle",
    "loading",
    "errorTitle",
    "errorMessage",
    "retry",
    "accessDenied",
    "historyTitle",
    "preferencesTitle",
    "preferencesSubtitle",
    "systemCriticalNote",
    "salesNotifications",
    "milestoneNotifications",
    "settlementNotifications",
    "academyNotifications",
    "complianceNotifications",
    "marketingMaterialUpdates",
    "generalAnnouncements",
    "savePreferences",
    "preferencesSaved",
    "actionFailed",
    "emptyTitle",
    "emptyMessage",
    "subject",
    "status",
    "sentAt",
    "preview",
    "faqTitle",
    "faqWhyEmail",
    "faqWhyEmailAnswer",
    "faqPreferences",
    "faqPreferencesAnswer",
    "faqSender",
    "faqSenderAnswer",
    "status_queued",
    "status_sent",
    "status_delivered",
    "status_opened",
    "status_clicked",
    "status_failed",
    "status_bounced",
  ];
  return Object.fromEntries(keys.map((key) => [key, t(`${p}.${key}`)]));
}

export function buildSuperPartnerCommunicationsLabels(t: (key: string) => string): Record<string, string> {
  const p = "superAdmin.partnerCommunications";
  const keys = [
    "title",
    "subtitle",
    "loading",
    "back",
    "templates",
    "campaigns",
    "automated",
    "recognition",
    "settlement",
    "compliance",
    "logs",
    "activeTemplates",
    "queuedEmails",
    "sentEmails",
    "failedEmails",
    "templateKey",
    "category",
    "status",
    "trigger",
    "sender",
    "preview",
    "sendTest",
    "testSent",
    "actionFailed",
    "emptyTemplates",
    "emptyLogs",
    "recipient",
    "language",
    "resend",
    "resent",
    "activate",
    "pause",
    "saved",
  ];
  return Object.fromEntries(keys.map((key) => [key, t(`${p}.${key}`)]));
}
