import type { ExecutiveForesightLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildExecutiveForesightLabels(t: Translator): ExecutiveForesightLabels {
  const p = "customerApp.portalStructure.executiveForesight";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    advisoryNote: t(`${p}.advisoryNote`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      timeHorizon: t(`${p}.filters.timeHorizon`),
      strategicPriority: t(`${p}.filters.strategicPriority`),
      organizationalArea: t(`${p}.filters.organizationalArea`),
      executiveOwner: t(`${p}.filters.executiveOwner`),
      reviewStatus: t(`${p}.filters.reviewStatus`),
      timePeriod: t(`${p}.filters.timePeriod`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      executiveOutlookScore: t(`${p}.dashboard.executiveOutlookScore`),
      executiveSummary: t(`${p}.dashboard.executiveSummary`),
      emergingOpportunities: t(`${p}.dashboard.emergingOpportunities`),
      emergingRisks: t(`${p}.dashboard.emergingRisks`),
      strategicTopicsRequiringAttention: t(`${p}.dashboard.strategicTopicsRequiringAttention`),
      longTermFocusAreas: t(`${p}.dashboard.longTermFocusAreas`),
      areasGainingMomentum: t(`${p}.dashboard.areasGainingMomentum`),
      areasLosingMomentum: t(`${p}.dashboard.areasLosingMomentum`),
      recommendedConversations: t(`${p}.dashboard.recommendedConversations`),
      executiveQuestions: t(`${p}.dashboard.executiveQuestions`),
      foresightInsights: t(`${p}.dashboard.foresightInsights`),
      observations: t(`${p}.dashboard.observations`),
      recommendations: t(`${p}.dashboard.recommendations`),
      timeline: t(`${p}.dashboard.timeline`),
      longTermPlanning: t(`${p}.dashboard.longTermPlanning`),
      viewObservation: t(`${p}.dashboard.viewObservation`),
    },
    card: {
      category: t(`${p}.card.category`),
      insightType: t(`${p}.card.insightType`),
      strategicPriority: t(`${p}.card.strategicPriority`),
      timeHorizon: t(`${p}.card.timeHorizon`),
      executiveOwner: t(`${p}.card.executiveOwner`),
      reviewStatus: t(`${p}.card.reviewStatus`),
      momentum: t(`${p}.card.momentum`),
    },
    detail: {
      back: t(`${p}.detail.back`),
      reviews: t(`${p}.detail.reviews`),
      notes: t(`${p}.detail.notes`),
      reviewNotes: t(`${p}.detail.reviewNotes`),
      noteText: t(`${p}.detail.noteText`),
      submitReview: t(`${p}.detail.submitReview`),
      addNote: t(`${p}.detail.addNote`),
      reviewSuccess: t(`${p}.detail.reviewSuccess`),
      noteSuccess: t(`${p}.detail.noteSuccess`),
      advisoryNote: t(`${p}.detail.advisoryNote`),
    },
    beginReview: {
      success: t(`${p}.beginReview.success`),
      governanceNote: t(`${p}.beginReview.governanceNote`),
    },
    categories: {
      organizational_growth: t(`${p}.categories.organizationalGrowth`),
      workforce_development: t(`${p}.categories.workforceDevelopment`),
      customer_evolution: t(`${p}.categories.customerEvolution`),
      technology_trends: t(`${p}.categories.technologyTrends`),
      market_dynamics: t(`${p}.categories.marketDynamics`),
      governance_evolution: t(`${p}.categories.governanceEvolution`),
      competitive_awareness: t(`${p}.categories.competitiveAwareness`),
      operational_resilience: t(`${p}.categories.operationalResilience`),
      strategic_innovation: t(`${p}.categories.strategicInnovation`),
      leadership_development: t(`${p}.categories.leadershipDevelopment`),
    },
    insightTypes: {
      momentum_gain: t(`${p}.insightTypes.momentumGain`),
      momentum_loss: t(`${p}.insightTypes.momentumLoss`),
      dependency: t(`${p}.insightTypes.dependency`),
      opportunity: t(`${p}.insightTypes.opportunity`),
      blind_spot: t(`${p}.insightTypes.blindSpot`),
      leadership_observation: t(`${p}.insightTypes.leadershipObservation`),
    },
    strategicPriorities: {
      low: t(`${p}.strategicPriorities.low`),
      moderate: t(`${p}.strategicPriorities.moderate`),
      high: t(`${p}.strategicPriorities.high`),
      strategic: t(`${p}.strategicPriorities.strategic`),
    },
    timeHorizons: {
      "30_days": t(`${p}.timeHorizons.30Days`),
      "90_days": t(`${p}.timeHorizons.90Days`),
      "6_months": t(`${p}.timeHorizons.6Months`),
      "12_months": t(`${p}.timeHorizons.12Months`),
      "24_months": t(`${p}.timeHorizons.24Months`),
      "36_months": t(`${p}.timeHorizons.36Months`),
    },
    reviewStatuses: {
      pending: t(`${p}.reviewStatuses.pending`),
      in_review: t(`${p}.reviewStatuses.inReview`),
      reviewed: t(`${p}.reviewStatuses.reviewed`),
      needs_follow_up: t(`${p}.reviewStatuses.needsFollowUp`),
    },
    momentumDirections: {
      gaining: t(`${p}.momentumDirections.gaining`),
      stable: t(`${p}.momentumDirections.stable`),
      losing: t(`${p}.momentumDirections.losing`),
    },
    recommendations: {
      scheduleStrategicReviews: t(`${p}.recommendations.scheduleStrategicReviews`),
      expandLeadershipConversations: t(`${p}.recommendations.expandLeadershipConversations`),
      strengthenSuccessionPlanning: t(`${p}.recommendations.strengthenSuccessionPlanning`),
      reviewEmergingOpportunities: t(`${p}.recommendations.reviewEmergingOpportunities`),
      improveOrganizationalResilience: t(`${p}.recommendations.improveOrganizationalResilience`),
      monitorEvolvingTrends: t(`${p}.recommendations.monitorEvolvingTrends`),
    },
    timelineEvents: {
      foresight_initialized: t(`${p}.timelineEvents.foresightInitialized`),
      strategic_review_begun: t(`${p}.timelineEvents.strategicReviewBegun`),
      foresight_review_completed: t(`${p}.timelineEvents.foresightReviewCompleted`),
      executive_note_added: t(`${p}.timelineEvents.executiveNoteAdded`),
      strategic_topic_identified: t(`${p}.timelineEvents.strategicTopicIdentified`),
      leadership_discussion_initiated: t(`${p}.timelineEvents.leadershipDiscussionInitiated`),
      opportunity_explored: t(`${p}.timelineEvents.opportunityExplored`),
      preparatory_action_launched: t(`${p}.timelineEvents.preparatoryActionLaunched`),
      lesson_captured: t(`${p}.timelineEvents.lessonCaptured`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      predictFuture: t(`${p}.faq.predictFuture`),
      predictFutureAnswer: t(`${p}.faq.predictFutureAnswer`),
      whoShouldUse: t(`${p}.faq.whoShouldUse`),
      whoShouldUseAnswer: t(`${p}.faq.whoShouldUseAnswer`),
    },
  };
}
