import type { CompanionCoverageEntry, CompanionCoverageReadiness } from "./companion-foundation-coverage-types";
import { UNONIGHT_DIRECTORY_MEMBER_CONTRACT } from "@/lib/unonight/provider-adapter/directory-member-contract";

/** Provider-specific live-source overrides — not generic Core logic. */
export type CoverageProviderOverride = Partial<
  Pick<
    CompanionCoverageEntry,
    | "source_type"
    | "source_reference"
    | "readiness"
    | "command_brief_status"
    | "limitations"
    | "next_required_step"
    | "test_status"
    | "activation_status"
  >
>;

export const UNONIGHT_ADAPTER_COVERAGE_OVERRIDES: Record<string, CoverageProviderOverride> = {
  unonight_community_adapter: {
    source_type: "adapter",
    source_reference: "lib/unonight/provider-adapter/",
    activation_status: "active",
    command_brief_status: "linked",
    test_status: "phase_tested",
  },
};

export const UNONIGHT_CAPABILITY_READINESS_OVERRIDES: Record<string, CompanionCoverageReadiness> = {
  "unonight_community_adapter.member.read.read": "production_ready_candidate",
  "unonight_community_adapter.moderation_queue.read.read": "production_ready_candidate",
  "unonight_community_adapter.report.read.read": "production_ready_candidate",
  "unonight_community_adapter.listing.read.read": "connected_but_partial",
  "unonight_community_adapter.verification_status.read.read": "connected_but_partial",
  "unonight_community_adapter.verification_queue.read.read": "connected_but_partial",
  "unonight_community_adapter.verification_case.read.read": "connected_but_partial",
  "unonight_community_adapter.activity.read.read": "connected_but_partial",
};

/** Explicit member verification coverage modules — Phase 34 audit. */
export const MEMBER_VERIFICATION_COVERAGE_MODULES: readonly CompanionCoverageEntry[] = [
  {
    module_id: "verification.unonight_adapter_status",
    domain: "member_verification",
    business_pack_key: "community_pack",
    provider_key: "unonight_community_adapter",
    capability_ids: ["verification_status.read"],
    source_type: "rpc",
    source_reference: "rpc:get_customer_community_network_center:best_practices",
    runtime_loader: "load-companion-community-context.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "linked",
    action_status: "blocked",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Uses community best-practice moderation_status metadata — not full verification queue.",
      "No document images, ID data, or sensitive profile fields exposed to Companion.",
    ],
    next_required_step: "Connect dedicated verification_queue.read source when Unonight verification RPC is approved.",
    panel: "app",
  },
  {
    module_id: "verification.trust_center",
    domain: "member_verification",
    business_pack_key: "trust_center",
    provider_key: "trust_center_verification",
    capability_ids: ["verification.read", "verification_status.read", "verification.request"],
    source_type: "rpc",
    source_reference: "rpc:get_customer_trust_center / security dashboard RPCs",
    runtime_loader: "load-companion-security-context.ts",
    schema_status: "wired",
    permission_status: "defined",
    activation_status: "active",
    command_brief_status: "none",
    action_status: "approval_required",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "verification.request requires explicit approval — no auto-approve.",
      "Privacy-sensitive verification metadata only.",
    ],
    next_required_step: "Wire verification queue pending counts to Command Brief when live adapter exists.",
    panel: "app",
  },
  {
    module_id: "verification.queue_read",
    domain: "member_verification",
    business_pack_key: "community_pack",
    provider_key: "unonight_community_adapter",
    capability_ids: ["verification_queue.read"],
    source_type: "rpc",
    source_reference: "rpc:get_customer_community_network_center:best_practices",
    runtime_loader: "verification-read-orchestrator.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "linked",
    action_status: "blocked",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Queue summary uses community metadata proxy until dedicated Unonight verification queue RPC is approved.",
      "No document images, ID numbers, or moderator notes exposed to Companion.",
    ],
    next_required_step: "Connect dedicated read-only Unonight verification queue RPC and promote Command Brief to exact semantic match.",
    panel: "app",
  },
  {
    module_id: "verification.case_read",
    domain: "member_verification",
    business_pack_key: "community_pack",
    provider_key: "unonight_community_adapter",
    capability_ids: ["verification_case.read"],
    source_type: "rpc",
    source_reference: "rpc:get_customer_community_network_center:best_practices",
    runtime_loader: "verification-read-orchestrator.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "none",
    action_status: "blocked",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Case lookup uses metadata-only proxy records with masked subject references.",
      "No identity documents or sensitive profile fields.",
    ],
    next_required_step: "Wire dedicated verification case RPC with audit-only metadata fields.",
    panel: "app",
  },
  {
    module_id: "verification.review_create",
    domain: "member_verification",
    business_pack_key: "trust_center",
    provider_key: "trust_center_verification",
    capability_ids: ["verification_review.create"],
    source_type: "none",
    source_reference: null,
    runtime_loader: "load-companion-security-context.ts",
    schema_status: "missing",
    permission_status: "defined",
    activation_status: "disabled",
    command_brief_status: "none",
    action_status: "approval_required",
    language_status: "partial",
    test_status: "missing",
    readiness: "specification_only",
    limitations: ["No reversible verification_review.create registered — verification.request exists instead."],
    next_required_step: "Register reversible review action only if existing Trust Center RPC supports it.",
    panel: "app",
  },
];

/** Explicit organization directory coverage — Phase 33C audit. */
export const ORGANIZATION_DIRECTORY_COVERAGE_MODULES: readonly CompanionCoverageEntry[] = [
  {
    module_id: "directory.core_search",
    domain: "organization_directory",
    business_pack_key: null,
    provider_key: "organization_directory_core",
    capability_ids: [
      "directory.search",
      "person.read",
      "organization.read",
      "relationship.read",
    ],
    source_type: "manifest",
    source_reference: "lib/integration-intelligence/directory/manifests.ts",
    runtime_loader: "companion-directory-context.ts",
    schema_status: "wired",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "none",
    action_status: "blocked",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: ["Generic Core contracts only — provider adapters supply live records."],
    next_required_step: "Connect provider adapters per relationship type with audit logging.",
    panel: "app",
  },
  {
    module_id: "directory.unonight_member",
    domain: "organization_directory",
    business_pack_key: "community_pack",
    provider_key: "unonight_community_member_directory",
    capability_ids: ["member.search"],
    source_type: "none",
    source_reference: null,
    runtime_loader: "companion-directory-context.ts",
    schema_status: "missing",
    permission_status: "defined",
    activation_status: "disabled",
    command_brief_status: "none",
    action_status: "blocked",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "source_missing",
    limitations: [
      "No member list exposed in Phase 33C — contract only.",
      "No raw email/phone — masked fields require explicit permission when source exists.",
    ],
    next_required_step: UNONIGHT_DIRECTORY_MEMBER_CONTRACT.next_required_step,
    panel: "app",
  },
  {
    module_id: "directory.hr_employee",
    domain: "organization_directory",
    business_pack_key: "hr_pack",
    provider_key: "hr_employee_directory",
    capability_ids: ["employee.search"],
    source_type: "rpc",
    source_reference: "rpc:workforce_employee_directory",
    runtime_loader: "load-companion-hr-context.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "none",
    action_status: "blocked",
    language_status: "complete",
    test_status: "partial",
    readiness: "adapter_missing",
    limitations: ["HR employee directory manifest registered — live search adapter missing."],
    next_required_step: "Implement hr_employee_directory search adapter with role scoping.",
    panel: "app",
  },
  {
    module_id: "directory.crm_customer",
    domain: "organization_directory",
    business_pack_key: "sales_pack",
    provider_key: "crm_customer_directory",
    capability_ids: ["customer.search", "lead.search", "contact.search"],
    source_type: "rpc",
    source_reference: "rpc:customer_relationship / lead_management",
    runtime_loader: "load-companion-sales-context.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "none",
    action_status: "blocked",
    language_status: "complete",
    test_status: "partial",
    readiness: "adapter_missing",
    limitations: ["CRM directory capabilities discovered — no live search adapter yet."],
    next_required_step: "Wire CRM customer/lead search adapter with masked contact fields.",
    panel: "app",
  },
];

export const HAIRDRESSER_SERVICE_COVERAGE_MODULES: readonly CompanionCoverageEntry[] = [
  {
    module_id: "service.appointment_booking",
    domain: "appointment_service",
    business_pack_key: "appointments_services",
    provider_key: "appointment_booking",
    capability_ids: [
      "service.read",
      "service.availability.read",
      "availability.read",
      "appointment.read",
      "booking.read",
      "resource.read",
      "customer.read",
      "location.read",
    ],
    source_type: "rpc",
    source_reference: "rpc:get_organization_appointment_center",
    runtime_loader: "booking-read-orchestrator.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "linked",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Read bundle uses appointment center metadata — adapter_available false until authenticated E2E.",
      "No invented availability slots — partial proxy only.",
    ],
    next_required_step: "Connect live booking write RPC with availability recheck and idempotent create.",
    panel: "app",
  },
  {
    module_id: "service.local_service_beauty",
    domain: "appointment_service",
    business_pack_key: "appointments_services",
    provider_key: "local_service_beauty",
    capability_ids: [
      "service.read",
      "treatment.read",
      "availability.read",
      "appointment.read",
      "appointment.create",
      "appointment.update",
    ],
    source_type: "rpc",
    source_reference: "industry_blueprint:local-service-business",
    runtime_loader: "load-companion-industry-pack-context.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "none",
    action_status: "approval_required",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Generic Services/Appointment provider — no salon-specific Core logic.",
      "Double-booking prevention depends on industry pack loader flags.",
    ],
    next_required_step: "Provider adapter for natural-language booking with employee match and buffer enforcement.",
    panel: "app",
  },
  {
    module_id: "service.workforce_scheduling",
    domain: "appointment_service",
    business_pack_key: "appointments_services",
    provider_key: "workforce_scheduling",
    capability_ids: [
      "resource.read",
      "employee.read",
      "service.availability.read",
      "availability.read",
      "assignment.read",
      "staff.read",
      "schedule.read",
    ],
    source_type: "rpc",
    source_reference: "rpc:get_organization_workforce_scheduling_center",
    runtime_loader: "booking-read-orchestrator.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "none",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: ["Employee.read mapped via resource/staff capabilities — not standalone adapter."],
    next_required_step: "Wire employee.read capability alias in services provider manifest.",
    panel: "app",
  },
  {
    module_id: "service.absence_vacation",
    domain: "appointment_service",
    business_pack_key: null,
    provider_key: "absence_vacation_coverage",
    capability_ids: [
      "service.availability.read",
      "resource.read",
      "vacation_mode.read",
      "absence.read",
      "post_vacation_availability.read",
    ],
    source_type: "rpc",
    source_reference: "rpc:get_organization_absence_center",
    runtime_loader: "booking-read-orchestrator.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "partial",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "vacation_mode.read and post_vacation_availability.read registered in services manifest — Phase 36.",
      "Post-vacation availability uses integration metadata, not computed slots.",
    ],
    next_required_step: "Wire exact Command Brief signals when live absence integration reports return dates.",
    panel: "app",
  },
  {
    module_id: "service.booking_write",
    domain: "appointment_service",
    business_pack_key: "appointments_services",
    provider_key: "local_service_beauty",
    capability_ids: ["booking.create", "booking.update", "booking.read", "cancellation.read"],
    source_type: "none",
    source_reference: null,
    runtime_loader: "booking-write-orchestrator.ts",
    schema_status: "missing",
    permission_status: "partial",
    activation_status: "disabled",
    command_brief_status: "none",
    action_status: "approval_required",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "source_missing",
    limitations: [
      "Write proposals require explicit confirmation — no auto-book.",
      "No live booking.create/update/cancel RPC connected in Phase 36 V1.",
    ],
    next_required_step: "Ship reversible booking write RPC with availability recheck and idempotency before enabling writes.",
    panel: "app",
  },
];

/** Command Brief live signal connection coverage — Phase 37. */
export const COMMAND_BRIEF_COVERAGE_MODULES: readonly CompanionCoverageEntry[] = [
  {
    module_id: "core.command_brief_signals",
    domain: "command_brief",
    business_pack_key: null,
    provider_key: "command_brief_core",
    capability_ids: ["signal.read", "attention_item.read"],
    source_type: "adapter",
    source_reference: "lib/integration-intelligence/command-brief/",
    runtime_loader: "command-brief-orchestrator.ts",
    schema_status: "wired",
    permission_status: "defined",
    activation_status: "active",
    command_brief_status: "linked",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected",
    limitations: [
      "Only exact_live and compatible_live domain signals are displayed.",
      "Partial proxy and source_missing signals are excluded from live Command Brief events.",
    ],
    next_required_step: "Connect hosts and support domain signal arrays when live adapters ship.",
    panel: "app",
  },
  {
    module_id: "command_brief.domain_signal_bus",
    domain: "command_brief",
    business_pack_key: "command_center",
    provider_key: "domain_signal_bus",
    capability_ids: ["signal.read"],
    source_type: "adapter",
    source_reference: "lib/companion-runtime/command-brief-signal-collector.ts",
    runtime_loader: "load-companion-proactive-context.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "linked",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "HR, warehouse, finance, sales, security, community, support, and hosts inline signal builders connected.",
      "Partial proxy signals excluded until dedicated exact sources ship.",
    ],
    next_required_step: "Wire booking read bundle into services context for live appointment signals.",
    panel: "app",
  },
];

/** Support case source & Command Brief — Phase 38. */
export const SUPPORT_COVERAGE_MODULES: readonly CompanionCoverageEntry[] = [
  {
    module_id: "support.queue_read",
    domain: "support",
    business_pack_key: "support_operations",
    provider_key: "autonomous_support_operations",
    capability_ids: ["support_queue.read", "support_metrics.read"],
    source_type: "rpc",
    source_reference: "get_customer_support_operations_center",
    runtime_loader: "support-read-orchestrator.ts",
    schema_status: "wired",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "linked",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Queue counts from ASO dashboard — assignment and SLA fields are partial.",
      "No production_ready without authenticated APP E2E against live support source.",
    ],
    next_required_step: "Connect dedicated SLA and assignment fields when provider exposes them.",
    panel: "app",
  },
  {
    module_id: "support.case_read",
    domain: "support",
    business_pack_key: "support_operations",
    provider_key: "autonomous_support_operations",
    capability_ids: ["support_case.read", "support_case_status.read"],
    source_type: "rpc",
    source_reference: "get_customer_support_operations_center",
    runtime_loader: "support-read-orchestrator.ts",
    schema_status: "wired",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "linked",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: ["Case metadata only — private messages and internal notes excluded."],
    next_required_step: "Wire Support AI case lookup merge when organization scope aligns.",
    panel: "app",
  },
  {
    module_id: "support.response_draft",
    domain: "support",
    business_pack_key: "support_operations",
    provider_key: "support_ai_engine",
    capability_ids: ["support_response.draft"],
    source_type: "rpc",
    source_reference: "suggest_support_ai_response",
    runtime_loader: "support-write-orchestrator.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "linked",
    action_status: "approval_required",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Draft-only — support_response.send and auto-close are blocked.",
      "Grounded sources required — Aipify never auto-sends to customers.",
    ],
    next_required_step: "Connect live draft RPC with explicit approval gate before send path.",
    panel: "app",
  },
  {
    module_id: "support.case_write",
    domain: "support",
    business_pack_key: "support_operations",
    provider_key: "support_ai_engine",
    capability_ids: ["support_case.assign", "support_case.escalate"],
    source_type: "rpc",
    source_reference: "assign_support_case / escalate_support_case",
    runtime_loader: "support-write-orchestrator.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "disabled",
    command_brief_status: "none",
    action_status: "approval_required",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "adapter_missing",
    limitations: [
      "Write RPCs exist but Companion runtime adapter is not connected — execution_source_missing.",
    ],
    next_required_step: "Enable reversible assign/escalate adapter with user confirmation and audit.",
    panel: "app",
  },
  {
    module_id: "support.command_brief_signals",
    domain: "support",
    business_pack_key: "support_operations",
    provider_key: "autonomous_support_operations",
    capability_ids: ["support_queue.read"],
    source_type: "adapter",
    source_reference: "lib/companion-runtime/support-read-orchestrator.ts",
    runtime_loader: "load-companion-support-context.ts",
    schema_status: "wired",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "linked",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Only exact_live ASO queue signals appear in Command Brief.",
      "Partial SLA proxy signals excluded until dedicated SLA source ships.",
    ],
    next_required_step: "Deduplicate support signals against proactive loader when both report same case.",
    panel: "app",
  },
];

/** Aipify Hosts V1 Companion & Command Brief — Phase 39. */
export const HOSTS_COVERAGE_MODULES: readonly CompanionCoverageEntry[] = [
  {
    module_id: "hosts.property_read",
    domain: "hosts",
    business_pack_key: "aipify_hosts",
    provider_key: "short_term_property",
    capability_ids: ["property.read", "occupancy.read"],
    source_type: "rpc",
    source_reference: "get_aipify_hosts_property_center_dashboard",
    runtime_loader: "hosts-read-orchestrator.ts",
    schema_status: "wired",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "linked",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Property metadata from Property Center — no external channel fields in Core.",
      "No production_ready without authenticated APP E2E against live Hosts source.",
    ],
    next_required_step: "Connect calendar occupancy merge when live occupancy RPC is exact.",
    panel: "app",
  },
  {
    module_id: "hosts.reservation_read",
    domain: "hosts",
    business_pack_key: "aipify_hosts",
    provider_key: "short_term_reservation",
    capability_ids: ["reservation.read", "arrival.read", "departure.read"],
    source_type: "rpc",
    source_reference: "get_aipify_hosts_booking_center_dashboard",
    runtime_loader: "hosts-read-orchestrator.ts",
    schema_status: "wired",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "linked",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: ["Guest references masked — full contact requires explicit permission."],
    next_required_step: "Wire guest directory lookup with audit when permission granted.",
    panel: "app",
  },
  {
    module_id: "hosts.operations_read",
    domain: "hosts",
    business_pack_key: "aipify_hosts",
    provider_key: "short_term_operations",
    capability_ids: ["cleaning.read", "maintenance.read", "host_task.read"],
    source_type: "rpc",
    source_reference: "get_aipify_hosts_operations_dashboard",
    runtime_loader: "hosts-read-orchestrator.ts",
    schema_status: "wired",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "linked",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: ["Operations boards are partial metadata — no private guest messages."],
    next_required_step: "Expose property readiness as exact signal when board fields stabilize.",
    panel: "app",
  },
  {
    module_id: "hosts.finance_read",
    domain: "hosts",
    business_pack_key: "aipify_hosts",
    provider_key: "short_term_finance",
    capability_ids: [
      "host_revenue.read",
      "host_payout.read",
      "host_expense.read",
      "host_forecast.read",
    ],
    source_type: "rpc",
    source_reference: "get_aipify_hosts_finance_center_dashboard",
    runtime_loader: "hosts-read-orchestrator.ts",
    schema_status: "wired",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "linked",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Forecast is expected income — never presented as booked revenue.",
      "Reuses Finance Core contracts — no parallel Hosts finance engine.",
    ],
    next_required_step: "Connect reconciliation exact source when provider exposes live status.",
    panel: "app",
  },
  {
    module_id: "hosts.guest_response_draft",
    domain: "hosts",
    business_pack_key: "aipify_hosts",
    provider_key: "short_term_communications",
    capability_ids: ["guest_response.draft"],
    source_type: "none",
    source_reference: "none",
    runtime_loader: "hosts-write-orchestrator.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "none",
    action_status: "approval_required",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Draft-only — guest_response.send and auto-send are blocked.",
      "No message sent without provider confirmation.",
    ],
    next_required_step: "Connect live draft RPC with explicit approval gate before any send path.",
    panel: "app",
  },
  {
    module_id: "hosts.task_write",
    domain: "hosts",
    business_pack_key: "aipify_hosts",
    provider_key: "short_term_operations",
    capability_ids: ["host_task.create", "cleaning_task.assign", "maintenance_task.create"],
    source_type: "rpc",
    source_reference: "record_aipify_hosts_operations_action",
    runtime_loader: "hosts-write-orchestrator.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "disabled",
    command_brief_status: "none",
    action_status: "approval_required",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "adapter_missing",
    limitations: [
      "Write RPC exists but Companion runtime adapter is not connected — execution_source_missing.",
    ],
    next_required_step: "Enable reversible task assign/create adapter with user confirmation and audit.",
    panel: "app",
  },
  {
    module_id: "hosts.command_brief_signals",
    domain: "hosts",
    business_pack_key: "aipify_hosts",
    provider_key: "short_term_operations",
    capability_ids: ["property.read"],
    source_type: "adapter",
    source_reference: "lib/companion-runtime/hosts-read-orchestrator.ts",
    runtime_loader: "load-companion-hosts-context.ts",
    schema_status: "wired",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "linked",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Only exact/compatible live Hosts V1 sources appear in Command Brief.",
      "Partial proxy and source_missing signals excluded.",
    ],
    next_required_step: "Deduplicate hosts signals against finance and proactive loaders.",
    panel: "app",
  },
  {
    module_id: "hosts.v2_specification_only",
    domain: "hosts",
    business_pack_key: "aipify_hosts",
    provider_key: "hosts_v2_smart_scheduling",
    capability_ids: [],
    source_type: "none",
    source_reference: null,
    runtime_loader: "load-companion-hosts-context.ts",
    schema_status: "missing",
    permission_status: "defined",
    activation_status: "disabled",
    command_brief_status: "none",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "specification_only",
    limitations: [
      "Parked V2 centers (Smart Scheduling, Inventory, Insurance, Vendor Marketplace, Enterprise Portfolio) are registered only — not built in Phase 39.",
    ],
    next_required_step: "Do not implement parked Hosts V2 phases until explicitly approved.",
    panel: "app",
  },
];
