import type { CompanionCoverageEntry, CompanionCoverageReadiness } from "./companion-foundation-coverage-types";
import { UNONIGHT_DIRECTORY_MEMBER_CONTRACT } from "@/lib/unonight/provider-adapter/directory-member-contract";

/** Provider-specific live-source overrides — not generic Core logic. */
export type CoverageProviderOverride = Partial<
  Pick<
    CompanionCoverageEntry,
    | "source_type"
    | "source_reference"
    | "readiness"
    | "command_brief_status"
    | "limitations"
    | "next_required_step"
    | "test_status"
    | "activation_status"
  >
>;

export const UNONIGHT_ADAPTER_COVERAGE_OVERRIDES: Record<string, CoverageProviderOverride> = {
  unonight_community_adapter: {
    source_type: "adapter",
    source_reference: "lib/unonight/provider-adapter/",
    activation_status: "active",
    command_brief_status: "linked",
    test_status: "phase_tested",
  },
};

export const UNONIGHT_CAPABILITY_READINESS_OVERRIDES: Record<string, CompanionCoverageReadiness> = {
  "unonight_community_adapter.member.read.read": "production_ready_candidate",
  "unonight_community_adapter.moderation_queue.read.read": "production_ready_candidate",
  "unonight_community_adapter.report.read.read": "production_ready_candidate",
  "unonight_community_adapter.listing.read.read": "connected_but_partial",
  "unonight_community_adapter.verification_status.read.read": "connected_but_partial",
  "unonight_community_adapter.verification_queue.read.read": "connected_but_partial",
  "unonight_community_adapter.verification_case.read.read": "connected_but_partial",
  "unonight_community_adapter.activity.read.read": "connected_but_partial",
};

/** Explicit member verification coverage modules — Phase 34 audit. */
export const MEMBER_VERIFICATION_COVERAGE_MODULES: readonly CompanionCoverageEntry[] = [
  {
    module_id: "verification.unonight_adapter_status",
    domain: "member_verification",
    business_pack_key: "community_pack",
    provider_key: "unonight_community_adapter",
    capability_ids: ["verification_status.read"],
    source_type: "rpc",
    source_reference: "rpc:get_customer_community_network_center:best_practices",
    runtime_loader: "load-companion-community-context.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "linked",
    action_status: "blocked",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Uses community best-practice moderation_status metadata — not full verification queue.",
      "No document images, ID data, or sensitive profile fields exposed to Companion.",
    ],
    next_required_step: "Connect dedicated verification_queue.read source when Unonight verification RPC is approved.",
    panel: "app",
  },
  {
    module_id: "verification.trust_center",
    domain: "member_verification",
    business_pack_key: "trust_center",
    provider_key: "trust_center_verification",
    capability_ids: ["verification.read", "verification_status.read", "verification.request"],
    source_type: "rpc",
    source_reference: "rpc:get_customer_trust_center / security dashboard RPCs",
    runtime_loader: "load-companion-security-context.ts",
    schema_status: "wired",
    permission_status: "defined",
    activation_status: "active",
    command_brief_status: "none",
    action_status: "approval_required",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "verification.request requires explicit approval — no auto-approve.",
      "Privacy-sensitive verification metadata only.",
    ],
    next_required_step: "Wire verification queue pending counts to Command Brief when live adapter exists.",
    panel: "app",
  },
  {
    module_id: "verification.queue_read",
    domain: "member_verification",
    business_pack_key: "community_pack",
    provider_key: "unonight_community_adapter",
    capability_ids: ["verification_queue.read"],
    source_type: "rpc",
    source_reference: "rpc:get_customer_community_network_center:best_practices",
    runtime_loader: "verification-read-orchestrator.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "linked",
    action_status: "blocked",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Queue summary uses community metadata proxy until dedicated Unonight verification queue RPC is approved.",
      "No document images, ID numbers, or moderator notes exposed to Companion.",
    ],
    next_required_step: "Connect dedicated read-only Unonight verification queue RPC and promote Command Brief to exact semantic match.",
    panel: "app",
  },
  {
    module_id: "verification.case_read",
    domain: "member_verification",
    business_pack_key: "community_pack",
    provider_key: "unonight_community_adapter",
    capability_ids: ["verification_case.read"],
    source_type: "rpc",
    source_reference: "rpc:get_customer_community_network_center:best_practices",
    runtime_loader: "verification-read-orchestrator.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "none",
    action_status: "blocked",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Case lookup uses metadata-only proxy records with masked subject references.",
      "No identity documents or sensitive profile fields.",
    ],
    next_required_step: "Wire dedicated verification case RPC with audit-only metadata fields.",
    panel: "app",
  },
  {
    module_id: "verification.review_create",
    domain: "member_verification",
    business_pack_key: "trust_center",
    provider_key: "trust_center_verification",
    capability_ids: ["verification_review.create"],
    source_type: "none",
    source_reference: null,
    runtime_loader: "load-companion-security-context.ts",
    schema_status: "missing",
    permission_status: "defined",
    activation_status: "disabled",
    command_brief_status: "none",
    action_status: "approval_required",
    language_status: "partial",
    test_status: "missing",
    readiness: "specification_only",
    limitations: ["No reversible verification_review.create registered — verification.request exists instead."],
    next_required_step: "Register reversible review action only if existing Trust Center RPC supports it.",
    panel: "app",
  },
];

/** Explicit organization directory coverage — Phase 33C audit. */
export const ORGANIZATION_DIRECTORY_COVERAGE_MODULES: readonly CompanionCoverageEntry[] = [
  {
    module_id: "directory.core_search",
    domain: "organization_directory",
    business_pack_key: null,
    provider_key: "organization_directory_core",
    capability_ids: [
      "directory.search",
      "person.read",
      "organization.read",
      "relationship.read",
    ],
    source_type: "manifest",
    source_reference: "lib/integration-intelligence/directory/manifests.ts",
    runtime_loader: "companion-directory-context.ts",
    schema_status: "wired",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "none",
    action_status: "blocked",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: ["Generic Core contracts only — provider adapters supply live records."],
    next_required_step: "Connect provider adapters per relationship type with audit logging.",
    panel: "app",
  },
  {
    module_id: "directory.unonight_member",
    domain: "organization_directory",
    business_pack_key: "community_pack",
    provider_key: "unonight_community_member_directory",
    capability_ids: ["member.search"],
    source_type: "none",
    source_reference: null,
    runtime_loader: "companion-directory-context.ts",
    schema_status: "missing",
    permission_status: "defined",
    activation_status: "disabled",
    command_brief_status: "none",
    action_status: "blocked",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "source_missing",
    limitations: [
      "No member list exposed in Phase 33C — contract only.",
      "No raw email/phone — masked fields require explicit permission when source exists.",
    ],
    next_required_step: UNONIGHT_DIRECTORY_MEMBER_CONTRACT.next_required_step,
    panel: "app",
  },
  {
    module_id: "directory.hr_employee",
    domain: "organization_directory",
    business_pack_key: "hr_pack",
    provider_key: "hr_employee_directory",
    capability_ids: ["employee.search"],
    source_type: "rpc",
    source_reference: "rpc:workforce_employee_directory",
    runtime_loader: "load-companion-hr-context.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "none",
    action_status: "blocked",
    language_status: "complete",
    test_status: "partial",
    readiness: "adapter_missing",
    limitations: ["HR employee directory manifest registered — live search adapter missing."],
    next_required_step: "Implement hr_employee_directory search adapter with role scoping.",
    panel: "app",
  },
  {
    module_id: "directory.crm_customer",
    domain: "organization_directory",
    business_pack_key: "sales_pack",
    provider_key: "crm_customer_directory",
    capability_ids: ["customer.search", "lead.search", "contact.search"],
    source_type: "rpc",
    source_reference: "rpc:customer_relationship / lead_management",
    runtime_loader: "load-companion-sales-context.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "none",
    action_status: "blocked",
    language_status: "complete",
    test_status: "partial",
    readiness: "adapter_missing",
    limitations: ["CRM directory capabilities discovered — no live search adapter yet."],
    next_required_step: "Wire CRM customer/lead search adapter with masked contact fields.",
    panel: "app",
  },
];

export const HAIRDRESSER_SERVICE_COVERAGE_MODULES: readonly CompanionCoverageEntry[] = [
  {
    module_id: "service.appointment_booking",
    domain: "appointment_service",
    business_pack_key: "appointments_services",
    provider_key: "appointment_booking",
    capability_ids: [
      "service.read",
      "service.availability.read",
      "availability.read",
      "appointment.read",
      "booking.read",
      "resource.read",
      "customer.read",
      "location.read",
    ],
    source_type: "rpc",
    source_reference: "rpc:get_organization_appointment_booking_center / service experience RPCs",
    runtime_loader: "load-companion-services-context.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "none",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: ["Discovery-first — adapter_available false in manifest.", "No live booking.create in Companion yet."],
    next_required_step: "Connect appointment provider adapter with availability and buffer rules.",
    panel: "app",
  },
  {
    module_id: "service.local_service_beauty",
    domain: "appointment_service",
    business_pack_key: "appointments_services",
    provider_key: "local_service_beauty",
    capability_ids: [
      "service.read",
      "treatment.read",
      "availability.read",
      "appointment.read",
      "appointment.create",
      "appointment.update",
    ],
    source_type: "rpc",
    source_reference: "industry_blueprint:local-service-business",
    runtime_loader: "load-companion-industry-pack-context.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "none",
    action_status: "approval_required",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "Generic Services/Appointment provider — no salon-specific Core logic.",
      "Double-booking prevention depends on industry pack loader flags.",
    ],
    next_required_step: "Provider adapter for natural-language booking with employee match and buffer enforcement.",
    panel: "app",
  },
  {
    module_id: "service.workforce_scheduling",
    domain: "appointment_service",
    business_pack_key: "appointments_services",
    provider_key: "workforce_scheduling",
    capability_ids: [
      "resource.read",
      "employee.read",
      "service.availability.read",
      "availability.read",
      "assignment.read",
      "staff.read",
      "schedule.read",
    ],
    source_type: "rpc",
    source_reference: "rpc:workforce scheduling / staff availability RPCs",
    runtime_loader: "load-companion-services-context.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "none",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: ["Employee.read mapped via resource/staff capabilities — not standalone adapter."],
    next_required_step: "Wire employee.read capability alias in services provider manifest.",
    panel: "app",
  },
  {
    module_id: "service.absence_vacation",
    domain: "appointment_service",
    business_pack_key: null,
    provider_key: "absence_vacation_coverage",
    capability_ids: [
      "service.availability.read",
      "resource.read",
      "vacation_mode.read",
      "absence.read",
      "post_vacation_availability.read",
    ],
    source_type: "rpc",
    source_reference: "rpc:absence_vacation_coverage / vacation mode engine",
    runtime_loader: "load-companion-services-context.ts",
    schema_status: "partial",
    permission_status: "defined",
    activation_status: "partial",
    command_brief_status: "none",
    action_status: "none",
    language_status: "complete",
    test_status: "phase_tested",
    readiness: "connected_but_partial",
    limitations: [
      "vacation_mode.read and post_vacation_availability.read are loader flags — not separate manifest capabilities.",
    ],
    next_required_step: "Register vacation_mode.read and post_vacation_availability.read in services manifest.",
    panel: "app",
  },
  {
    module_id: "service.booking_write",
    domain: "appointment_service",
    business_pack_key: "appointments_services",
    provider_key: "local_service_beauty",
    capability_ids: ["booking.create", "booking.update", "booking.read", "cancellation.read"],
    source_type: "none",
    source_reference: null,
    runtime_loader: "load-companion-industry-pack-context.ts",
    schema_status: "missing",
    permission_status: "partial",
    activation_status: "disabled",
    command_brief_status: "none",
    action_status: "approval_required",
    language_status: "partial",
    test_status: "missing",
    readiness: "source_missing",
    limitations: [
      "Manifest uses appointment.create/update — booking.* capability IDs not registered.",
    ],
    next_required_step: "Align booking.* capability IDs with appointment.* in services manifest or add aliases.",
    panel: "app",
  },
];
