import type { Translator } from "@/lib/i18n/translate";

export function buildActivityOperationsLabels(t: Translator) {
  const p = "customerApp.activityOperations";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    accessDenied: t(`${p}.accessDenied`),
    permissionMissing: t(`${p}.permissionMissing`),
    entitlementMissing: t(`${p}.entitlementMissing`),
    organizationMissing: t(`${p}.organizationMissing`),
    loadError: t(`${p}.loadError`),
    retry: t(`${p}.retry`),
    returnToDashboard: t(`${p}.returnToDashboard`),
    overview: t(`${p}.overview`),
    sinceLastLogin: t(`${p}.sinceLastLogin`),
    organization: t(`${p}.organization`),
    myActivity: t(`${p}.myActivity`),
    team: t(`${p}.team`),
    approvals: t(`${p}.approvals`),
    businessPacks: t(`${p}.businessPacks`),
    domains: t(`${p}.domains`),
    companionInsights: t(`${p}.companionInsights`),
    reports: t(`${p}.reports`),
    totalEvents: t(`${p}.totalEvents`),
    eventsSinceLogin: t(`${p}.eventsSinceLogin`),
    pendingApprovals: t(`${p}.pendingApprovals`),
    criticalItems: t(`${p}.criticalItems`),
    highlightsToday: t(`${p}.highlightsToday`),
    generateSummary: t(`${p}.generateSummary`),
    markLogin: t(`${p}.markLogin`),
    generateHighlights: t(`${p}.generateHighlights`),
    noEvents: t(`${p}.noEvents`),
    emptyHint: t(`${p}.emptyHint`),
    unknownEventType: t(`${p}.unknownEventType`),
    topChanges: t(`${p}.topChanges`),
    topRisks: t(`${p}.topRisks`),
    topOpportunities: t(`${p}.topOpportunities`),
    recommendedActions: t(`${p}.recommendedActions`),
    companionSummary: t(`${p}.companionSummary`),
    activityIntelligence: t(`${p}.activityIntelligence`),
    trends: t(`${p}.trends`),
    patterns: t(`${p}.patterns`),
    anomalies: t(`${p}.anomalies`),
    importantChanges: t(`${p}.importantChanges`),
    executiveBriefing: t(`${p}.executiveBriefing`),
    notificationsIntegration: t(`${p}.notificationsIntegration`),
    searchIntegration: t(`${p}.searchIntegration`),
    searchActivity: t(`${p}.searchActivity`),
    searchPlaceholder: t(`${p}.searchPlaceholder`),
    auditLog: t(`${p}.auditLog`),
    companionIntegration: t(`${p}.companionIntegration`),
    mobileReady: t(`${p}.mobileReady`),
    viewRecord: t(`${p}.viewRecord`),
    sinceLastLoginTitle: t(`${p}.sinceLastLoginTitle`),
    sinceLastLoginSubtitle: t(`${p}.sinceLastLoginSubtitle`),
    save: t(`${p}.save`),
  };
}

export type ActivityOperationsLabels = ReturnType<typeof buildActivityOperationsLabels>;
