import type { TrustCultureLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildTrustCultureLabels(t: Translator): TrustCultureLabels {
  const p = "customerApp.portalStructure.trustCulture";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    privacyNote: t(`${p}.privacyNote`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      dimension: t(`${p}.filters.dimension`),
      periodFrom: t(`${p}.filters.periodFrom`),
      periodTo: t(`${p}.filters.periodTo`),
      department: t(`${p}.filters.department`),
      trend: t(`${p}.filters.trend`),
      all: t(`${p}.filters.all`),
    },
    snapshot: {
      cultureScore: t(`${p}.snapshot.cultureScore`),
      trustScore: t(`${p}.snapshot.trustScore`),
      participationRate: t(`${p}.snapshot.participationRate`),
      trendDirection: t(`${p}.snapshot.trendDirection`),
      improvementMomentum: t(`${p}.snapshot.improvementMomentum`),
      areasAttention: t(`${p}.snapshot.areasAttention`),
      suppressed: t(`${p}.snapshot.suppressed`),
    },
    dashboard: {
      trustIndicators: t(`${p}.dashboard.trustIndicators`),
      collaborationIndicators: t(`${p}.dashboard.collaborationIndicators`),
      communicationIndicators: t(`${p}.dashboard.communicationIndicators`),
      recognitionTrends: t(`${p}.dashboard.recognitionTrends`),
      psychologicalSafetyTrends: t(`${p}.dashboard.psychologicalSafetyTrends`),
      leadershipConfidenceTrends: t(`${p}.dashboard.leadershipConfidenceTrends`),
      checkIns: t(`${p}.dashboard.checkIns`),
    },
    checkIn: {
      launchTitle: t(`${p}.checkIn.launchTitle`),
      title: t(`${p}.checkIn.title`),
      description: t(`${p}.checkIn.description`),
      frequency: t(`${p}.checkIn.frequency`),
      submit: t(`${p}.checkIn.submit`),
      cancel: t(`${p}.checkIn.cancel`),
      voluntaryNote: t(`${p}.checkIn.voluntaryNote`),
      submitResponse: t(`${p}.checkIn.submitResponse`),
      responseThanks: t(`${p}.checkIn.responseThanks`),
    },
    detail: {
      historicalTrends: t(`${p}.detail.historicalTrends`),
      participationHistory: t(`${p}.detail.participationHistory`),
      strengths: t(`${p}.detail.strengths`),
      improvementOpportunities: t(`${p}.detail.improvementOpportunities`),
      recommendedActions: t(`${p}.detail.recommendedActions`),
      reviewHistory: t(`${p}.detail.reviewHistory`),
      recommendations: t(`${p}.detail.recommendations`),
    },
    dimensions: {
      trust: t(`${p}.dimensions.trust`),
      collaboration: t(`${p}.dimensions.collaboration`),
      communication: t(`${p}.dimensions.communication`),
      recognition: t(`${p}.dimensions.recognition`),
      accountability: t(`${p}.dimensions.accountability`),
      inclusion: t(`${p}.dimensions.inclusion`),
      psychological_safety: t(`${p}.dimensions.psychologicalSafety`),
      leadership_confidence: t(`${p}.dimensions.leadershipConfidence`),
      organizational_alignment: t(`${p}.dimensions.organizationalAlignment`),
      learning_mindset: t(`${p}.dimensions.learningMindset`),
    },
    trends: {
      improving: t(`${p}.trends.improving`),
      stable: t(`${p}.trends.stable`),
      declining: t(`${p}.trends.declining`),
      insufficient_data: t(`${p}.trends.insufficientData`),
    },
    frequencies: {
      weekly: t(`${p}.frequencies.weekly`),
      monthly: t(`${p}.frequencies.monthly`),
      quarterly: t(`${p}.frequencies.quarterly`),
      on_demand: t(`${p}.frequencies.onDemand`),
    },
    recommendations: {
      celebrateTrends: t(`${p}.recommendations.celebrateTrends`),
      reviewDecliningTrust: t(`${p}.recommendations.reviewDecliningTrust`),
      encourageRecognition: t(`${p}.recommendations.encourageRecognition`),
      facilitateCollaboration: t(`${p}.recommendations.facilitateCollaboration`),
      schedulePulseSurvey: t(`${p}.recommendations.schedulePulseSurvey`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      anonymous: t(`${p}.faq.anonymous`),
      anonymousAnswer: t(`${p}.faq.anonymousAnswer`),
      goodCulture: t(`${p}.faq.goodCulture`),
      goodCultureAnswer: t(`${p}.faq.goodCultureAnswer`),
    },
  };
}
