import type { Translator } from "@/lib/i18n/translate";

export function buildAssetManagementLabels(t: Translator) {
  const p = "customerApp.assetManagement";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    philosophy: t(`${p}.philosophy`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    assets: t(`${p}.assets`),
    equipment: t(`${p}.equipment`),
    vehicles: t(`${p}.vehicles`),
    properties: t(`${p}.properties`),
    itEquipment: t(`${p}.itEquipment`),
    softwareLicenses: t(`${p}.softwareLicenses`),
    licenses: t(`${p}.licenses`),
    assignments: t(`${p}.assignments`),
    maintenance: t(`${p}.maintenance`),
    audits: t(`${p}.audits`),
    reports: t(`${p}.reports`),
    active: t(`${p}.active`),
    available: t(`${p}.available`),
    assigned: t(`${p}.assigned`),
    reserved: t(`${p}.reserved`),
    maintenanceRequired: t(`${p}.maintenanceRequired`),
    restricted: t(`${p}.restricted`),
    retired: t(`${p}.retired`),
    createAsset: t(`${p}.createAsset`),
    assetName: t(`${p}.assetName`),
    category: t(`${p}.category`),
    status: t(`${p}.status`),
    assignedTo: t(`${p}.assignedTo`),
    department: t(`${p}.department`),
    domain: t(`${p}.domain`),
    warranty: t(`${p}.warranty`),
    qrCode: t(`${p}.qrCode`),
    noAssets: t(`${p}.noAssets`),
    noAssetsHint: t(`${p}.noAssetsHint`),
    scheduleMaintenance: t(`${p}.scheduleMaintenance`),
    reportIssue: t(`${p}.reportIssue`),
    totalValue: t(`${p}.totalValue`),
    maintenanceCosts: t(`${p}.maintenanceCosts`),
    licenseSeats: t(`${p}.licenseSeats`),
    assetUtilization: t(`${p}.assetUtilization`),
    auditCompliance: t(`${p}.auditCompliance`),
    auditLog: t(`${p}.auditLog`),
    calendarLink: t(`${p}.calendarLink`),
    organizationLink: t(`${p}.organizationLink`),
    peopleLink: t(`${p}.peopleLink`),
    inventoryLink: t(`${p}.inventoryLink`),
    vehiclesTitle: t(`${p}.vehiclesTitle`),
    backToAssets: t(`${p}.backToAssets`),
    startAudit: t(`${p}.startAudit`),
    scanQr: t(`${p}.scanQr`),
    lookupAsset: t(`${p}.lookupAsset`),
    nextService: t(`${p}.nextService`),
    mobileReady: t(`${p}.mobileReady`),
    save: t(`${p}.save`),
  };
}

export type AssetManagementLabels = ReturnType<typeof buildAssetManagementLabels>;
