import type { Translator } from "@/lib/i18n/translate";

export function buildCustomerSuccessAdoptionCenterLabels(t: Translator) {
  const p = "customerApp.customerSuccessAdoptionCenter";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    organizationName: t(`${p}.organizationName`),
    plan: t(`${p}.plan`),
    healthScore: t(`${p}.healthScore`),
    adoptionScore: t(`${p}.adoptionScore`),
    engagementScore: t(`${p}.engagementScore`),
    retentionRisk: t(`${p}.retentionRisk`),
    companionAdviceTitle: t(`${p}.companionAdviceTitle`),
    topRecommendations: t(`${p}.topRecommendations`),
    governanceNote: t(`${p}.governanceNote`),
    privacyNote: t(`${p}.privacyNote`),
    refresh: t(`${p}.refresh`),
    accessDenied: t(`${p}.accessDenied`),
    auditHistory: t(`${p}.auditHistory`),
    noAudit: t(`${p}.noAudit`),
    relatedLinks: t(`${p}.relatedLinks`),
    onboardingCenter: t(`${p}.onboardingCenter`),
    customerSuccessEngine: t(`${p}.customerSuccessEngine`),
    goalSummary: t(`${p}.goalSummary`),
    milestone: t(`${p}.milestone`),
    targetOutcome: t(`${p}.targetOutcome`),
    reviewDate: t(`${p}.reviewDate`),
    owner: t(`${p}.owner`),
    achievements: t(`${p}.achievements`),
    challenges: t(`${p}.challenges`),
    recommendations: t(`${p}.recommendations`),
    dueDate: t(`${p}.dueDate`),
    usage: t(`${p}.usage`),
    highChurnRisk: t(`${p}.highChurnRisk`),
    sections: {
      overview: t(`${p}.sections.overview`),
      adoption: t(`${p}.sections.adoption`),
      health: t(`${p}.sections.health`),
      expansion: t(`${p}.sections.expansion`),
      plans: t(`${p}.sections.plans`),
      training: t(`${p}.sections.training`),
      engagement: t(`${p}.sections.engagement`),
      businessPacks: t(`${p}.sections.businessPacks`),
      journey: t(`${p}.sections.journey`),
      reviews: t(`${p}.sections.reviews`),
      tasks: t(`${p}.sections.tasks`),
      executive: t(`${p}.sections.executive`),
      governance: t(`${p}.sections.governance`),
    },
    healthBand: {
      excellent: t(`${p}.healthBand.excellent`),
      healthy: t(`${p}.healthBand.healthy`),
      at_risk: t(`${p}.healthBand.atRisk`),
      critical: t(`${p}.healthBand.critical`),
    },
    status: {
      completed: t(`${p}.status.completed`),
      notAllowed: t(`${p}.status.notAllowed`),
      requiresAttention: t(`${p}.status.requiresAttention`),
      information: t(`${p}.status.information`),
      restricted: t(`${p}.status.restricted`),
      verified: t(`${p}.status.verified`),
      waiting: t(`${p}.status.waiting`),
    },
  };
}

export type CustomerSuccessAdoptionCenterLabels = ReturnType<typeof buildCustomerSuccessAdoptionCenterLabels>;
