import type { AbosCommandCenterLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildAbosCommandCenterLabels(t: Translator): AbosCommandCenterLabels {
  const p = "customerApp.portalStructure.abosCommandCenter";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      priority: t(`${p}.filters.priority`),
      organizationalArea: t(`${p}.filters.organizationalArea`),
      recommendationType: t(`${p}.filters.recommendationType`),
      focusCategory: t(`${p}.filters.focusCategory`),
      periodFrom: t(`${p}.filters.periodFrom`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      executiveBriefing: t(`${p}.dashboard.executiveBriefing`),
      organizationalStatus: t(`${p}.dashboard.organizationalStatus`),
      todaysPriorities: t(`${p}.dashboard.todaysPriorities`),
      strategicOverview: t(`${p}.dashboard.strategicOverview`),
      momentumOverview: t(`${p}.dashboard.momentumOverview`),
      resilienceOverview: t(`${p}.dashboard.resilienceOverview`),
      capacityOverview: t(`${p}.dashboard.capacityOverview`),
      riskOverview: t(`${p}.dashboard.riskOverview`),
      successOverview: t(`${p}.dashboard.successOverview`),
      customerHealthOverview: t(`${p}.dashboard.customerHealthOverview`),
      recommendations: t(`${p}.dashboard.recommendations`),
      executiveTimeline: t(`${p}.dashboard.executiveTimeline`),
    },
    briefing: {
      goodMorning: t(`${p}.briefing.goodMorning`),
      overallHealth: t(`${p}.briefing.overallHealth`),
      strategicInitiativesAttention: t(`${p}.briefing.strategicInitiativesAttention`),
      resilienceVulnerability: t(`${p}.briefing.resilienceVulnerability`),
      momentumPositive: t(`${p}.briefing.momentumPositive`),
      focusPrioritiesToday: t(`${p}.briefing.focusPrioritiesToday`),
    },
    orgStatus: {
      thriving: t(`${p}.orgStatus.thriving`),
      healthy: t(`${p}.orgStatus.healthy`),
      stable: t(`${p}.orgStatus.stable`),
      requires_attention: t(`${p}.orgStatus.requiresAttention`),
      critical_attention_required: t(`${p}.orgStatus.criticalAttentionRequired`),
    },
    overviews: {
      onTrack: t(`${p}.overviews.onTrack`),
      delayed: t(`${p}.overviews.delayed`),
      milestonesAchieved: t(`${p}.overviews.milestonesAchieved`),
      momentumScore: t(`${p}.overviews.momentumScore`),
      teamsAccelerating: t(`${p}.overviews.teamsAccelerating`),
      initiativesSlowing: t(`${p}.overviews.initiativesSlowing`),
      bottlenecks: t(`${p}.overviews.bottlenecks`),
      resilienceScore: t(`${p}.overviews.resilienceScore`),
      vulnerabilities: t(`${p}.overviews.vulnerabilities`),
      continuityReadiness: t(`${p}.overviews.continuityReadiness`),
      teamsApproachingLimits: t(`${p}.overviews.teamsApproachingLimits`),
      healthyDistribution: t(`${p}.overviews.healthyDistribution`),
      capacityRisks: t(`${p}.overviews.capacityRisks`),
      highPriorityRisks: t(`${p}.overviews.highPriorityRisks`),
      recentlyMitigated: t(`${p}.overviews.recentlyMitigated`),
      highPerforming: t(`${p}.overviews.highPerforming`),
      adoptionScore: t(`${p}.overviews.adoptionScore`),
      learningScore: t(`${p}.overviews.learningScore`),
      supportEngagement: t(`${p}.overviews.supportEngagement`),
    },
    priorities: {
      decisionAttention: t(`${p}.priorities.decisionAttention`),
      strategicAtRisk: t(`${p}.priorities.strategicAtRisk`),
      executiveCommitment: t(`${p}.priorities.executiveCommitment`),
      criticalFollowUp: t(`${p}.priorities.criticalFollowUp`),
      highPriorityRecommendation: t(`${p}.priorities.highPriorityRecommendation`),
      importantReview: t(`${p}.priorities.importantReview`),
    },
    priorityLevels: {
      informational: t(`${p}.priorityLevels.informational`),
      opportunity: t(`${p}.priorityLevels.opportunity`),
      important: t(`${p}.priorityLevels.important`),
      immediate_attention: t(`${p}.priorityLevels.immediateAttention`),
    },
    recommendationTypes: {
      risk: t(`${p}.recommendationTypes.risk`),
      strategic: t(`${p}.recommendationTypes.strategic`),
      success: t(`${p}.recommendationTypes.success`),
      capacity: t(`${p}.recommendationTypes.capacity`),
      resilience: t(`${p}.recommendationTypes.resilience`),
    },
    recommendations: {
      reviewCriticalRisks: t(`${p}.recommendations.reviewCriticalRisks`),
      scheduleStrategicMilestoneReviews: t(`${p}.recommendations.scheduleStrategicMilestoneReviews`),
      addressDelayedInitiatives: t(`${p}.recommendations.addressDelayedInitiatives`),
      celebrateSuccessfulTeams: t(`${p}.recommendations.celebrateSuccessfulTeams`),
      reviewCapacityPressures: t(`${p}.recommendations.reviewCapacityPressures`),
      monitorResilienceImprovements: t(`${p}.recommendations.monitorResilienceImprovements`),
    },
    timeline: { title: t(`${p}.timeline.title`) },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      replacesModules: t(`${p}.faq.replacesModules`),
      replacesModulesAnswer: t(`${p}.faq.replacesModulesAnswer`),
      runsOrganization: t(`${p}.faq.runsOrganization`),
      runsOrganizationAnswer: t(`${p}.faq.runsOrganizationAnswer`),
    },
  };
}
