import type { Translator } from "@/lib/i18n/translate";

export function buildGlobalExpansionIntelligenceCenterLabels(t: Translator) {
  const p = "customerApp.globalExpansionIntelligenceCenter";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    philosophy: t(`${p}.philosophy`),
    governanceNote: t(`${p}.governanceNote`),
    privacyNote: t(`${p}.privacyNote`),
    refresh: t(`${p}.refresh`),
    emptyState: t(`${p}.emptyState`),
    accessDenied: t(`${p}.accessDenied`),
    source: t(`${p}.source`),
    date: t(`${p}.date`),
    confidence: t(`${p}.confidence`),
    risk: t(`${p}.risk`),
    evidence: t(`${p}.evidence`),
    reasoning: t(`${p}.reasoning`),
    expansionScore: t(`${p}.expansionScore`),
    marketSize: t(`${p}.marketSize`),
    language: t(`${p}.language`),
    businessEnvironment: t(`${p}.businessEnvironment`),
    growthPotential: t(`${p}.growthPotential`),
    competitionLevel: t(`${p}.competitionLevel`),
    riskLevel: t(`${p}.riskLevel`),
    demand: t(`${p}.demand`),
    investment: t(`${p}.investment`),
    revenuePotential: t(`${p}.revenuePotential`),
    bestCase: t(`${p}.bestCase`),
    expectedCase: t(`${p}.expectedCase`),
    worstCase: t(`${p}.worstCase`),
    sections: {
      expansionOverview: t(`${p}.sections.expansionOverview`),
      countryIntelligence: t(`${p}.sections.countryIntelligence`),
      localizationIntelligence: t(`${p}.sections.localizationIntelligence`),
      regulatoryIntelligence: t(`${p}.sections.regulatoryIntelligence`),
      marketEntryAnalysis: t(`${p}.sections.marketEntryAnalysis`),
      expansionOpportunities: t(`${p}.sections.expansionOpportunities`),
      expansionRoadmaps: t(`${p}.sections.expansionRoadmaps`),
    },
    countryIntelligenceEngine: { title: t(`${p}.countryIntelligenceEngine.title`) },
    localizationIntelligence: { title: t(`${p}.localizationIntelligence.title`) },
    marketEntryAnalysis: { title: t(`${p}.marketEntryAnalysis.title`) },
    expansionReadinessEngine: { title: t(`${p}.expansionReadinessEngine.title`) },
    regulatoryIntelligence: { title: t(`${p}.regulatoryIntelligence.title`) },
    internationalOperationsIntelligence: { title: t(`${p}.internationalOperationsIntelligence.title`) },
    expansionOpportunities: { title: t(`${p}.expansionOpportunities.title`) },
    executiveExpansionDashboard: { title: t(`${p}.executiveExpansionDashboard.title`) },
    companionAdvisor: { title: t(`${p}.companionAdvisor.title`), evidence: t(`${p}.companionAdvisor.evidence`) },
    expansionSimulationEngine: { title: t(`${p}.expansionSimulationEngine.title`) },
    governanceControls: {
      title: t(`${p}.governanceControls.title`),
      enabled: t(`${p}.governanceControls.enabled`),
      disabled: t(`${p}.governanceControls.disabled`),
      humanControl: t(`${p}.governanceControls.humanControl`),
    },
    actions: {
      acknowledge: t(`${p}.actions.acknowledge`),
      dismiss: t(`${p}.actions.dismiss`),
      escalate: t(`${p}.actions.escalate`),
      resolve: t(`${p}.actions.resolve`),
    },
    status: {
      completed: t(`${p}.status.completed`),
      notAllowed: t(`${p}.status.notAllowed`),
      requiresAttention: t(`${p}.status.requiresAttention`),
      information: t(`${p}.status.information`),
      restricted: t(`${p}.status.restricted`),
      verified: t(`${p}.status.verified`),
      waiting: t(`${p}.status.waiting`),
    },
    links: {
      marketIntelligence: t(`${p}.links.marketIntelligence`),
      industryIntelligence: t(`${p}.links.industryIntelligence`),
      economicIntelligence: t(`${p}.links.economicIntelligence`),
      legacyGlobalExpansion: t(`${p}.links.legacyGlobalExpansion`),
    },
  };
}

export type GlobalExpansionIntelligenceCenterLabels = ReturnType<typeof buildGlobalExpansionIntelligenceCenterLabels>;
