import type { Translator } from "@/lib/i18n/translate";

export function buildCommunityNetworkCenterLabels(t: Translator) {
  const p = "customerApp.communityNetworkCenter";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    corePrinciple: t(`${p}.corePrinciple`),
    governanceNote: t(`${p}.governanceNote`),
    privacyNote: t(`${p}.privacyNote`),
    refresh: t(`${p}.refresh`),
    accessDenied: t(`${p}.accessDenied`),
    auditHistory: t(`${p}.auditHistory`),
    noAudit: t(`${p}.noAudit`),
    companionTitle: t(`${p}.companionTitle`),
    yourReputation: t(`${p}.yourReputation`),
    replies: t(`${p}.replies`),
    members: t(`${p}.members`),
    joined: t(`${p}.joined`),
    notJoined: t(`${p}.notJoined`),
    moderation: t(`${p}.moderation`),
    feedTarget: t(`${p}.feedTarget`),
    relatedContent: t(`${p}.relatedContent`),
    progress: t(`${p}.progress`),
    architectureNote: t(`${p}.architectureNote`),
    marketplaceDisabled: t(`${p}.marketplaceDisabled`),
    openAdmin: t(`${p}.openAdmin`),
    openLegacyIntelligence: t(`${p}.openLegacyIntelligence`),
    upcomingEvents: t(`${p}.upcomingEvents`),
    pastEvents: t(`${p}.pastEvents`),
    registration: t(`${p}.registration`),
    partnerRestricted: t(`${p}.partnerRestricted`),
    sections: {
      overview: t(`${p}.sections.overview`),
      discussions: t(`${p}.sections.discussions`),
      knowledge: t(`${p}.sections.knowledge`),
      bestPractices: t(`${p}.sections.bestPractices`),
      industryGroups: t(`${p}.sections.industryGroups`),
      partnerNetwork: t(`${p}.sections.partnerNetwork`),
      events: t(`${p}.sections.events`),
      certifications: t(`${p}.sections.certifications`),
      reputation: t(`${p}.sections.reputation`),
      intelligence: t(`${p}.sections.intelligence`),
      successStories: t(`${p}.sections.successStories`),
      executive: t(`${p}.sections.executive`),
      governance: t(`${p}.sections.governance`),
      marketplace: t(`${p}.sections.marketplace`),
    },
    reputationTier: {
      new_member: t(`${p}.reputationTier.newMember`),
      active_contributor: t(`${p}.reputationTier.activeContributor`),
      trusted_contributor: t(`${p}.reputationTier.trustedContributor`),
      community_expert: t(`${p}.reputationTier.communityExpert`),
      community_leader: t(`${p}.reputationTier.communityLeader`),
    },
    discussionCategory: {
      general: t(`${p}.discussionCategory.general`),
      operations: t(`${p}.discussionCategory.operations`),
      support: t(`${p}.discussionCategory.support`),
      commerce: t(`${p}.discussionCategory.commerce`),
      hospitality: t(`${p}.discussionCategory.hospitality`),
      growth_partners: t(`${p}.discussionCategory.growthPartners`),
      enterprise: t(`${p}.discussionCategory.enterprise`),
      companion: t(`${p}.discussionCategory.companion`),
      integrations: t(`${p}.discussionCategory.integrations`),
    },
    status: {
      completed: t(`${p}.status.completed`),
      notAllowed: t(`${p}.status.notAllowed`),
      requiresAttention: t(`${p}.status.requiresAttention`),
      information: t(`${p}.status.information`),
      restricted: t(`${p}.status.restricted`),
      verified: t(`${p}.status.verified`),
      waiting: t(`${p}.status.waiting`),
    },
  };
}

export type CommunityNetworkCenterLabels = ReturnType<typeof buildCommunityNetworkCenterLabels>;
