import {
  COMPANION_CAPABILITY_IDS,
  COMPANION_QUICK_ACTION_IDS,
} from "./constants";
import type { CompanionExperienceLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildCompanionExperienceLabels(t: Translator): CompanionExperienceLabels {
  const p = "customerApp.companionExperience";
  const qa = `${p}.quickActions`;
  const cap = `${p}.capabilities`;
  const ctx = `${p}.contextPages`;
  const sug = `${p}.contextSuggestions`;

  const quickActions = Object.fromEntries(
    COMPANION_QUICK_ACTION_IDS.map((id) => [
      id,
      {
        title: t(`${qa}.${id}.title`),
        description: t(`${qa}.${id}.description`),
      },
    ])
  ) as CompanionExperienceLabels["quickActions"];

  const capabilities = Object.fromEntries(
    COMPANION_CAPABILITY_IDS.map((id) => [id, t(`${cap}.${id}`)])
  ) as CompanionExperienceLabels["capabilities"];

  const contextPages = Object.fromEntries(
    [
      "default",
      "commandCenter",
      "sinceLastLogin",
      "notifications",
      "support",
      "businessPacks",
      "integrations",
      "integrationSetup",
      "organization",
      "billing",
      "operations",
    ].map((key) => [key, t(`${ctx}.${key}`)])
  ) as CompanionExperienceLabels["contextPages"];

  const contextSuggestions = Object.fromEntries(
    [
      "commandBriefSummary",
      "pendingApprovals",
      "sinceLastLoginPriorities",
      "sinceLastLoginActions",
      "notificationsPriority",
      "notificationsNext",
      "supportOpenCases",
      "supportKnowledge",
      "businessPackStatus",
      "businessPackValue",
      "integrationStatus",
      "integrationSecurity",
      "whereFindKey",
      "whichProject",
      "isAccessSafe",
      "whyConnectionFails",
      "checkMySetup",
      "organizationHealth",
      "organizationTeam",
      "billingStatus",
      "billingUpgrade",
      "operationsPriority",
      "operationsEvents",
      "defaultOrgStatus",
      "defaultWhatNow",
    ].map((key) => [key, t(`${sug}.${key}`)])
  ) as CompanionExperienceLabels["contextSuggestions"];

  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    openCompanion: t(`${p}.openCompanion`),
    askAipify: t(`${p}.askAipify`),
    askAipifyButton: t(`${p}.askAipifyButton`),
    newConversation: t(`${p}.newConversation`),
    viewSuggestions: t(`${p}.viewSuggestions`),
    secondarySectionsToggle: t(`${p}.secondarySectionsToggle`),
    secondarySectionsHide: t(`${p}.secondarySectionsHide`),
    inputPlaceholder: t(`${p}.inputPlaceholder`),
    activePage: t(`${p}.activePage`),
    activeOrganization: t(`${p}.activeOrganization`),
    verifiedContext: t(`${p}.verifiedContext`),
    contextPending: t(`${p}.contextPending`),
    orgNameFallback: t(`${p}.orgNameFallback`),
    roleLabel: t(`${p}.roleLabel`),
    roleFallback: t(`${p}.roleFallback`),
    languageLabel: t(`${p}.languageLabel`),
    modeLabel: t(`${p}.modeLabel`),
    modeAssisted: t(`${p}.modeAssisted`),
    capabilitiesTitle: t(`${p}.capabilitiesTitle`),
    recentConversationsTitle: t(`${p}.recentConversationsTitle`),
    suggestedQuestionsTitle: t(`${p}.suggestedQuestionsTitle`),
    pinnedLabel: t(`${p}.pinnedLabel`),
    emptyWelcomeTitle: t(`${p}.emptyWelcomeTitle`),
    emptyWelcomeBody: t(`${p}.emptyWelcomeBody`),
    errorTitle: t(`${p}.errorTitle`),
    errorBody: t(`${p}.errorBody`),
    retry: t(`${p}.retry`),
    noResults: t(`${p}.noResults`),
    stillNeedHelp: t(`${p}.stillNeedHelp`),
    createSupportRequest: t(`${p}.createSupportRequest`),
    closeDrawer: t(`${p}.closeDrawer`),
    fullPageLink: t(`${p}.fullPageLink`),
    quickActions,
    capabilities,
    contextPages,
    contextSuggestions,
    ariaCompanionPanel: t(`${p}.ariaCompanionPanel`),
    ariaOpenCompanion: t(`${p}.ariaOpenCompanion`),
    ariaFloatingButton: t(`${p}.ariaFloatingButton`),
    companionAvailable: t(`${p}.companionAvailable`),
    ariaCompanionAvailable: t(`${p}.ariaCompanionAvailable`),
    sessionConversationUnavailable: t(`${p}.sessionConversationUnavailable`),
    feedbackHelpful: t(`${p}.feedbackHelpful`),
    feedbackNotHelpful: t(`${p}.feedbackNotHelpful`),
    feedbackOrgConfirm: t(`${p}.feedbackOrgConfirm`),
    feedbackThanks: t(`${p}.feedbackThanks`),
    feedbackReasonTitle: t(`${p}.feedbackReasonTitle`),
    feedbackReasonWrongInfo: t(`${p}.feedbackReasonWrongInfo`),
    feedbackReasonOutdated: t(`${p}.feedbackReasonOutdated`),
    feedbackReasonMisunderstood: t(`${p}.feedbackReasonMisunderstood`),
    feedbackReasonWrongLink: t(`${p}.feedbackReasonWrongLink`),
    feedbackReasonTooVague: t(`${p}.feedbackReasonTooVague`),
    feedbackReasonOther: t(`${p}.feedbackReasonOther`),
    feedbackSubmitReason: t(`${p}.feedbackSubmitReason`),
    feedbackOrgConfirmThanks: t(`${p}.feedbackOrgConfirmThanks`),
    feedbackOrgConfirmBlocked: t(`${p}.feedbackOrgConfirmBlocked`),
    feedbackOrgConfirmBlockedHint: t(`${p}.feedbackOrgConfirmBlockedHint`),
    sourcesTitle: t(`${p}.sourcesTitle`),
    sourcesShow: t(`${p}.sourcesShow`),
    sourcesHide: t(`${p}.sourcesHide`),
    sourcePlatformCorpus: t(`${p}.sourcePlatformCorpus`),
    sourceRouteRegistry: t(`${p}.sourceRouteRegistry`),
    sourceKnowledgeCenter: t(`${p}.sourceKnowledgeCenter`),
    sourceCustomerContext: t(`${p}.sourceCustomerContext`),
    sourceOrgKnowledge: t(`${p}.sourceOrgKnowledge`),
    sourceVerifiedIntegration: t(`${p}.sourceVerifiedIntegration`),
    recentDelete: t(`${p}.recentDelete`),
    recentActive: t(`${p}.recentActive`),
    supportEscalationHint: t(`${p}.supportEscalationHint`),
    scrollToLatest: t(`${p}.scrollToLatest`),
    scrollToLatestAria: t(`${p}.scrollToLatestAria`),
    ariaUserMessage: t(`${p}.ariaUserMessage`),
    ariaUserMessageIdentity: t(`${p}.ariaUserMessageIdentity`),
    attachments: {
      addAttachment: t(`${p}.attachments.addAttachment`),
      stagedTitle: t(`${p}.attachments.stagedTitle`),
      activeArtifactLabel: t(`${p}.attachments.activeArtifactLabel`),
      activeBadge: t(`${p}.attachments.activeBadge`),
      remove: t(`${p}.attachments.remove`),
      removeAttachment: t(`${p}.attachments.removeAttachment`),
      statusUploading: t(`${p}.attachments.statusUploading`),
      dropHint: t(`${p}.attachments.dropHint`),
      previewAlt: t(`${p}.attachments.previewAlt`),
      errors: {
        filenameMissing: t(`${p}.attachments.errors.filenameMissing`),
        emptyFile: t(`${p}.attachments.errors.emptyFile`),
        fileTooLarge: t(`${p}.attachments.errors.fileTooLarge`),
        typeNotAllowed: t(`${p}.attachments.errors.typeNotAllowed`),
        tooManyFiles: t(`${p}.attachments.errors.tooManyFiles`),
        uploadFailed: t(`${p}.attachments.errors.uploadFailed`),
        removeFailed: t(`${p}.attachments.errors.removeFailed`),
      },
      context: {
        resolvedActive: t(`${p}.attachments.context.resolvedActive`),
        unresolvedReference: t(`${p}.attachments.context.unresolvedReference`),
        noBinaryNote: t(`${p}.attachments.context.noBinaryNote`),
      },
      externalHandoff: {
        adapterMissing: t(`${p}.attachments.externalHandoff.adapterMissing`),
        partial: t(`${p}.attachments.externalHandoff.partial`),
        consentRequired: t(`${p}.attachments.externalHandoff.consentRequired`),
        permissionDenied: t(`${p}.attachments.externalHandoff.permissionDenied`),
        ready: t(`${p}.attachments.externalHandoff.ready`),
      },
      canvaHandoff: {
        title: t(`${p}.attachments.canvaHandoff.title`),
        subtitle: t(`${p}.attachments.canvaHandoff.subtitle`),
        fileLabel: t(`${p}.attachments.canvaHandoff.fileLabel`),
        typeLabel: t(`${p}.attachments.canvaHandoff.typeLabel`),
        recipientLabel: t(`${p}.attachments.canvaHandoff.recipientLabel`),
        recipient: t(`${p}.attachments.canvaHandoff.recipient`),
        accessLabel: t(`${p}.attachments.canvaHandoff.accessLabel`),
        accessScope: t(`${p}.attachments.canvaHandoff.accessScope`),
        actionLabel: t(`${p}.attachments.canvaHandoff.actionLabel`),
        expectedUpload: t(`${p}.attachments.canvaHandoff.expectedUpload`),
        expectedImport: t(`${p}.attachments.canvaHandoff.expectedImport`),
        expectedUnsupported: t(`${p}.attachments.canvaHandoff.expectedUnsupported`),
        connectRequired: t(`${p}.attachments.canvaHandoff.connectRequired`),
        connectCanva: t(`${p}.attachments.canvaHandoff.connectCanva`),
        approveSend: t(`${p}.attachments.canvaHandoff.approveSend`),
        cancel: t(`${p}.attachments.canvaHandoff.cancel`),
        sendToCanva: t(`${p}.attachments.canvaHandoff.sendToCanva`),
        loadingPreview: t(`${p}.attachments.canvaHandoff.loadingPreview`),
        successOpen: t(`${p}.attachments.canvaHandoff.successOpen`),
        errors: {
          previewFailed: t(`${p}.attachments.canvaHandoff.errors.previewFailed`),
          connectFailed: t(`${p}.attachments.canvaHandoff.errors.connectFailed`),
          notConnected: t(`${p}.attachments.canvaHandoff.errors.notConnected`),
          unsupportedType: t(`${p}.attachments.canvaHandoff.errors.unsupportedType`),
          handoffFailed: t(`${p}.attachments.canvaHandoff.errors.handoffFailed`),
        },
      },
    },
  };
}
