import type { PlatformCorpusArticleId, PlatformCorpusEntry } from "./types";

const BASE = "customerApp.companionPlatformKnowledge.articles";

export const PLATFORM_KNOWLEDGE_CORPUS: PlatformCorpusEntry[] = [
  {
    id: "aipify-overview",
    titleKey: `${BASE}.aipifyOverview.title`,
    directAnswerKey: `${BASE}.aipifyOverview.directAnswer`,
    explanationKey: `${BASE}.aipifyOverview.explanation`,
    stepKeys: [`${BASE}.aipifyOverview.step1`, `${BASE}.aipifyOverview.step2`],
    searchTermsKey: `${BASE}.aipifyOverview.searchTerms`,
    category: "general",
    primaryRouteKey: "knowledgeCenter",
    actionRouteKeys: ["knowledgeCenter", "gettingStarted", "aipifyCompanion"],
  },
  {
    id: "aipify-capabilities",
    titleKey: `${BASE}.aipifyCapabilities.title`,
    directAnswerKey: `${BASE}.aipifyCapabilities.directAnswer`,
    explanationKey: `${BASE}.aipifyCapabilities.explanation`,
    stepKeys: [`${BASE}.aipifyCapabilities.step1`, `${BASE}.aipifyCapabilities.step2`],
    searchTermsKey: `${BASE}.aipifyCapabilities.searchTerms`,
    category: "general",
    primaryRouteKey: "aipifyCompanion",
    actionRouteKeys: ["aipifyCompanion", "commandBrief", "knowledgeCenter"],
  },
  {
    id: "app-panel-navigation",
    titleKey: `${BASE}.appPanelNavigation.title`,
    directAnswerKey: `${BASE}.appPanelNavigation.directAnswer`,
    explanationKey: `${BASE}.appPanelNavigation.explanation`,
    stepKeys: [`${BASE}.appPanelNavigation.step1`, `${BASE}.appPanelNavigation.step2`, `${BASE}.appPanelNavigation.step3`],
    searchTermsKey: `${BASE}.appPanelNavigation.searchTerms`,
    category: "navigation",
    primaryRouteKey: "appDashboard",
    actionRouteKeys: ["appDashboard", "aipifyCompanion"],
  },
  {
    id: "add-team-members",
    titleKey: `${BASE}.addTeamMembers.title`,
    directAnswerKey: `${BASE}.addTeamMembers.directAnswer`,
    explanationKey: `${BASE}.addTeamMembers.explanation`,
    stepKeys: [`${BASE}.addTeamMembers.step1`, `${BASE}.addTeamMembers.step2`, `${BASE}.addTeamMembers.step3`],
    searchTermsKey: `${BASE}.addTeamMembers.searchTerms`,
    category: "organization",
    primaryRouteKey: "teamMembers",
    actionRouteKeys: ["teamMembers"],
    requiredRoles: ["owner", "admin"],
  },
  {
    id: "change-roles",
    titleKey: `${BASE}.changeRoles.title`,
    directAnswerKey: `${BASE}.changeRoles.directAnswer`,
    explanationKey: `${BASE}.changeRoles.explanation`,
    stepKeys: [`${BASE}.changeRoles.step1`, `${BASE}.changeRoles.step2`, `${BASE}.changeRoles.step3`],
    searchTermsKey: `${BASE}.changeRoles.searchTerms`,
    category: "organization",
    primaryRouteKey: "rolesPermissions",
    actionRouteKeys: ["rolesPermissions", "teamMembers"],
    requiredRoles: ["owner", "admin"],
    featureKey: "team_management",
  },
  {
    id: "upgrade-subscription",
    titleKey: `${BASE}.upgradeSubscription.title`,
    directAnswerKey: `${BASE}.upgradeSubscription.directAnswer`,
    explanationKey: `${BASE}.upgradeSubscription.explanation`,
    stepKeys: [`${BASE}.upgradeSubscription.step1`, `${BASE}.upgradeSubscription.step2`, `${BASE}.upgradeSubscription.step3`],
    searchTermsKey: `${BASE}.upgradeSubscription.searchTerms`,
    category: "billing",
    primaryRouteKey: "upgradeOptions",
    actionRouteKeys: ["upgradeOptions", "subscription"],
    requiredRoles: ["owner", "admin"],
    featureKey: "billing",
  },
  {
    id: "subscription-pricing",
    titleKey: `${BASE}.subscriptionPricing.title`,
    directAnswerKey: `${BASE}.subscriptionPricing.directAnswer`,
    explanationKey: `${BASE}.subscriptionPricing.explanation`,
    stepKeys: [`${BASE}.subscriptionPricing.step1`, `${BASE}.subscriptionPricing.step2`],
    searchTermsKey: `${BASE}.subscriptionPricing.searchTerms`,
    category: "billing",
    primaryRouteKey: "upgradeOptions",
    actionRouteKeys: ["upgradeOptions", "subscription"],
  },
  {
    id: "my-subscription",
    titleKey: `${BASE}.mySubscription.title`,
    directAnswerKey: `${BASE}.mySubscription.directAnswer`,
    explanationKey: `${BASE}.mySubscription.explanation`,
    stepKeys: [`${BASE}.mySubscription.step1`, `${BASE}.mySubscription.step2`],
    searchTermsKey: `${BASE}.mySubscription.searchTerms`,
    category: "billing",
    primaryRouteKey: "subscription",
    actionRouteKeys: ["subscription", "upgradeOptions"],
    requiresCustomerContext: true,
    featureKey: "billing",
  },
  {
    id: "find-invoices",
    titleKey: `${BASE}.findInvoices.title`,
    directAnswerKey: `${BASE}.findInvoices.directAnswer`,
    explanationKey: `${BASE}.findInvoices.explanation`,
    stepKeys: [`${BASE}.findInvoices.step1`, `${BASE}.findInvoices.step2`],
    searchTermsKey: `${BASE}.findInvoices.searchTerms`,
    category: "billing",
    primaryRouteKey: "invoices",
    actionRouteKeys: ["invoices"],
    featureKey: "billing",
  },
  {
    id: "find-receipts",
    titleKey: `${BASE}.findReceipts.title`,
    directAnswerKey: `${BASE}.findReceipts.directAnswer`,
    explanationKey: `${BASE}.findReceipts.explanation`,
    stepKeys: [`${BASE}.findReceipts.step1`, `${BASE}.findReceipts.step2`],
    searchTermsKey: `${BASE}.findReceipts.searchTerms`,
    category: "billing",
    primaryRouteKey: "paymentHistory",
    actionRouteKeys: ["paymentHistory", "invoices"],
    featureKey: "billing",
  },
  {
    id: "connect-shopify",
    titleKey: `${BASE}.connectShopify.title`,
    directAnswerKey: `${BASE}.connectShopify.directAnswer`,
    explanationKey: `${BASE}.connectShopify.explanation`,
    stepKeys: [`${BASE}.connectShopify.step1`, `${BASE}.connectShopify.step2`, `${BASE}.connectShopify.step3`],
    searchTermsKey: `${BASE}.connectShopify.searchTerms`,
    category: "integrations",
    primaryRouteKey: "connectIntegration",
    actionRouteKeys: ["connectIntegration", "integrations", "connectedIntegrations"],
    requiredRoles: ["owner", "admin"],
    featureKey: "integrations",
  },
  {
    id: "enable-2fa",
    titleKey: `${BASE}.enable2fa.title`,
    directAnswerKey: `${BASE}.enable2fa.directAnswer`,
    explanationKey: `${BASE}.enable2fa.explanation`,
    stepKeys: [`${BASE}.enable2fa.step1`, `${BASE}.enable2fa.step2`, `${BASE}.enable2fa.step3`],
    searchTermsKey: `${BASE}.enable2fa.searchTerms`,
    category: "security",
    primaryRouteKey: "accountSecurity",
    actionRouteKeys: ["accountSecurity"],
  },
  {
    id: "install-web-app",
    titleKey: `${BASE}.installWebApp.title`,
    directAnswerKey: `${BASE}.installWebApp.directAnswer`,
    explanationKey: `${BASE}.installWebApp.explanation`,
    stepKeys: [`${BASE}.installWebApp.step1`, `${BASE}.installWebApp.step2`, `${BASE}.installWebApp.step3`],
    searchTermsKey: `${BASE}.installWebApp.searchTerms`,
    category: "account",
    primaryRouteKey: "knowledgeCenter",
    actionRouteKeys: ["knowledgeCenter", "preferences"],
  },
  {
    id: "contact-support",
    titleKey: `${BASE}.contactSupport.title`,
    directAnswerKey: `${BASE}.contactSupport.directAnswer`,
    explanationKey: `${BASE}.contactSupport.explanation`,
    stepKeys: [`${BASE}.contactSupport.step1`, `${BASE}.contactSupport.step2`],
    searchTermsKey: `${BASE}.contactSupport.searchTerms`,
    category: "support",
    primaryRouteKey: "contactSupport",
    actionRouteKeys: ["contactSupport", "supportRequests", "knowledgeCenter"],
  },
  {
    id: "aipify-group-location",
    titleKey: `${BASE}.aipifyGroupLocation.title`,
    directAnswerKey: `${BASE}.aipifyGroupLocation.directAnswer`,
    explanationKey: `${BASE}.aipifyGroupLocation.explanation`,
    stepKeys: [],
    searchTermsKey: `${BASE}.aipifyGroupLocation.searchTerms`,
    category: "general",
    actionRouteKeys: ["knowledgeCenter"],
  },
  {
    id: "business-packs",
    titleKey: `${BASE}.businessPacks.title`,
    directAnswerKey: `${BASE}.businessPacks.directAnswer`,
    explanationKey: `${BASE}.businessPacks.explanation`,
    stepKeys: [`${BASE}.businessPacks.step1`, `${BASE}.businessPacks.step2`],
    searchTermsKey: `${BASE}.businessPacks.searchTerms`,
    category: "business_packs",
    primaryRouteKey: "availableBusinessPacks",
    actionRouteKeys: ["availableBusinessPacks", "installedBusinessPacks"],
    featureKey: "business_packs",
  },
  {
    id: "since-last-login",
    titleKey: `${BASE}.sinceLastLogin.title`,
    directAnswerKey: `${BASE}.sinceLastLogin.directAnswer`,
    explanationKey: `${BASE}.sinceLastLogin.explanation`,
    stepKeys: [`${BASE}.sinceLastLogin.step1`, `${BASE}.sinceLastLogin.step2`],
    searchTermsKey: `${BASE}.sinceLastLogin.searchTerms`,
    category: "companion",
    primaryRouteKey: "sinceLastLogin",
    actionRouteKeys: ["sinceLastLogin", "appNotifications", "commandBrief"],
  },
  {
    id: "companion-overview",
    titleKey: `${BASE}.companionOverview.title`,
    directAnswerKey: `${BASE}.companionOverview.directAnswer`,
    explanationKey: `${BASE}.companionOverview.explanation`,
    stepKeys: [`${BASE}.companionOverview.step1`],
    searchTermsKey: `${BASE}.companionOverview.searchTerms`,
    category: "companion",
    primaryRouteKey: "aipifyCompanion",
    actionRouteKeys: ["aipifyCompanion"],
  },
  {
    id: "command-brief",
    titleKey: `${BASE}.commandBrief.title`,
    directAnswerKey: `${BASE}.commandBrief.directAnswer`,
    explanationKey: `${BASE}.commandBrief.explanation`,
    stepKeys: [`${BASE}.commandBrief.step1`],
    searchTermsKey: `${BASE}.commandBrief.searchTerms`,
    category: "companion",
    primaryRouteKey: "commandBrief",
    actionRouteKeys: ["commandBrief", "appDashboard"],
  },
  {
    id: "knowledge-center",
    titleKey: `${BASE}.knowledgeCenter.title`,
    directAnswerKey: `${BASE}.knowledgeCenter.directAnswer`,
    explanationKey: `${BASE}.knowledgeCenter.explanation`,
    stepKeys: [`${BASE}.knowledgeCenter.step1`],
    searchTermsKey: `${BASE}.knowledgeCenter.searchTerms`,
    category: "support",
    primaryRouteKey: "knowledgeCenter",
    actionRouteKeys: ["knowledgeCenter"],
  },
  {
    id: "notifications-preferences",
    titleKey: `${BASE}.notificationsPreferences.title`,
    directAnswerKey: `${BASE}.notificationsPreferences.directAnswer`,
    explanationKey: `${BASE}.notificationsPreferences.explanation`,
    stepKeys: [`${BASE}.notificationsPreferences.step1`],
    searchTermsKey: `${BASE}.notificationsPreferences.searchTerms`,
    category: "account",
    primaryRouteKey: "accountNotifications",
    actionRouteKeys: ["accountNotifications", "appNotifications"],
  },
  {
    id: "vacation-mode",
    titleKey: `${BASE}.vacationMode.title`,
    directAnswerKey: `${BASE}.vacationMode.directAnswer`,
    explanationKey: `${BASE}.vacationMode.explanation`,
    stepKeys: [`${BASE}.vacationMode.step1`],
    searchTermsKey: `${BASE}.vacationMode.searchTerms`,
    category: "account",
    primaryRouteKey: "preferences",
    actionRouteKeys: ["preferences", "accountNotifications"],
  },
  {
    id: "api-access",
    titleKey: `${BASE}.apiAccess.title`,
    directAnswerKey: `${BASE}.apiAccess.directAnswer`,
    explanationKey: `${BASE}.apiAccess.explanation`,
    stepKeys: [`${BASE}.apiAccess.step1`, `${BASE}.apiAccess.step2`],
    searchTermsKey: `${BASE}.apiAccess.searchTerms`,
    category: "integrations",
    primaryRouteKey: "apiAccess",
    actionRouteKeys: ["apiAccess"],
    requiredRoles: ["owner", "admin"],
    featureKey: "integrations",
  },
  {
    id: "what-is-api",
    titleKey: `${BASE}.whatIsApi.title`,
    directAnswerKey: `${BASE}.whatIsApi.directAnswer`,
    explanationKey: `${BASE}.whatIsApi.explanation`,
    stepKeys: [],
    searchTermsKey: `${BASE}.whatIsApi.searchTerms`,
    category: "integrations",
    actionRouteKeys: ["integrations", "knowledgeCenter"],
  },
  {
    id: "find-api-key",
    titleKey: `${BASE}.findApiKey.title`,
    directAnswerKey: `${BASE}.findApiKey.directAnswer`,
    explanationKey: `${BASE}.findApiKey.explanation`,
    stepKeys: [`${BASE}.findApiKey.step1`, `${BASE}.findApiKey.step2`],
    searchTermsKey: `${BASE}.findApiKey.searchTerms`,
    category: "integrations",
    primaryRouteKey: "apiAccess",
    actionRouteKeys: ["apiAccess"],
    requiredRoles: ["owner", "admin"],
    featureKey: "integrations",
  },
  {
    id: "create-api-key",
    titleKey: `${BASE}.createApiKey.title`,
    directAnswerKey: `${BASE}.createApiKey.directAnswer`,
    explanationKey: `${BASE}.createApiKey.explanation`,
    stepKeys: [`${BASE}.createApiKey.step1`, `${BASE}.createApiKey.step2`, `${BASE}.createApiKey.step3`],
    searchTermsKey: `${BASE}.createApiKey.searchTerms`,
    category: "integrations",
    primaryRouteKey: "apiAccess",
    actionRouteKeys: ["apiAccess"],
    requiredRoles: ["owner", "admin"],
    featureKey: "integrations",
  },
  {
    id: "connect-system",
    titleKey: `${BASE}.connectSystem.title`,
    directAnswerKey: `${BASE}.connectSystem.directAnswer`,
    explanationKey: `${BASE}.connectSystem.explanation`,
    stepKeys: [`${BASE}.connectSystem.step1`, `${BASE}.connectSystem.step2`, `${BASE}.connectSystem.step3`],
    searchTermsKey: `${BASE}.connectSystem.searchTerms`,
    category: "integrations",
    primaryRouteKey: "connectIntegration",
    actionRouteKeys: ["connectIntegration", "integrations", "connectedIntegrations"],
    requiredRoles: ["owner", "admin"],
    featureKey: "integrations",
  },
  {
    id: "aipify-data-access",
    titleKey: `${BASE}.aipifyDataAccess.title`,
    directAnswerKey: `${BASE}.aipifyDataAccess.directAnswer`,
    explanationKey: `${BASE}.aipifyDataAccess.explanation`,
    stepKeys: [`${BASE}.aipifyDataAccess.step1`, `${BASE}.aipifyDataAccess.step2`],
    searchTermsKey: `${BASE}.aipifyDataAccess.searchTerms`,
    category: "security",
    actionRouteKeys: ["knowledgeCenter", "accountSecurity", "integrations"],
  },
  {
    id: "approvals",
    titleKey: `${BASE}.approvals.title`,
    directAnswerKey: `${BASE}.approvals.directAnswer`,
    explanationKey: `${BASE}.approvals.explanation`,
    stepKeys: [`${BASE}.approvals.step1`],
    searchTermsKey: `${BASE}.approvals.searchTerms`,
    category: "governance",
    actionRouteKeys: ["knowledgeCenter"],
  },
  {
    id: "audit-governance",
    titleKey: `${BASE}.auditGovernance.title`,
    directAnswerKey: `${BASE}.auditGovernance.directAnswer`,
    explanationKey: `${BASE}.auditGovernance.explanation`,
    stepKeys: [`${BASE}.auditGovernance.step1`],
    searchTermsKey: `${BASE}.auditGovernance.searchTerms`,
    category: "governance",
    primaryRouteKey: "activityOverview",
    actionRouteKeys: ["activityOverview", "accountSecurity"],
  },
  {
    id: "language-settings",
    titleKey: `${BASE}.languageSettings.title`,
    directAnswerKey: `${BASE}.languageSettings.directAnswer`,
    explanationKey: `${BASE}.languageSettings.explanation`,
    stepKeys: [`${BASE}.languageSettings.step1`],
    searchTermsKey: `${BASE}.languageSettings.searchTerms`,
    category: "account",
    primaryRouteKey: "preferences",
    actionRouteKeys: ["preferences", "profile"],
  },
];

export const PLATFORM_CORPUS_IDS = PLATFORM_KNOWLEDGE_CORPUS.map((a) => a.id);

export function getPlatformCorpusEntry(id: PlatformCorpusArticleId): PlatformCorpusEntry | undefined {
  return PLATFORM_KNOWLEDGE_CORPUS.find((a) => a.id === id);
}

/** Norwegian acceptance-test question → corpus article mapping. */
export const ACCEPTANCE_QUESTION_ARTICLE_MAP: Record<string, PlatformCorpusArticleId> = {
  "hva er aipify": "aipify-overview",
  "hva er aipify?": "aipify-overview",
  "hva kan aipify hjelpe meg med": "aipify-capabilities",
  "hva kan aipify hjelpe meg med?": "aipify-capabilities",
  "hvordan fungerer app-panelet": "app-panel-navigation",
  "hvordan fungerer app-panelet?": "app-panel-navigation",
  "hvordan legger jeg til ansatte": "add-team-members",
  "hvordan legger jeg til ansatte?": "add-team-members",
  "hvordan endrer jeg roller": "change-roles",
  "hvordan endrer jeg roller?": "change-roles",
  "hvordan oppgraderer jeg": "upgrade-subscription",
  "hvordan oppgraderer jeg?": "upgrade-subscription",
  "hva koster abonnementet": "subscription-pricing",
  "hva koster abonnementet?": "subscription-pricing",
  "hvilket abonnement har jeg": "my-subscription",
  "hvilket abonnement har jeg?": "my-subscription",
  "hvor finner jeg fakturaen": "find-invoices",
  "hvor finner jeg fakturaen?": "find-invoices",
  "hvor finner jeg kvitteringen": "find-receipts",
  "hvor finner jeg kvitteringen?": "find-receipts",
  "hvordan kobler jeg til shopify": "connect-shopify",
  "hvordan kobler jeg til shopify?": "connect-shopify",
  "hvordan aktiverer jeg 2fa": "enable-2fa",
  "hvordan aktiverer jeg 2fa?": "enable-2fa",
  "hvordan installerer jeg aipify web app": "install-web-app",
  "hvordan installerer jeg aipify web app?": "install-web-app",
  "hvordan kontakter jeg support": "contact-support",
  "hvordan kontakter jeg support?": "contact-support",
  "hvor holder aipify group as til": "aipify-group-location",
  "hvor holder aipify group as til?": "aipify-group-location",
  "hva er et business pack": "business-packs",
  "hva er et business pack?": "business-packs",
  "hvordan ser jeg hva som har skjedd siden sist": "since-last-login",
  "hvordan ser jeg hva som har skjedd siden sist?": "since-last-login",
  "hva er et api": "what-is-api",
  "hva er et api?": "what-is-api",
  "hva er api": "what-is-api",
  "hva er api?": "what-is-api",
  "hvor finner jeg api-nøkkelen": "find-api-key",
  "hvor finner jeg api-nøkkelen?": "find-api-key",
  "hvordan oppretter jeg en api-nøkkel": "create-api-key",
  "hvordan oppretter jeg en api-nøkkel?": "create-api-key",
  "hvordan kobler jeg et system til aipify": "connect-system",
  "hvordan kobler jeg et system til aipify?": "connect-system",
  "hva får aipify tilgang til": "aipify-data-access",
  "hva får aipify tilgang til?": "aipify-data-access",
  "hvordan kan aipify hjelpe meg": "aipify-capabilities",
  "hvordan kan aipify hjelpe meg?": "aipify-capabilities",
  "hvor finner jeg fakturaene mine": "find-invoices",
  "hvor finner jeg fakturaene mine?": "find-invoices",
  "hvordan oppgraderer jeg abonnementet": "upgrade-subscription",
  "hvordan oppgraderer jeg abonnementet?": "upgrade-subscription",
  "hvordan kobler jeg til en nettbutikk": "connect-shopify",
  "hvordan kobler jeg til en nettbutikk?": "connect-shopify",
};
