import type { Translator } from "@/lib/i18n/translate";

export function buildInventoryOperationsLabels(t: Translator) {
  const p = "customerApp.inventoryOperations";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    products: t(`${p}.products`),
    inventory: t(`${p}.inventory`),
    warehouses: t(`${p}.warehouses`),
    movements: t(`${p}.movements`),
    receiving: t(`${p}.receiving`),
    transfers: t(`${p}.transfers`),
    adjustments: t(`${p}.adjustments`),
    reports: t(`${p}.reports`),
    totalProducts: t(`${p}.totalProducts`),
    totalWarehouses: t(`${p}.totalWarehouses`),
    inventoryValue: t(`${p}.inventoryValue`),
    lowStockCount: t(`${p}.lowStockCount`),
    outOfStockCount: t(`${p}.outOfStockCount`),
    pendingReceiving: t(`${p}.pendingReceiving`),
    activeTransfers: t(`${p}.activeTransfers`),
    activeReservations: t(`${p}.activeReservations`),
    pendingReorders: t(`${p}.pendingReorders`),
    movements7d: t(`${p}.movements7d`),
    createProduct: t(`${p}.createProduct`),
    createWarehouse: t(`${p}.createWarehouse`),
    updateStock: t(`${p}.updateStock`),
    createTransfer: t(`${p}.createTransfer`),
    completeTransfer: t(`${p}.completeTransfer`),
    createReceiving: t(`${p}.createReceiving`),
    completeReceiving: t(`${p}.completeReceiving`),
    createAdjustment: t(`${p}.createAdjustment`),
    createReservation: t(`${p}.createReservation`),
    acknowledgeReorder: t(`${p}.acknowledgeReorder`),
    productName: t(`${p}.productName`),
    sku: t(`${p}.sku`),
    warehouseName: t(`${p}.warehouseName`),
    quantity: t(`${p}.quantity`),
    supplier: t(`${p}.supplier`),
    stockStatus: t(`${p}.stockStatus`),
    inStock: t(`${p}.inStock`),
    lowStock: t(`${p}.lowStock`),
    outOfStock: t(`${p}.outOfStock`),
    reserved: t(`${p}.reserved`),
    incoming: t(`${p}.incoming`),
    noProducts: t(`${p}.noProducts`),
    noProductsHint: t(`${p}.noProductsHint`),
    noInventory: t(`${p}.noInventory`),
    noWarehouses: t(`${p}.noWarehouses`),
    auditLog: t(`${p}.auditLog`),
    movementActivity: t(`${p}.movementActivity`),
    warehouseUtilization: t(`${p}.warehouseUtilization`),
    save: t(`${p}.save`),
  };
}

export type InventoryOperationsLabels = ReturnType<typeof buildInventoryOperationsLabels>;
