import type { StrategicInitiativePortfolioLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildStrategicInitiativePortfolioLabels(t: Translator): StrategicInitiativePortfolioLabels {
  const p = "customerApp.actionCenter.strategicInitiativePortfolio";
  return {
    centerTitle: t(`${p}.centerTitle`),
    centerSubtitle: t(`${p}.centerSubtitle`),
    tabImpact: t(`${p}.tabImpact`),
    tabApprovals: t(`${p}.tabApprovals`),
    tabExecution: t(`${p}.tabExecution`),
    tabPortfolio: t(`${p}.tabPortfolio`),
    humanOversight: t(`${p}.humanOversight`),
    sections: {
      dashboard: t(`${p}.sections.dashboard`),
      categories: t(`${p}.sections.categories`),
      alignment: t(`${p}.sections.alignment`),
      health: t(`${p}.sections.health`),
      executive: t(`${p}.sections.executive`),
      details: t(`${p}.sections.details`),
      riskAnalysis: t(`${p}.sections.riskAnalysis`),
      resources: t(`${p}.sections.resources`),
      decisionSupport: t(`${p}.sections.decisionSupport`),
      learning: t(`${p}.sections.learning`),
      knowledgeCenter: t(`${p}.sections.knowledgeCenter`),
      audit: t(`${p}.sections.audit`),
    },
    categories: {
      revenue_growth: t(`${p}.categories.revenueGrowth`),
      customer_experience: t(`${p}.categories.customerExperience`),
      operational_efficiency: t(`${p}.categories.operationalEfficiency`),
      compliance: t(`${p}.categories.compliance`),
      risk_reduction: t(`${p}.categories.riskReduction`),
      product_development: t(`${p}.categories.productDevelopment`),
      employee_experience: t(`${p}.categories.employeeExperience`),
      market_expansion: t(`${p}.categories.marketExpansion`),
      cost_optimization: t(`${p}.categories.costOptimization`),
      innovation: t(`${p}.categories.innovation`),
    },
    health: {
      on_track: t(`${p}.health.onTrack`),
      at_risk: t(`${p}.health.atRisk`),
      blocked: t(`${p}.health.blocked`),
      overdue: t(`${p}.health.overdue`),
      completed: t(`${p}.health.completed`),
    },
    priority: {
      level: t(`${p}.priority.level`),
      levels: {
        critical: t(`${p}.priority.levels.critical`),
        high: t(`${p}.priority.levels.high`),
        medium: t(`${p}.priority.levels.medium`),
        low: t(`${p}.priority.levels.low`),
        optional: t(`${p}.priority.levels.optional`),
      },
    },
    confidence: {
      level: t(`${p}.confidence.level`),
      disclaimer: t(`${p}.confidence.disclaimer`),
      levels: {
        very_low: t(`${p}.confidence.levels.veryLow`),
        low: t(`${p}.confidence.levels.low`),
        moderate: t(`${p}.confidence.levels.moderate`),
        high: t(`${p}.confidence.levels.high`),
        very_high: t(`${p}.confidence.levels.veryHigh`),
      },
    },
    widgets: {
      active: t(`${p}.widgets.active`),
      awaitingApproval: t(`${p}.widgets.awaitingApproval`),
      inExecution: t(`${p}.widgets.inExecution`),
      blocked: t(`${p}.widgets.blocked`),
      completed: t(`${p}.widgets.completed`),
      cancelled: t(`${p}.widgets.cancelled`),
      executivePriority: t(`${p}.widgets.executivePriority`),
      empty: t(`${p}.widgets.empty`),
      viewInitiative: t(`${p}.widgets.viewInitiative`),
    },
    executive: {
      topStrategic: t(`${p}.executive.topStrategic`),
      highestRisk: t(`${p}.executive.highestRisk`),
      highestValue: t(`${p}.executive.highestValue`),
      mostDelayed: t(`${p}.executive.mostDelayed`),
      executiveDecisions: t(`${p}.executive.executiveDecisions`),
      healthSummary: t(`${p}.executive.healthSummary`),
    },
    healthSummary: {
      onTrack: t(`${p}.healthSummary.onTrack`),
      atRisk: t(`${p}.healthSummary.atRisk`),
      blocked: t(`${p}.healthSummary.blocked`),
      overdue: t(`${p}.healthSummary.overdue`),
      completed: t(`${p}.healthSummary.completed`),
    },
    riskAnalysis: {
      title: t(`${p}.riskAnalysis.title`),
      highRiskConcentration: t(`${p}.riskAnalysis.highRiskConcentration`),
      unresolvedBlockers: t(`${p}.riskAnalysis.unresolvedBlockers`),
      missingOwners: t(`${p}.riskAnalysis.missingOwners`),
      unclearOutcomes: t(`${p}.riskAnalysis.unclearOutcomes`),
      lowConfidence: t(`${p}.riskAnalysis.lowConfidence`),
    },
    alignment: {
      businessGoal: t(`${p}.alignment.businessGoal`),
      department: t(`${p}.alignment.department`),
      executiveSponsor: t(`${p}.alignment.executiveSponsor`),
      alignmentScore: t(`${p}.alignment.alignmentScore`),
      expectedValue: t(`${p}.alignment.expectedValue`),
    },
    details: {
      owner: t(`${p}.details.owner`),
      timeline: t(`${p}.details.timeline`),
      plannedStart: t(`${p}.details.plannedStart`),
      estimatedCompletion: t(`${p}.details.estimatedCompletion`),
      expectedOutcome: t(`${p}.details.expectedOutcome`),
      actualOutcome: t(`${p}.details.actualOutcome`),
      linkedActions: t(`${p}.details.linkedActions`),
      linkedApprovals: t(`${p}.details.linkedApprovals`),
      linkedRisks: t(`${p}.details.linkedRisks`),
      linkedDependencies: t(`${p}.details.linkedDependencies`),
    },
    resources: {
      requiredTeams: t(`${p}.resources.requiredTeams`),
      requiredRoles: t(`${p}.resources.requiredRoles`),
      estimatedWorkload: t(`${p}.resources.estimatedWorkload`),
      capacityConcerns: t(`${p}.resources.capacityConcerns`),
      overloadedOwners: t(`${p}.resources.overloadedOwners`),
    },
    decisionSupport: {
      title: t(`${p}.decisionSupport.title`),
      whyItMatters: t(`${p}.decisionSupport.whyItMatters`),
      ifSucceeds: t(`${p}.decisionSupport.ifSucceeds`),
      ifFails: t(`${p}.decisionSupport.ifFails`),
      ifDelayed: t(`${p}.decisionSupport.ifDelayed`),
      whoInvolved: t(`${p}.decisionSupport.whoInvolved`),
      decisionNeeded: t(`${p}.decisionSupport.decisionNeeded`),
    },
    learning: {
      intro: t(`${p}.learning.intro`),
      expectedResult: t(`${p}.learning.expectedResult`),
      actualResult: t(`${p}.learning.actualResult`),
      timelineAccuracy: t(`${p}.learning.timelineAccuracy`),
      businessImpact: t(`${p}.learning.businessImpact`),
      lessonsLearned: t(`${p}.learning.lessonsLearned`),
      improvements: t(`${p}.learning.improvements`),
      submit: t(`${p}.learning.submit`),
      submitted: t(`${p}.learning.submitted`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIsInitiative: t(`${p}.faq.whatIsInitiative`),
      whatIsInitiativeAnswer: t(`${p}.faq.whatIsInitiativeAnswer`),
      howPrioritize: t(`${p}.faq.howPrioritize`),
      howPrioritizeAnswer: t(`${p}.faq.howPrioritizeAnswer`),
      whatIsAlignment: t(`${p}.faq.whatIsAlignment`),
      whatIsAlignmentAnswer: t(`${p}.faq.whatIsAlignmentAnswer`),
      portfolioHealth: t(`${p}.faq.portfolioHealth`),
      portfolioHealthAnswer: t(`${p}.faq.portfolioHealthAnswer`),
      whoOwns: t(`${p}.faq.whoOwns`),
      whoOwnsAnswer: t(`${p}.faq.whoOwnsAnswer`),
      howEstimateRisk: t(`${p}.faq.howEstimateRisk`),
      howEstimateRiskAnswer: t(`${p}.faq.howEstimateRiskAnswer`),
      canAipifyDecide: t(`${p}.faq.canAipifyDecide`),
      canAipifyDecideAnswer: t(`${p}.faq.canAipifyDecideAnswer`),
    },
    empty: t(`${p}.empty`),
    principle: t(`${p}.principle`),
    actions: { back: t(`${p}.actions.back`) },
  };
}
