type TranslateFn = (key: string) => string;

export function buildTrustPanelLabels(t: TranslateFn) {
  return {
    assistantMemory: {
      title: t("platform.assistantMemory.title"),
      subtitle: t("platform.assistantMemory.subtitle"),
      loading: t("platform.assistantMemory.loading"),
      active: t("platform.assistantMemory.active"),
      tenants: t("platform.assistantMemory.tenants"),
      disabled: t("platform.assistantMemory.disabled"),
      byCategory: t("platform.assistantMemory.byCategory"),
      privacyNote: t("platform.assistantMemory.privacyNote"),
    },
    commercialPackages: {
      title: t("platform.commercialPackages.title"),
      subtitle: t("platform.commercialPackages.subtitle"),
      loading: t("platform.commercialPackages.loading"),
      packages: t("platform.commercialPackages.packages"),
      tenants: t("platform.commercialPackages.tenants"),
      licensed: t("platform.commercialPackages.licensed"),
      enabled: t("platform.commercialPackages.enabled"),
      trials: t("platform.commercialPackages.trials"),
      privacyNote: t("platform.commercialPackages.privacyNote"),
    },
    employeeKnowledge: {
      title: t("platform.employeeKnowledge.title"),
      subtitle: t("platform.employeeKnowledge.subtitle"),
      loading: t("platform.employeeKnowledge.loading"),
      profiles: t("platform.employeeKnowledge.profiles"),
      approved: t("platform.employeeKnowledge.approved"),
      pending: t("platform.employeeKnowledge.pending"),
      gaps: t("platform.employeeKnowledge.gaps"),
      paths: t("platform.employeeKnowledge.paths"),
      avgHealth: t("platform.employeeKnowledge.avgHealth"),
      privacyNote: t("platform.employeeKnowledge.privacyNote"),
    },
    supportOperations: {
      title: t("platform.supportOperations.title"),
      subtitle: t("platform.supportOperations.subtitle"),
      loading: t("platform.supportOperations.loading"),
      profiles: t("platform.supportOperations.profiles"),
      openCases: t("platform.supportOperations.openCases"),
      autoReplied: t("platform.supportOperations.autoReplied"),
      escalated: t("platform.supportOperations.escalated"),
      gaps: t("platform.supportOperations.gaps"),
      privacyNote: t("platform.supportOperations.privacyNote"),
    },
    aef: {
      title: t("platform.aef.title"),
      subtitle: t("platform.aef.subtitle"),
      loading: t("platform.aef.loading"),
      profiles: t("platform.aef.profiles"),
      total: t("platform.aef.total"),
      pending: t("platform.aef.pending"),
      executed: t("platform.aef.executed"),
      blocked: t("platform.aef.blocked"),
      rules: t("platform.aef.rules"),
      privacyNote: t("platform.aef.privacyNote"),
    },
    businessDna: {
      title: t("platform.businessDna.title"),
      subtitle: t("platform.businessDna.subtitle"),
      loading: t("platform.businessDna.loading"),
      profiles: t("platform.businessDna.profiles"),
      active: t("platform.businessDna.active"),
      templates: t("platform.businessDna.templates"),
      knowledge: t("platform.businessDna.knowledge"),
      drafts: t("platform.businessDna.drafts"),
      avgHealth: t("platform.businessDna.avgHealth"),
      privacyNote: t("platform.businessDna.privacyNote"),
    },
    decisionSupport: {
      title: t("platform.decisionSupport.title"),
      subtitle: t("platform.decisionSupport.subtitle"),
      loading: t("platform.decisionSupport.loading"),
      profiles: t("platform.decisionSupport.profiles"),
      pending: t("platform.decisionSupport.pending"),
      accepted: t("platform.decisionSupport.accepted"),
      byDomain: t("platform.decisionSupport.byDomain"),
      byConfidence: t("platform.decisionSupport.byConfidence"),
      privacyNote: t("platform.decisionSupport.privacyNote"),
    },
    attentionGuardian: {
      title: t("platform.attentionGuardian.title"),
      subtitle: t("platform.attentionGuardian.subtitle"),
      loading: t("platform.attentionGuardian.loading"),
      profiles: t("platform.attentionGuardian.profiles"),
      activeFocus: t("platform.attentionGuardian.activeFocus"),
      blocks: t("platform.attentionGuardian.blocks"),
      enabled: t("platform.attentionGuardian.enabled"),
      privacyNote: t("platform.attentionGuardian.privacyNote"),
    },
    goalsDreams: {
      title: t("platform.goalsDreams.title"),
      subtitle: t("platform.goalsDreams.subtitle"),
      loading: t("platform.goalsDreams.loading"),
      users: t("platform.goalsDreams.users"),
      active: t("platform.goalsDreams.active"),
      completed: t("platform.goalsDreams.completed"),
      milestones: t("platform.goalsDreams.milestones"),
      byCategory: t("platform.goalsDreams.byCategory"),
      privacyNote: t("platform.goalsDreams.privacyNote"),
    },
    contextEngine: {
      title: t("platform.contextEngine.title"),
      subtitle: t("platform.contextEngine.subtitle"),
      loading: t("platform.contextEngine.loading"),
      profiles: t("platform.contextEngine.profiles"),
      connections: t("platform.contextEngine.connections"),
      pending: t("platform.contextEngine.pending"),
      events: t("platform.contextEngine.events"),
      byMode: t("platform.contextEngine.byMode"),
      privacyNote: t("platform.contextEngine.privacyNote"),
    },
    identity: {
      title: t("platform.identity.title"),
      subtitle: t("platform.identity.subtitle"),
      loading: t("platform.identity.loading"),
      profiles: t("platform.identity.profiles"),
      onboarded: t("platform.identity.onboarded"),
      pending: t("platform.identity.pending"),
      byMode: t("platform.identity.byMode"),
      privacyNote: t("platform.identity.privacyNote"),
    },
    relationships: {
      title: t("platform.relationships.title"),
      subtitle: t("platform.relationships.subtitle"),
      loading: t("platform.relationships.loading"),
      tenants: t("platform.relationships.tenants"),
      people: t("platform.relationships.people"),
      notes: t("platform.relationships.notes"),
      timeline: t("platform.relationships.timeline"),
      disabled: t("platform.relationships.disabled"),
      byType: t("platform.relationships.byType"),
      privacyNote: t("platform.relationships.privacyNote"),
    },
    lifeOs: {
      title: t("platform.lifeOs.title"),
      subtitle: t("platform.lifeOs.subtitle"),
      loading: t("platform.lifeOs.loading"),
      tenants: t("platform.lifeOs.tenants"),
      checklists: t("platform.lifeOs.checklists"),
      memories: t("platform.lifeOs.memories"),
      reschedule: t("platform.lifeOs.reschedule"),
      byPriority: t("platform.lifeOs.byPriority"),
      byLifeArea: t("platform.lifeOs.byLifeArea"),
      privacyNote: t("platform.lifeOs.privacyNote"),
    },
    trustActions: {
      title: t("platform.trustActions.title"),
      subtitle: t("platform.trustActions.subtitle"),
      loading: t("platform.trustActions.loading"),
      pending: t("platform.trustActions.pending"),
      executed: t("platform.trustActions.executed"),
      rejected: t("platform.trustActions.rejected"),
      emergency: t("platform.trustActions.emergency"),
      highestRisk: t("platform.trustActions.highestRisk"),
      recentActivity: t("platform.trustActions.recentActivity"),
      noActivity: t("platform.trustActions.noActivity"),
    },
  };
}
