import { defineSkill } from "../define";

export const commerceAssistantSkill = defineSkill({
  id: "commerce-assistant",
  name: "Commerce Specialist",
  description: "Planned modular skill for commerce and store operations.",
  purpose: "Future capability — architecture placeholder only.",
  dataSources: [],
  permissionsRequired: ["admin", "staff"],
  approvalRequirements: "TBD before release.",
  learningBehaviour: "approved_only",
  tenantIsolation: "tenant",
  escalationRules: [],
  rollbackSupport: false,
  ownerTeam: "product",
  category: "future",
  status: "planned",
  enabledByDefault: false,
  requiresApproval: true,
  supportsLearning: true,
  requiresInstallation: true,
  minimumPlan: "growth",
  core: false,
  tenantScoped: true,
  version: "0.1.0",
  layers: ["embedded", "customer_app"],
  moduleKey: "commerce_ai",
  releaseStage: "aipify_internal",
});
