import type { Translator } from "@/lib/i18n/translate";

export function buildProcurementOperationsLabels(t: Translator) {
  const p = "customerApp.procurementOperations";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    purchaseRequests: t(`${p}.purchaseRequests`),
    approvals: t(`${p}.approvals`),
    vendors: t(`${p}.vendors`),
    contracts: t(`${p}.contracts`),
    orders: t(`${p}.orders`),
    deliveries: t(`${p}.deliveries`),
    reports: t(`${p}.reports`),
    pendingApprovals: t(`${p}.pendingApprovals`),
    openRequests: t(`${p}.openRequests`),
    activeVendors: t(`${p}.activeVendors`),
    contractExposure: t(`${p}.contractExposure`),
    ordersInTransit: t(`${p}.ordersInTransit`),
    expiringContracts: t(`${p}.expiringContracts`),
    highRiskVendors: t(`${p}.highRiskVendors`),
    purchasingVolume: t(`${p}.purchasingVolume`),
    overdueRequests: t(`${p}.overdueRequests`),
    createRequest: t(`${p}.createRequest`),
    submitRequest: t(`${p}.submitRequest`),
    approveRequest: t(`${p}.approveRequest`),
    rejectRequest: t(`${p}.rejectRequest`),
    createVendor: t(`${p}.createVendor`),
    createContract: t(`${p}.createContract`),
    createOrder: t(`${p}.createOrder`),
    markDelivered: t(`${p}.markDelivered`),
    requestTitle: t(`${p}.requestTitle`),
    vendorName: t(`${p}.vendorName`),
    amount: t(`${p}.amount`),
    contractName: t(`${p}.contractName`),
    status: t(`${p}.status`),
    approvalStatus: t(`${p}.approvalStatus`),
    vendorRating: t(`${p}.vendorRating`),
    preferred: t(`${p}.preferred`),
    noRequests: t(`${p}.noRequests`),
    noRequestsHint: t(`${p}.noRequestsHint`),
    noVendors: t(`${p}.noVendors`),
    noOrders: t(`${p}.noOrders`),
    auditLog: t(`${p}.auditLog`),
    avgApprovalDays: t(`${p}.avgApprovalDays`),
    supplierConcentration: t(`${p}.supplierConcentration`),
    save: t(`${p}.save`),
  };
}

export type ProcurementOperationsLabels = ReturnType<typeof buildProcurementOperationsLabels>;
