import type { Translator } from "@/lib/i18n/translate";

export function buildProcurementOperationsLabels(t: Translator) {
  const p = "customerApp.procurementOperations";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    purchaseRequests: t(`${p}.purchaseRequests`),
    approvals: t(`${p}.approvals`),
    vendors: t(`${p}.vendors`),
    suppliers: t(`${p}.suppliers`),
    contracts: t(`${p}.contracts`),
    orders: t(`${p}.orders`),
    deliveries: t(`${p}.deliveries`),
    incomingGoods: t(`${p}.incomingGoods`),
    quotations: t(`${p}.quotations`),
    spendAnalysis: t(`${p}.spendAnalysis`),
    reports: t(`${p}.reports`),
    pendingApprovals: t(`${p}.pendingApprovals`),
    openRequests: t(`${p}.openRequests`),
    activeVendors: t(`${p}.activeVendors`),
    activeSuppliers: t(`${p}.activeSuppliers`),
    preferredSuppliers: t(`${p}.preferredSuppliers`),
    contractExposure: t(`${p}.contractExposure`),
    ordersInTransit: t(`${p}.ordersInTransit`),
    expiringContracts: t(`${p}.expiringContracts`),
    highRiskVendors: t(`${p}.highRiskVendors`),
    highRiskSuppliers: t(`${p}.highRiskSuppliers`),
    openRfqs: t(`${p}.openRfqs`),
    pendingReceiving: t(`${p}.pendingReceiving`),
    purchasingVolume: t(`${p}.purchasingVolume`),
    overdueRequests: t(`${p}.overdueRequests`),
    createRequest: t(`${p}.createRequest`),
    submitRequest: t(`${p}.submitRequest`),
    approveRequest: t(`${p}.approveRequest`),
    rejectRequest: t(`${p}.rejectRequest`),
    createVendor: t(`${p}.createVendor`),
    createSupplier: t(`${p}.createSupplier`),
    createContract: t(`${p}.createContract`),
    createOrder: t(`${p}.createOrder`),
    createRfq: t(`${p}.createRfq`),
    markDelivered: t(`${p}.markDelivered`),
    receiveGoods: t(`${p}.receiveGoods`),
    refreshScorecard: t(`${p}.refreshScorecard`),
    requestTitle: t(`${p}.requestTitle`),
    vendorName: t(`${p}.vendorName`),
    supplierName: t(`${p}.supplierName`),
    rfqTitle: t(`${p}.rfqTitle`),
    amount: t(`${p}.amount`),
    contractName: t(`${p}.contractName`),
    status: t(`${p}.status`),
    approvalStatus: t(`${p}.approvalStatus`),
    vendorRating: t(`${p}.vendorRating`),
    supplierHealth: t(`${p}.supplierHealth`),
    preferred: t(`${p}.preferred`),
    condition: t(`${p}.condition`),
    noRequests: t(`${p}.noRequests`),
    noRequestsHint: t(`${p}.noRequestsHint`),
    noVendors: t(`${p}.noVendors`),
    noSuppliers: t(`${p}.noSuppliers`),
    noOrders: t(`${p}.noOrders`),
    noIncomingGoods: t(`${p}.noIncomingGoods`),
    auditLog: t(`${p}.auditLog`),
    avgApprovalDays: t(`${p}.avgApprovalDays`),
    supplierConcentration: t(`${p}.supplierConcentration`),
    spendBySupplier: t(`${p}.spendBySupplier`),
    suppliersTitle: t(`${p}.suppliersTitle`),
    receivingTitle: t(`${p}.receivingTitle`),
    companionInsights: t(`${p}.companionInsights`),
    save: t(`${p}.save`),
  };
}

export type ProcurementOperationsLabels = ReturnType<typeof buildProcurementOperationsLabels>;
