import type { Translator } from "@/lib/i18n/translate";

export function buildMarketingBrandOperationsLabels(t: Translator) {
  const p = "customerApp.marketingBrandOperations";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    philosophy: t(`${p}.philosophy`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    campaigns: t(`${p}.campaigns`),
    content: t(`${p}.content`),
    audiences: t(`${p}.audiences`),
    channels: t(`${p}.channels`),
    assets: t(`${p}.assets`),
    performance: t(`${p}.performance`),
    reports: t(`${p}.reports`),
    activeCampaigns: t(`${p}.activeCampaigns`),
    needsAttention: t(`${p}.needsAttention`),
    draftCampaigns: t(`${p}.draftCampaigns`),
    audienceCount: t(`${p}.audienceCount`),
    approvedContent: t(`${p}.approvedContent`),
    pendingContentReview: t(`${p}.pendingContentReview`),
    approvedAssets: t(`${p}.approvedAssets`),
    activeChannels: t(`${p}.activeChannels`),
    partnerMaterials: t(`${p}.partnerMaterials`),
    upcomingEvents: t(`${p}.upcomingEvents`),
    brandHealthScore: t(`${p}.brandHealthScore`),
    createCampaign: t(`${p}.createCampaign`),
    campaignName: t(`${p}.campaignName`),
    activateCampaign: t(`${p}.activateCampaign`),
    pauseCampaign: t(`${p}.pauseCampaign`),
    completeCampaign: t(`${p}.completeCampaign`),
    createAudience: t(`${p}.createAudience`),
    audienceName: t(`${p}.audienceName`),
    createContent: t(`${p}.createContent`),
    contentTitle: t(`${p}.contentTitle`),
    approveContent: t(`${p}.approveContent`),
    rejectContent: t(`${p}.rejectContent`),
    createAsset: t(`${p}.createAsset`),
    assetTitle: t(`${p}.assetTitle`),
    approveAsset: t(`${p}.approveAsset`),
    createChannel: t(`${p}.createChannel`),
    channelName: t(`${p}.channelName`),
    noCampaigns: t(`${p}.noCampaigns`),
    noAudiences: t(`${p}.noAudiences`),
    noContent: t(`${p}.noContent`),
    noAssets: t(`${p}.noAssets`),
    noChannels: t(`${p}.noChannels`),
    emptyHint: t(`${p}.emptyHint`),
    audienceGrowth: t(`${p}.audienceGrowth`),
    marketingRoi: t(`${p}.marketingRoi`),
    partnerDistributed: t(`${p}.partnerDistributed`),
    auditLog: t(`${p}.auditLog`),
    status: t(`${p}.status`),
    mobileReady: t(`${p}.mobileReady`),
    calendar: t(`${p}.calendar`),
    partnerReferralNote: t(`${p}.partnerReferralNote`),
    reach: t(`${p}.reach`),
    leads: t(`${p}.leads`),
    roi: t(`${p}.roi`),
  };
}

export type MarketingBrandOperationsLabels = ReturnType<typeof buildMarketingBrandOperationsLabels>;
