import type { OrganizationalEarlyWarningLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildOrganizationalEarlyWarningLabels(t: Translator): OrganizationalEarlyWarningLabels {
  const p = "customerApp.organizationalEarlyWarning";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    humanOversight: t(`${p}.humanOversight`),
    principle: t(`${p}.principle`),
    executiveLink: t(`${p}.executiveLink`),
    cockpitLink: t(`${p}.cockpitLink`),
    actionCenterLink: t(`${p}.actionCenterLink`),
    boardInvestorIntelligenceLink: t(`${p}.boardInvestorIntelligenceLink`),
    tabs: {
      dashboard: t(`${p}.tabs.dashboard`),
      warnings: t(`${p}.tabs.warnings`),
      trends: t(`${p}.tabs.trends`),
      forecasts: t(`${p}.tabs.forecasts`),
      opportunities: t(`${p}.tabs.opportunities`),
      escalation: t(`${p}.tabs.escalation`),
      queue: t(`${p}.tabs.queue`),
      learning: t(`${p}.tabs.learning`),
    },
    dashboard: {
      title: t(`${p}.dashboard.title`),
      emergingRisks: t(`${p}.dashboard.emergingRisks`),
      escalatingBottlenecks: t(`${p}.dashboard.escalatingBottlenecks`),
      losingMomentum: t(`${p}.dashboard.losingMomentum`),
      teamOverload: t(`${p}.dashboard.teamOverload`),
      customerDeterioration: t(`${p}.dashboard.customerDeterioration`),
      complianceWarnings: t(`${p}.dashboard.complianceWarnings`),
      revenueWarnings: t(`${p}.dashboard.revenueWarnings`),
    },
    warnings: {
      title: t(`${p}.warnings.title`),
      category: t(`${p}.warnings.category`),
      severity: t(`${p}.warnings.severity`),
      explanation: t(`${p}.warnings.explanation`),
      reasoning: t(`${p}.warnings.reasoning`),
      suggestedActions: t(`${p}.warnings.suggestedActions`),
      confidence: t(`${p}.warnings.confidence`),
      disclaimer: t(`${p}.warnings.disclaimer`),
      viewBriefing: t(`${p}.warnings.viewBriefing`),
      acknowledge: t(`${p}.warnings.acknowledge`),
      dismiss: t(`${p}.warnings.dismiss`),
      escalate: t(`${p}.warnings.escalate`),
      empty: t(`${p}.warnings.empty`),
      categories: {
        operational_risk: t(`${p}.warnings.categories.operationalRisk`),
        financial_risk: t(`${p}.warnings.categories.financialRisk`),
        customer_risk: t(`${p}.warnings.categories.customerRisk`),
        employee_risk: t(`${p}.warnings.categories.employeeRisk`),
        compliance_risk: t(`${p}.warnings.categories.complianceRisk`),
        strategic_execution_risk: t(`${p}.warnings.categories.strategicExecutionRisk`),
        partner_risk: t(`${p}.warnings.categories.partnerRisk`),
        capacity_risk: t(`${p}.warnings.categories.capacityRisk`),
      },
      severities: {
        informational: t(`${p}.warnings.severities.informational`),
        monitor: t(`${p}.warnings.severities.monitor`),
        elevated_concern: t(`${p}.warnings.severities.elevatedConcern`),
        high_risk: t(`${p}.warnings.severities.highRisk`),
        critical_attention_required: t(`${p}.warnings.severities.criticalAttentionRequired`),
      },
    },
    trends: {
      title: t(`${p}.trends.title`),
      detected: t(`${p}.trends.detected`),
      notDetected: t(`${p}.trends.notDetected`),
      count: t(`${p}.trends.count`),
    },
    forecasts: {
      title: t(`${p}.forecasts.title`),
      disclaimer: t(`${p}.forecasts.disclaimer`),
      days30: t(`${p}.forecasts.days30`),
      days60: t(`${p}.forecasts.days60`),
      days90: t(`${p}.forecasts.days90`),
      days180: t(`${p}.forecasts.days180`),
      estimate: t(`${p}.forecasts.estimate`),
      factors: t(`${p}.forecasts.factors`),
    },
    opportunities: {
      title: t(`${p}.opportunities.title`),
      empty: t(`${p}.opportunities.empty`),
      types: {
        efficiency_gain: t(`${p}.opportunities.types.efficiencyGain`),
        growth_opportunity: t(`${p}.opportunities.types.growthOpportunity`),
        partnership_opportunity: t(`${p}.opportunities.types.partnershipOpportunity`),
        underutilized_capability: t(`${p}.opportunities.types.underutilizedCapability`),
      },
    },
    escalation: {
      title: t(`${p}.escalation.title`),
      threshold: t(`${p}.escalation.threshold`),
      enabled: t(`${p}.escalation.enabled`),
    },
    queue: {
      title: t(`${p}.queue.title`),
      urgency: t(`${p}.queue.urgency`),
      impact: t(`${p}.queue.impact`),
      confidence: t(`${p}.queue.confidence`),
      reviewTimeline: t(`${p}.queue.reviewTimeline`),
      stakeholder: t(`${p}.queue.stakeholder`),
      empty: t(`${p}.queue.empty`),
    },
    briefing: {
      title: t(`${p}.briefing.title`),
      whatChanged: t(`${p}.briefing.whatChanged`),
      whyImportant: t(`${p}.briefing.whyImportant`),
      whatNext: t(`${p}.briefing.whatNext`),
      responseOptions: t(`${p}.briefing.responseOptions`),
      urgency: t(`${p}.briefing.urgency`),
      back: t(`${p}.briefing.back`),
    },
    learning: {
      title: t(`${p}.learning.title`),
      accuracy: t(`${p}.learning.accuracy`),
      falsePositives: t(`${p}.learning.falsePositives`),
      responseEffectiveness: t(`${p}.learning.responseEffectiveness`),
      forecastReliability: t(`${p}.learning.forecastReliability`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatAreSignals: t(`${p}.faq.whatAreSignals`),
      whatAreSignalsAnswer: t(`${p}.faq.whatAreSignalsAnswer`),
      canPredict: t(`${p}.faq.canPredict`),
      canPredictAnswer: t(`${p}.faq.canPredictAnswer`),
      howGenerated: t(`${p}.faq.howGenerated`),
      howGeneratedAnswer: t(`${p}.faq.howGeneratedAnswer`),
      howRespond: t(`${p}.faq.howRespond`),
      howRespondAnswer: t(`${p}.faq.howRespondAnswer`),
      confidenceLevels: t(`${p}.faq.confidenceLevels`),
      confidenceLevelsAnswer: t(`${p}.faq.confidenceLevelsAnswer`),
    },
    empty: t(`${p}.empty`),
    upgradeTitle: t(`${p}.upgrade.title`),
    upgradeBody: t(`${p}.upgrade.body`),
    upgradeCta: t(`${p}.upgrade.cta`),
  };
}
