import type { Translator } from "@/lib/i18n/translate";

export function buildCustomerRelationshipLabels(t: Translator) {
  const p = "customerApp.customerRelationship";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    prospects: t(`${p}.prospects`),
    customers: t(`${p}.customers`),
    contacts: t(`${p}.contacts`),
    organizations: t(`${p}.organizations`),
    leads: t(`${p}.leads`),
    opportunities: t(`${p}.opportunities`),
    activities: t(`${p}.activities`),
    renewals: t(`${p}.renewals`),
    contracts: t(`${p}.contracts`),
    relationships: t(`${p}.relationships`),
    communication: t(`${p}.communication`),
    documents: t(`${p}.documents`),
    reports: t(`${p}.reports`),
    totalCustomers: t(`${p}.totalCustomers`),
    activeCustomers: t(`${p}.activeCustomers`),
    atRisk: t(`${p}.atRisk`),
    requiresAttention: t(`${p}.requiresAttention`),
    openLeads: t(`${p}.openLeads`),
    openOpportunities: t(`${p}.openOpportunities`),
    pipelineValue: t(`${p}.pipelineValue`),
    renewalsDue: t(`${p}.renewalsDue`),
    contractsExpiring: t(`${p}.contractsExpiring`),
    healthyCustomers: t(`${p}.healthyCustomers`),
    followUpsDue: t(`${p}.followUpsDue`),
    createCustomer: t(`${p}.createCustomer`),
    createLead: t(`${p}.createLead`),
    createOpportunity: t(`${p}.createOpportunity`),
    createContract: t(`${p}.createContract`),
    triggerRenewal: t(`${p}.triggerRenewal`),
    refreshHealth: t(`${p}.refreshHealth`),
    customerName: t(`${p}.customerName`),
    companyName: t(`${p}.companyName`),
    opportunityName: t(`${p}.opportunityName`),
    contractTitle: t(`${p}.contractTitle`),
    email: t(`${p}.email`),
    phone: t(`${p}.phone`),
    value: t(`${p}.value`),
    stage: t(`${p}.stage`),
    addNote: t(`${p}.addNote`),
    followUpTask: t(`${p}.followUpTask`),
    searchPlaceholder: t(`${p}.searchPlaceholder`),
    search: t(`${p}.search`),
    noCustomers: t(`${p}.noCustomers`),
    noCustomersHint: t(`${p}.noCustomersHint`),
    noOpportunities: t(`${p}.noOpportunities`),
    noContracts: t(`${p}.noContracts`),
    noRenewals: t(`${p}.noRenewals`),
    auditLog: t(`${p}.auditLog`),
    leadsLink: t(`${p}.leadsLink`),
    opportunitiesLink: t(`${p}.opportunitiesLink`),
    contractsLink: t(`${p}.contractsLink`),
    backToCustomers: t(`${p}.backToCustomers`),
    leadsTitle: t(`${p}.leadsTitle`),
    opportunitiesTitle: t(`${p}.opportunitiesTitle`),
    contractsTitle: t(`${p}.contractsTitle`),
    pipeline: t(`${p}.pipeline`),
    convertLead: t(`${p}.convertLead`),
    updateStatus: t(`${p}.updateStatus`),
    companionInsights: t(`${p}.companionInsights`),
    subscriptionAwareness: t(`${p}.subscriptionAwareness`),
    healthScore: t(`${p}.healthScore`),
    save: t(`${p}.save`),
  };
}

export type CustomerRelationshipLabels = ReturnType<typeof buildCustomerRelationshipLabels>;
