export function buildPartnerSettlementsLabels(t: (key: string) => string): Record<string, string> {
  const p = "partnerSettlements";
  const keys = [
    "title",
    "subtitle",
    "loading",
    "errorTitle",
    "errorMessage",
    "retry",
    "accessDenied",
    "positioning",
    "currentPeriod",
    "pendingTotal",
    "noPayableTitle",
    "noPayableMessage",
    "prepareSettlement",
    "prepared",
    "selfBillingTitle",
    "selfBillingDescription",
    "acceptAgreement",
    "agreementAccepted",
    "agreementRequired",
    "settlementDetailTitle",
    "settlementPeriod",
    "commissionTotal",
    "vatRate",
    "vatAmount",
    "totalPayable",
    "dueDate",
    "paymentTerms",
    "sellerTitle",
    "buyerTitle",
    "companyName",
    "organizationNumber",
    "vatNumber",
    "businessAddress",
    "country",
    "bankAccount",
    "contactEmail",
    "lineItemsTitle",
    "saleReference",
    "customer",
    "package",
    "saleValue",
    "commissionRate",
    "commissionAmount",
    "description",
    "approveSettlement",
    "approvalText",
    "approved",
    "actionFailed",
    "historyTitle",
    "invoiceNumber",
    "invoiceDate",
    "invoiceStatus",
    "status_draft",
    "status_awaiting_partner_approval",
    "status_approved",
    "status_invoice_generated",
    "status_sent_to_accounting",
    "status_paid",
    "status_rejected",
    "status_cancelled",
    "status_finalized",
    "viewCommissions",
  ];
  return Object.fromEntries(keys.map((key) => [key, t(`${p}.${key}`)]));
}

export function settlementStatusLabel(labels: Record<string, string>, status: string): string {
  return labels[`status_${status}`] ?? status.replace(/_/g, " ");
}
