import type { MeetingsLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildMeetingsLabels(t: Translator): MeetingsLabels {
  const p = "customerApp.portalStructure.meetings";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    filters: {
      search: t(`${p}.filters.search`),
      type: t(`${p}.filters.type`),
      status: t(`${p}.filters.status`),
      organizer: t(`${p}.filters.organizer`),
      dateFrom: t(`${p}.filters.dateFrom`),
      dateTo: t(`${p}.filters.dateTo`),
      outstandingActions: t(`${p}.filters.outstandingActions`),
      all: t(`${p}.filters.all`),
      yes: t(`${p}.filters.yes`),
      no: t(`${p}.filters.no`),
    },
    dashboard: {
      upcoming: t(`${p}.dashboard.upcoming`),
      needsOutcomes: t(`${p}.dashboard.needsOutcomes`),
      outstandingActions: t(`${p}.dashboard.outstandingActions`),
      recentlyCompleted: t(`${p}.dashboard.recentlyCompleted`),
      withoutNotes: t(`${p}.dashboard.withoutNotes`),
      overdueActions: t(`${p}.dashboard.overdueActions`),
    },
    form: {
      createTitle: t(`${p}.form.createTitle`),
      title: t(`${p}.form.title`),
      type: t(`${p}.form.type`),
      description: t(`${p}.form.description`),
      objectives: t(`${p}.form.objectives`),
      meetingAt: t(`${p}.form.meetingAt`),
      duration: t(`${p}.form.duration`),
      notes: t(`${p}.form.notes`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
    },
    card: {
      organizer: t(`${p}.card.organizer`),
      meetingAt: t(`${p}.card.meetingAt`),
      duration: t(`${p}.card.duration`),
      openActions: t(`${p}.card.openActions`),
      view: t(`${p}.card.view`),
    },
    detail: {
      overview: t(`${p}.detail.overview`),
      participants: t(`${p}.detail.participants`),
      notes: t(`${p}.detail.notes`),
      objectives: t(`${p}.detail.objectives`),
      decisions: t(`${p}.detail.decisions`),
      actionItems: t(`${p}.detail.actionItems`),
      relatedGoals: t(`${p}.detail.relatedGoals`),
      relatedFollowUps: t(`${p}.detail.relatedFollowUps`),
      activity: t(`${p}.detail.activity`),
      audit: t(`${p}.detail.audit`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
      recommendations: t(`${p}.detail.recommendations`),
      addAction: t(`${p}.detail.addAction`),
      addDecision: t(`${p}.detail.addDecision`),
      actionTitle: t(`${p}.detail.actionTitle`),
      actionDue: t(`${p}.detail.actionDue`),
      decisionTitle: t(`${p}.detail.decisionTitle`),
      decisionRationale: t(`${p}.detail.decisionRationale`),
    },
    types: {
      executive_meeting: t(`${p}.types.executiveMeeting`),
      team_meeting: t(`${p}.types.teamMeeting`),
      project_meeting: t(`${p}.types.projectMeeting`),
      customer_meeting: t(`${p}.types.customerMeeting`),
      vendor_meeting: t(`${p}.types.vendorMeeting`),
      retrospective: t(`${p}.types.retrospective`),
      planning_session: t(`${p}.types.planningSession`),
      incident_review: t(`${p}.types.incidentReview`),
      compliance_review: t(`${p}.types.complianceReview`),
      custom_meeting: t(`${p}.types.customMeeting`),
    },
    statuses: {
      scheduled: t(`${p}.statuses.scheduled`),
      in_progress: t(`${p}.statuses.inProgress`),
      completed: t(`${p}.statuses.completed`),
      cancelled: t(`${p}.statuses.cancelled`),
    },
    actionStatuses: {
      open: t(`${p}.actionStatuses.open`),
      in_progress: t(`${p}.actionStatuses.inProgress`),
      waiting: t(`${p}.actionStatuses.waiting`),
      completed: t(`${p}.actionStatuses.completed`),
      cancelled: t(`${p}.actionStatuses.cancelled`),
    },
    priorities: {
      low: t(`${p}.priorities.low`),
      medium: t(`${p}.priorities.medium`),
      high: t(`${p}.priorities.high`),
    },
    recommendations: {
      assignActionOwners: t(`${p}.recommendations.assignActionOwners`),
      recordOutcomes: t(`${p}.recommendations.recordOutcomes`),
      followUpOverdue: t(`${p}.recommendations.followUpOverdue`),
      linkGoals: t(`${p}.recommendations.linkGoals`),
      scheduleRecurringReview: t(`${p}.recommendations.scheduleRecurringReview`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      outcomes: t(`${p}.faq.outcomes`),
      outcomesAnswer: t(`${p}.faq.outcomesAnswer`),
      autoComplete: t(`${p}.faq.autoComplete`),
      autoCompleteAnswer: t(`${p}.faq.autoCompleteAnswer`),
    },
  };
}
