import type { EnterpriseTransformationChangeLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildEnterpriseTransformationChangeLabels(t: Translator): EnterpriseTransformationChangeLabels {
  const p = "customerApp.enterpriseTransformationChange";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    humanOversight: t(`${p}.humanOversight`),
    principle: t(`${p}.principle`),
    executiveLink: t(`${p}.executiveLink`),
    cockpitLink: t(`${p}.cockpitLink`),
    earlyWarningLink: t(`${p}.earlyWarningLink`),
    portfolioLink: t(`${p}.portfolioLink`),
    generateBriefing: t(`${p}.generateBriefing`),
    recorded: t(`${p}.recorded`),
    tabs: {
      dashboard: t(`${p}.tabs.dashboard`),
      categories: t(`${p}.tabs.categories`),
      readiness: t(`${p}.tabs.readiness`),
      adoption: t(`${p}.tabs.adoption`),
      resistance: t(`${p}.tabs.resistance`),
      briefing: t(`${p}.tabs.briefing`),
      stakeholders: t(`${p}.tabs.stakeholders`),
      communication: t(`${p}.tabs.communication`),
      training: t(`${p}.tabs.training`),
      milestones: t(`${p}.tabs.milestones`),
      learning: t(`${p}.tabs.learning`),
      reflection: t(`${p}.tabs.reflection`),
    },
    dashboard: {
      title: t(`${p}.dashboard.title`),
      activePrograms: t(`${p}.dashboard.activePrograms`),
      healthStatus: t(`${p}.dashboard.healthStatus`),
      adoptionProgress: t(`${p}.dashboard.adoptionProgress`),
      readiness: t(`${p}.dashboard.readiness`),
      resistanceSignals: t(`${p}.dashboard.resistanceSignals`),
      milestonesAchieved: t(`${p}.dashboard.milestonesAchieved`),
      sponsorship: t(`${p}.dashboard.sponsorship`),
      programs: t(`${p}.dashboard.programs`),
    },
    categories: { title: t(`${p}.categories.title`) },
    categoryLabels: {
      digital_transformation: t(`${p}.categoryLabels.digitalTransformation`),
      organizational_restructuring: t(`${p}.categoryLabels.organizationalRestructuring`),
      process_transformation: t(`${p}.categoryLabels.processTransformation`),
      technology_adoption: t(`${p}.categoryLabels.technologyAdoption`),
      cultural_transformation: t(`${p}.categoryLabels.culturalTransformation`),
      compliance_transformation: t(`${p}.categoryLabels.complianceTransformation`),
      customer_experience_transformation: t(`${p}.categoryLabels.customerExperienceTransformation`),
      strategic_pivot_initiatives: t(`${p}.categoryLabels.strategicPivotInitiatives`),
      growth_transformation: t(`${p}.categoryLabels.growthTransformation`),
      operational_excellence_programs: t(`${p}.categoryLabels.operationalExcellencePrograms`),
    },
    readiness: {
      title: t(`${p}.readiness.title`),
      overall: t(`${p}.readiness.overall`),
      leadershipAlignment: t(`${p}.readiness.leadershipAlignment`),
      employeeUnderstanding: t(`${p}.readiness.employeeUnderstanding`),
      communicationEffectiveness: t(`${p}.readiness.communicationEffectiveness`),
      resourceAvailability: t(`${p}.readiness.resourceAvailability`),
      trainingReadiness: t(`${p}.readiness.trainingReadiness`),
      governanceReadiness: t(`${p}.readiness.governanceReadiness`),
      statuses: {
        ready: t(`${p}.readiness.statuses.ready`),
        mostly_ready: t(`${p}.readiness.statuses.mostlyReady`),
        partially_ready: t(`${p}.readiness.statuses.partiallyReady`),
        not_ready: t(`${p}.readiness.statuses.notReady`),
        critical_concerns: t(`${p}.readiness.statuses.criticalConcerns`),
      },
    },
    adoption: {
      title: t(`${p}.adoption.title`),
      trainingParticipation: t(`${p}.adoption.trainingParticipation`),
      processAdoption: t(`${p}.adoption.processAdoption`),
      usagePattern: t(`${p}.adoption.usagePattern`),
      supportRequests: t(`${p}.adoption.supportRequests`),
      feedbackTrend: t(`${p}.adoption.feedbackTrend`),
      departmentNotes: t(`${p}.adoption.departmentNotes`),
      departmentDifferences: t(`${p}.adoption.departmentDifferences`),
    },
    resistance: {
      title: t(`${p}.resistance.title`),
      supportiveNote: t(`${p}.resistance.supportiveNote`),
      severity: t(`${p}.resistance.severity`),
      empty: t(`${p}.resistance.empty`),
    },
    resistanceSignals: {
      declining_engagement: t(`${p}.resistanceSignals.decliningEngagement`),
      repeated_delays: t(`${p}.resistanceSignals.repeatedDelays`),
      low_participation: t(`${p}.resistanceSignals.lowParticipation`),
      negative_sentiment: t(`${p}.resistanceSignals.negativeSentiment`),
      escalating_concerns: t(`${p}.resistanceSignals.escalatingConcerns`),
      conflicting_priorities: t(`${p}.resistanceSignals.conflictingPriorities`),
    },
    briefing: {
      title: t(`${p}.briefing.title`),
      status: t(`${p}.briefing.status`),
      achievements: t(`${p}.briefing.achievements`),
      risks: t(`${p}.briefing.risks`),
      adoptionTrends: t(`${p}.briefing.adoptionTrends`),
      interventions: t(`${p}.briefing.interventions`),
      priorityFocus: t(`${p}.briefing.priorityFocus`),
      confidence: t(`${p}.briefing.confidence`),
      disclaimer: t(`${p}.briefing.disclaimer`),
    },
    stakeholders: {
      title: t(`${p}.stakeholders.title`),
      executiveSponsors: t(`${p}.stakeholders.executiveSponsors`),
      transformationLeaders: t(`${p}.stakeholders.transformationLeaders`),
      departmentChampions: t(`${p}.stakeholders.departmentChampions`),
      subjectMatterExperts: t(`${p}.stakeholders.subjectMatterExperts`),
      impactedTeams: t(`${p}.stakeholders.impactedTeams`),
      communicationOwners: t(`${p}.stakeholders.communicationOwners`),
    },
    communication: {
      title: t(`${p}.communication.title`),
      frequency: t(`${p}.communication.frequency`),
      reach: t(`${p}.communication.reach`),
      acknowledgement: t(`${p}.communication.acknowledgement`),
      understanding: t(`${p}.communication.understanding`),
      missedAudiences: t(`${p}.communication.missedAudiences`),
      recommendedActions: t(`${p}.communication.recommendedActions`),
    },
    training: {
      title: t(`${p}.training.title`),
      completionRate: t(`${p}.training.completionRate`),
      knowledgeGaps: t(`${p}.training.knowledgeGaps`),
      departmentReadiness: t(`${p}.training.departmentReadiness`),
      followUp: t(`${p}.training.followUp`),
      learningPathways: t(`${p}.training.learningPathways`),
    },
    milestones: {
      title: t(`${p}.milestones.title`),
      planned: t(`${p}.milestones.planned`),
      completed: t(`${p}.milestones.completed`),
      delayed: t(`${p}.milestones.delayed`),
      blocked: t(`${p}.milestones.blocked`),
      executiveReview: t(`${p}.milestones.executiveReview`),
    },
    learning: { title: t(`${p}.learning.title`) },
    reflection: { title: t(`${p}.reflection.title`), guidance: t(`${p}.reflection.guidance`) },
    faq: {
      title: t(`${p}.faq.title`),
      whatIsTransformation: t(`${p}.faq.whatIsTransformation`),
      whatIsTransformationAnswer: t(`${p}.faq.whatIsTransformationAnswer`),
      whyFail: t(`${p}.faq.whyFail`),
      whyFailAnswer: t(`${p}.faq.whyFailAnswer`),
      howSupport: t(`${p}.faq.howSupport`),
      howSupportAnswer: t(`${p}.faq.howSupportAnswer`),
      autoManage: t(`${p}.faq.autoManage`),
      autoManageAnswer: t(`${p}.faq.autoManageAnswer`),
      respondResistance: t(`${p}.faq.respondResistance`),
      respondResistanceAnswer: t(`${p}.faq.respondResistanceAnswer`),
      readinessAssessments: t(`${p}.faq.readinessAssessments`),
      readinessAssessmentsAnswer: t(`${p}.faq.readinessAssessmentsAnswer`),
    },
    upgradeTitle: t(`${p}.upgrade.title`),
    upgradeBody: t(`${p}.upgrade.body`),
    upgradeCta: t(`${p}.upgrade.cta`),
  };
}
