import type { Translator } from "@/lib/i18n/translate";

export function buildGovernanceManagementLabels(t: Translator) {
  const p = "customerApp.governanceManagement";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    companionNote: t(`${p}.companionNote`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    policies: t(`${p}.policies`),
    approvals: t(`${p}.approvals`),
    accessReviews: t(`${p}.accessReviews`),
    compliance: t(`${p}.compliance`),
    audit: t(`${p}.audit`),
    risk: t(`${p}.risk`),
    controls: t(`${p}.controls`),
    reports: t(`${p}.reports`),
    governanceHealth: t(`${p}.governanceHealth`),
    openRisks: t(`${p}.openRisks`),
    pendingApprovals: t(`${p}.pendingApprovals`),
    pendingReviews: t(`${p}.pendingReviews`),
    activePolicies: t(`${p}.activePolicies`),
    pendingAcknowledgements: t(`${p}.pendingAcknowledgements`),
    createPolicy: t(`${p}.createPolicy`),
    policyTitle: t(`${p}.policyTitle`),
    acknowledge: t(`${p}.acknowledge`),
    decline: t(`${p}.decline`),
    clarify: t(`${p}.clarify`),
    createReview: t(`${p}.createReview`),
    createRisk: t(`${p}.createRisk`),
    approve: t(`${p}.approve`),
    reject: t(`${p}.reject`),
    noPolicies: t(`${p}.noPolicies`),
    noPoliciesHint: t(`${p}.noPoliciesHint`),
    auditLog: t(`${p}.auditLog`),
    backToGovernance: t(`${p}.backToGovernance`),
    policiesTitle: t(`${p}.policiesTitle`),
    complianceTitle: t(`${p}.complianceTitle`),
    riskTitle: t(`${p}.riskTitle`),
    controlsTitle: t(`${p}.controlsTitle`),
    accessReviewsTitle: t(`${p}.accessReviewsTitle`),
    auditTitle: t(`${p}.auditTitle`),
    taccLink: t(`${p}.taccLink`),
    approvalCenterLink: t(`${p}.approvalCenterLink`),
    save: t(`${p}.save`),
    draft: t(`${p}.draft`),
    reviewRequired: t(`${p}.reviewRequired`),
    active: t(`${p}.active`),
    expiring: t(`${p}.expiring`),
    retired: t(`${p}.retired`),
  };
}

export type GovernanceManagementLabels = ReturnType<typeof buildGovernanceManagementLabels>;
