import type { ActionImpactLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildActionImpactLabels(t: Translator): ActionImpactLabels {
  const p = "customerApp.actionCenter.impactAnalysis";
  return {
    centerTitle: t(`${p}.centerTitle`),
    centerSubtitle: t(`${p}.centerSubtitle`),
    viewModeFull: t(`${p}.viewModeFull`),
    viewModeExecutive: t(`${p}.viewModeExecutive`),
    humanOversight: {
      basedOnAvailableInformation: t(`${p}.humanOversight.basedOnAvailableInformation`),
      aipifyEstimates: t(`${p}.humanOversight.aipifyEstimates`),
      reviewBeforeExecution: t(`${p}.humanOversight.reviewBeforeExecution`),
    },
    sections: {
      summary: t(`${p}.sections.summary`),
      expectedOutcome: t(`${p}.sections.expectedOutcome`),
      businessImpact: t(`${p}.sections.businessImpact`),
      impactCategories: t(`${p}.sections.impactCategories`),
      riskAnalysis: t(`${p}.sections.riskAnalysis`),
      effortEstimation: t(`${p}.sections.effortEstimation`),
      confidence: t(`${p}.sections.confidence`),
      decisionSupport: t(`${p}.sections.decisionSupport`),
      executiveSummary: t(`${p}.sections.executiveSummary`),
      rollback: t(`${p}.sections.rollback`),
      affectedSystems: t(`${p}.sections.affectedSystems`),
      approvalChain: t(`${p}.sections.approvalChain`),
      auditPreview: t(`${p}.sections.auditPreview`),
      relatedActions: t(`${p}.sections.relatedActions`),
      timeline: t(`${p}.sections.timeline`),
      postExecution: t(`${p}.sections.postExecution`),
      learningLoop: t(`${p}.sections.learningLoop`),
      knowledgeCenter: t(`${p}.sections.knowledgeCenter`),
      widgets: t(`${p}.sections.widgets`),
    },
    summary: {
      status: t(`${p}.summary.status`),
      recommendedBy: t(`${p}.summary.recommendedBy`),
      priority: t(`${p}.summary.priority`),
      impactScore: t(`${p}.summary.impactScore`),
    },
    expectedOutcome: {
      intendedOutcome: t(`${p}.expectedOutcome.intendedOutcome`),
      recommendationRationale: t(`${p}.expectedOutcome.recommendationRationale`),
      estimatedValueCreation: t(`${p}.expectedOutcome.estimatedValueCreation`),
      strategicAlignment: t(`${p}.expectedOutcome.strategicAlignment`),
    },
    businessImpact: {
      expectedBenefits: t(`${p}.businessImpact.expectedBenefits`),
      timeSavings: t(`${p}.businessImpact.timeSavings`),
      affectedTeams: t(`${p}.businessImpact.affectedTeams`),
      customerImpact: t(`${p}.businessImpact.customerImpact`),
    },
    impactCategories: {
      revenue: t(`${p}.impactCategories.revenue`),
      customer_satisfaction: t(`${p}.impactCategories.customerSatisfaction`),
      employee_experience: t(`${p}.impactCategories.employeeExperience`),
      operational_efficiency: t(`${p}.impactCategories.operationalEfficiency`),
      compliance: t(`${p}.impactCategories.compliance`),
      strategic_goals: t(`${p}.impactCategories.strategicGoals`),
      growth: t(`${p}.impactCategories.growth`),
      risk_reduction: t(`${p}.impactCategories.riskReduction`),
    },
    impactLevels: {
      none: t(`${p}.impactLevels.none`),
      low: t(`${p}.impactLevels.low`),
      moderate: t(`${p}.impactLevels.moderate`),
      high: t(`${p}.impactLevels.high`),
    },
    riskAnalysis: {
      riskLevel: t(`${p}.riskAnalysis.riskLevel`),
      riskRationale: t(`${p}.riskAnalysis.riskRationale`),
      sideEffects: t(`${p}.riskAnalysis.sideEffects`),
      mitigation: t(`${p}.riskAnalysis.mitigation`),
    },
    effortEstimation: {
      title: t(`${p}.effortEstimation.title`),
      requiredStakeholders: t(`${p}.effortEstimation.requiredStakeholders`),
      requiredApprovals: t(`${p}.effortEstimation.requiredApprovals`),
      requiredIntegrations: t(`${p}.effortEstimation.requiredIntegrations`),
      units: {
        minutes: t(`${p}.effortEstimation.units.minutes`),
        hours: t(`${p}.effortEstimation.units.hours`),
        days: t(`${p}.effortEstimation.units.days`),
        weeks: t(`${p}.effortEstimation.units.weeks`),
      },
    },
    confidence: {
      score: t(`${p}.confidence.score`),
      level: t(`${p}.confidence.level`),
      reasoning: t(`${p}.confidence.reasoning`),
      historicalSuccess: t(`${p}.confidence.historicalSuccess`),
      operatingConditions: t(`${p}.confidence.operatingConditions`),
      levels: {
        very_low: t(`${p}.confidence.levels.veryLow`),
        low: t(`${p}.confidence.levels.low`),
        moderate: t(`${p}.confidence.levels.moderate`),
        high: t(`${p}.confidence.levels.high`),
        very_high: t(`${p}.confidence.levels.veryHigh`),
      },
      factors: {
        organizational_data: t(`${p}.confidence.factors.organizationalData`),
        historical_outcomes: t(`${p}.confidence.factors.historicalOutcomes`),
        similar_actions: t(`${p}.confidence.factors.similarActions`),
        knowledge_center: t(`${p}.confidence.factors.knowledgeCenter`),
        human_validation: t(`${p}.confidence.factors.humanValidation`),
      },
    },
    decisionSupport: {
      whyImportantNow: t(`${p}.decisionSupport.whyImportantNow`),
      ifDelayed: t(`${p}.decisionSupport.ifDelayed`),
      ifIgnored: t(`${p}.decisionSupport.ifIgnored`),
      whoInvolved: t(`${p}.decisionSupport.whoInvolved`),
    },
    executiveSummary: {
      situation: t(`${p}.executiveSummary.situation`),
      recommendation: t(`${p}.executiveSummary.recommendation`),
      expectedBenefits: t(`${p}.executiveSummary.expectedBenefits`),
      risks: t(`${p}.executiveSummary.risks`),
      requiredActions: t(`${p}.executiveSummary.requiredActions`),
      confidenceScore: t(`${p}.executiveSummary.confidenceScore`),
    },
    learningLoop: {
      intro: t(`${p}.learningLoop.intro`),
      actualOutcome: t(`${p}.learningLoop.actualOutcome`),
      userSatisfaction: t(`${p}.learningLoop.userSatisfaction`),
      goalAchievement: t(`${p}.learningLoop.goalAchievement`),
      lessonsLearned: t(`${p}.learningLoop.lessonsLearned`),
      submit: t(`${p}.learningLoop.submit`),
      submitted: t(`${p}.learningLoop.submitted`),
      satisfaction: {
        very_dissatisfied: t(`${p}.learningLoop.satisfaction.veryDissatisfied`),
        dissatisfied: t(`${p}.learningLoop.satisfaction.dissatisfied`),
        neutral: t(`${p}.learningLoop.satisfaction.neutral`),
        satisfied: t(`${p}.learningLoop.satisfaction.satisfied`),
        very_satisfied: t(`${p}.learningLoop.satisfaction.verySatisfied`),
      },
      achievement: {
        not_achieved: t(`${p}.learningLoop.achievement.notAchieved`),
        partially: t(`${p}.learningLoop.achievement.partially`),
        mostly: t(`${p}.learningLoop.achievement.mostly`),
        fully: t(`${p}.learningLoop.achievement.fully`),
      },
    },
    widgets: {
      recommendedByImpact: t(`${p}.widgets.recommendedByImpact`),
      highImpactOpportunities: t(`${p}.widgets.highImpactOpportunities`),
      highRiskRecommendations: t(`${p}.widgets.highRiskRecommendations`),
      recentlyValidatedOutcomes: t(`${p}.widgets.recentlyValidatedOutcomes`),
      awaitingReview: t(`${p}.widgets.awaitingReview`),
      executiveApproval: t(`${p}.widgets.executiveApproval`),
      empty: t(`${p}.widgets.empty`),
      viewAction: t(`${p}.widgets.viewAction`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIsImpactAnalysis: t(`${p}.faq.whatIsImpactAnalysis`),
      whatIsImpactAnalysisAnswer: t(`${p}.faq.whatIsImpactAnalysisAnswer`),
      howEstimateOutcomes: t(`${p}.faq.howEstimateOutcomes`),
      howEstimateOutcomesAnswer: t(`${p}.faq.howEstimateOutcomesAnswer`),
      canPredictFuture: t(`${p}.faq.canPredictFuture`),
      canPredictFutureAnswer: t(`${p}.faq.canPredictFutureAnswer`),
      confidenceScores: t(`${p}.faq.confidenceScores`),
      confidenceScoresAnswer: t(`${p}.faq.confidenceScoresAnswer`),
      whoResponsible: t(`${p}.faq.whoResponsible`),
      whoResponsibleAnswer: t(`${p}.faq.whoResponsibleAnswer`),
    },
    rollback: {
      available: t(`${p}.rollback.available`),
      notAvailable: t(`${p}.rollback.notAvailable`),
      recoveryTime: t(`${p}.rollback.recoveryTime`),
      steps: t(`${p}.rollback.steps`),
      manualRequired: t(`${p}.rollback.manualRequired`),
    },
    approvalChain: {
      requestedBy: t(`${p}.approvalChain.requestedBy`),
      requiresApprovalFrom: t(`${p}.approvalChain.requiresApprovalFrom`),
      escalationPath: t(`${p}.approvalChain.escalationPath`),
    },
    auditPreview: {
      intro: t(`${p}.auditPreview.intro`),
      approvalEvent: t(`${p}.auditPreview.approvalEvent`),
      executionEvent: t(`${p}.auditPreview.executionEvent`),
      outcomeEvent: t(`${p}.auditPreview.outcomeEvent`),
      rollbackEvent: t(`${p}.auditPreview.rollbackEvent`),
    },
    relatedActions: {
      similarExecuted: t(`${p}.relatedActions.similarExecuted`),
      averageSuccess: t(`${p}.relatedActions.averageSuccess`),
    },
    timeline: {
      review: t(`${p}.timeline.review`),
      approve: t(`${p}.timeline.approve`),
      execute: t(`${p}.timeline.execute`),
      verify: t(`${p}.timeline.verify`),
      monitor: t(`${p}.timeline.monitor`),
      close: t(`${p}.timeline.close`),
    },
    timelineStatus: {
      pending: t(`${p}.timelineStatus.pending`),
      current: t(`${p}.timelineStatus.current`),
      complete: t(`${p}.timelineStatus.complete`),
      blocked: t(`${p}.timelineStatus.blocked`),
    },
    postExecution: {
      result: t(`${p}.postExecution.result`),
      executionTime: t(`${p}.postExecution.executionTime`),
      unexpectedEvents: t(`${p}.postExecution.unexpectedEvents`),
      businessOutcome: t(`${p}.postExecution.businessOutcome`),
      successful: t(`${p}.postExecution.successful`),
      failed: t(`${p}.postExecution.failed`),
      positive: t(`${p}.postExecution.positive`),
      reviewRequired: t(`${p}.postExecution.reviewRequired`),
      none: t(`${p}.postExecution.none`),
    },
    categories: {
      support: t(`${p}.categories.support`),
      automation: t(`${p}.categories.automation`),
      billing: t(`${p}.categories.billing`),
      installation: t(`${p}.categories.installation`),
      governance: t(`${p}.categories.governance`),
      customer: t(`${p}.categories.customer`),
      growth_partner: t(`${p}.categories.growthPartner`),
      workflow_recovery: t(`${p}.categories.workflowRecovery`),
    },
    empty: t(`${p}.empty`),
    emptyMonitoring: t(`${p}.emptyMonitoring`),
    principle: t(`${p}.principle`),
    actions: {
      approve: t(`${p}.actions.approve`),
      reject: t(`${p}.actions.reject`),
      execute: t(`${p}.actions.execute`),
      back: t(`${p}.actions.back`),
    },
    priority: {
      low: t(`${p}.priority.low`),
      medium: t(`${p}.priority.medium`),
      high: t(`${p}.priority.high`),
      critical: t(`${p}.priority.critical`),
    },
    customerImpact: {
      Positive: t(`${p}.customerImpact.positive`),
      "Monitor closely": t(`${p}.customerImpact.monitorClosely`),
      positive: t(`${p}.customerImpact.positive`),
      "monitor closely": t(`${p}.customerImpact.monitorClosely`),
    },
  };
}
