import type { Translator } from "@/lib/i18n/translate";

export function buildRiskOperationsLabels(t: Translator) {
  const p = "customerApp.riskOperations";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    riskRegister: t(`${p}.riskRegister`),
    assessments: t(`${p}.assessments`),
    mitigationPlans: t(`${p}.mitigationPlans`),
    businessContinuity: t(`${p}.businessContinuity`),
    incidents: t(`${p}.incidents`),
    dependencies: t(`${p}.dependencies`),
    reports: t(`${p}.reports`),
    executiveRisk: t(`${p}.executiveRisk`),
    overallRiskScore: t(`${p}.overallRiskScore`),
    openRisks: t(`${p}.openRisks`),
    criticalRisks: t(`${p}.criticalRisks`),
    elevatedRisks: t(`${p}.elevatedRisks`),
    openAssessments: t(`${p}.openAssessments`),
    openMitigations: t(`${p}.openMitigations`),
    overdueMitigations: t(`${p}.overdueMitigations`),
    activeContinuityPlans: t(`${p}.activeContinuityPlans`),
    criticalDependencies: t(`${p}.criticalDependencies`),
    highVendorRisk: t(`${p}.highVendorRisk`),
    openIncidents: t(`${p}.openIncidents`),
    governanceHealth: t(`${p}.governanceHealth`),
    createRisk: t(`${p}.createRisk`),
    escalateRisk: t(`${p}.escalateRisk`),
    createAssessment: t(`${p}.createAssessment`),
    createMitigation: t(`${p}.createMitigation`),
    completeMitigation: t(`${p}.completeMitigation`),
    createContinuityPlan: t(`${p}.createContinuityPlan`),
    activateContinuityPlan: t(`${p}.activateContinuityPlan`),
    addVendorDependency: t(`${p}.addVendorDependency`),
    addDependency: t(`${p}.addDependency`),
    declareIncident: t(`${p}.declareIncident`),
    closeIncident: t(`${p}.closeIncident`),
    riskTitle: t(`${p}.riskTitle`),
    assessmentTitle: t(`${p}.assessmentTitle`),
    continuityTitle: t(`${p}.continuityTitle`),
    vendorName: t(`${p}.vendorName`),
    dependencyName: t(`${p}.dependencyName`),
    incidentTitle: t(`${p}.incidentTitle`),
    mitigationTitle: t(`${p}.mitigationTitle`),
    noRisks: t(`${p}.noRisks`),
    noAssessments: t(`${p}.noAssessments`),
    noMitigations: t(`${p}.noMitigations`),
    noContinuityPlans: t(`${p}.noContinuityPlans`),
    noDependencies: t(`${p}.noDependencies`),
    noIncidents: t(`${p}.noIncidents`),
    emptyHint: t(`${p}.emptyHint`),
    heatMap: t(`${p}.heatMap`),
    topRisks: t(`${p}.topRisks`),
    companionInsights: t(`${p}.companionInsights`),
    governanceLink: t(`${p}.governanceLink`),
    auditLog: t(`${p}.auditLog`),
    registerTitle: t(`${p}.registerTitle`),
    continuityTitlePage: t(`${p}.continuityTitlePage`),
    save: t(`${p}.save`),
  };
}

export type RiskOperationsLabels = ReturnType<typeof buildRiskOperationsLabels>;
