import type { PrioritizationEngineLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildPrioritizationEngineLabels(t: Translator): PrioritizationEngineLabels {
  const p = "customerApp.portalStructure.prioritizationEngine";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      priorityStatus: t(`${p}.filters.priorityStatus`),
      owner: t(`${p}.filters.owner`),
      sponsor: t(`${p}.filters.sponsor`),
      alignmentMin: t(`${p}.filters.alignmentMin`),
      dueFrom: t(`${p}.filters.dueFrom`),
      dueTo: t(`${p}.filters.dueTo`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      highestPriority: t(`${p}.dashboard.highestPriority`),
      deferred: t(`${p}.dashboard.deferred`),
      capacityConflicts: t(`${p}.dashboard.capacityConflicts`),
      strategicAlignment: t(`${p}.dashboard.strategicAlignment`),
      recommendedActions: t(`${p}.dashboard.recommendedActions`),
      recentlyReprioritized: t(`${p}.dashboard.recentlyReprioritized`),
    },
    matrix: {
      title: t(`${p}.matrix.title`),
      impact: t(`${p}.matrix.impact`),
      effort: t(`${p}.matrix.effort`),
      quickWins: t(`${p}.matrix.quickWins`),
      majorProjects: t(`${p}.matrix.majorProjects`),
      fillIns: t(`${p}.matrix.fillIns`),
      reconsider: t(`${p}.matrix.reconsider`),
    },
    form: {
      createTitle: t(`${p}.form.createTitle`),
      title: t(`${p}.form.title`),
      description: t(`${p}.form.description`),
      category: t(`${p}.form.category`),
      dueDate: t(`${p}.form.dueDate`),
      notes: t(`${p}.form.notes`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
    },
    card: {
      owner: t(`${p}.card.owner`),
      sponsor: t(`${p}.card.sponsor`),
      alignment: t(`${p}.card.alignment`),
      impact: t(`${p}.card.impact`),
      urgency: t(`${p}.card.urgency`),
      composite: t(`${p}.card.composite`),
      quadrant: t(`${p}.card.quadrant`),
      dueDate: t(`${p}.card.dueDate`),
    },
    detail: {
      overview: t(`${p}.detail.overview`),
      scoringBreakdown: t(`${p}.detail.scoringBreakdown`),
      strategicAlignment: t(`${p}.detail.strategicAlignment`),
      impact: t(`${p}.detail.impact`),
      urgency: t(`${p}.detail.urgency`),
      effort: t(`${p}.detail.effort`),
      capacity: t(`${p}.detail.capacity`),
      capacityConsiderations: t(`${p}.detail.capacityConsiderations`),
      dependencies: t(`${p}.detail.dependencies`),
      relatedGoals: t(`${p}.detail.relatedGoals`),
      relatedFollowUps: t(`${p}.detail.relatedFollowUps`),
      relatedRisks: t(`${p}.detail.relatedRisks`),
      relatedStrategicInitiatives: t(`${p}.detail.relatedStrategicInitiatives`),
      recommendationHistory: t(`${p}.detail.recommendationHistory`),
      activityTimeline: t(`${p}.detail.activityTimeline`),
      audit: t(`${p}.detail.audit`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
      score: t(`${p}.detail.score`),
      scored: t(`${p}.detail.scored`),
      recommendations: t(`${p}.detail.recommendations`),
      priorityStatus: t(`${p}.detail.priorityStatus`),
      notes: t(`${p}.detail.notes`),
    },
    categories: {
      strategic_initiative: t(`${p}.categories.strategicInitiative`),
      operational_improvement: t(`${p}.categories.operationalImprovement`),
      customer_initiative: t(`${p}.categories.customerInitiative`),
      technology_initiative: t(`${p}.categories.technologyInitiative`),
      risk_mitigation: t(`${p}.categories.riskMitigation`),
      compliance_requirement: t(`${p}.categories.complianceRequirement`),
      revenue_opportunity: t(`${p}.categories.revenueOpportunity`),
      workforce_initiative: t(`${p}.categories.workforceInitiative`),
      innovation_opportunity: t(`${p}.categories.innovationOpportunity`),
      custom_category: t(`${p}.categories.customCategory`),
    },
    priorityStatuses: {
      under_evaluation: t(`${p}.priorityStatuses.underEvaluation`),
      recommended: t(`${p}.priorityStatuses.recommended`),
      high_priority: t(`${p}.priorityStatuses.highPriority`),
      medium_priority: t(`${p}.priorityStatuses.mediumPriority`),
      low_priority: t(`${p}.priorityStatuses.lowPriority`),
      deferred: t(`${p}.priorityStatuses.deferred`),
      completed: t(`${p}.priorityStatuses.completed`),
    },
    quadrants: {
      quick_wins: t(`${p}.quadrants.quickWins`),
      major_projects: t(`${p}.quadrants.majorProjects`),
      fill_ins: t(`${p}.quadrants.fillIns`),
      reconsider: t(`${p}.quadrants.reconsider`),
    },
    recommendations: {
      elevateStrategic: t(`${p}.recommendations.elevateStrategic`),
      reconsiderLowValue: t(`${p}.recommendations.reconsiderLowValue`),
      addressUrgentCustomer: t(`${p}.recommendations.addressUrgentCustomer`),
      deferOverCapacity: t(`${p}.recommendations.deferOverCapacity`),
      reviewConflicts: t(`${p}.recommendations.reviewConflicts`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      canChange: t(`${p}.faq.canChange`),
      canChangeAnswer: t(`${p}.faq.canChangeAnswer`),
      autoDecide: t(`${p}.faq.autoDecide`),
      autoDecideAnswer: t(`${p}.faq.autoDecideAnswer`),
    },
  };
}
