import type { Translator } from "@/lib/i18n/translate";
import { PLATFORM_CONTROL_PLANE_IA } from "./information-architecture";
import { PLATFORM_EXCEPTION_DEFINITIONS } from "./exceptions";

export function buildPlatformControlPlaneLabels(t: Translator) {
  return {
    title: t("platform.controlPlane.title"),
    subtitle: t("platform.controlPlane.subtitle"),
    principle: t("platform.controlPlane.principle"),
    openSurface: t("platform.controlPlane.openSurface"),
    readiness: {
      production: t("platform.controlPlane.readiness.production"),
      engine: t("platform.controlPlane.readiness.engine"),
      hub: t("platform.controlPlane.readiness.hub"),
      planned: t("platform.controlPlane.readiness.planned"),
      stub: t("platform.controlPlane.readiness.stub"),
    },
    metrics: {
      noData: t("platform.controlPlane.metrics.noData"),
      notConnected: t("platform.controlPlane.metrics.notConnected"),
      updateFailed: t("platform.controlPlane.metrics.updateFailed"),
      freshness: t("platform.controlPlane.metrics.freshness"),
      partial: t("platform.controlPlane.metrics.partial"),
      organizationsTotal: t("platform.controlPlane.metrics.organizationsTotal"),
      activeSubscriptions: t("platform.controlPlane.metrics.activeSubscriptions"),
      requiringAttention: t("platform.controlPlane.metrics.requiringAttention"),
      openSupport: t("platform.controlPlane.metrics.openSupport"),
      paymentPastDue: t("platform.controlPlane.metrics.paymentPastDue"),
      outstandingInvoices: t("platform.controlPlane.metrics.outstandingInvoices"),
      failedPayments: t("platform.controlPlane.metrics.failedPayments"),
      mrr: t("platform.controlPlane.metrics.mrr"),
      activePartners: t("platform.controlPlane.metrics.activePartners"),
      earnedCommission: t("platform.controlPlane.metrics.earnedCommission"),
      pendingPartnerInvoices: t("platform.controlPlane.metrics.pendingPartnerInvoices"),
      systemHealth: t("platform.controlPlane.metrics.systemHealth"),
      openIncidents: t("platform.controlPlane.metrics.openIncidents"),
      pendingApprovals: t("platform.controlPlane.metrics.pendingApprovals"),
      drillDown: t("platform.controlPlane.metrics.drillDown"),
      source: t("platform.controlPlane.metrics.source"),
    },
    health: {
      healthy: t("platform.controlPlane.health.healthy"),
      degraded: t("platform.controlPlane.health.degraded"),
      critical: t("platform.controlPlane.health.critical"),
      unknown: t("platform.controlPlane.health.unknown"),
      noSource: t("platform.controlPlane.health.noSource"),
    },
    partnersHub: {
      title: t("platform.controlPlane.partnersHub.title"),
      subtitle: t("platform.controlPlane.partnersHub.subtitle"),
      attribution: t("platform.controlPlane.partnersHub.attribution"),
      commissions: t("platform.controlPlane.partnersHub.commissions"),
      settlement: t("platform.controlPlane.partnersHub.settlement"),
      settlementNote: t("platform.controlPlane.partnersHub.settlementNote"),
      noPayoutHere: t("platform.controlPlane.partnersHub.noPayoutHere"),
    },
    settlementOps: {
      title: t("platform.controlPlane.settlementOps.title"),
      subtitle: t("platform.controlPlane.settlementOps.subtitle"),
      empty: t("platform.controlPlane.settlementOps.empty"),
      error: t("platform.controlPlane.settlementOps.error"),
      partial: t("platform.controlPlane.settlementOps.partial"),
      freshness: t("platform.controlPlane.settlementOps.freshness"),
      filters: t("platform.controlPlane.settlementOps.filters"),
      searchPlaceholder: t("platform.controlPlane.settlementOps.searchPlaceholder"),
      noMutations: t("platform.controlPlane.settlementOps.noMutations"),
      discrepanciesTitle: t("platform.controlPlane.settlementOps.discrepanciesTitle"),
      discrepanciesSubtitle: t("platform.controlPlane.settlementOps.discrepanciesSubtitle"),
      discrepanciesEmpty: t("platform.controlPlane.settlementOps.discrepanciesEmpty"),
      columns: {
        partner: t("platform.controlPlane.settlementOps.columns.partner"),
        period: t("platform.controlPlane.settlementOps.columns.period"),
        commissionBasis: t("platform.controlPlane.settlementOps.columns.commissionBasis"),
        qualified: t("platform.controlPlane.settlementOps.columns.qualified"),
        earned: t("platform.controlPlane.settlementOps.columns.earned"),
        approved: t("platform.controlPlane.settlementOps.columns.approved"),
        invoiceBasis: t("platform.controlPlane.settlementOps.columns.invoiceBasis"),
        invoice: t("platform.controlPlane.settlementOps.columns.invoice"),
        matching: t("platform.controlPlane.settlementOps.columns.matching"),
        discrepancy: t("platform.controlPlane.settlementOps.columns.discrepancy"),
        approval: t("platform.controlPlane.settlementOps.columns.approval"),
        payout: t("platform.controlPlane.settlementOps.columns.payout"),
        accounting: t("platform.controlPlane.settlementOps.columns.accounting"),
        updated: t("platform.controlPlane.settlementOps.columns.updated"),
        owner: t("platform.controlPlane.settlementOps.columns.owner"),
        nextAction: t("platform.controlPlane.settlementOps.columns.nextAction"),
        severity: t("platform.controlPlane.settlementOps.columns.severity"),
        expected: t("platform.controlPlane.settlementOps.columns.expected"),
        actual: t("platform.controlPlane.settlementOps.columns.actual"),
        difference: t("platform.controlPlane.settlementOps.columns.difference"),
        reason: t("platform.controlPlane.settlementOps.columns.reason"),
        dueDate: t("platform.controlPlane.settlementOps.columns.dueDate"),
        status: t("platform.controlPlane.settlementOps.columns.status"),
      },
    },
    search: {
      navigationSearch: t("platform.controlPlane.search.navigationSearch"),
      navigationSearchHint: t("platform.controlPlane.search.navigationSearchHint"),
      entitySearch: t("platform.controlPlane.search.entitySearch"),
      entitySearchPlanned: t("platform.controlPlane.search.entitySearchPlanned"),
      entitySearchGap: t("platform.controlPlane.search.entitySearchGap"),
    },
    financeBoundaries: {
      subscriptionNote: t("platform.controlPlane.financeBoundaries.subscriptionNote"),
      invoiceNote: t("platform.controlPlane.financeBoundaries.invoiceNote"),
      paidNote: t("platform.controlPlane.financeBoundaries.paidNote"),
      outstandingSource: t("platform.controlPlane.financeBoundaries.outstandingSource"),
    },
    exceptions: {
      title: t("platform.controlPlane.exceptions.title"),
      subtitle: t("platform.controlPlane.exceptions.subtitle"),
      open: t("platform.controlPlane.exceptions.open"),
      severity: {
        info: t("platform.controlPlane.exceptions.severity.info"),
        attention: t("platform.controlPlane.exceptions.severity.attention"),
        critical: t("platform.controlPlane.exceptions.severity.critical"),
      },
      items: Object.fromEntries(
        PLATFORM_EXCEPTION_DEFINITIONS.map((item) => [
          item.id,
          {
            label: t(item.labelKey),
            nextAction: t(item.nextActionKey),
          },
        ]),
      ) as Record<string, { label: string; nextAction: string }>,
    },
    sections: PLATFORM_CONTROL_PLANE_IA.map((section) => ({
      id: section.id,
      label: t(section.labelKey),
      description: t(section.descriptionKey),
    })),
  };
}

export type PlatformControlPlaneLabels = ReturnType<typeof buildPlatformControlPlaneLabels>;
