import type { ExecutionCoordinationLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildExecutionCoordinationLabels(t: Translator): ExecutionCoordinationLabels {
  const p = "customerApp.actionCenter.executionCoordination";
  return {
    centerTitle: t(`${p}.centerTitle`),
    centerSubtitle: t(`${p}.centerSubtitle`),
    tabImpact: t(`${p}.tabImpact`),
    tabApprovals: t(`${p}.tabApprovals`),
    tabExecution: t(`${p}.tabExecution`),
    humanOversight: t(`${p}.humanOversight`),
    sections: {
      lifecycle: t(`${p}.sections.lifecycle`),
      ownership: t(`${p}.sections.ownership`),
      dependencies: t(`${p}.sections.dependencies`),
      blockers: t(`${p}.sections.blockers`),
      priority: t(`${p}.sections.priority`),
      timeline: t(`${p}.sections.timeline`),
      confidence: t(`${p}.sections.confidence`),
      collaboration: t(`${p}.sections.collaboration`),
      learning: t(`${p}.sections.learning`),
      executive: t(`${p}.sections.executive`),
      widgets: t(`${p}.sections.widgets`),
      audit: t(`${p}.sections.audit`),
      knowledgeCenter: t(`${p}.sections.knowledgeCenter`),
    },
    lifecycle: {
      stages: {
        recommended: t(`${p}.lifecycle.stages.recommended`),
        under_review: t(`${p}.lifecycle.stages.underReview`),
        approved: t(`${p}.lifecycle.stages.approved`),
        assigned: t(`${p}.lifecycle.stages.assigned`),
        in_progress: t(`${p}.lifecycle.stages.inProgress`),
        waiting: t(`${p}.lifecycle.stages.waiting`),
        blocked: t(`${p}.lifecycle.stages.blocked`),
        completed: t(`${p}.lifecycle.stages.completed`),
        cancelled: t(`${p}.lifecycle.stages.cancelled`),
      },
      stepStatus: {
        pending: t(`${p}.lifecycle.stepStatus.pending`),
        current: t(`${p}.lifecycle.stepStatus.current`),
        complete: t(`${p}.lifecycle.stepStatus.complete`),
        blocked: t(`${p}.lifecycle.stepStatus.blocked`),
      },
    },
    ownership: {
      primary: t(`${p}.ownership.primary`),
      secondary: t(`${p}.ownership.secondary`),
      contributors: t(`${p}.ownership.contributors`),
      executiveSponsor: t(`${p}.ownership.executiveSponsor`),
      history: t(`${p}.ownership.history`),
      responsibilities: t(`${p}.ownership.responsibilities`),
    },
    dependencies: {
      title: t(`${p}.dependencies.title`),
      statuses: {
        ready: t(`${p}.dependencies.statuses.ready`),
        waiting_for_dependency: t(`${p}.dependencies.statuses.waitingForDependency`),
        dependency_delayed: t(`${p}.dependencies.statuses.dependencyDelayed`),
        dependency_resolved: t(`${p}.dependencies.statuses.dependencyResolved`),
      },
      types: {
        action: t(`${p}.dependencies.types.action`),
        approval: t(`${p}.dependencies.types.approval`),
        external_system: t(`${p}.dependencies.types.externalSystem`),
        customer_decision: t(`${p}.dependencies.types.customerDecision`),
        compliance: t(`${p}.dependencies.types.compliance`),
      },
    },
    blockers: {
      title: t(`${p}.blockers.title`),
      register: t(`${p}.blockers.register`),
      category: t(`${p}.blockers.category`),
      description: t(`${p}.blockers.description`),
      severity: t(`${p}.blockers.severity`),
      owner: t(`${p}.blockers.owner`),
      resolutionPlan: t(`${p}.blockers.resolutionPlan`),
      targetDate: t(`${p}.blockers.targetDate`),
      submit: t(`${p}.blockers.submit`),
      categories: {
        resource_constraints: t(`${p}.blockers.categories.resourceConstraints`),
        approval_delays: t(`${p}.blockers.categories.approvalDelays`),
        technical_issues: t(`${p}.blockers.categories.technicalIssues`),
        vendor_delays: t(`${p}.blockers.categories.vendorDelays`),
        missing_information: t(`${p}.blockers.categories.missingInformation`),
        policy_restrictions: t(`${p}.blockers.categories.policyRestrictions`),
      },
    },
    priority: {
      level: t(`${p}.priority.level`),
      levels: {
        critical: t(`${p}.priority.levels.critical`),
        high: t(`${p}.priority.levels.high`),
        medium: t(`${p}.priority.levels.medium`),
        low: t(`${p}.priority.levels.low`),
        optional: t(`${p}.priority.levels.optional`),
      },
      recommendation: t(`${p}.priority.recommendation`),
    },
    timeline: {
      plannedStart: t(`${p}.timeline.plannedStart`),
      actualStart: t(`${p}.timeline.actualStart`),
      estimatedCompletion: t(`${p}.timeline.estimatedCompletion`),
      actualCompletion: t(`${p}.timeline.actualCompletion`),
      milestones: t(`${p}.timeline.milestones`),
      deviation: t(`${p}.timeline.deviation`),
    },
    confidence: {
      score: t(`${p}.confidence.score`),
      level: t(`${p}.confidence.level`),
      disclaimer: t(`${p}.confidence.disclaimer`),
      levels: {
        very_low: t(`${p}.confidence.levels.veryLow`),
        low: t(`${p}.confidence.levels.low`),
        moderate: t(`${p}.confidence.levels.moderate`),
        high: t(`${p}.confidence.levels.high`),
        very_high: t(`${p}.confidence.levels.veryHigh`),
      },
      factors: {
        resource_availability: t(`${p}.confidence.factors.resourceAvailability`),
        historical_completion: t(`${p}.confidence.factors.historicalCompletion`),
        dependency_stability: t(`${p}.confidence.factors.dependencyStability`),
        complexity: t(`${p}.confidence.factors.complexity`),
        team_workload: t(`${p}.confidence.factors.teamWorkload`),
      },
    },
    collaboration: {
      addUpdate: t(`${p}.collaboration.addUpdate`),
      addNote: t(`${p}.collaboration.addNote`),
      requestAssistance: t(`${p}.collaboration.requestAssistance`),
      mentionStakeholder: t(`${p}.collaboration.mentionStakeholder`),
      submit: t(`${p}.collaboration.submit`),
      placeholder: t(`${p}.collaboration.placeholder`),
    },
    learning: {
      intro: t(`${p}.learning.intro`),
      expectedOutcome: t(`${p}.learning.expectedOutcome`),
      actualOutcome: t(`${p}.learning.actualOutcome`),
      timelineAccuracy: t(`${p}.learning.timelineAccuracy`),
      blockersEncountered: t(`${p}.learning.blockersEncountered`),
      lessonsLearned: t(`${p}.learning.lessonsLearned`),
      improvements: t(`${p}.learning.improvements`),
      submit: t(`${p}.learning.submit`),
      submitted: t(`${p}.learning.submitted`),
    },
    executive: {
      healthScore: t(`${p}.executive.healthScore`),
      completionRate: t(`${p}.executive.completionRate`),
      blocked: t(`${p}.executive.blocked`),
      overdue: t(`${p}.executive.overdue`),
      strategicProgress: t(`${p}.executive.strategicProgress`),
    },
    widgets: {
      startingToday: t(`${p}.widgets.startingToday`),
      inProgress: t(`${p}.widgets.inProgress`),
      blocked: t(`${p}.widgets.blocked`),
      awaitingDependencies: t(`${p}.widgets.awaitingDependencies`),
      upcomingDeadlines: t(`${p}.widgets.upcomingDeadlines`),
      completed: t(`${p}.widgets.completed`),
      executivePriority: t(`${p}.widgets.executivePriority`),
      empty: t(`${p}.widgets.empty`),
      viewAction: t(`${p}.widgets.viewAction`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIsCoordination: t(`${p}.faq.whatIsCoordination`),
      whatIsCoordinationAnswer: t(`${p}.faq.whatIsCoordinationAnswer`),
      howTrackProgress: t(`${p}.faq.howTrackProgress`),
      howTrackProgressAnswer: t(`${p}.faq.howTrackProgressAnswer`),
      autoExecute: t(`${p}.faq.autoExecute`),
      autoExecuteAnswer: t(`${p}.faq.autoExecuteAnswer`),
      whenBlocked: t(`${p}.faq.whenBlocked`),
      whenBlockedAnswer: t(`${p}.faq.whenBlockedAnswer`),
      confidenceScores: t(`${p}.faq.confidenceScores`),
      confidenceScoresAnswer: t(`${p}.faq.confidenceScoresAnswer`),
    },
    empty: t(`${p}.empty`),
    principle: t(`${p}.principle`),
    actions: { back: t(`${p}.actions.back`) },
  };
}
