import type { StrategyExecutionLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildStrategyExecutionLabels(t: Translator): StrategyExecutionLabels {
  const p = "customerApp.portalStructure.strategyExecution";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    filters: {
      search: t(`${p}.filters.search`),
      category: t(`${p}.filters.category`),
      status: t(`${p}.filters.status`),
      owner: t(`${p}.filters.owner`),
      sponsor: t(`${p}.filters.sponsor`),
      importance: t(`${p}.filters.importance`),
      targetFrom: t(`${p}.filters.targetFrom`),
      targetTo: t(`${p}.filters.targetTo`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      active: t(`${p}.dashboard.active`),
      requiringAttention: t(`${p}.dashboard.requiringAttention`),
      progressOverview: t(`${p}.dashboard.progressOverview`),
      upcomingMilestones: t(`${p}.dashboard.upcomingMilestones`),
      recentlyCompleted: t(`${p}.dashboard.recentlyCompleted`),
      executionTrends: t(`${p}.dashboard.executionTrends`),
    },
    form: {
      createTitle: t(`${p}.form.createTitle`),
      title: t(`${p}.form.title`),
      description: t(`${p}.form.description`),
      category: t(`${p}.form.category`),
      importance: t(`${p}.form.importance`),
      successDefinition: t(`${p}.form.successDefinition`),
      targetDate: t(`${p}.form.targetDate`),
      notes: t(`${p}.form.notes`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
    },
    card: {
      owner: t(`${p}.card.owner`),
      sponsor: t(`${p}.card.sponsor`),
      importance: t(`${p}.card.importance`),
      progress: t(`${p}.card.progress`),
      targetDate: t(`${p}.card.targetDate`),
      view: t(`${p}.card.view`),
    },
    detail: {
      overview: t(`${p}.detail.overview`),
      ownership: t(`${p}.detail.ownership`),
      progressTracking: t(`${p}.detail.progressTracking`),
      successDefinition: t(`${p}.detail.successDefinition`),
      relatedGoals: t(`${p}.detail.relatedGoals`),
      relatedDecisions: t(`${p}.detail.relatedDecisions`),
      relatedFollowUps: t(`${p}.detail.relatedFollowUps`),
      relatedRisks: t(`${p}.detail.relatedRisks`),
      milestoneTimeline: t(`${p}.detail.milestoneTimeline`),
      audit: t(`${p}.detail.audit`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
      recommendations: t(`${p}.detail.recommendations`),
      executionInsights: t(`${p}.detail.executionInsights`),
      addMilestone: t(`${p}.detail.addMilestone`),
      milestoneTitle: t(`${p}.detail.milestoneTitle`),
      milestoneTarget: t(`${p}.detail.milestoneTarget`),
      milestoneNotes: t(`${p}.detail.milestoneNotes`),
      milestoneSubmit: t(`${p}.detail.milestoneSubmit`),
    },
    categories: {
      growth_strategy: t(`${p}.categories.growthStrategy`),
      customer_strategy: t(`${p}.categories.customerStrategy`),
      operational_excellence: t(`${p}.categories.operationalExcellence`),
      digital_transformation: t(`${p}.categories.digitalTransformation`),
      innovation_strategy: t(`${p}.categories.innovationStrategy`),
      employee_strategy: t(`${p}.categories.employeeStrategy`),
      financial_strategy: t(`${p}.categories.financialStrategy`),
      risk_strategy: t(`${p}.categories.riskStrategy`),
      sustainability_strategy: t(`${p}.categories.sustainabilityStrategy`),
      custom_strategic_theme: t(`${p}.categories.customStrategicTheme`),
    },
    statuses: {
      planning: t(`${p}.statuses.planning`),
      active: t(`${p}.statuses.active`),
      on_track: t(`${p}.statuses.onTrack`),
      needs_attention: t(`${p}.statuses.needsAttention`),
      delayed: t(`${p}.statuses.delayed`),
      completed: t(`${p}.statuses.completed`),
      archived: t(`${p}.statuses.archived`),
    },
    importanceLevels: {
      important: t(`${p}.importanceLevels.important`),
      high_priority: t(`${p}.importanceLevels.highPriority`),
      critical_priority: t(`${p}.importanceLevels.criticalPriority`),
      transformational: t(`${p}.importanceLevels.transformational`),
    },
    milestoneStatuses: {
      pending: t(`${p}.milestoneStatuses.pending`),
      in_progress: t(`${p}.milestoneStatuses.inProgress`),
      completed: t(`${p}.milestoneStatuses.completed`),
      missed: t(`${p}.milestoneStatuses.missed`),
      cancelled: t(`${p}.milestoneStatuses.cancelled`),
    },
    insights: {
      consistentlyDelayed: t(`${p}.insights.consistentlyDelayed`),
      resourceConflicts: t(`${p}.insights.resourceConflicts`),
      dependenciesSlowing: t(`${p}.insights.dependenciesSlowing`),
      positiveMomentum: t(`${p}.insights.positiveMomentum`),
      emergingRisks: t(`${p}.insights.emergingRisks`),
    },
    recommendations: {
      reviewDelayed: t(`${p}.recommendations.reviewDelayed`),
      assignOwnership: t(`${p}.recommendations.assignOwnership`),
      clarifySuccessCriteria: t(`${p}.recommendations.clarifySuccessCriteria`),
      reassessDependencies: t(`${p}.recommendations.reassessDependencies`),
      celebrateMilestones: t(`${p}.recommendations.celebrateMilestones`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      whyOwners: t(`${p}.faq.whyOwners`),
      whyOwnersAnswer: t(`${p}.faq.whyOwnersAnswer`),
      autoExecute: t(`${p}.faq.autoExecute`),
      autoExecuteAnswer: t(`${p}.faq.autoExecuteAnswer`),
    },
  };
}
