import type { NormalizedActionItem } from "../types";

export const UNONIGHT_PILOT_ACTIONS: NormalizedActionItem[] = [
  {
    action_key: "action.unonight.verify.pending",
    title: "Review pending verifications",
    description: "Unonight marketplace has verifications awaiting admin review.",
    source_module: "unonight",
    source_type: "pilot_action",
    action_type: "moderation",
    severity: "high",
    priority: "high",
    recommended_owner: "admin",
    action_url: "/app/approvals",
    requires_approval: true,
    rationale: "Unonight pilot: marketplace verifications require governance approval.",
  },
  {
    action_key: "action.unonight.listing.approve",
    title: "Approve marketplace listing",
    description: "A new Unonight listing is ready for moderation review.",
    source_module: "unonight",
    source_type: "pilot_action",
    action_type: "moderation",
    severity: "high",
    priority: "high",
    recommended_owner: "admin",
    action_url: "/app/approvals",
    requires_approval: true,
    rationale: "Unonight pilot: listing approval workflow.",
  },
  {
    action_key: "action.unonight.support.draft",
    title: "Review support drafts",
    description: "Support Specialist generated drafts that need human review before sending.",
    source_module: "support",
    source_type: "pilot_action",
    action_type: "support",
    severity: "medium",
    priority: "high",
    recommended_owner: "support_lead",
    action_url: "/app/support",
    requires_approval: true,
    rationale: "Unonight pilot: support draft review.",
  },
  {
    action_key: "action.unonight.quality.alert",
    title: "Resolve Quality Guardian alerts",
    description: "Frontend or image quality alerts need resolution.",
    source_module: "quality",
    source_type: "pilot_action",
    action_type: "quality",
    severity: "high",
    priority: "high",
    recommended_owner: "quality_owner",
    action_url: "/app/quality",
    requires_approval: false,
    rationale: "Unonight pilot: quality incident follow-up.",
  },
  {
    action_key: "action.unonight.knowledge.gap",
    title: "Follow up Knowledge Gaps",
    description: "Knowledge gaps detected for Unonight support topics.",
    source_module: "knowledge",
    source_type: "pilot_action",
    action_type: "knowledge",
    severity: "medium",
    priority: "medium",
    recommended_owner: "knowledge_owner",
    action_url: "/app/knowledge-center",
    requires_approval: false,
    rationale: "Unonight pilot: knowledge gap follow-up.",
  },
];
