export {
  AIPIFY_FORBIDDEN_EMAIL_DOMAINS,
  AIPIFY_INTERNAL_CUSTOMER_SLUGS,
  AIPIFY_INTERNAL_PROVISION_EMAIL,
  AIPIFY_OWNED_EMAIL_DOMAINS,
  AIPIFY_PRIMARY_EMAIL_DOMAIN,
  AIPIFY_RESERVED_EXAMPLE_DOMAINS,
  assertAuthorizedAipifyEmail,
  containsForbiddenAipifyCom,
  evaluateAipifyEmailDomain,
  evaluateCustomerContactEmail,
  extractEmailDomain,
  findForbiddenAipifyComHits,
  isForbiddenUnownedAipifyDomain,
  isInternalAipifyCustomerSlug,
  isOwnedAipifyEmailDomain,
  isReservedExampleDomain,
  isValidEmailFormat,
  normalizeEmail,
  type AipifyDomainOwnershipDecision,
  type CustomerContactEmailDecision,
} from "./policy";
