import type { CapacityWorkloadLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildCapacityWorkloadLabels(t: Translator): CapacityWorkloadLabels {
  const p = "customerApp.portalStructure.capacityWorkload";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      team: t(`${p}.filters.team`),
      category: t(`${p}.filters.category`),
      status: t(`${p}.filters.status`),
      owner: t(`${p}.filters.owner`),
      workload: t(`${p}.filters.workload`),
      trend: t(`${p}.filters.trend`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      overview: t(`${p}.dashboard.overview`),
      approachingLimits: t(`${p}.dashboard.approachingLimits`),
      balancedTeams: t(`${p}.dashboard.balancedTeams`),
      capacityTrends: t(`${p}.dashboard.capacityTrends`),
      recentChanges: t(`${p}.dashboard.recentChanges`),
      recommendedReviews: t(`${p}.dashboard.recommendedReviews`),
    },
    insights: {
      title: t(`${p}.insights.title`),
      persistentOverload: t(`${p}.insights.persistentOverload`),
      suddenIncrease: t(`${p}.insights.suddenIncrease`),
      aboveLimits: t(`${p}.insights.aboveLimits`),
      unusedCapacity: t(`${p}.insights.unusedCapacity`),
      operationalStrain: t(`${p}.insights.operationalStrain`),
      inactive: t(`${p}.insights.inactive`),
    },
    form: {
      createTitle: t(`${p}.form.createTitle`),
      title: t(`${p}.form.title`),
      team: t(`${p}.form.team`),
      category: t(`${p}.form.category`),
      currentUtilization: t(`${p}.form.currentUtilization`),
      recommendedUtilization: t(`${p}.form.recommendedUtilization`),
      trend: t(`${p}.form.trend`),
      notes: t(`${p}.form.notes`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
    },
    card: {
      owner: t(`${p}.card.owner`),
      team: t(`${p}.card.team`),
      utilization: t(`${p}.card.utilization`),
      recommended: t(`${p}.card.recommended`),
      trend: t(`${p}.card.trend`),
      workload: t(`${p}.card.workload`),
      lastUpdated: t(`${p}.card.lastUpdated`),
      view: t(`${p}.card.view`),
    },
    detail: {
      overview: t(`${p}.detail.overview`),
      trendAnalysis: t(`${p}.detail.trendAnalysis`),
      teamBreakdown: t(`${p}.detail.teamBreakdown`),
      relatedActivities: t(`${p}.detail.relatedActivities`),
      relatedFollowUps: t(`${p}.detail.relatedFollowUps`),
      followUpRecommendations: t(`${p}.detail.followUpRecommendations`),
      timeline: t(`${p}.detail.timeline`),
      audit: t(`${p}.detail.audit`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
      recommendations: t(`${p}.detail.recommendations`),
    },
    categories: {
      individual_capacity: t(`${p}.categories.individualCapacity`),
      team_capacity: t(`${p}.categories.teamCapacity`),
      department_capacity: t(`${p}.categories.departmentCapacity`),
      operational_capacity: t(`${p}.categories.operationalCapacity`),
      leadership_capacity: t(`${p}.categories.leadershipCapacity`),
      support_capacity: t(`${p}.categories.supportCapacity`),
      project_capacity: t(`${p}.categories.projectCapacity`),
      seasonal_capacity: t(`${p}.categories.seasonalCapacity`),
      growth_capacity: t(`${p}.categories.growthCapacity`),
      custom_category: t(`${p}.categories.customCategory`),
    },
    statuses: {
      healthy: t(`${p}.statuses.healthy`),
      approaching_limit: t(`${p}.statuses.approachingLimit`),
      overloaded: t(`${p}.statuses.overloaded`),
      underutilized: t(`${p}.statuses.underutilized`),
      requires_review: t(`${p}.statuses.requiresReview`),
    },
    workload: {
      very_low: t(`${p}.workload.veryLow`),
      balanced: t(`${p}.workload.balanced`),
      elevated: t(`${p}.workload.elevated`),
      high: t(`${p}.workload.high`),
      critical: t(`${p}.workload.critical`),
    },
    trends: {
      increasing: t(`${p}.trends.increasing`),
      stable: t(`${p}.trends.stable`),
      decreasing: t(`${p}.trends.decreasing`),
    },
    recommendations: {
      reviewOverload: t(`${p}.recommendations.reviewOverload`),
      redistribute: t(`${p}.recommendations.redistribute`),
      evaluateStaffing: t(`${p}.recommendations.evaluateStaffing`),
      scheduleReview: t(`${p}.recommendations.scheduleReview`),
      recognizeHealthy: t(`${p}.recommendations.recognizeHealthy`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      monitoring: t(`${p}.faq.monitoring`),
      monitoringAnswer: t(`${p}.faq.monitoringAnswer`),
      autoRebalance: t(`${p}.faq.autoRebalance`),
      autoRebalanceAnswer: t(`${p}.faq.autoRebalanceAnswer`),
    },
  };
}
