import type { SystemNoticePreset, SystemNoticeStatus } from "./types";

export const SYSTEM_NOTICE_PRESETS: Record<SystemNoticeStatus, SystemNoticePreset> = {
  forbidden: {
    status: "forbidden",
    icon: "🔒",
    titleKey: "forbidden.title",
    messageKey: "forbidden.message",
    primaryLabelKey: "goToLogin",
    primaryHref: "/login",
    secondaryLabelKey: "backToAipify",
    secondaryHref: "/",
  },
  not_found: {
    status: "not_found",
    icon: "ℹ️",
    titleKey: "notFound.title",
    messageKey: "notFound.message",
    primaryLabelKey: "goToHome",
    primaryHref: "/",
    secondaryLabelKey: "knowledgeCenter",
    secondaryHref: "/knowledge",
  },
  unauthorized_panel: {
    status: "unauthorized_panel",
    icon: "🔒",
    titleKey: "unauthorizedPanel.title",
    messageKey: "unauthorizedPanel.message",
    primaryLabelKey: "returnToDashboard",
    primaryHref: "/app",
    secondaryLabelKey: "returnToDashboard",
    secondaryHref: "/app",
    layout: { hideSecondary: true, ghostDashboard: false },
  },
  growth_partner_required: {
    status: "growth_partner_required",
    icon: "🔒",
    titleKey: "growthPartner.title",
    messageKey: "growthPartner.message",
    primaryLabelKey: "registerGrowthPartnerAccount",
    primaryHref: "/growth-partners",
    secondaryLabelKey: "returnToDashboard",
    secondaryHref: "/app",
    layout: { hideSecondary: true, ghostDashboard: true, dashboardHref: "/app" },
  },
  business_pack_required: {
    status: "business_pack_required",
    icon: "🔒",
    titleKey: "businessPack.title",
    messageKey: "businessPack.message",
    primaryLabelKey: "viewBusinessPacks",
    primaryHref: "/app/settings/modules",
    secondaryLabelKey: "returnToDashboard",
    secondaryHref: "/app",
    layout: { hideSecondary: true, ghostDashboard: true, dashboardHref: "/app" },
  },
  professional_plan_required: {
    status: "professional_plan_required",
    icon: "🔒",
    titleKey: "professionalPlan.title",
    messageKey: "professionalPlan.message",
    primaryLabelKey: "upgradePlan",
    primaryHref: "/app/settings/billing",
    secondaryLabelKey: "returnToDashboard",
    secondaryHref: "/app",
    layout: { hideSecondary: true, ghostDashboard: true, dashboardHref: "/app" },
  },
  enterprise_access_required: {
    status: "enterprise_access_required",
    icon: "🔒",
    titleKey: "enterpriseAccess.title",
    messageKey: "enterpriseAccess.message",
    primaryLabelKey: "upgradeToEnterprise",
    primaryHref: "/app/settings/billing",
    secondaryLabelKey: "returnToDashboard",
    secondaryHref: "/app",
    layout: { hideSecondary: true, ghostDashboard: true, dashboardHref: "/app" },
  },
  administrator_access_required: {
    status: "administrator_access_required",
    icon: "🔒",
    titleKey: "administratorAccess.title",
    messageKey: "administratorAccess.message",
    primaryLabelKey: "returnToDashboard",
    primaryHref: "/app",
    secondaryLabelKey: "returnToDashboard",
    secondaryHref: "/app",
    layout: { hideSecondary: true, ghostDashboard: false },
  },
  executive_access_required: {
    status: "executive_access_required",
    icon: "🔒",
    titleKey: "executiveAccess.title",
    messageKey: "executiveAccess.message",
    primaryLabelKey: "returnToDashboard",
    primaryHref: "/app",
    secondaryLabelKey: "returnToDashboard",
    secondaryHref: "/app",
    layout: { hideSecondary: true, ghostDashboard: false },
  },
  platform_required: {
    status: "platform_required",
    icon: "🛡️",
    titleKey: "platform.title",
    messageKey: "platform.message",
    primaryLabelKey: "goToLogin",
    primaryHref: "/login?next=/platform",
    secondaryLabelKey: "backToAipify",
    secondaryHref: "/",
  },
  super_admin_required: {
    status: "super_admin_required",
    icon: "🛡️",
    titleKey: "superAdmin.title",
    messageKey: "superAdmin.message",
    primaryLabelKey: "goToLogin",
    primaryHref: "/login?next=/super",
    secondaryLabelKey: "backToAipify",
    secondaryHref: "/",
  },
  app_required: {
    status: "app_required",
    icon: "🔒",
    titleKey: "app.title",
    messageKey: "app.message",
    primaryLabelKey: "goToLogin",
    primaryHref: "/login?next=/app",
    secondaryLabelKey: "backToAipify",
    secondaryHref: "/",
  },
  subscription_required: {
    status: "subscription_required",
    icon: "⚠️",
    titleKey: "subscription.title",
    messageKey: "subscription.message",
    primaryLabelKey: "renewSubscription",
    primaryHref: "/app/settings/billing",
    secondaryLabelKey: "billing",
    secondaryHref: "/app/settings/billing",
  },
  suspended_account: {
    status: "suspended_account",
    icon: "⚠️",
    titleKey: "suspended.title",
    messageKey: "suspended.message",
    primaryLabelKey: "renewSubscription",
    primaryHref: "/app/settings/billing",
    secondaryLabelKey: "contactSupport",
    secondaryHref: "/contact",
  },
  cancelled_account: {
    status: "cancelled_account",
    icon: "❌",
    titleKey: "cancelled.title",
    messageKey: "cancelled.message",
    primaryLabelKey: "contactSupport",
    primaryHref: "/contact",
    secondaryLabelKey: "backToAipify",
    secondaryHref: "/",
  },
};
