import type { Translator } from "@/lib/i18n/translate";

export function buildQualityOperationsLabels(t: Translator) {
  const p = "customerApp.qualityOperations";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    standards: t(`${p}.standards`),
    audits: t(`${p}.audits`),
    compliance: t(`${p}.compliance`),
    incidents: t(`${p}.incidents`),
    correctiveActions: t(`${p}.correctiveActions`),
    improvements: t(`${p}.improvements`),
    reports: t(`${p}.reports`),
    qualityScore: t(`${p}.qualityScore`),
    qualityStatus: t(`${p}.qualityStatus`),
    activeStandards: t(`${p}.activeStandards`),
    standardsReviewDue: t(`${p}.standardsReviewDue`),
    openAudits: t(`${p}.openAudits`),
    complianceRisks: t(`${p}.complianceRisks`),
    openIncidents: t(`${p}.openIncidents`),
    criticalFindings: t(`${p}.criticalFindings`),
    openCorrectiveActions: t(`${p}.openCorrectiveActions`),
    overdueCorrectiveActions: t(`${p}.overdueCorrectiveActions`),
    improvementPipeline: t(`${p}.improvementPipeline`),
    createStandard: t(`${p}.createStandard`),
    activateStandard: t(`${p}.activateStandard`),
    createComplianceItem: t(`${p}.createComplianceItem`),
    createAudit: t(`${p}.createAudit`),
    startAudit: t(`${p}.startAudit`),
    closeAudit: t(`${p}.closeAudit`),
    reportIncident: t(`${p}.reportIncident`),
    resolveIncident: t(`${p}.resolveIncident`),
    createCorrectiveAction: t(`${p}.createCorrectiveAction`),
    verifyCorrectiveAction: t(`${p}.verifyCorrectiveAction`),
    submitImprovement: t(`${p}.submitImprovement`),
    approveImprovement: t(`${p}.approveImprovement`),
    refreshQualityScore: t(`${p}.refreshQualityScore`),
    standardTitle: t(`${p}.standardTitle`),
    auditTitle: t(`${p}.auditTitle`),
    incidentTitle: t(`${p}.incidentTitle`),
    improvementTitle: t(`${p}.improvementTitle`),
    complianceTitle: t(`${p}.complianceTitle`),
    noStandards: t(`${p}.noStandards`),
    noAudits: t(`${p}.noAudits`),
    noIncidents: t(`${p}.noIncidents`),
    noImprovements: t(`${p}.noImprovements`),
    noComplianceItems: t(`${p}.noComplianceItems`),
    noCorrectiveActions: t(`${p}.noCorrectiveActions`),
    emptyHint: t(`${p}.emptyHint`),
    auditLog: t(`${p}.auditLog`),
    companionInsights: t(`${p}.companionInsights`),
    standardsTitle: t(`${p}.standardsTitle`),
    complianceTitlePage: t(`${p}.complianceTitlePage`),
    auditsTitle: t(`${p}.auditsTitle`),
    incidentsTitle: t(`${p}.incidentsTitle`),
    improvementsTitle: t(`${p}.improvementsTitle`),
    knowledgeIntegration: t(`${p}.knowledgeIntegration`),
    peopleIntegration: t(`${p}.peopleIntegration`),
    save: t(`${p}.save`),
  };
}

export type QualityOperationsLabels = ReturnType<typeof buildQualityOperationsLabels>;
