export function buildPartnerOpportunitiesLabels(t: (key: string) => string): Record<string, string> {
  const p = "partnerOpportunities";
  const keys = [
    "title",
    "subtitle",
    "loading",
    "errorTitle",
    "errorMessage",
    "retry",
    "accessDenied",
    "activeOpportunities",
    "newOpportunities",
    "qualifiedOpportunities",
    "proposalOpportunities",
    "closedWon",
    "closedLost",
    "pipelineValue",
    "expectedRevenue",
    "weightedRevenue",
    "potentialCommission",
    "conversionRate",
    "averageDealSize",
    "winRate",
    "pipelineGrowth",
    "allOpportunities",
    "pipelineView",
    "forecastView",
    "tableView",
    "createOpportunity",
    "saveOpportunity",
    "created",
    "saved",
    "actionFailed",
    "companyName",
    "contactPerson",
    "contactEmail",
    "contactPhone",
    "country",
    "industry",
    "opportunityValue",
    "expectedCloseDate",
    "currentStage",
    "partnerOwner",
    "nextAction",
    "nextActionDue",
    "lastActivity",
    "healthScore",
    "insightsTitle",
    "timelineTitle",
    "searchPlaceholder",
    "filterStage",
    "filterCountry",
    "filterIndustry",
    "filterAll",
    "emptyTitle",
    "emptyMessage",
    "viewDetails",
    "addActivity",
    "health_excellent",
    "health_healthy",
    "health_needs_attention",
    "health_at_risk",
    "stage_lead",
    "stage_contacted",
    "stage_discovery",
    "stage_qualified",
    "stage_demo_scheduled",
    "stage_proposal_sent",
    "stage_negotiation",
    "stage_closed_won",
    "stage_closed_lost",
    "faqTitle",
    "faqWhatIs",
    "faqWhatIsAnswer",
    "faqWhyTrack",
    "faqWhyTrackAnswer",
    "faqRecommendations",
    "faqRecommendationsAnswer",
  ];
  return Object.fromEntries(keys.map((key) => [key, t(`${p}.${key}`)]));
}

export function stageLabel(labels: Record<string, string>, key: string, fallback?: string): string {
  return labels[`stage_${key}`] ?? fallback ?? key.replace(/_/g, " ");
}

export function healthLabel(labels: Record<string, string>, key: string): string {
  return labels[`health_${key}`] ?? key.replace(/_/g, " ");
}
