import type { Translator } from "@/lib/i18n/translate";

export function buildSalesRevenuePipelineLabels(t: Translator) {
  const p = "customerApp.salesRevenuePipeline";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    pipeline: t(`${p}.pipeline`),
    opportunities: t(`${p}.opportunities`),
    quotes: t(`${p}.quotes`),
    forecasting: t(`${p}.forecasting`),
    activities: t(`${p}.activities`),
    customers: t(`${p}.customers`),
    reports: t(`${p}.reports`),
    playbooks: t(`${p}.playbooks`),
    openOpportunities: t(`${p}.openOpportunities`),
    pipelineValue: t(`${p}.pipelineValue`),
    expectedRevenue: t(`${p}.expectedRevenue`),
    weightedForecast: t(`${p}.weightedForecast`),
    closedRevenue: t(`${p}.closedRevenue`),
    conversionRate: t(`${p}.conversionRate`),
    upcomingFollowUps: t(`${p}.upcomingFollowUps`),
    forecastAccuracy: t(`${p}.forecastAccuracy`),
    topOpportunities: t(`${p}.topOpportunities`),
    atRiskDeals: t(`${p}.atRiskDeals`),
    createOpportunity: t(`${p}.createOpportunity`),
    createQuote: t(`${p}.createQuote`),
    createActivity: t(`${p}.createActivity`),
    refreshForecast: t(`${p}.refreshForecast`),
    advanceStage: t(`${p}.advanceStage`),
    markWon: t(`${p}.markWon`),
    markLost: t(`${p}.markLost`),
    submitQuote: t(`${p}.submitQuote`),
    approveQuote: t(`${p}.approveQuote`),
    acceptQuote: t(`${p}.acceptQuote`),
    opportunityName: t(`${p}.opportunityName`),
    customerName: t(`${p}.customerName`),
    amount: t(`${p}.amount`),
    stage: t(`${p}.stage`),
    probability: t(`${p}.probability`),
    health: t(`${p}.health`),
    healthy: t(`${p}.healthy`),
    stable: t(`${p}.stable`),
    attention: t(`${p}.attention`),
    atRisk: t(`${p}.atRisk`),
    noOpportunities: t(`${p}.noOpportunities`),
    noOpportunitiesHint: t(`${p}.noOpportunitiesHint`),
    noQuotes: t(`${p}.noQuotes`),
    auditLog: t(`${p}.auditLog`),
    save: t(`${p}.save`),
  };
}

export type SalesRevenuePipelineLabels = ReturnType<typeof buildSalesRevenuePipelineLabels>;
