-- Trust gate: unknown operational metadata defaults to uncertified — never implicit live.
-- Canonical fail-closed metadata and certification DDL is deferred until Phase 620
-- prerequisites exist; installed in 20261862510000_phase620_app_showcase_seed_function_fix.sql.
