-- AIPIFY Global Naming Standard — Aipify-First Language Policy
-- Extends Brand Identity & Personhood Standard and Companion Identity Engine (Phase A.84 / ABOS Phase 6).
-- Unified _aflp_* namespace — no conflicting _cnp_* helpers (Companion Naming Policy not yet shipped).

-- ---------------------------------------------------------------------------
-- 1. Core policy helpers
-- ---------------------------------------------------------------------------
create or replace function public._aflp_distinction_note()
returns text language sql immutable as $$
  select 'AIPIFY Global Naming Standard — Aipify-First Language Policy. Ecosystem-wide customer-facing label policy. Extends Brand Identity & Personhood Standard and Companion Identity Engine orchestration at /app/companion-identity-engine. Does NOT rename routes, skill IDs, or API paths. Technical/compliance docs may retain "AI" per technical exception.';
$$;

create or replace function public._aflp_core_principle()
returns text language sql immutable as $$
  select 'Aipify is the product name. Artificial Intelligence is the underlying technology. Customer-facing copy uses Aipify-first labels — not generic AI product names.';
$$;

create or replace function public._aflp_label_replacements()
returns jsonb language sql immutable as $$
  select jsonb_build_array(
    jsonb_build_object('avoid', 'AI Assistant', 'use', 'Aipify Companion', 'example', 'Your Aipify Companion helps with daily tasks.'),
    jsonb_build_object('avoid', 'AI Support', 'use', 'Aipify Support', 'example', 'Support dashboard and case resolution labels'),
    jsonb_build_object('avoid', 'Resolved by AI', 'use', 'Resolved by Aipify', 'example', 'Support metrics and pilot dashboards'),
    jsonb_build_object('avoid', 'Escalated by AI', 'use', 'Escalated by Aipify', 'example', 'Escalation attribution in analytics'),
    jsonb_build_object('avoid', 'AI Summary', 'use', 'Aipify Summary', 'example', 'Meeting summaries, briefing cards'),
    jsonb_build_object('avoid', 'AI Recommendation', 'use', 'Aipify Insight', 'example', 'Single executive or admin recommendation'),
    jsonb_build_object('avoid', 'AI Recommendations', 'use', 'Aipify Insights', 'example', 'Recommendation lists and module labels'),
    jsonb_build_object('avoid', 'AI Notes', 'use', 'Aipify Notes', 'example', 'Meeting and support case notes'),
    jsonb_build_object('avoid', 'AI Notification', 'use', 'Aipify Notification', 'example', 'Desktop and in-app notifications'),
    jsonb_build_object('avoid', 'AI Meeting Assistant', 'use', 'Aipify Meeting Companion', 'example', 'Visible Teams/Meet join — never hidden'),
    jsonb_build_object('avoid', 'AI Generated', 'use', 'Generated by Aipify', 'example', 'Draft badges and document footers'),
    jsonb_build_object('avoid', 'AI Coach', 'use', 'Aipify Coach', 'example', 'Learning and training companion'),
    jsonb_build_object('avoid', 'AI Trainer', 'use', 'Aipify Trainer', 'example', 'Certification and training modules'),
    jsonb_build_object('avoid', 'AI-powered', 'use', 'Aipify-powered or outcome-focused phrasing', 'example', 'Prefer outcomes over technology headlines')
  );
$$;

create or replace function public._aflp_applies_to_surfaces()
returns jsonb language sql immutable as $$
  select jsonb_build_array(
    'Customer App UI — navigation, dashboards, notifications, onboarding',
    'Companion Orb and Desktop Companion',
    'Support dashboards and self-support flows',
    'Admin Assistant and executive surfaces',
    'Meeting Companion, calendar companion, collaboration intelligence',
    'Knowledge Center customer-facing articles and FAQ',
    'Workflow approvals, document output labels, marketing copy',
    'Assistant replies and proactive guidance (ILM adaptation)',
    'Platform Admin customer-facing support value metrics'
  );
$$;

create or replace function public._aflp_technical_exceptions()
returns jsonb language sql immutable as $$
  select jsonb_build_array(
    'Investor, security, compliance, and regulatory documentation where "artificial intelligence" is required',
    'Internal engineering docs — model providers, ML pipelines, risk enums',
    'User-typed natural language ("Hi AI") — Aipify responds as Aipify',
    'Code identifiers, routes, skill registry IDs, API paths (e.g. support-ai-engine)',
    'Database column and enum names — UI copy still follows Aipify-first policy'
  );
$$;

create or replace function public._aflp_companion_phrases()
returns jsonb language sql immutable as $$
  select jsonb_build_array(
    'Aipify Companion — daily operational assistance',
    'Aipify Meeting Companion — visible when joining meetings; never secret recording',
    'Aipify Support — customer-facing support with human oversight',
    'This feels like Aipify — consistent naming builds trust'
  );
$$;

create or replace function public._aflp_marketing_principle()
returns text language sql immutable as $$
  select 'Lead with outcomes and trust — not "AI-powered platform" headlines. Prefer: Aipify works in the background so your team can move forward.';
$$;

create or replace function public._aflp_abos_principle()
returns text language sql immutable as $$
  select 'Aipify Business Operating System (ABOS) is the product category. Individual modules are Aipify capabilities — not separate generic AI products.';
$$;

create or replace function public._aflp_implementation_requirements()
returns jsonb language sql immutable as $$
  select jsonb_build_array(
    'i18n first — locales en/no/sv/da for all customer-facing strings',
    'ILM — applyAipifyFirstLanguagePolicy() on generated and legacy copy',
    'Core RPC — _aflp_* helpers exposed via Companion Identity Engine dashboard',
    'Knowledge Center FAQ — brand-identity/aipify-first-language-policy-faq.md',
    'No route renames — copy-only; preserve install-first architecture',
    'Module consistency reviews via Companion Identity Engine'
  );
$$;

create or replace function public._aflp_faq_items()
returns jsonb language sql immutable as $$
  select jsonb_build_array(
    jsonb_build_object(
      'question', 'Why does Aipify use its own name instead of "AI" in the product?',
      'answer', 'Aipify is a complete business operating system — not a generic AI service. Consistent naming helps you recognize when Aipify is assisting. Artificial intelligence is one technology Aipify uses; the product you interact with is Aipify.'
    ),
    jsonb_build_object(
      'question', 'Can I still say "AI" when I talk to Aipify?',
      'answer', 'Yes. Aipify understands natural language including "Hi AI." Aipify generally refers to itself as Aipify in replies and product labels for a consistent, trustworthy experience.'
    ),
    jsonb_build_object(
      'question', 'Does Aipify hide that it uses artificial intelligence?',
      'answer', 'No. Aipify is transparent that advanced intelligence powers many features. The naming policy is about product identity — not concealing how the platform works. Compliance and technical docs may still refer to artificial intelligence where required.'
    )
  );
$$;

create or replace function public._aflp_vision_phrases()
returns jsonb language sql immutable as $$
  select jsonb_build_array(
    'This feels like Aipify — one name across every module.',
    'People build relationships with names, not technologies.',
    'Aipify informs and prepares. Humans decide.'
  );
$$;

create or replace function public._aflp_policy_bundle()
returns jsonb language sql immutable as $$
  select jsonb_build_object(
    'doc', 'AIPIFY_GLOBAL_NAMING_STANDARD_AIPIFY_FIRST_LANGUAGE_POLICY.md',
    'distinction_note', public._aflp_distinction_note(),
    'core_principle', public._aflp_core_principle(),
    'marketing_principle', public._aflp_marketing_principle(),
    'abos_principle', public._aflp_abos_principle(),
    'label_replacements', public._aflp_label_replacements(),
    'applies_to_surfaces', public._aflp_applies_to_surfaces(),
    'technical_exceptions', public._aflp_technical_exceptions(),
    'companion_phrases', public._aflp_companion_phrases(),
    'implementation_requirements', public._aflp_implementation_requirements(),
    'faq_items', public._aflp_faq_items(),
    'vision_phrases', public._aflp_vision_phrases(),
    'ilm_corpus', 'aipify-first-language-policy.txt',
    'ilm_module', 'lib/internal-language-model/brand-identity-vocabulary.ts',
    'kc_faq', 'content/knowledge/aipify/brand-identity/faq/aipify-first-language-policy-faq.md',
    'cross_links', jsonb_build_array(
      'BRAND_IDENTITY_PERSONHOOD_STANDARD.md',
      'ABOS_BRAND_TERMINOLOGY_STANDARD.md',
      'AIPIFY_BRANDING_STANDARD_COMPANION_NAMING_POLICY.md',
      'COMPANION_IDENTITY_ENGINE_PHASE_A84.md'
    ),
    'companion_naming_policy', public._cnp_companion_naming_policy(),
    'support_panel_examples', public._cnp_support_panel_examples()
  );
$$;

-- ---------------------------------------------------------------------------
-- 2. Replace Companion Identity Engine card — preserve ALL prior fields
-- ---------------------------------------------------------------------------
create or replace function public.get_companion_identity_engine_card()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  v_org_id uuid;
  v_modules int := 0;
  v_aligned int := 0;
begin
  perform public._irp_require_permission('companion_identity.view');
  v_org_id := public._mta_require_organization();
  perform public._cie_ensure_settings(v_org_id);
  perform public._cie_seed_module_registry(v_org_id);

  select count(*), count(*) filter (where identity_aligned = true)
  into v_modules, v_aligned
  from public.companion_identity_module_registry
  where organization_id = v_org_id;

  return jsonb_build_object(
    'has_organization', true,
    'philosophy', 'This feels like Aipify — through behavior, not logos.',
    'modules_tracked', v_modules,
    'modules_aligned', v_aligned,
    'enabled', (select enabled from public.organization_companion_identity_settings where organization_id = v_org_id),
    'learning_journey_philosophy', public._cie_learning_journey_philosophy(),
    'vision_rose_phrase', public._cie_vision_rose_phrase(),
    'learning_journey_standard_note', public._cie_learning_journey_standard_note(),
    'implementation_blueprint', jsonb_build_object(
      'phase', 'Phase 6 — Companion Identity Foundation',
      'doc', 'IMPLEMENTATION_BLUEPRINT_PHASE6_COMPANION_IDENTITY_FOUNDATION.md',
      'distinction', 'Distinct from Implementation Blueprint Phase 6 Action & Approval (Trust & Action Engine at /app/approvals)'
    ),
    'companion_identity_engine_note', 'Companion Identity Foundation (ABOS Phase 6) — extends Companion Identity Engine (Phase A.84).',
    'companion_naming_policy', public._cnp_companion_naming_policy(),
    'aipify_first_language_policy', public._aflp_policy_bundle()
  );
exception when others then
  return jsonb_build_object('has_organization', false);
end; $$;

-- ---------------------------------------------------------------------------
-- 3. Replace Companion Identity Engine dashboard — preserve ALL prior fields
-- ---------------------------------------------------------------------------
create or replace function public.get_companion_identity_engine_dashboard()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  v_org_id uuid;
  v_settings public.organization_companion_identity_settings;
  v_modules int := 0;
  v_aligned int := 0;
begin
  perform public._irp_require_permission('companion_identity.view');
  v_org_id := public._mta_require_organization();
  v_settings := public._cie_ensure_settings(v_org_id);
  perform public._cie_seed_module_registry(v_org_id);

  select count(*), count(*) filter (where identity_aligned = true)
  into v_modules, v_aligned
  from public.companion_identity_module_registry
  where organization_id = v_org_id;

  return jsonb_build_object(
    'has_organization', true,
    'philosophy', 'People remember how they felt — helpful, warm, respectful, encouraging, honest, human-centered. Consistent companion experience across every module.',
    'mission', 'Unified Aipify experience across all touchpoints — values, personality, and communication principles that make Aipify recognizable and trustworthy.',
    'abos_principle', 'Reliable technology plus genuine companionship — Aipify augments people; humans decide.',
    'vision', 'Users say "This feels like Aipify" because of how Aipify behaves, not because of branding alone.',
    'distinction_note', 'Distinct from Identity Engine Phase 34 (per-user style observations), Brand Identity & Personhood Standard (product naming), Humor & Personal Connection (/app/personality), Companion Presence A.67 (floating orb), and Purpose & Values A.82 (tenant organizational values). Also distinct from Implementation Blueprint Phase 6 Action & Approval (Trust & Action Engine). This engine orchestrates unified companion identity across ABOS modules.',
    'implementation_blueprint', jsonb_build_object(
      'phase', 'Phase 6 — Companion Identity Foundation',
      'doc', 'IMPLEMENTATION_BLUEPRINT_PHASE6_COMPANION_IDENTITY_FOUNDATION.md',
      'distinction', 'Distinct from Implementation Blueprint Phase 6 Action & Approval (Trust & Action Engine at /app/approvals)'
    ),
    'companion_identity_engine_note', 'Companion Identity Foundation (ABOS Phase 6) — extends Companion Identity Engine (Phase A.84).',
    'companion_characteristics', public._cie_companion_characteristics(),
    'communication_standards', public._cie_communication_standards(),
    'playful_moments', public._cie_playful_moments(),
    'self_love_implementation', public._cie_self_love_implementation(),
    'companion_memory_rules', public._cie_companion_memory_rules(),
    'org_configuration_boundaries', public._cie_org_configuration_boundaries(),
    'dogfooding', public._cie_blueprint_dogfooding(),
    'success_criteria', public._cie_blueprint_success_criteria(v_org_id),
    'vision_phrases', public._cie_vision_phrases(),
    'core_identity_traits', public._cie_core_identity_traits(),
    'communication_style_rules', public._cie_communication_style_rules(),
    'personality_traits', public._cie_personality_traits(),
    'signature_elements', public._cie_signature_elements(),
    'fox_exchange', public._cie_fox_exchange_example(),
    'module_consistency', public._cie_list_module_consistency(v_org_id),
    'self_love_note', 'Self Love — healthy pacing, balance, celebrate recovery, recognize effort. Growth never at the expense of wellbeing. ' || public._cie_learning_journey_self_love_note(),
    'learning_journey_abos_principle', public._cie_learning_journey_abos_principle(),
    'learning_journey_philosophy', public._cie_learning_journey_philosophy(),
    'capability_gap_examples', public._cie_capability_gap_examples(),
    'growth_principle_phrases', public._cie_growth_principle_phrases(),
    'vision_rose_phrase', public._cie_vision_rose_phrase(),
    'learning_journey_standard_note', public._cie_learning_journey_standard_note(),
    'settings', row_to_json(v_settings)::jsonb,
    'summary', jsonb_build_object(
      'modules_tracked', v_modules,
      'modules_aligned', v_aligned,
      'signature_elements_enabled', v_settings.signature_elements_enabled,
      'playful_when_appropriate', v_settings.playful_when_appropriate,
      'bell_moments_enabled', v_settings.bell_moments_enabled,
      'self_love_refs_enabled', v_settings.self_love_refs_enabled
    ),
    'integration_links', jsonb_build_object(
      'brand_identity', '/content/knowledge/aipify/abos/articles/brand-identity-personhood',
      'aipify_first_language_policy', 'AIPIFY_GLOBAL_NAMING_STANDARD_AIPIFY_FIRST_LANGUAGE_POLICY.md',
      'companion_naming_policy', 'AIPIFY_BRANDING_STANDARD_COMPANION_NAMING_POLICY.md',
      'learning_journey', '/content/knowledge/aipify/abos/articles/learning-journey-communication',
      'personality', '/app/personality',
      'humor_personality', '/app/personality',
      'playful_seed', 'HUMOR_PERSONAL_CONNECTION_ENGINE.md',
      'identity_engine', '/app/assistant/identity',
      'inclusion_humanity', '/app/inclusion-humanity-engine',
      'learning_engine', '/app/learning',
      'presence_comfort', '/app/presence-comfort-protocol',
      'gratitude_recognition', '/app/gratitude-recognition-engine',
      'dedication_engine', '/app/dedication-engine',
      'hope_engine', '/app/hope-engine',
      'wisdom_engine', '/app/wisdom-engine',
      'wisdom_intervention', '/app/wisdom-intervention-protocol',
      'proactive_companion', '/app/proactive-companion-engine',
      'trust_engine', '/app/trust',
      'self_love_naming', 'SELF_LOVE_NAMING_STANDARD.md',
      'companion_identity_blueprint', 'IMPLEMENTATION_BLUEPRINT_PHASE6_COMPANION_IDENTITY_FOUNDATION.md'
    ),
    'permissions', jsonb_build_object(
      'can_manage', public._irp_has_permission('companion_identity.manage'),
      'can_export', public._irp_has_permission('companion_identity.export')
    ),
    'companion_naming_policy', public._cnp_companion_naming_policy(),
    'aipify_first_language_policy', public._aflp_policy_bundle()
  );
exception when others then
  return jsonb_build_object('has_organization', false);
end; $$;

grant execute on function public._aflp_policy_bundle() to authenticated;

insert into public.aipify_knowledge_categories (slug, name, description, visibility, sort_order)
select 'aipify-first-language-policy', 'Aipify-First Language Policy',
  'Global naming standard — Aipify-first labels across all customer-facing surfaces.',
  'authenticated', 101
where not exists (
  select 1 from public.aipify_knowledge_categories
  where slug = 'aipify-first-language-policy' and tenant_id is null
);
