-- Companion Naming Policy — Aipify Branding Standard
-- Extends Companion Identity Engine (Phase A.84 + ABOS Phase 6). No new tables.
-- Cross-ref: AIPIFY_BRANDING_STANDARD_COMPANION_NAMING_POLICY.md · BRAND_IDENTITY_PERSONHOOD_STANDARD.md

create or replace function public._cnp_label_replacements()
returns jsonb language sql immutable as $$
  select jsonb_build_array(
    jsonb_build_object('avoid', 'AI Assistant', 'use', 'Aipify Companion'),
    jsonb_build_object('avoid', 'AI Support', 'use', 'Aipify Support'),
    jsonb_build_object('avoid', 'Resolved by AI', 'use', 'Resolved by Aipify'),
    jsonb_build_object('avoid', 'AI Escalation', 'use', 'Escalated by Aipify'),
    jsonb_build_object('avoid', 'AI Notes', 'use', 'Aipify Notes'),
    jsonb_build_object('avoid', 'AI Recommendations', 'use', 'Aipify Insights'),
    jsonb_build_object('avoid', 'AI Summary', 'use', 'Aipify Summary'),
    jsonb_build_object('avoid', 'AI Generated', 'use', 'Generated by Aipify')
  );
$$;

create or replace function public._cnp_support_panel_examples()
returns jsonb language sql immutable as $$
  select jsonb_build_array(
    jsonb_build_object('old', 'Support AI', 'new', 'Aipify Support'),
    jsonb_build_object('old', 'AI Responses', 'new', 'Aipify Responses'),
    jsonb_build_object('old', 'AI Statistics', 'new', 'Aipify Support Statistics'),
    jsonb_build_object('old', 'AI usage rate', 'new', 'Aipify usage rate'),
    jsonb_build_object('old', 'Support AI Principles', 'new', 'Aipify Support Principles'),
    jsonb_build_object('old', 'Support AI Engine', 'new', 'Aipify Support Engine'),
    jsonb_build_object('old', 'Secure AI Actions', 'new', 'Secure Aipify Actions'),
    jsonb_build_object('old', 'Resolved by AI', 'new', 'Resolved by Aipify'),
    jsonb_build_object('old', 'Escalated by AI', 'new', 'Escalated by Aipify')
  );
$$;

create or replace function public._cnp_companion_philosophy()
returns jsonb language sql immutable as $$
  select jsonb_build_array(
    'Aipify is the companion users interact with — not a generic AI service.',
    'Consistent naming builds familiarity and trust across every module.',
    'Aipify augments people; humans decide.',
    'Users may say "AI"; product copy uses Aipify.'
  );
$$;

create or replace function public._cnp_vision_phrases()
returns jsonb language sql immutable as $$
  select jsonb_build_array(
    'People build relationships with names, not technologies.',
    'Users recognize Aipify in every touchpoint — Support, Insights, Notes, and Approvals.',
    'This feels like Aipify — because of consistent naming and behavior, not logos alone.'
  );
$$;

create or replace function public._cnp_faq_items()
returns jsonb language sql immutable as $$
  select jsonb_build_array(
    jsonb_build_object(
      'key', 'labels_ai_or_aipify',
      'question', 'Should customer-facing labels say "AI" or "Aipify"?',
      'answer', 'Prefer Aipify. Generic "AI" labels describe the technology, not the product users purchased. Use Aipify-branded names in dashboards, support panels, notifications, and Knowledge Center articles.'
    ),
    jsonb_build_object(
      'key', 'users_say_ai',
      'question', 'Can users still call Aipify "AI"?',
      'answer', 'Yes. Users may naturally say "AI" in conversation. Aipify understands that phrasing and responds as Aipify — but product copy should consistently use the Aipify name.'
    ),
    jsonb_build_object(
      'key', 'support_ai_rename',
      'question', 'Why change "Support AI" to "Aipify Support"?',
      'answer', '"Support AI" sounds like a feature category. Aipify Support names the product capability customers rely on — the same trusted companion across every module, not a separate AI tool.'
    )
  );
$$;

create or replace function public._cnp_companion_naming_policy()
returns jsonb language sql immutable as $$
  select jsonb_build_object(
    'doc', 'AIPIFY_BRANDING_STANDARD_COMPANION_NAMING_POLICY.md',
    'principle', 'Aipify is the product name. Artificial Intelligence is the underlying technology. Users interact with Aipify, not generic AI.',
    'label_replacements', public._cnp_label_replacements(),
    'support_panel_examples', public._cnp_support_panel_examples(),
    'companion_philosophy', public._cnp_companion_philosophy(),
    'vision_phrases', public._cnp_vision_phrases(),
    'faq_items', public._cnp_faq_items()
  );
$$;

-- Card RPC — preserve ALL Phase 6 fields; append companion_naming_policy
create or replace function public.get_companion_identity_engine_card()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  v_org_id uuid;
  v_modules int := 0;
  v_aligned int := 0;
begin
  perform public._irp_require_permission('companion_identity.view');
  v_org_id := public._mta_require_organization();
  perform public._cie_ensure_settings(v_org_id);
  perform public._cie_seed_module_registry(v_org_id);

  select count(*), count(*) filter (where identity_aligned = true)
  into v_modules, v_aligned
  from public.companion_identity_module_registry
  where organization_id = v_org_id;

  return jsonb_build_object(
    'has_organization', true,
    'philosophy', 'This feels like Aipify — through behavior, not logos.',
    'modules_tracked', v_modules,
    'modules_aligned', v_aligned,
    'enabled', (select enabled from public.organization_companion_identity_settings where organization_id = v_org_id),
    'learning_journey_philosophy', public._cie_learning_journey_philosophy(),
    'vision_rose_phrase', public._cie_vision_rose_phrase(),
    'learning_journey_standard_note', public._cie_learning_journey_standard_note(),
    'implementation_blueprint', jsonb_build_object(
      'phase', 'Phase 6 — Companion Identity Foundation',
      'doc', 'IMPLEMENTATION_BLUEPRINT_PHASE6_COMPANION_IDENTITY_FOUNDATION.md',
      'distinction', 'Distinct from Implementation Blueprint Phase 6 Action & Approval (Trust & Action Engine at /app/approvals)'
    ),
    'companion_identity_engine_note', 'Companion Identity Foundation (ABOS Phase 6) — extends Companion Identity Engine (Phase A.84).',
    'companion_naming_policy', public._cnp_companion_naming_policy()
  );
exception when others then
  return jsonb_build_object('has_organization', false);
end; $$;

-- Dashboard RPC — preserve ALL Phase 6 fields; append companion_naming_policy
create or replace function public.get_companion_identity_engine_dashboard()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  v_org_id uuid;
  v_settings public.organization_companion_identity_settings;
  v_modules int := 0;
  v_aligned int := 0;
begin
  perform public._irp_require_permission('companion_identity.view');
  v_org_id := public._mta_require_organization();
  v_settings := public._cie_ensure_settings(v_org_id);
  perform public._cie_seed_module_registry(v_org_id);

  select count(*), count(*) filter (where identity_aligned = true)
  into v_modules, v_aligned
  from public.companion_identity_module_registry
  where organization_id = v_org_id;

  return jsonb_build_object(
    'has_organization', true,
    'philosophy', 'People remember how they felt — helpful, warm, respectful, encouraging, honest, human-centered. Consistent companion experience across every module.',
    'mission', 'Unified Aipify experience across all touchpoints — values, personality, and communication principles that make Aipify recognizable and trustworthy.',
    'abos_principle', 'Reliable technology plus genuine companionship — Aipify augments people; humans decide.',
    'vision', 'Users say "This feels like Aipify" because of how Aipify behaves, not because of branding alone.',
    'distinction_note', 'Distinct from Identity Engine Phase 34 (per-user style observations), Brand Identity & Personhood Standard (product naming), Humor & Personal Connection (/app/personality), Companion Presence A.67 (floating orb), and Purpose & Values A.82 (tenant organizational values). Also distinct from Implementation Blueprint Phase 6 Action & Approval (Trust & Action Engine). This engine orchestrates unified companion identity across ABOS modules.',
    'implementation_blueprint', jsonb_build_object(
      'phase', 'Phase 6 — Companion Identity Foundation',
      'doc', 'IMPLEMENTATION_BLUEPRINT_PHASE6_COMPANION_IDENTITY_FOUNDATION.md',
      'distinction', 'Distinct from Implementation Blueprint Phase 6 Action & Approval (Trust & Action Engine at /app/approvals)'
    ),
    'companion_identity_engine_note', 'Companion Identity Foundation (ABOS Phase 6) — extends Companion Identity Engine (Phase A.84).',
    'companion_characteristics', public._cie_companion_characteristics(),
    'communication_standards', public._cie_communication_standards(),
    'playful_moments', public._cie_playful_moments(),
    'self_love_implementation', public._cie_self_love_implementation(),
    'companion_memory_rules', public._cie_companion_memory_rules(),
    'org_configuration_boundaries', public._cie_org_configuration_boundaries(),
    'dogfooding', public._cie_blueprint_dogfooding(),
    'success_criteria', public._cie_blueprint_success_criteria(v_org_id),
    'vision_phrases', public._cie_vision_phrases(),
    'core_identity_traits', public._cie_core_identity_traits(),
    'communication_style_rules', public._cie_communication_style_rules(),
    'personality_traits', public._cie_personality_traits(),
    'signature_elements', public._cie_signature_elements(),
    'fox_exchange', public._cie_fox_exchange_example(),
    'module_consistency', public._cie_list_module_consistency(v_org_id),
    'self_love_note', 'Self Love — healthy pacing, balance, celebrate recovery, recognize effort. Growth never at the expense of wellbeing. ' || public._cie_learning_journey_self_love_note(),
    'learning_journey_abos_principle', public._cie_learning_journey_abos_principle(),
    'learning_journey_philosophy', public._cie_learning_journey_philosophy(),
    'capability_gap_examples', public._cie_capability_gap_examples(),
    'growth_principle_phrases', public._cie_growth_principle_phrases(),
    'vision_rose_phrase', public._cie_vision_rose_phrase(),
    'learning_journey_standard_note', public._cie_learning_journey_standard_note(),
    'settings', row_to_json(v_settings)::jsonb,
    'summary', jsonb_build_object(
      'modules_tracked', v_modules,
      'modules_aligned', v_aligned,
      'signature_elements_enabled', v_settings.signature_elements_enabled,
      'playful_when_appropriate', v_settings.playful_when_appropriate,
      'bell_moments_enabled', v_settings.bell_moments_enabled,
      'self_love_refs_enabled', v_settings.self_love_refs_enabled
    ),
    'integration_links', jsonb_build_object(
      'brand_identity', '/content/knowledge/aipify/abos/articles/brand-identity-personhood',
      'companion_naming_policy', 'AIPIFY_BRANDING_STANDARD_COMPANION_NAMING_POLICY.md',
      'learning_journey', '/content/knowledge/aipify/abos/articles/learning-journey-communication',
      'personality', '/app/personality',
      'humor_personality', '/app/personality',
      'playful_seed', 'HUMOR_PERSONAL_CONNECTION_ENGINE.md',
      'identity_engine', '/app/assistant/identity',
      'inclusion_humanity', '/app/inclusion-humanity-engine',
      'learning_engine', '/app/learning',
      'presence_comfort', '/app/presence-comfort-protocol',
      'gratitude_recognition', '/app/gratitude-recognition-engine',
      'dedication_engine', '/app/dedication-engine',
      'hope_engine', '/app/hope-engine',
      'wisdom_engine', '/app/wisdom-engine',
      'wisdom_intervention', '/app/wisdom-intervention-protocol',
      'proactive_companion', '/app/proactive-companion-engine',
      'trust_engine', '/app/trust',
      'self_love_naming', 'SELF_LOVE_NAMING_STANDARD.md',
      'companion_identity_blueprint', 'IMPLEMENTATION_BLUEPRINT_PHASE6_COMPANION_IDENTITY_FOUNDATION.md'
    ),
    'permissions', jsonb_build_object(
      'can_manage', public._irp_has_permission('companion_identity.manage'),
      'can_export', public._irp_has_permission('companion_identity.export')
    ),
    'companion_naming_policy', public._cnp_companion_naming_policy()
  );
exception when others then
  return jsonb_build_object('has_organization', false);
end; $$;

grant execute on function public._cnp_label_replacements() to authenticated;
grant execute on function public._cnp_support_panel_examples() to authenticated;
grant execute on function public._cnp_companion_philosophy() to authenticated;
grant execute on function public._cnp_vision_phrases() to authenticated;
grant execute on function public._cnp_faq_items() to authenticated;
grant execute on function public._cnp_companion_naming_policy() to authenticated;

insert into public.aipify_knowledge_categories (slug, name, description, visibility, sort_order)
select 'companion-naming-policy', 'Companion Naming Policy',
  'Aipify branding standard — customer-facing labels prefer Aipify over generic AI terminology.',
  'authenticated', 109
where not exists (
  select 1 from public.aipify_knowledge_categories
  where slug = 'companion-naming-policy' and tenant_id is null
);
