import type { OrganizationalAssetsLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildOrganizationalAssetsLabels(t: Translator): OrganizationalAssetsLabels {
  const p = "customerApp.portalStructure.organizationalAssets";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    filters: {
      search: t(`${p}.filters.search`),
      type: t(`${p}.filters.type`),
      status: t(`${p}.filters.status`),
      owner: t(`${p}.filters.owner`),
      vendor: t(`${p}.filters.vendor`),
      criticality: t(`${p}.filters.criticality`),
      renewalBefore: t(`${p}.filters.renewalBefore`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      active: t(`${p}.dashboard.active`),
      needsReview: t(`${p}.dashboard.needsReview`),
      upcomingRenewals: t(`${p}.dashboard.upcomingRenewals`),
      missionCritical: t(`${p}.dashboard.missionCritical`),
      withoutOwner: t(`${p}.dashboard.withoutOwner`),
      recent: t(`${p}.dashboard.recent`),
    },
    form: {
      createTitle: t(`${p}.form.createTitle`),
      assetName: t(`${p}.form.assetName`),
      type: t(`${p}.form.type`),
      description: t(`${p}.form.description`),
      vendor: t(`${p}.form.vendor`),
      purchaseDate: t(`${p}.form.purchaseDate`),
      renewalDate: t(`${p}.form.renewalDate`),
      renewalReminder: t(`${p}.form.renewalReminder`),
      criticality: t(`${p}.form.criticality`),
      notes: t(`${p}.form.notes`),
      referenceNote: t(`${p}.form.referenceNote`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
    },
    card: {
      owner: t(`${p}.card.owner`),
      backupOwner: t(`${p}.card.backupOwner`),
      vendor: t(`${p}.card.vendor`),
      renewalDate: t(`${p}.card.renewalDate`),
      criticality: t(`${p}.card.criticality`),
      view: t(`${p}.card.view`),
    },
    detail: {
      overview: t(`${p}.detail.overview`),
      ownership: t(`${p}.detail.ownership`),
      vendorInfo: t(`${p}.detail.vendorInfo`),
      renewals: t(`${p}.detail.renewals`),
      relatedFollowUps: t(`${p}.detail.relatedFollowUps`),
      relatedRisks: t(`${p}.detail.relatedRisks`),
      relatedRelationships: t(`${p}.detail.relatedRelationships`),
      relatedModules: t(`${p}.detail.relatedModules`),
      renewalHistory: t(`${p}.detail.renewalHistory`),
      activity: t(`${p}.detail.activity`),
      audit: t(`${p}.detail.audit`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
      recommendations: t(`${p}.detail.recommendations`),
      renewalNote: t(`${p}.detail.renewalNote`),
      recordRenewal: t(`${p}.detail.recordRenewal`),
    },
    types: {
      software_license: t(`${p}.types.softwareLicense`),
      hardware: t(`${p}.types.hardware`),
      subscription: t(`${p}.types.subscription`),
      domain_name: t(`${p}.types.domainName`),
      api_key_reference: t(`${p}.types.apiKeyReference`),
      shared_account: t(`${p}.types.sharedAccount`),
      training_resource: t(`${p}.types.trainingResource`),
      internal_resource: t(`${p}.types.internalResource`),
      documentation_resource: t(`${p}.types.documentationResource`),
      custom_asset: t(`${p}.types.customAsset`),
    },
    statuses: {
      active: t(`${p}.statuses.active`),
      under_review: t(`${p}.statuses.underReview`),
      pending_renewal: t(`${p}.statuses.pendingRenewal`),
      retired: t(`${p}.statuses.retired`),
      archived: t(`${p}.statuses.archived`),
    },
    criticality: {
      low: t(`${p}.criticality.low`),
      moderate: t(`${p}.criticality.moderate`),
      high: t(`${p}.criticality.high`),
      mission_critical: t(`${p}.criticality.missionCritical`),
    },
    recommendations: {
      assignOwner: t(`${p}.recommendations.assignOwner`),
      reviewUpcomingRenewals: t(`${p}.recommendations.reviewUpcomingRenewals`),
      addBackupOwner: t(`${p}.recommendations.addBackupOwner`),
      archiveUnused: t(`${p}.recommendations.archiveUnused`),
      reviewMissionCritical: t(`${p}.recommendations.reviewMissionCritical`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      apiKeys: t(`${p}.faq.apiKeys`),
      apiKeysAnswer: t(`${p}.faq.apiKeysAnswer`),
      owners: t(`${p}.faq.owners`),
      ownersAnswer: t(`${p}.faq.ownersAnswer`),
    },
  };
}
