import type { ExecutiveCompanionLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildExecutiveCompanionLabels(t: Translator): ExecutiveCompanionLabels {
  const p = "customerApp.portalStructure.executiveCompanion";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      priority: t(`${p}.filters.priority`),
      strategicArea: t(`${p}.filters.strategicArea`),
      organizationalArea: t(`${p}.filters.organizationalArea`),
      focusCategory: t(`${p}.filters.focusCategory`),
      periodFrom: t(`${p}.filters.periodFrom`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      executiveBriefing: t(`${p}.dashboard.executiveBriefing`),
      todaysPriorities: t(`${p}.dashboard.todaysPriorities`),
      itemsAttention: t(`${p}.dashboard.itemsAttention`),
      upcomingResponsibilities: t(`${p}.dashboard.upcomingResponsibilities`),
      strategicProgress: t(`${p}.dashboard.strategicProgress`),
      organizationalHealth: t(`${p}.dashboard.organizationalHealth`),
      recommendedActions: t(`${p}.dashboard.recommendedActions`),
      activeInitiatives: t(`${p}.dashboard.activeInitiatives`),
      delayedInitiatives: t(`${p}.dashboard.delayedInitiatives`),
    },
    briefing: {
      goodMorning: t(`${p}.briefing.goodMorning`),
      strategicInitiativesAttention: t(`${p}.briefing.strategicInitiativesAttention`),
      commitmentsApproaching: t(`${p}.briefing.commitmentsApproaching`),
      riskShouldReview: t(`${p}.briefing.riskShouldReview`),
      momentumHealthy: t(`${p}.briefing.momentumHealthy`),
      momentumStable: t(`${p}.briefing.momentumStable`),
      momentumNeedsAttention: t(`${p}.briefing.momentumNeedsAttention`),
    },
    priorities: {
      title: t(`${p}.priorities.title`),
      criticalCommitment: t(`${p}.priorities.criticalCommitment`),
      delayedInitiative: t(`${p}.priorities.delayedInitiative`),
      highPriorityDecision: t(`${p}.priorities.highPriorityDecision`),
      emergingRisk: t(`${p}.priorities.emergingRisk`),
      upcomingReview: t(`${p}.priorities.upcomingReview`),
      executiveAction: t(`${p}.priorities.executiveAction`),
    },
    meetingPrep: {
      title: t(`${p}.meetingPrep.title`),
      relatedCommitments: t(`${p}.meetingPrep.relatedCommitments`),
      relatedDecisions: t(`${p}.meetingPrep.relatedDecisions`),
      relatedFollowUps: t(`${p}.meetingPrep.relatedFollowUps`),
      previousSummary: t(`${p}.meetingPrep.previousSummary`),
      preparationTopics: t(`${p}.meetingPrep.preparationTopics`),
    },
    health: {
      title: t(`${p}.health.title`),
      strategy: t(`${p}.health.strategy`),
      momentum: t(`${p}.health.momentum`),
      resilience: t(`${p}.health.resilience`),
      capacity: t(`${p}.health.capacity`),
      risk: t(`${p}.health.risk`),
      success: t(`${p}.health.success`),
    },
    memory: {
      title: t(`${p}.memory.title`),
      decision: t(`${p}.memory.decision`),
      commitment: t(`${p}.memory.commitment`),
    },
    timeline: { title: t(`${p}.timeline.title`) },
    priorityLevels: {
      informational: t(`${p}.priorityLevels.informational`),
      recommended: t(`${p}.priorityLevels.recommended`),
      important: t(`${p}.priorityLevels.important`),
      immediate_attention: t(`${p}.priorityLevels.immediateAttention`),
    },
    recommendations: {
      reviewDelayedInitiatives: t(`${p}.recommendations.reviewDelayedInitiatives`),
      scheduleExecutiveFollowUps: t(`${p}.recommendations.scheduleExecutiveFollowUps`),
      recognizeSuccessfulTeams: t(`${p}.recommendations.recognizeSuccessfulTeams`),
      revisitUnresolvedRisks: t(`${p}.recommendations.revisitUnresolvedRisks`),
      prepareUpcomingCommitments: t(`${p}.recommendations.prepareUpcomingCommitments`),
      reviewDecisionsNearDeadline: t(`${p}.recommendations.reviewDecisionsNearDeadline`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      makesDecisions: t(`${p}.faq.makesDecisions`),
      makesDecisionsAnswer: t(`${p}.faq.makesDecisionsAnswer`),
      replaceLeadership: t(`${p}.faq.replaceLeadership`),
      replaceLeadershipAnswer: t(`${p}.faq.replaceLeadershipAnswer`),
    },
  };
}
