import type { PilotProvisionConfig } from "@/lib/aipify/pilot/types";

/** Unonight-specific pilot preset — lives in integration package, not Aipify core. */
export const UNONIGHT_PILOT_PRESET: PilotProvisionConfig = {
  slug: "unonight",
  name: "Unonight",
  company_slug: "unonight",
  tenant_type: "pilot_customer",
  industry: "adult_social_platform",
  region: "Norway / Nordic / International",
  default_language: "en",
  supported_languages: ["en", "no", "sv", "da"],
  timezone: "Europe/Oslo",
  pilot_status: "setup",
  pilot_stage: 1,
  /** Tenant provisioning contact only — never used as Unonight API base URL. */
  contact_email: "admin@unonight.com",
  country: "NO",
  plan_name: "Enterprise",
  plan_type: "enterprise",
  metadata: { pilot_customer: true, integration_adapter: "unonight_platform" },
  modules: [
    { module_key: "knowledge_center", enabled: true, mode: "active" },
    { module_key: "support_ai", enabled: true, mode: "draft_only", settings: { external_send: false } },
    { module_key: "governance", enabled: true, mode: "active" },
    { module_key: "audit", enabled: true, mode: "active" },
    { module_key: "install_discovery", enabled: true, mode: "read_only" },
    { module_key: "basic_insights", enabled: true, mode: "read_only" },
    { module_key: "workflow_event_recording", enabled: true, mode: "active" },
    { module_key: "knowledge_gap_detection", enabled: true, mode: "active" },
    { module_key: "automation", enabled: false, mode: "suggestions_only" },
    { module_key: "autonomous_automation_execution", enabled: false, mode: "disabled" },
    { module_key: "high_risk_actions", enabled: false, mode: "disabled" },
    { module_key: "automatic_content_approval", enabled: false, mode: "disabled" },
    { module_key: "billing_actions", enabled: false, mode: "disabled" },
    { module_key: "destructive_actions", enabled: false, mode: "disabled" },
  ],
  integrations: [
    {
      integration_key: "unonight_platform",
      display_name: "Unonight Platform",
      status: "pending",
      connection_mode: "api",
      capabilities: {
        workflows: [
          "account_verification",
          "support_case",
          "marketplace_listing_review",
          "digital_product_approval",
          "image_moderation",
          "admin_task",
        ],
        read_only: true,
      },
    },
    {
      integration_key: "supabase",
      display_name: "Supabase",
      status: "not_connected",
      connection_mode: "database_readonly",
    },
    {
      integration_key: "shopify",
      display_name: "Shopify",
      status: "not_connected",
      connection_mode: "api",
      capabilities: { mode: "read_only" },
    },
    {
      integration_key: "resend",
      display_name: "Resend",
      status: "not_connected",
      connection_mode: "api",
      capabilities: { mode: "draft_approval" },
    },
    {
      integration_key: "vercel",
      display_name: "Vercel",
      status: "not_connected",
      connection_mode: "api",
    },
    {
      integration_key: "email",
      display_name: "Email Support",
      status: "not_connected",
      connection_mode: "manual",
    },
  ],
  workflows: [
    {
      workflow_key: "unonight.account_verification",
      name: "Account Verification",
      description: "Member identity verification queue",
      category: "onboarding",
      expected_response_time_minutes: 1440,
    },
    {
      workflow_key: "unonight.support_case",
      name: "Support Case Handling",
      description: "Member support conversations",
      category: "support",
      expected_response_time_minutes: 60,
    },
    {
      workflow_key: "unonight.image_moderation",
      name: "Image Moderation",
      description: "Profile and content image review queue",
      category: "moderation",
      expected_response_time_minutes: 1440,
    },
    {
      workflow_key: "unonight.digital_product_approval",
      name: "Digital Product Approval",
      description: "Marketplace digital product review",
      category: "moderation",
      expected_response_time_minutes: 1440,
    },
    {
      workflow_key: "unonight.marketplace_listing_review",
      name: "Marketplace Listing Review",
      description: "Physical and digital listing moderation",
      category: "ecommerce",
      expected_response_time_minutes: 1440,
    },
    {
      workflow_key: "unonight.member_upgrade_support",
      name: "Member Upgrade Support",
      description: "Membership level and shop upgrade assistance",
      category: "support",
      expected_response_time_minutes: 240,
    },
    {
      workflow_key: "unonight.gift_wishlist_support",
      name: "Gift and Wishlist Support",
      description: "Gifts, wishlists, and birthday reminders",
      category: "support",
      expected_response_time_minutes: 240,
    },
    {
      workflow_key: "unonight.admin_task_followup",
      name: "Admin Task Follow-up",
      description: "Internal admin task tracking",
      category: "internal",
      expected_response_time_minutes: 1440,
    },
  ],
  checklist: [
    { checklist_key: "create_tenant", title: "Create Unonight tenant", priority: 100 },
    { checklist_key: "enable_knowledge_center", title: "Enable Knowledge Center", priority: 95 },
    { checklist_key: "seed_faq", title: "Seed Unonight FAQ", priority: 90 },
    { checklist_key: "enable_governance", title: "Enable Governance", priority: 85 },
    { checklist_key: "enable_emergency_stop", title: "Enable Emergency Stop", priority: 84 },
    { checklist_key: "enable_audit", title: "Enable Audit Timeline", priority: 83 },
    { checklist_key: "connect_unonight_adapter", title: "Connect Unonight platform adapter", priority: 80 },
    { checklist_key: "connect_supabase", title: "Connect Supabase read-only", priority: 75 },
    { checklist_key: "connect_resend", title: "Connect Resend in draft/approval mode", priority: 70 },
    { checklist_key: "connect_shopify", title: "Connect Shopify read-only", priority: 65 },
    { checklist_key: "run_discovery", title: "Run discovery scan", priority: 60 },
    { checklist_key: "review_workflows", title: "Review discovered workflows", priority: 55 },
    { checklist_key: "enable_support_ai_draft", title: "Enable Support Specialist draft mode", priority: 50 },
    { checklist_key: "test_verification_faq", title: "Test support question about verification", priority: 45 },
    { checklist_key: "test_marketplace_faq", title: "Test support question about marketplace", priority: 40 },
    { checklist_key: "test_knowledge_gap", title: "Test Knowledge Gap creation", priority: 35 },
    { checklist_key: "test_approval_center", title: "Test Approval Center", priority: 30 },
    { checklist_key: "test_blocked_action", title: "Test blocked high-risk action", priority: 25 },
    { checklist_key: "test_audit_log", title: "Test audit log", priority: 20 },
    { checklist_key: "review_dashboard", title: "Review pilot status dashboard", priority: 10 },
  ],
  governance: {
    mode: "enterprise_control",
    approval_defaults: { require_medium_risk: true, require_high_risk: true },
    permissions: [
      { action_key: "approve_digital_product", permission_level: "approval_required", risk_level: "high", requires_approval: true },
      { action_key: "approve_image_content", permission_level: "approval_required", risk_level: "high", requires_approval: true },
      { action_key: "change_membership_status", permission_level: "approval_required", risk_level: "high", requires_approval: true },
      { action_key: "modify_marketplace_listing", permission_level: "approval_required", risk_level: "high", requires_approval: true },
      { action_key: "ban_user", permission_level: "blocked", risk_level: "blocked", requires_approval: true },
      { action_key: "delete_user", permission_level: "blocked", risk_level: "blocked", requires_approval: true },
      { action_key: "issue_refund", permission_level: "blocked", risk_level: "blocked", requires_approval: true },
      { action_key: "approve_adult_content_auto", permission_level: "blocked", risk_level: "blocked", requires_approval: true },
      { action_key: "send_legal_notice", permission_level: "blocked", risk_level: "blocked", requires_approval: true },
    ],
  },
};

export const UNONIGHT_PILOT_SLUG = UNONIGHT_PILOT_PRESET.slug;
