import type { PackCommandLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildPackCommandLabels(t: Translator): PackCommandLabels {
  const p = "customerApp.portalStructure.businessPackCommandCenter";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search: t(`${p}.filters.search`),
      packKey: t(`${p}.filters.packKey`),
      healthStatus: t(`${p}.filters.healthStatus`),
      adoptionLevel: t(`${p}.filters.adoptionLevel`),
      valueCategory: t(`${p}.filters.valueCategory`),
      owner: t(`${p}.filters.owner`),
      priorityLevel: t(`${p}.filters.priorityLevel`),
      periodFrom: t(`${p}.filters.periodFrom`),
      all: t(`${p}.filters.all`),
      lowAdoption: t(`${p}.filters.lowAdoption`),
      healthyAdoption: t(`${p}.filters.healthyAdoption`),
      highAdoption: t(`${p}.filters.highAdoption`),
    },
    dashboard: {
      totalInstalled: t(`${p}.dashboard.totalInstalled`),
      activePacks: t(`${p}.dashboard.activePacks`),
      adoptionOverview: t(`${p}.dashboard.adoptionOverview`),
      valueOverview: t(`${p}.dashboard.valueOverview`),
      packsRequiringAttention: t(`${p}.dashboard.packsRequiringAttention`),
      optimizationOpportunities: t(`${p}.dashboard.optimizationOpportunities`),
      executiveSummary: t(`${p}.dashboard.executiveSummary`),
      recommendedActions: t(`${p}.dashboard.recommendedActions`),
      ecosystemStatus: t(`${p}.dashboard.ecosystemStatus`),
      healthOverview: t(`${p}.dashboard.healthOverview`),
      commandInsights: t(`${p}.dashboard.commandInsights`),
      timeline: t(`${p}.dashboard.timeline`),
    },
    card: {
      healthStatus: t(`${p}.card.healthStatus`),
      adoptionScore: t(`${p}.card.adoptionScore`),
      valueScore: t(`${p}.card.valueScore`),
      usageTrend: t(`${p}.card.usageTrend`),
      lastActivity: t(`${p}.card.lastActivity`),
      assignedOwner: t(`${p}.card.assignedOwner`),
      recommendedAction: t(`${p}.card.recommendedAction`),
      viewDetails: t(`${p}.card.viewDetails`),
    },
    ecosystemStatuses: {
      thriving: t(`${p}.ecosystemStatuses.thriving`),
      healthy: t(`${p}.ecosystemStatuses.healthy`),
      stable: t(`${p}.ecosystemStatuses.stable`),
      requires_attention: t(`${p}.ecosystemStatuses.requiresAttention`),
      critical_review_needed: t(`${p}.ecosystemStatuses.criticalReviewNeeded`),
    },
    healthStatuses: {
      thriving: t(`${p}.healthStatuses.thriving`),
      healthy: t(`${p}.healthStatuses.healthy`),
      stable: t(`${p}.healthStatuses.stable`),
      requires_attention: t(`${p}.healthStatuses.requiresAttention`),
      at_risk: t(`${p}.healthStatuses.atRisk`),
    },
    priorityLevels: {
      opportunity: t(`${p}.priorityLevels.opportunity`),
      recommended: t(`${p}.priorityLevels.recommended`),
      important: t(`${p}.priorityLevels.important`),
      immediate_attention: t(`${p}.priorityLevels.immediateAttention`),
    },
    usageTrends: {
      growing: t(`${p}.usageTrends.growing`),
      stable: t(`${p}.usageTrends.stable`),
      declining: t(`${p}.usageTrends.declining`),
    },
    valueCategories: {
      productivity_value: t(`${p}.valueCategories.productivityValue`),
      operational_efficiency: t(`${p}.valueCategories.operationalEfficiency`),
      customer_experience: t(`${p}.valueCategories.customerExperience`),
      revenue_enablement: t(`${p}.valueCategories.revenueEnablement`),
      cost_reduction: t(`${p}.valueCategories.costReduction`),
      risk_reduction: t(`${p}.valueCategories.riskReduction`),
      employee_experience: t(`${p}.valueCategories.employeeExperience`),
      strategic_value: t(`${p}.valueCategories.strategicValue`),
    },
    recommendations: {
      scheduleReviews: t(`${p}.recommendations.scheduleReviews`),
      increaseAdoptionLearning: t(`${p}.recommendations.increaseAdoptionLearning`),
      reassignOwnership: t(`${p}.recommendations.reassignOwnership`),
      exploreExpansion: t(`${p}.recommendations.exploreExpansion`),
      retireUnderutilized: t(`${p}.recommendations.retireUnderutilized`),
      celebrateSuccess: t(`${p}.recommendations.celebrateSuccess`),
    },
    insights: {
      mostValuable: t(`${p}.insights.mostValuable`),
      leastAdopted: t(`${p}.insights.leastAdopted`),
      fastestGrowing: t(`${p}.insights.fastestGrowing`),
      requiringReview: t(`${p}.insights.requiringReview`),
      trainingOpportunities: t(`${p}.insights.trainingOpportunities`),
      governanceObservations: t(`${p}.insights.governanceObservations`),
    },
    timelineEvents: {
      installation_completed: t(`${p}.timelineEvents.installationCompleted`),
      milestone_achieved: t(`${p}.timelineEvents.milestoneAchieved`),
      optimization_initiative: t(`${p}.timelineEvents.optimizationInitiative`),
      review_completed: t(`${p}.timelineEvents.reviewCompleted`),
      recommendation_resolved: t(`${p}.timelineEvents.recommendationResolved`),
      value_milestone: t(`${p}.timelineEvents.valueMilestone`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      replacePages: t(`${p}.faq.replacePages`),
      replacePagesAnswer: t(`${p}.faq.replacePagesAnswer`),
      autoManage: t(`${p}.faq.autoManage`),
      autoManageAnswer: t(`${p}.faq.autoManageAnswer`),
    },
  };
}
