import type { Translator } from "@/lib/i18n/translate";

export function buildCompanionCommandCenterLabels(t: Translator) {
  const p = "customerApp.companionCommandCenter";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    organizationHealth: t(`${p}.organizationHealth`),
    sinceLastLogin: t(`${p}.sinceLastLogin`),
    recommendedActions: t(`${p}.recommendedActions`),
    approvals: t(`${p}.approvals`),
    criticalAlerts: t(`${p}.criticalAlerts`),
    companionRecommendations: t(`${p}.companionRecommendations`),
    businessPackHighlights: t(`${p}.businessPackHighlights`),
    personalPriorities: t(`${p}.personalPriorities`),
    executiveBriefing: t(`${p}.executiveBriefing`),
    actionCenter: t(`${p}.actionCenter`),
    actionCenterTitle: t(`${p}.actionCenterTitle`),
    actionCenterSubtitle: t(`${p}.actionCenterSubtitle`),
    personalWorkspace: t(`${p}.personalWorkspace`),
    decisionSupport: t(`${p}.decisionSupport`),
    meetingIntelligence: t(`${p}.meetingIntelligence`),
    notificationsHub: t(`${p}.notificationsHub`),
    companionConversation: t(`${p}.companionConversation`),
    searchIntegration: t(`${p}.searchIntegration`),
    searchPlaceholder: t(`${p}.searchPlaceholder`),
    overallHealth: t(`${p}.overallHealth`),
    pendingApprovals: t(`${p}.pendingApprovals`),
    upcomingDeadlines: t(`${p}.upcomingDeadlines`),
    generateSummary: t(`${p}.generateSummary`),
    acknowledgeAlert: t(`${p}.acknowledgeAlert`),
    completeAction: t(`${p}.completeAction`),
    viewRecord: t(`${p}.viewRecord`),
    noItems: t(`${p}.noItems`),
    emptyHint: t(`${p}.emptyHint`),
    executiveMode: t(`${p}.executiveMode`),
    managerMode: t(`${p}.managerMode`),
    employeeMode: t(`${p}.employeeMode`),
    opportunities: t(`${p}.opportunities`),
    risks: t(`${p}.risks`),
    teamActivity: t(`${p}.teamActivity`),
    myTasks: t(`${p}.myTasks`),
    myMeetings: t(`${p}.myMeetings`),
    myApprovals: t(`${p}.myApprovals`),
    auditLog: t(`${p}.auditLog`),
    mobileReady: t(`${p}.mobileReady`),
    desktopConnect: t(`${p}.desktopConnect`),
    save: t(`${p}.save`),
  };
}

export type CompanionCommandCenterLabels = ReturnType<typeof buildCompanionCommandCenterLabels>;
