import type { Translator } from "@/lib/i18n/translate";

export function buildPeopleOperationsLabels(t: Translator) {
  const p = "customerApp.peopleOperations";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    accessDenied: t(`${p}.accessDenied`),
    overview: t(`${p}.overview`),
    workforce: t(`${p}.workforce`),
    attendance: t(`${p}.attendance`),
    leave: t(`${p}.leave`),
    development: t(`${p}.development`),
    performance: t(`${p}.performance`),
    reviews: t(`${p}.reviews`),
    planning: t(`${p}.planning`),
    goals: t(`${p}.goals`),
    reports: t(`${p}.reports`),
    recognition: t(`${p}.recognition`),
    workforceSize: t(`${p}.workforceSize`),
    presentToday: t(`${p}.presentToday`),
    onLeaveToday: t(`${p}.onLeaveToday`),
    pendingLeave: t(`${p}.pendingLeave`),
    upcomingReviews: t(`${p}.upcomingReviews`),
    activeGoals: t(`${p}.activeGoals`),
    trainingInProgress: t(`${p}.trainingInProgress`),
    openPositions: t(`${p}.openPositions`),
    employee: t(`${p}.employee`),
    department: t(`${p}.department`),
    manager: t(`${p}.manager`),
    role: t(`${p}.role`),
    location: t(`${p}.location`),
    status: t(`${p}.status`),
    approveLeave: t(`${p}.approveLeave`),
    rejectLeave: t(`${p}.rejectLeave`),
    createReview: t(`${p}.createReview`),
    completeReview: t(`${p}.completeReview`),
    createGoal: t(`${p}.createGoal`),
    goalTitle: t(`${p}.goalTitle`),
    createRecognition: t(`${p}.createRecognition`),
    noWorkforce: t(`${p}.noWorkforce`),
    noWorkforceHint: t(`${p}.noWorkforceHint`),
    noAttendance: t(`${p}.noAttendance`),
    noLeave: t(`${p}.noLeave`),
    noReviews: t(`${p}.noReviews`),
    noGoals: t(`${p}.noGoals`),
    headcount: t(`${p}.headcount`),
    leaveUsage: t(`${p}.leaveUsage`),
    reviewCompletion: t(`${p}.reviewCompletion`),
    goalAchievement: t(`${p}.goalAchievement`),
    trainingCompleted: t(`${p}.trainingCompleted`),
    auditLog: t(`${p}.auditLog`),
    viewEmployees: t(`${p}.viewEmployees`),
    mobileReady: t(`${p}.mobileReady`),
  };
}

export type PeopleOperationsLabels = ReturnType<typeof buildPeopleOperationsLabels>;
