import type { OnboardingLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildOnboardingLabels(t: Translator): OnboardingLabels {
  const p = "customerApp.portalStructure.gettingStarted";
  return {
    eyebrow: t(`${p}.eyebrow`),
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    breadcrumbSupport: t(`${p}.breadcrumbSupport`),
    breadcrumbGettingStarted: t(`${p}.breadcrumbGettingStarted`),
    backToSupport: t(`${p}.backToSupport`),
    sections: {
      progress: t(`${p}.sections.progress`),
      nextAction: t(`${p}.sections.nextAction`),
      remaining: t(`${p}.sections.remaining`),
      completed: t(`${p}.sections.completed`),
      adoption: t(`${p}.sections.adoption`),
      understanding: t(`${p}.sections.understanding`),
    },
    progress: {
      percentComplete: t(`${p}.progress.percentComplete`),
      stepsCompleted: t(`${p}.progress.stepsCompleted`),
      workflowState: t(`${p}.progress.workflowState`),
      lastUpdated: t(`${p}.progress.lastUpdated`),
      continueSetup: t(`${p}.progress.continueSetup`),
      advisory: t(`${p}.progress.advisory`),
    },
    workflowStates: {
      not_started: t(`${p}.workflowStates.notStarted`),
      in_progress: t(`${p}.workflowStates.inProgress`),
      requires_attention: t(`${p}.workflowStates.requiresAttention`),
      completed: t(`${p}.workflowStates.completed`),
      blocked: t(`${p}.workflowStates.blocked`),
    },
    taskPriorities: {
      required: t(`${p}.taskPriorities.required`),
      recommended: t(`${p}.taskPriorities.recommended`),
      optional: t(`${p}.taskPriorities.optional`),
    },
    categories: {
      organization: t(`${p}.categories.organization`),
      team: t(`${p}.categories.team`),
      security: t(`${p}.categories.security`),
      integrations: t(`${p}.categories.integrations`),
      business_packs: t(`${p}.categories.businessPacks`),
      knowledge_support: t(`${p}.categories.knowledgeSupport`),
    },
    tasks: {
      org_profile: t(`${p}.tasks.orgProfile`),
      org_settings: t(`${p}.tasks.orgSettings`),
      org_localization: t(`${p}.tasks.orgLocalization`),
      team_invite: t(`${p}.tasks.teamInvite`),
      team_admin_roles: t(`${p}.tasks.teamAdminRoles`),
      team_permissions: t(`${p}.tasks.teamPermissions`),
      security_2fa: t(`${p}.tasks.security2fa`),
      security_access: t(`${p}.tasks.securityAccess`),
      security_preferences: t(`${p}.tasks.securityPreferences`),
      integration_connect: t(`${p}.tasks.integrationConnect`),
      integration_health: t(`${p}.tasks.integrationHealth`),
      integration_sync: t(`${p}.tasks.integrationSync`),
      pack_install: t(`${p}.tasks.packInstall`),
      pack_review: t(`${p}.tasks.packReview`),
      pack_configure: t(`${p}.tasks.packConfigure`),
      knowledge_explore: t(`${p}.tasks.knowledgeExplore`),
      support_assistant: t(`${p}.tasks.supportAssistant`),
      support_contact: t(`${p}.tasks.supportContact`),
    },
    recommendations: {
      inviteAdmins: t(`${p}.recommendations.inviteAdmins`),
      enable2fa: t(`${p}.recommendations.enable2fa`),
      installFirstPack: t(`${p}.recommendations.installFirstPack`),
      reviewSupportAssistant: t(`${p}.recommendations.reviewSupportAssistant`),
      exploreExecutiveInsights: t(`${p}.recommendations.exploreExecutiveInsights`),
    },
    milestones: {
      org_setup_complete: t(`${p}.milestones.orgSetupComplete`),
      first_integration: t(`${p}.milestones.firstIntegration`),
      onboarding_complete: t(`${p}.milestones.onboardingComplete`),
    },
    adoption: {
      explored: t(`${p}.adoption.explored`),
      recommended: t(`${p}.adoption.recommended`),
      suggestedPacks: t(`${p}.adoption.suggestedPacks`),
      noneExplored: t(`${p}.adoption.noneExplored`),
      noneRecommended: t(`${p}.adoption.noneRecommended`),
    },
    understanding: {
      revisit: t(`${p}.understanding.revisit`),
      revisitAnswer: t(`${p}.understanding.revisitAnswer`),
      progressMeaning: t(`${p}.understanding.progressMeaning`),
      progressMeaningAnswer: t(`${p}.understanding.progressMeaningAnswer`),
      permissions: t(`${p}.understanding.permissions`),
      permissionsAnswer: t(`${p}.understanding.permissionsAnswer`),
    },
    empty: {
      title: t(`${p}.empty.title`),
      body: t(`${p}.empty.body`),
      action: t(`${p}.empty.action`),
    },
    error: {
      title: t(`${p}.error.title`),
      body: t(`${p}.error.body`),
      retry: t(`${p}.error.retry`),
    },
    actions: {
      open: t(`${p}.actions.open`),
      markComplete: t(`${p}.actions.markComplete`),
      hide: t(`${p}.actions.hide`),
      startCourse: t(`${p}.actions.startCourse`),
    },
    taskStatuses: {
      not_started: t(`${p}.taskStatuses.notStarted`),
      in_progress: t(`${p}.taskStatuses.inProgress`),
      completed: t(`${p}.taskStatuses.completed`),
      optional: t(`${p}.taskStatuses.optional`),
      blocked: t(`${p}.taskStatuses.blocked`),
    },
  };
}
