import type { ExecutiveStrategicDecisionCockpitLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildExecutiveStrategicDecisionCockpitLabels(t: Translator): ExecutiveStrategicDecisionCockpitLabels {
  const p = "customerApp.executiveStrategicDecisionCockpit";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    humanOversight: t(`${p}.humanOversight`),
    principle: t(`${p}.principle`),
    executiveLink: t(`${p}.executiveLink`),
    actionCenterLink: t(`${p}.actionCenterLink`),
    portfolioLink: t(`${p}.portfolioLink`),
    earlyWarningLink: t(`${p}.earlyWarningLink`),
    tabs: {
      overview: t(`${p}.tabs.overview`),
      decisions: t(`${p}.tabs.decisions`),
      health: t(`${p}.tabs.health`),
      alerts: t(`${p}.tabs.alerts`),
      opportunities: t(`${p}.tabs.opportunities`),
      meeting: t(`${p}.tabs.meeting`),
      insights: t(`${p}.tabs.insights`),
    },
    overview: {
      title: t(`${p}.overview.title`),
      onTrack: t(`${p}.overview.onTrack`),
      atRisk: t(`${p}.overview.atRisk`),
      criticalDecisions: t(`${p}.overview.criticalDecisions`),
      highImpactOpportunities: t(`${p}.overview.highImpactOpportunities`),
      escalatedApprovals: t(`${p}.overview.escalatedApprovals`),
      orgHealth: t(`${p}.overview.orgHealth`),
      actionQueue: t(`${p}.overview.actionQueue`),
    },
    decisions: {
      title: t(`${p}.decisions.title`),
      critical: t(`${p}.decisions.critical`),
      highPriority: t(`${p}.decisions.highPriority`),
      mediumPriority: t(`${p}.decisions.mediumPriority`),
      informational: t(`${p}.decisions.informational`),
      owner: t(`${p}.decisions.owner`),
      approvers: t(`${p}.decisions.approvers`),
      strategicImpact: t(`${p}.decisions.strategicImpact`),
      riskLevel: t(`${p}.decisions.riskLevel`),
      deadline: t(`${p}.decisions.deadline`),
      nextStep: t(`${p}.decisions.nextStep`),
      viewBriefing: t(`${p}.decisions.viewBriefing`),
      empty: t(`${p}.decisions.empty`),
    },
    health: {
      title: t(`${p}.health.title`),
      operationalEfficiency: t(`${p}.health.operationalEfficiency`),
      employeeEngagement: t(`${p}.health.employeeEngagement`),
      customerSatisfaction: t(`${p}.health.customerSatisfaction`),
      revenueMomentum: t(`${p}.health.revenueMomentum`),
      riskExposure: t(`${p}.health.riskExposure`),
      complianceStatus: t(`${p}.health.complianceStatus`),
      strategicExecution: t(`${p}.health.strategicExecution`),
      statuses: {
        excellent: t(`${p}.health.statuses.excellent`),
        healthy: t(`${p}.health.statuses.healthy`),
        monitor_closely: t(`${p}.health.statuses.monitorClosely`),
        needs_attention: t(`${p}.health.statuses.needsAttention`),
        critical: t(`${p}.health.statuses.critical`),
      },
    },
    alerts: {
      title: t(`${p}.alerts.title`),
      empty: t(`${p}.alerts.empty`),
      viewAction: t(`${p}.alerts.viewAction`),
    },
    opportunities: {
      title: t(`${p}.opportunities.title`),
      expectedBenefit: t(`${p}.opportunities.expectedBenefit`),
      estimatedEffort: t(`${p}.opportunities.estimatedEffort`),
      riskAssessment: t(`${p}.opportunities.riskAssessment`),
      confidence: t(`${p}.opportunities.confidence`),
      types: {
        revenue: t(`${p}.opportunities.types.revenue`),
        cost_optimization: t(`${p}.opportunities.types.costOptimization`),
        partnership: t(`${p}.opportunities.types.partnership`),
        process_improvement: t(`${p}.opportunities.types.processImprovement`),
        expansion: t(`${p}.opportunities.types.expansion`),
        innovation: t(`${p}.opportunities.types.innovation`),
      },
      empty: t(`${p}.opportunities.empty`),
    },
    briefing: {
      title: t(`${p}.briefing.title`),
      situation: t(`${p}.briefing.situation`),
      context: t(`${p}.briefing.context`),
      recommendation: t(`${p}.briefing.recommendation`),
      benefits: t(`${p}.briefing.benefits`),
      risks: t(`${p}.briefing.risks`),
      alternatives: t(`${p}.briefing.alternatives`),
      recommendedActions: t(`${p}.briefing.recommendedActions`),
      confidence: t(`${p}.briefing.confidence`),
      urgency: t(`${p}.briefing.urgency`),
      disclaimer: t(`${p}.briefing.disclaimer`),
      back: t(`${p}.briefing.back`),
      urgencies: {
        critical: t(`${p}.briefing.urgencies.critical`),
        high_priority: t(`${p}.briefing.urgencies.highPriority`),
        medium_priority: t(`${p}.briefing.urgencies.mediumPriority`),
        informational: t(`${p}.briefing.urgencies.informational`),
      },
    },
    meeting: {
      title: t(`${p}.meeting.title`),
      topics: t(`${p}.meeting.topics`),
      pendingApprovals: t(`${p}.meeting.pendingApprovals`),
      blocked: t(`${p}.meeting.blocked`),
      achievements: t(`${p}.meeting.achievements`),
      criticalRisks: t(`${p}.meeting.criticalRisks`),
      agenda: t(`${p}.meeting.agenda`),
      followUps: t(`${p}.meeting.followUps`),
    },
    insights: {
      title: t(`${p}.insights.title`),
      departments: t(`${p}.insights.departments`),
      strategicInitiatives: t(`${p}.insights.strategicInitiatives`),
      trends: t(`${p}.insights.trends`),
      emergingIssues: t(`${p}.insights.emergingIssues`),
      decisionHistory: t(`${p}.insights.decisionHistory`),
      learningTitle: t(`${p}.insights.learningTitle`),
      decisionAccuracy: t(`${p}.insights.decisionAccuracy`),
      bottlenecks: t(`${p}.insights.bottlenecks`),
      interventionEffectiveness: t(`${p}.insights.interventionEffectiveness`),
      successPatterns: t(`${p}.insights.successPatterns`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIsCockpit: t(`${p}.faq.whatIsCockpit`),
      whatIsCockpitAnswer: t(`${p}.faq.whatIsCockpitAnswer`),
      howPrioritize: t(`${p}.faq.howPrioritize`),
      howPrioritizeAnswer: t(`${p}.faq.howPrioritizeAnswer`),
      howOpportunities: t(`${p}.faq.howOpportunities`),
      howOpportunitiesAnswer: t(`${p}.faq.howOpportunitiesAnswer`),
      canAipifyDecide: t(`${p}.faq.canAipifyDecide`),
      canAipifyDecideAnswer: t(`${p}.faq.canAipifyDecideAnswer`),
      confidenceScores: t(`${p}.faq.confidenceScores`),
      confidenceScoresAnswer: t(`${p}.faq.confidenceScoresAnswer`),
    },
    empty: t(`${p}.empty`),
    upgradeTitle: t(`${p}.upgrade.title`),
    upgradeBody: t(`${p}.upgrade.body`),
    upgradeCta: t(`${p}.upgrade.cta`),
  };
}
