import type { OrgForecastingLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildOrgForecastingLabels(t: Translator): OrgForecastingLabels {
  const p = "customerApp.portalStructure.organizationalForecasting";
  return {
    title:        t(`${p}.title`),
    subtitle:     t(`${p}.subtitle`),
    loading:      t(`${p}.loading`),
    principle:    t(`${p}.principle`),
    advisoryNote: t(`${p}.advisoryNote`),
    emptyTitle:   t(`${p}.emptyTitle`),
    emptyBody:    t(`${p}.emptyBody`),
    emptyCta:     t(`${p}.emptyCta`),
    accessDenied: t(`${p}.accessDenied`),
    filters: {
      search:           t(`${p}.filters.search`),
      category:         t(`${p}.filters.category`),
      department:       t(`${p}.filters.department`),
      timeHorizon:      t(`${p}.filters.timeHorizon`),
      confidenceLevel:  t(`${p}.filters.confidenceLevel`),
      executiveOwner:   t(`${p}.filters.executiveOwner`),
      reviewStatus:     t(`${p}.filters.reviewStatus`),
      all:              t(`${p}.filters.all`),
    },
    dashboard: {
      forecastScore:     t(`${p}.dashboard.forecastScore`),
      executiveSummary:  t(`${p}.dashboard.executiveSummary`),
      growthForecast:    t(`${p}.dashboard.growthForecast`),
      capacityForecast:  t(`${p}.dashboard.capacityForecast`),
      workforceForecast: t(`${p}.dashboard.workforceForecast`),
      customerForecast:  t(`${p}.dashboard.customerForecast`),
      revenueForecast:   t(`${p}.dashboard.revenueForecast`),
      supportForecast:   t(`${p}.dashboard.supportForecast`),
      improvingTrends:   t(`${p}.dashboard.improvingTrends`),
      stableTrends:      t(`${p}.dashboard.stableTrends`),
      decliningTrends:   t(`${p}.dashboard.decliningTrends`),
      emergingTrends:    t(`${p}.dashboard.emergingTrends`),
      capacityView:      t(`${p}.dashboard.capacityView`),
      forecasts:         t(`${p}.dashboard.forecasts`),
      timeline:          t(`${p}.dashboard.timeline`),
      reviewQuestions:   t(`${p}.dashboard.reviewQuestions`),
      viewForecast:      t(`${p}.dashboard.viewForecast`),
      beginReview:       t(`${p}.dashboard.beginReview`),
    },
    forecastCard: {
      currentState:      t(`${p}.forecastCard.currentState`),
      conservative:      t(`${p}.forecastCard.conservative`),
      expected:          t(`${p}.forecastCard.expected`),
      optimistic:        t(`${p}.forecastCard.optimistic`),
      confidence:        t(`${p}.forecastCard.confidence`),
      timeHorizon:       t(`${p}.forecastCard.timeHorizon`),
      trend:             t(`${p}.forecastCard.trend`),
      owner:             t(`${p}.forecastCard.owner`),
      recommendedAction: t(`${p}.forecastCard.recommendedAction`),
    },
    capacityCard: {
      currentCapacity:     t(`${p}.capacityCard.currentCapacity`),
      estimatedFuture:     t(`${p}.capacityCard.estimatedFuture`),
      bottlenecks:         t(`${p}.capacityCard.bottlenecks`),
      constraints:         t(`${p}.capacityCard.constraints`),
      requiresAttention:   t(`${p}.capacityCard.requiresAttention`),
    },
    detail: {
      back:          t(`${p}.detail.back`),
      models:        t(`${p}.detail.models`),
      reviewHistory: t(`${p}.detail.reviewHistory`),
      reviewNotes:   t(`${p}.detail.reviewNotes`),
      submitReview:  t(`${p}.detail.submitReview`),
      reviewSuccess: t(`${p}.detail.reviewSuccess`),
      advisoryNote:  t(`${p}.detail.advisoryNote`),
    },
    beginReview: {
      success:       t(`${p}.beginReview.success`),
      governanceNote:t(`${p}.beginReview.governanceNote`),
    },
    categories: {
      workforce_growth:         t(`${p}.categories.workforceGrowth`),
      customer_growth:          t(`${p}.categories.customerGrowth`),
      revenue_development:      t(`${p}.categories.revenueDevelopment`),
      support_demand:           t(`${p}.categories.supportDemand`),
      operational_capacity:     t(`${p}.categories.operationalCapacity`),
      knowledge_growth:         t(`${p}.categories.knowledgeGrowth`),
      department_expansion:     t(`${p}.categories.departmentExpansion`),
      resource_requirements:    t(`${p}.categories.resourceRequirements`),
      training_requirements:    t(`${p}.categories.trainingRequirements`),
      organizational_complexity:t(`${p}.categories.organizationalComplexity`),
    },
    confidenceLevels: {
      low:      t(`${p}.confidenceLevels.low`),
      moderate: t(`${p}.confidenceLevels.moderate`),
      high:     t(`${p}.confidenceLevels.high`),
    },
    trendDirections: {
      improving: t(`${p}.trendDirections.improving`),
      stable:    t(`${p}.trendDirections.stable`),
      declining: t(`${p}.trendDirections.declining`),
      emerging:  t(`${p}.trendDirections.emerging`),
    },
    reviewStatuses: {
      pending:        t(`${p}.reviewStatuses.pending`),
      in_review:      t(`${p}.reviewStatuses.inReview`),
      reviewed:       t(`${p}.reviewStatuses.reviewed`),
      needs_follow_up:t(`${p}.reviewStatuses.needsFollowUp`),
    },
    timeHorizons: {
      "30_days":  t(`${p}.timeHorizons.30Days`),
      "90_days":  t(`${p}.timeHorizons.90Days`),
      "6_months": t(`${p}.timeHorizons.6Months`),
      "12_months":t(`${p}.timeHorizons.12Months`),
      "24_months":t(`${p}.timeHorizons.24Months`),
      "36_months":t(`${p}.timeHorizons.36Months`),
    },
    timelineEvents: {
      forecasting_initialized:    t(`${p}.timelineEvents.forecastingInitialized`),
      forecast_review_begun:      t(`${p}.timelineEvents.forecastReviewBegun`),
      forecast_review_completed:  t(`${p}.timelineEvents.forecastReviewCompleted`),
      capacity_milestone:         t(`${p}.timelineEvents.capacityMilestone`),
      organizational_event:       t(`${p}.timelineEvents.organizationalEvent`),
      growth_milestone:           t(`${p}.timelineEvents.growthMilestone`),
      strategic_planning_session: t(`${p}.timelineEvents.strategicPlanningSession`),
    },
    reviewQuestions: [
      t(`${p}.reviewQuestions.resourcesSufficient`),
      t(`${p}.reviewQuestions.capacityConstraints`),
      t(`${p}.reviewQuestions.teamsNeedSupport`),
      t(`${p}.reviewQuestions.hiringPlansAligned`),
      t(`${p}.reviewQuestions.systemsRequireScaling`),
      t(`${p}.reviewQuestions.preparationsToday`),
    ],
    faq: {
      title:             t(`${p}.faq.title`),
      whatIs:            t(`${p}.faq.whatIs`),
      whatIsAnswer:      t(`${p}.faq.whatIsAnswer`),
      guaranteed:        t(`${p}.faq.guaranteed`),
      guaranteedAnswer:  t(`${p}.faq.guaranteedAnswer`),
      whoShouldUse:      t(`${p}.faq.whoShouldUse`),
      whoShouldUseAnswer:t(`${p}.faq.whoShouldUseAnswer`),
    },
  };
}
