import type { Translator } from "@/lib/i18n/translate";
import { buildSinceLastLoginUxLabels } from "@/lib/command-center/since-last-login-labels";
import { buildCommandCenterLabelLookup } from "./label-lookup";

export function buildExecutiveCommandCenterLabels(t: Translator) {
  const p = "customerApp.executiveCommandCenter";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    principle: t(`${p}.principle`),
    privacyNote: t(`${p}.privacyNote`),
    loading: t(`${p}.loading`),
    empty: t(`${p}.empty`),
    refresh: t(`${p}.refresh`),
    overallHealthScore: t(`${p}.overallHealthScore`),
    companionRecommendations: t(`${p}.companionRecommendations`),
    noRecords: t(`${p}.noRecords`),
    sinceLastLogin: t(`${p}.sinceLastLogin`),
    morningBriefing: t(`${p}.morningBriefing`),
    organizationalTimeline: t(`${p}.organizationalTimeline`),
    businessPackSignals: t(`${p}.businessPackSignals`),
    boardReadyReports: t(`${p}.boardReadyReports`),
    commandMode: t(`${p}.commandMode`),
    mobileExecutiveMode: t(`${p}.mobileExecutiveMode`),
    priority: {
      information: t(`${p}.priority.information`),
      attention: t(`${p}.priority.attention`),
      urgent: t(`${p}.priority.urgent`),
      critical: t(`${p}.priority.critical`),
    },
    sections: {
      overview: t(`${p}.sections.overview`),
      sinceLastLogin: t(`${p}.sections.sinceLastLogin`),
      alerts: t(`${p}.sections.alerts`),
      approvals: t(`${p}.sections.approvals`),
      risks: t(`${p}.sections.risks`),
      opportunities: t(`${p}.sections.opportunities`),
      performance: t(`${p}.sections.performance`),
      companionBriefing: t(`${p}.sections.companionBriefing`),
    },
    stats: {
      sinceLastLoginItems: t(`${p}.stats.sinceLastLoginItems`),
      openAlerts: t(`${p}.stats.openAlerts`),
      pendingActions: t(`${p}.stats.pendingActions`),
      openOpportunities: t(`${p}.stats.openOpportunities`),
      criticalItems: t(`${p}.stats.criticalItems`),
    },
    briefing: {
      revenue: t(`${p}.briefing.revenue`),
      customer: t(`${p}.briefing.customer`),
      risk: t(`${p}.briefing.risk`),
      operational: t(`${p}.briefing.operational`),
      growth: t(`${p}.briefing.growth`),
      companion: t(`${p}.briefing.companion`),
    },
    premium: {
      eyebrow: t(`${p}.premium.eyebrow`),
      description: t(`${p}.premium.description`),
      viewSinceLastLogin: t(`${p}.premium.viewSinceLastLogin`),
      refreshing: t(`${p}.premium.refreshing`),
      todaysOverview: t(`${p}.premium.todaysOverview`),
      companionInsight: t(`${p}.premium.companionInsight`),
      needsAttention: t(`${p}.premium.needsAttention`),
      needsAttentionSubtitle: t(`${p}.premium.needsAttentionSubtitle`),
      returnToDashboard: t(`${p}.premium.returnToDashboard`),
      retry: t(`${p}.premium.retry`),
      openRecord: t(`${p}.premium.openRecord`),
      emptySection: t(`${p}.premium.emptySection`),
      recommendationCategory: t(`${p}.premium.recommendationCategory`),
      context: {
        organizationActive: t(`${p}.premium.context.organizationActive`),
        executiveAccessVerified: t(`${p}.premium.context.executiveAccessVerified`),
      },
      access: {
        permissionMissing: {
          title: t(`${p}.premium.access.permissionMissing.title`),
          description: t(`${p}.premium.access.permissionMissing.description`),
        },
        entitlementMissing: {
          title: t(`${p}.premium.access.entitlementMissing.title`),
          description: t(`${p}.premium.access.entitlementMissing.description`),
        },
        planRequired: {
          title: t(`${p}.premium.access.planRequired.title`),
          description: t(`${p}.premium.access.planRequired.description`),
        },
        organizationContextMissing: {
          title: t(`${p}.premium.access.organizationContextMissing.title`),
          description: t(`${p}.premium.access.organizationContextMissing.description`),
        },
        activationInProgress: {
          title: t(`${p}.premium.access.activationInProgress.title`),
          description: t(`${p}.premium.access.activationInProgress.description`),
        },
        generic: {
          title: t(`${p}.premium.access.generic.title`),
          description: t(`${p}.premium.access.generic.description`),
        },
      },
      metrics: {
        healthDescription: t(`${p}.premium.metrics.healthDescription`),
        sinceLastLoginDescription: t(`${p}.premium.metrics.sinceLastLoginDescription`),
        openAlertsDescription: t(`${p}.premium.metrics.openAlertsDescription`),
        pendingActionsDescription: t(`${p}.premium.metrics.pendingActionsDescription`),
        criticalItemsDescription: t(`${p}.premium.metrics.criticalItemsDescription`),
        healthStatusGood: t(`${p}.premium.metrics.healthStatusGood`),
        healthStatusModerate: t(`${p}.premium.metrics.healthStatusModerate`),
        healthStatusLow: t(`${p}.premium.metrics.healthStatusLow`),
        countActive: t(`${p}.premium.metrics.countActive`),
        countNone: t(`${p}.premium.metrics.countNone`),
        sinceLastLoginUpdated: t(`${p}.premium.metrics.sinceLastLoginUpdated`),
        noCriticalItems: t(`${p}.premium.metrics.noCriticalItems`),
        workflowOpen: t("common.status.semantic.workflow.open"),
        workflowPending: t("common.status.semantic.workflow.pending"),
        severityCritical: t("common.status.semantic.severity.critical"),
      },
    },
    sinceLastLoginUx: buildSinceLastLoginUxLabels(t),
    tabs: {
      insights: {
        alerts: t(`${p}.tabs.insights.alerts`),
        approvals: t(`${p}.tabs.insights.approvals`),
        risks: t(`${p}.tabs.insights.risks`),
        opportunities: t(`${p}.tabs.insights.opportunities`),
        performance: t(`${p}.tabs.insights.performance`),
        companionBriefing: t(`${p}.tabs.insights.companionBriefing`),
      },
      empty: {
        alerts: t(`${p}.tabs.empty.alerts`),
        approvals: t(`${p}.tabs.empty.approvals`),
        risks: t(`${p}.tabs.empty.risks`),
        opportunities: t(`${p}.tabs.empty.opportunities`),
        performance: t(`${p}.tabs.empty.performance`),
        companionBriefing: t(`${p}.tabs.empty.companionBriefing`),
        activeRisks: t(`${p}.tabs.empty.activeRisks`),
        operationalHealth: t(`${p}.tabs.empty.operationalHealth`),
        executiveBriefing: t(`${p}.tabs.empty.executiveBriefing`),
        dailyBriefing: t(`${p}.tabs.empty.dailyBriefing`),
        boardReports: t(`${p}.tabs.empty.boardReports`),
      },
      sections: {
        activeRisks: t(`${p}.tabs.sections.activeRisks`),
        operationalHealth: t(`${p}.tabs.sections.operationalHealth`),
        executiveBriefing: t(`${p}.tabs.sections.executiveBriefing`),
        dailyBriefing: t(`${p}.tabs.sections.dailyBriefing`),
        boardReports: t(`${p}.tabs.sections.boardReports`),
        performanceHealth: t(`${p}.tabs.sections.performanceHealth`),
      },
      metrics: {
        upToDate: t(`${p}.tabs.metrics.upToDate`),
        noOpenAlerts: t(`${p}.tabs.metrics.noOpenAlerts`),
        noPendingActions: t(`${p}.tabs.metrics.noPendingActions`),
        noCriticalItems: t(`${p}.tabs.metrics.noCriticalItems`),
      },
      shared: {
        open: t(`${p}.tabs.shared.open`),
        type: t(`${p}.tabs.shared.type`),
        timestamp: t(`${p}.tabs.shared.timestamp`),
        items: t(`${p}.tabs.shared.items`),
      },
      approvals: {
        requester: t(`${p}.tabs.approvals.requester`),
        blocked: t(`${p}.tabs.approvals.blocked`),
      },
      opportunities: {
        value: t(`${p}.tabs.opportunities.value`),
        confidence: t(`${p}.tabs.opportunities.confidence`),
        nextStep: t(`${p}.tabs.opportunities.nextStep`),
      },
    },
    labelLookup: buildCommandCenterLabelLookup(t),
    commandBriefOverview: {
      title: t(`${p}.commandBriefOverview.title`),
      subtitle: t(`${p}.commandBriefOverview.subtitle`),
      contextVerified: t(`${p}.commandBriefOverview.contextVerified`),
      contextReadOnly: t(`${p}.commandBriefOverview.contextReadOnly`),
      organizationActive: t(`${p}.commandBriefOverview.organizationActive`),
      accessVerified: t(`${p}.commandBriefOverview.accessVerified`),
      kpiSinceLastLogin: t(`${p}.commandBriefOverview.kpiSinceLastLogin`),
      kpiPrepared: t(`${p}.commandBriefOverview.kpiPrepared`),
      kpiAttention: t(`${p}.commandBriefOverview.kpiAttention`),
      kpiHealth: t(`${p}.commandBriefOverview.kpiHealth`),
      kpiSinceLastLoginDesc: t(`${p}.commandBriefOverview.kpiSinceLastLoginDesc`),
      kpiPreparedDesc: t(`${p}.commandBriefOverview.kpiPreparedDesc`),
      kpiAttentionDesc: t(`${p}.commandBriefOverview.kpiAttentionDesc`),
      kpiHealthDesc: t(`${p}.commandBriefOverview.kpiHealthDesc`),
      kpiNone: t(`${p}.commandBriefOverview.kpiNone`),
      kpiActive: t(`${p}.commandBriefOverview.kpiActive`),
      kpiHealthUnavailable: t(`${p}.commandBriefOverview.kpiHealthUnavailable`),
      attentionTitle: t(`${p}.commandBriefOverview.attentionTitle`),
      attentionEmptyTitle: t(`${p}.commandBriefOverview.attentionEmptyTitle`),
      attentionEmptyBody: t(`${p}.commandBriefOverview.attentionEmptyBody`),
      sinceLastLoginTitle: t(`${p}.commandBriefOverview.sinceLastLoginTitle`),
      viewAllActivity: t(`${p}.commandBriefOverview.viewAllActivity`),
      viewAllAlerts: t(`${p}.commandBriefOverview.viewAllAlerts`),
      viewAllApprovals: t(`${p}.commandBriefOverview.viewAllApprovals`),
      viewAllIntegrations: t(`${p}.commandBriefOverview.viewAllIntegrations`),
      alertsSummaryTitle: t(`${p}.commandBriefOverview.alertsSummaryTitle`),
      approvalsSummaryTitle: t(`${p}.commandBriefOverview.approvalsSummaryTitle`),
      integrationsSummaryTitle: t(`${p}.commandBriefOverview.integrationsSummaryTitle`),
      integrationSignalMeta: t(`${p}.commandBriefOverview.integrationSignalMeta`),
      orgNameUnavailable: t(`${p}.commandBriefOverview.orgNameUnavailable`),
      nextActionTitle: t(`${p}.commandBriefOverview.nextActionTitle`),
      nextActionEmptyTitle: t(`${p}.commandBriefOverview.nextActionEmptyTitle`),
      nextActionEmptyBody: t(`${p}.commandBriefOverview.nextActionEmptyBody`),
      nextActionReason: t(`${p}.commandBriefOverview.nextActionReason`),
      nextActionValue: t(`${p}.commandBriefOverview.nextActionValue`),
      nextActionArea: t(`${p}.commandBriefOverview.nextActionArea`),
      companionTitle: t(`${p}.commandBriefOverview.companionTitle`),
      companionIntro: t(`${p}.commandBriefOverview.companionIntro`),
      companionActiveOrg: t(`${p}.commandBriefOverview.companionActiveOrg`),
      companionInputLabel: t(`${p}.commandBriefOverview.companionInputLabel`),
      companionInputPlaceholder: t(`${p}.commandBriefOverview.companionInputPlaceholder`),
      companionAsk: t(`${p}.commandBriefOverview.companionAsk`),
      companionSuggestions: {
        prioritizeToday: t(`${p}.commandBriefOverview.companionSuggestions.prioritizeToday`),
        sinceLastVisit: t(`${p}.commandBriefOverview.companionSuggestions.sinceLastVisit`),
        connected: t(`${p}.commandBriefOverview.companionSuggestions.connected`),
        explainHealth: t(`${p}.commandBriefOverview.companionSuggestions.explainHealth`),
      },
      activityCategories: {
        completed_by_aipify: t(`${p}.commandBriefOverview.activityCategories.completed_by_aipify`),
        observed_by_aipify: t(`${p}.commandBriefOverview.activityCategories.observed_by_aipify`),
        requires_attention: t(`${p}.commandBriefOverview.activityCategories.requires_attention`),
        information: t(`${p}.commandBriefOverview.activityCategories.information`),
        changed: t(`${p}.commandBriefOverview.activityCategories.changed`),
        awaiting_review: t(`${p}.commandBriefOverview.activityCategories.awaiting_review`),
        integration: t(`${p}.commandBriefOverview.activityCategories.integration`),
        support: t(`${p}.commandBriefOverview.activityCategories.support`),
      },
    },
  };
}
