import type { CommunicationsLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildCommunicationsLabels(t: Translator): CommunicationsLabels {
  const p = "customerApp.portalStructure.communications";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    filters: {
      search: t(`${p}.filters.search`),
      type: t(`${p}.filters.type`),
      status: t(`${p}.filters.status`),
      priority: t(`${p}.filters.priority`),
      audience: t(`${p}.filters.audience`),
      publishFrom: t(`${p}.filters.publishFrom`),
      publishTo: t(`${p}.filters.publishTo`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      active: t(`${p}.dashboard.active`),
      scheduled: t(`${p}.dashboard.scheduled`),
      critical: t(`${p}.dashboard.critical`),
      expiring: t(`${p}.dashboard.expiring`),
      recentlyPublished: t(`${p}.dashboard.recentlyPublished`),
      drafts: t(`${p}.dashboard.drafts`),
    },
    form: {
      createTitle: t(`${p}.form.createTitle`),
      title: t(`${p}.form.title`),
      summary: t(`${p}.form.summary`),
      message: t(`${p}.form.message`),
      type: t(`${p}.form.type`),
      audience: t(`${p}.form.audience`),
      priority: t(`${p}.form.priority`),
      publishDate: t(`${p}.form.publishDate`),
      expirationDate: t(`${p}.form.expirationDate`),
      requiresAck: t(`${p}.form.requiresAck`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
      publish: t(`${p}.form.publish`),
    },
    card: {
      author: t(`${p}.card.author`),
      publishDate: t(`${p}.card.publishDate`),
      priority: t(`${p}.card.priority`),
      audience: t(`${p}.card.audience`),
      acknowledged: t(`${p}.card.acknowledged`),
      pending: t(`${p}.card.pending`),
      view: t(`${p}.card.view`),
    },
    detail: {
      overview: t(`${p}.detail.overview`),
      message: t(`${p}.detail.message`),
      audience: t(`${p}.detail.audience`),
      delivery: t(`${p}.detail.delivery`),
      acknowledgements: t(`${p}.detail.acknowledgements`),
      acknowledge: t(`${p}.detail.acknowledge`),
      acknowledged: t(`${p}.detail.acknowledged`),
      pendingAck: t(`${p}.detail.pendingAck`),
      relatedPolicies: t(`${p}.detail.relatedPolicies`),
      activity: t(`${p}.detail.activity`),
      audit: t(`${p}.detail.audit`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
      recommendations: t(`${p}.detail.recommendations`),
      outstanding: t(`${p}.detail.outstanding`),
    },
    types: {
      company_announcement: t(`${p}.types.companyAnnouncement`),
      operational_update: t(`${p}.types.operationalUpdate`),
      policy_update: t(`${p}.types.policyUpdate`),
      security_notice: t(`${p}.types.securityNotice`),
      executive_message: t(`${p}.types.executiveMessage`),
      team_update: t(`${p}.types.teamUpdate`),
      maintenance_notification: t(`${p}.types.maintenanceNotification`),
      celebration_recognition: t(`${p}.types.celebrationRecognition`),
      emergency_communication: t(`${p}.types.emergencyCommunication`),
      custom_communication: t(`${p}.types.customCommunication`),
    },
    statuses: {
      draft: t(`${p}.statuses.draft`),
      scheduled: t(`${p}.statuses.scheduled`),
      published: t(`${p}.statuses.published`),
      expired: t(`${p}.statuses.expired`),
      archived: t(`${p}.statuses.archived`),
    },
    priorities: {
      informational: t(`${p}.priorities.informational`),
      important: t(`${p}.priorities.important`),
      high_priority: t(`${p}.priorities.highPriority`),
      critical: t(`${p}.priorities.critical`),
    },
    audiences: {
      entire_organization: t(`${p}.audiences.entireOrganization`),
      specific_departments: t(`${p}.audiences.specificDepartments`),
      administrators_only: t(`${p}.audiences.administratorsOnly`),
      executives_only: t(`${p}.audiences.executivesOnly`),
      custom_groups: t(`${p}.audiences.customGroups`),
      individual_users: t(`${p}.audiences.individualUsers`),
    },
    recommendations: {
      remindAcknowledgement: t(`${p}.recommendations.remindAcknowledgement`),
      archiveOutdated: t(`${p}.recommendations.archiveOutdated`),
      scheduleRecurring: t(`${p}.recommendations.scheduleRecurring`),
      reviewAudience: t(`${p}.recommendations.reviewAudience`),
      publishSecurityPromptly: t(`${p}.recommendations.publishSecurityPromptly`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      acknowledgements: t(`${p}.faq.acknowledgements`),
      acknowledgementsAnswer: t(`${p}.faq.acknowledgementsAnswer`),
      autoCommunicate: t(`${p}.faq.autoCommunicate`),
      autoCommunicateAnswer: t(`${p}.faq.autoCommunicateAnswer`),
    },
  };
}
