import type { CommitmentTrackingLabels } from "./types";
import type { Translator } from "@/lib/i18n/translate";

export function buildCommitmentTrackingLabels(t: Translator): CommitmentTrackingLabels {
  const p = "customerApp.portalStructure.commitmentTracking";
  return {
    title: t(`${p}.title`),
    subtitle: t(`${p}.subtitle`),
    loading: t(`${p}.loading`),
    principle: t(`${p}.principle`),
    emptyTitle: t(`${p}.emptyTitle`),
    emptyBody: t(`${p}.emptyBody`),
    emptyCta: t(`${p}.emptyCta`),
    back: t(`${p}.back`),
    notFound: t(`${p}.notFound`),
    filters: {
      search: t(`${p}.filters.search`),
      type: t(`${p}.filters.type`),
      status: t(`${p}.filters.status`),
      owner: t(`${p}.filters.owner`),
      recipient: t(`${p}.filters.recipient`),
      priority: t(`${p}.filters.priority`),
      dueFrom: t(`${p}.filters.dueFrom`),
      dueTo: t(`${p}.filters.dueTo`),
      all: t(`${p}.filters.all`),
    },
    dashboard: {
      active: t(`${p}.dashboard.active`),
      atRisk: t(`${p}.dashboard.atRisk`),
      recentlyFulfilled: t(`${p}.dashboard.recentlyFulfilled`),
      overdue: t(`${p}.dashboard.overdue`),
      highPriority: t(`${p}.dashboard.highPriority`),
      completionTrends: t(`${p}.dashboard.completionTrends`),
    },
    form: {
      createTitle: t(`${p}.form.createTitle`),
      title: t(`${p}.form.title`),
      description: t(`${p}.form.description`),
      type: t(`${p}.form.type`),
      recipient: t(`${p}.form.recipient`),
      priority: t(`${p}.form.priority`),
      dueDate: t(`${p}.form.dueDate`),
      fulfillmentCriteria: t(`${p}.form.fulfillmentCriteria`),
      notes: t(`${p}.form.notes`),
      submit: t(`${p}.form.submit`),
      cancel: t(`${p}.form.cancel`),
    },
    card: {
      owner: t(`${p}.card.owner`),
      recipient: t(`${p}.card.recipient`),
      priority: t(`${p}.card.priority`),
      progress: t(`${p}.card.progress`),
      dueDate: t(`${p}.card.dueDate`),
      view: t(`${p}.card.view`),
    },
    detail: {
      overview: t(`${p}.detail.overview`),
      ownership: t(`${p}.detail.ownership`),
      fulfillmentCriteria: t(`${p}.detail.fulfillmentCriteria`),
      fulfillmentTracking: t(`${p}.detail.fulfillmentTracking`),
      milestonesAchieved: t(`${p}.detail.milestonesAchieved`),
      delaysEncountered: t(`${p}.detail.delaysEncountered`),
      obstaclesIdentified: t(`${p}.detail.obstaclesIdentified`),
      progressUpdate: t(`${p}.detail.progressUpdate`),
      completionEvidence: t(`${p}.detail.completionEvidence`),
      lessonsLearned: t(`${p}.detail.lessonsLearned`),
      progressHistory: t(`${p}.detail.progressHistory`),
      relatedGoals: t(`${p}.detail.relatedGoals`),
      relatedFollowUps: t(`${p}.detail.relatedFollowUps`),
      relatedDecisions: t(`${p}.detail.relatedDecisions`),
      relatedCommunications: t(`${p}.detail.relatedCommunications`),
      activityTimeline: t(`${p}.detail.activityTimeline`),
      audit: t(`${p}.detail.audit`),
      save: t(`${p}.detail.save`),
      saved: t(`${p}.detail.saved`),
      recordProgress: t(`${p}.detail.recordProgress`),
      progressRecorded: t(`${p}.detail.progressRecorded`),
      recommendations: t(`${p}.detail.recommendations`),
      status: t(`${p}.detail.status`),
      notes: t(`${p}.detail.notes`),
    },
    types: {
      customer_commitment: t(`${p}.types.customerCommitment`),
      employee_commitment: t(`${p}.types.employeeCommitment`),
      executive_commitment: t(`${p}.types.executiveCommitment`),
      team_commitment: t(`${p}.types.teamCommitment`),
      vendor_commitment: t(`${p}.types.vendorCommitment`),
      regulatory_commitment: t(`${p}.types.regulatoryCommitment`),
      strategic_commitment: t(`${p}.types.strategicCommitment`),
      operational_commitment: t(`${p}.types.operationalCommitment`),
      partnership_commitment: t(`${p}.types.partnershipCommitment`),
      custom_commitment: t(`${p}.types.customCommitment`),
    },
    statuses: {
      proposed: t(`${p}.statuses.proposed`),
      accepted: t(`${p}.statuses.accepted`),
      in_progress: t(`${p}.statuses.inProgress`),
      at_risk: t(`${p}.statuses.atRisk`),
      fulfilled: t(`${p}.statuses.fulfilled`),
      cancelled: t(`${p}.statuses.cancelled`),
      archived: t(`${p}.statuses.archived`),
    },
    priorities: {
      low: t(`${p}.priorities.low`),
      medium: t(`${p}.priorities.medium`),
      high: t(`${p}.priorities.high`),
      critical: t(`${p}.priorities.critical`),
    },
    recommendations: {
      reviewDeadlines: t(`${p}.recommendations.reviewDeadlines`),
      escalateAtRisk: t(`${p}.recommendations.escalateAtRisk`),
      clarifyCriteria: t(`${p}.recommendations.clarifyCriteria`),
      assignSupport: t(`${p}.recommendations.assignSupport`),
      celebrateFulfilled: t(`${p}.recommendations.celebrateFulfilled`),
    },
    faq: {
      title: t(`${p}.faq.title`),
      whatIs: t(`${p}.faq.whatIs`),
      whatIsAnswer: t(`${p}.faq.whatIsAnswer`),
      whyTrack: t(`${p}.faq.whyTrack`),
      whyTrackAnswer: t(`${p}.faq.whyTrackAnswer`),
      autoFulfill: t(`${p}.faq.autoFulfill`),
      autoFulfillAnswer: t(`${p}.faq.autoFulfillAnswer`),
    },
  };
}
